### ISSUE TITLE
Linkul de flexiuni trece neobservat

### ISSUE THREAD

**Issue by CatalinFrancu** [dexonline/dexonline#104]
AM întrebat mai multe persoane şi habar nu aveau că există un asemenea link... :)
De asemenea, alăturarea de link-ul 'Abrevieri' te face să crezi că e vorba de ceva global, nu relativ la cuvîntul căutat.

**Comment by CatalinFrancu** [comment]
Subsumat de #412.

**Comment by raduborza** [comment]
Nu mi se pare că e subsumat de #412. Ar trebui să apară un link mare, care să se vadă.

**Comment by CatalinFrancu** [comment]
Păi va fi, când va fi gata. :-) Mă gândesc că ar putea fi o secțiune collapsabilă, cum are wikipedia pe mobil. Sau altceva proeminent.

**Comment by raduborza** [comment]
Păi este colapsabilă (și se face un ajax dacă nu are deja datele despre flexiune).
Ideea e că nu e observabilă. Cred că ar trebui să punem event special  în analytics pentru deschiderea secțiunii respective (acum avem doar linkurile cu # la grămadă). 
Și poate promovat... Îi facem lui Doru o listă cu lucrurile pe care trebuie să le promoveze periodic pe facebook?

**Comment by CatalinFrancu** [comment]
Mă gândeam să fie o secțiune de aceeași importanță cu celelalte - lista de cuvinte găsite; flexiuni; rezultate. Doar că ar fi colapsat la început, exact cum face [Wikipedia](https://en.m.wikipedia.org/wiki/Paradigm) pe rezoluții mici.

Mișto că poți urmări și evenimente pe Analytics, dar nu știu cât de relevant ar fi. Dacă aflăm că sunt 10.000 de paradigme văzute pe zi, cum știm dacă e bine sau rău?

Dacă un feature trebuie promovat, înseamnă că facem ceva greșit. :-)

Dacă vrei să reparăm asta înainte de #412, hai să-l facem mai proeminent. Poate să punem un buton în loc de link?
