### ISSUE TITLE
Dicţionarul Universal a lui Şăineanu

### ISSUE THREAD

**Issue by CatalinFrancu** [dexonline/dexonline#105]
De introdus la surse.
De asemenea, ar trebui discutat cu vasilache71@gmail.com

Avînd în vedere că dicţionarul este în domeniul public, mă gîndesc că ar putea fi pus pe wiki.dexonline.ro ca să se poată corecta ce introduce nenea ăla.

**Comment by CatalinFrancu** [comment]
Îl închid, avem deja ediția a 6-a.

**Comment by raduborza** [comment]
Dacă putem obține și ediția a III-a, cu atît mai bine. Avem prima ediție (dar scanată prost, se poate introduce NUMAI manual)...

**Comment by CatalinFrancu** [comment]
Parcă era undeva o listă a dicționarelor pe care le avem / dorim? Ar sta mai bine acolo decât într-un issue.

**Comment by raduborza** [comment]
Da, era într-o pagină de wiki. E ok să punem acolo dicționarele pe care le
vrem. Dar să facem și curățenie din cînd în cînd. Eu am prostul obicei să
uit... nu ar fi bine să avem și un checklist cu îndatoririle periodice?
Pe 6 ian. 2016 00:39, "Cătălin Frâncu" <notifications@github.com> a scris:

**Comment by CatalinFrancu** [comment]
Cred că [asta](http://wiki.dexonline.ro/wiki/Dic%C8%9Bionare_disponibile) e pagina. Ultima versiune e de acum vreun an.
