### ISSUE TITLE
Nu există modalitate pentru a introduce un newline

### ISSUE THREAD

**Issue by CatalinFrancu** [dexonline/dexonline#109]
Sau nu am descoperit-o eu... În anumite cazuri chiar este necesar

**Comment by CatalinFrancu** [comment]
Radu - sumarul este că putem suporta cu ușurință caractere \n în definiții, dacă zici că trebuie. Închide tu tichetul dacă nu mai este cazul.

**Comment by raduborza** [comment]
Chiar este cazul! Acum lucrăm la Dicționarul Analogic și chiar ar fi nevoie de <br/>.
Mă pot ocupa eu, dar aș vrea să număr cîte newline-uri avem deja.

**Comment by CatalinFrancu** [comment]
Mai trec și prin _issue_-rile vechi din când în când. :-)

Suportul pentru linii noi există, `Str::htmlize()` poate fi apelat cu parametrul `$obeyNewlines`. Nu este însă o idee bună să păstrăm toate caracterele `\n`, căci editorii le folosesc neconsecvent. Unii le folosesc pentru a-și ordona vizual munca, alții deloc.

L-aș face un parametru pe sursă. La sursele care nu folosesc linii noi (în original), ele vor fi ignorate în cursul conversiei la HTML. La cele care le folosesc, ele vor fi transformate în `<br>`. În cazul acesta din urmă, editorii trebuie să știe că nu mai pot folosi `\n` oricând au chef, ci trebuie să respecte originalul.

**Comment by LadislauStrifler** [comment]
În cazul acesta ar fi necesar un avertisment vizual la editarea definiției.

**Comment by CatalinFrancu** [comment]
Cred că un avertisment ar crea mult zgomot, nu? Editorii care folosesc `\n` pentru a-și ordona munca ar primi alerta la fiecare salvare. Mai degrabă îi atenționăm pe editori când ne apucăm de o sursă care folosește `\n`.

**Comment by revolter** [comment]
Ar ajuta daca `newline`-urile consecutive ar fi inlocuite cu un singur `newline`, si apoi inlocuit (implicit, cu un singur) `br`?

Si eu votez pentru adaugarea `br`-urilor.

Fara:

![image](https://user-images.githubusercontent.com/5748627/87230999-1ca40280-c3bc-11ea-9f67-6cdeaa4fcb5e.png)

---

Cu:

![image](https://user-images.githubusercontent.com/5748627/87231089-dbf8b900-c3bc-11ea-80e9-850ff5accebf.png)

**Comment by CatalinFrancu** [comment]
Sună bine! Am adăugat sintaxa `\n\n => <br>`. Nu am limitat la un singur newline, poate vreodată sînt necesare mai multe (deci `\n\n\n\n => <br><br>`).

Prezentarea mai bună e o problemă discutată și răsdiscutată. Asta începem să obținem prin definițiile structurate (vezi [buză](https://dexonline.ro/definitie/buz%C4%83/sinteza) sau [urs](https://dexonline.ro/definitie/urs/sinteza)). Definițiile mai lungi întotdeauna vor arăta rău cîtă vreme le arătăm complet, căci se vor întinde fie pe orizontală, fie pe verticală.
