### ISSUE TITLE
crearea tabelei de abrevieri

### ISSUE THREAD

**Issue by CatalinFrancu** [dexonline/dexonline#137]
plus funcționalitatea pentur afișare.

Pe viitor (după ce fac tabela), trebuie pus un task de înlocuire automată

**Comment by CatalinFrancu** [comment]
Propun să-l închidem.

**Comment by raduborza** [comment]
Păi cînd l-am pus m-am gîndit că abrevierilor le-ar sta bine într-o tabelă, iar tabela să fie încărcată într-un cache (APC mă gîndisem atunci).

**Comment by CatalinFrancu** [comment]
Cred că avea mai mult sens. Am deschis #420 pentru asta. Structurarea va elimina problema, dar probabil vom vrea să păstrăm și definițiile ca atare. Ok, atunci reformulez: propun să-l închidem ca duplicat al lui #420. :-)
