### ISSUE TITLE
Digitize the introduction to DOOM2

### ISSUE THREAD

**Issue by CatalinFrancu** [dexonline/dexonline#198]
It contains 100 pages of useful norms ("Principalele norme ortografice, ortoepice și morfologice ale limbii române").

**Comment by CatalinFrancu** [comment]
@raduborza, cred că tu ai digitizat deja introducerea de la DOOM2, nu? Te asignez să-l închizi tu când crezi.

**Comment by raduborza** [comment]
Da, partea introductivă din DOOM2 e introdus la articole (https://dexonline.ro/articole) de multișor.
