### ISSUE TITLE
Convert pronunciation information to IPA

### ISSUE THREAD

**Issue by CatalinFrancu** [dexonline/dexonline#201]
DOOM2, DEX and other dictionaries contain incomplete, simplistic pronunciation information:

http://dexonline.ro/definitie/chewinggum/8366
http://dexonline.ro/definitie/shakespearian/63561
http://dexonline.ro/definitie/kitsch/18432
http://dexonline.ro/definitie/kitsch/341034

We should use the IPA to standardize and improve this information:

http://en.wikipedia.org/wiki/International_Phonetic_Alphabet

**Comment by CatalinFrancu** [comment]
îl închid în favoarea lui #425.

**Comment by raduborza** [comment]
Nu putem încerca să creăm un script care să genereze pronunția, iar dup-aia să îl corectăm manual?

**Comment by CatalinFrancu** [comment]
Ba da, păi cam asta ar fi și ideea. Am deschis din greșeală celălalt tichet, de-asta l-am închis. Comentez acolo, ca să fie clar.

**Comment by raduborza** [comment]
A, ok. De acord!
