### ISSUE TITLE
Autocomplete for search box

### ISSUE THREAD

**Issue by CatalinFrancu** [dexonline/dexonline#224]
Based on the lexem list. Should work with / without diacritical marks.

We need to determine if this is worth doing, as it will cause additional load on the server.

**Comment by aifrim** [comment]
@CatalinFrancu  câte cuvinte sunt?

**Comment by CatalinFrancu** [comment]
Hm, pe ăsta l-a  rezolvat @david-batranu. Sunt vreo 210.000 de forme. Merge rezonabil cu Varnish, sau nu am observat un load suplimentar îngrijorător.
