### ISSUE TITLE
Modifică abrevierile în unele surse

### ISSUE THREAD

**Issue by CatalinFrancu** [dexonline/dexonline#244]
**Update:** ne trebuie un script care să elimine conflictele de mai jos înlocuind una dintre apariții cu altceva, de exemplu „s.” cu „sg.”.

În MDN există abrevieri care sînt diferențiate și prin formatare (a înseamnă „anul”, iar ''a'' înseamnă „adjectiv”. În dexonline acestea cauzează erori, deci trebui găsită o soluție...

O să număr conflictele înainte de a propune o soluție.

**Comment by LadislauStrifler** [comment]
Cred că și aici putem închide. Noul sistem permite formatări, deci **`a`** pentru _adjectiv_ în MDA2 trebuie formatat întocmai în definiție, adică **`$a$`**, pentru a fi recunoscut.  Cealaltă abreviere, **`a.`** neformatată, va fi recunoscută ca **`anul`**. Rămâne să închidem doar #719 pentru abrevieri (deocamdată).

**Comment by CatalinFrancu** [comment]
De acord, îl închid. Dincolo de faptul că există suportul, trebuie făcute și modificările în sine (de pus `a` și `$a$` și toate celelalte în lista de abrevieri, apoi de regenerat definițiile). Dar acest tichet nu mă mulțumește, fiindcă cere modificarea definițiilor originale, or acum avem o soluție care nu necesită asta. Deschid unul nou care să depindă de #719.
