### ISSUE TITLE
implementarea versiunii noastre de boggle flash

### ISSUE THREAD

**Issue by CatalinFrancu** [dexonline/dexonline#273]
vezi ceva similar: http://www.hubworld.com/scrabble/shows/showdown/games/scrabble-flash

îl putem generaliza, eventual!

**Comment by raduborza** [comment]
Eu zic să punem aici cerințele minimale, dinainte de a începe ceva!

**Comment by AdamBlade** [comment]
De acord.
Uitati ce am facut eu pana acum,
Trei nivele de dificultate(5-6-7 nr de caractere). 
Pe baza acestui nivel de dificultate selecteaza random un cuvant din baza.
Pe baza literelor acestui cuvant face un brute-force search pentru toate cuvintele posibile care se pot forma cu acele litere si populeaza un dictionar. (Nu-mi convine brute force-ul, dar momentan e cea mai buna solutie care am gasit-o, pana la 7! merge ok dupa face probleme).
Literele selectate se duc intr-o zona dupa care se auto pozitioneaza.
Punctajul se acorda dupa numarul de litere al cuvantului, si acorda bonus daca formeaza 3 cuvinte distince la rand, fara sa greseasca.
Am o optiune sa afisez cuvintele ghicite si definitiile lor ( s-ar putea sa arate urat pe forma mobile).

Ce mi-a ramas din perspectiva mea:
Un buchet frumos de buguri ce trebuie reparate + o metoda mai eficienta de generare a cuvintelor posibile.

**Comment by CatalinFrancu** [comment]
Scuze pentru întârziere.

Dacă vrei, dă-ne un code review. E mai ușor să dai feedback pe chestii concrete. :-) S-ar putea să fie problematic dacă stilul tău de codare diferă mult de al nostru, dar cred că nu e grav, căci jocul e un modul destul de bine separat de restul codului.

Dacă s-ar mișca fulgerător pentru 7 litere ar fi fantastic, dar cred că realist jocul poate fi jucat și cu 6 litere (în engleză eu am suficient de furcă și cu 5).

Pentru eficiență, bănuiesc că problema nu e generarea cuvintelor. Sunt vreo 13.000 pentru toate aranjamentele de 7 luate câte 2, 3, 4, 5, 6, 7. Bănuiesc că problema apare dacă faci câte o interogare pentru fiecare cuvânt. Am următoarele idei:

1. Verifică corectitudinea prin Ajax, doar când jucătorul depune o literă. Atunci numărul de interogări e limitat de numărul de mutări, care pentru majoritatea jucătorilor va fi mic. E drept că introduce un server roundtrip, dar se poate compensa pentru asta (oprești ceasul de joc etc.).

2. Generăm o tabelă separată cu formele legale (asta oricum e o idee bună, ca să filtrăm obscenitățile numele proprii etc.). Iar în acea tabelă ținem și o coloană cu literele ordonate ale cuvântului (deci pentru _carte_ ținem _acert_). Și atunci construirea dicționarului face doar 2^7 interogări, astfel:

  * Sortează mulțimea de 7 litere.
  * Generează cele 2^7 submulțimi de litere. Datorită pasului anterior, submulțimile vor avea literele sortate.
  * Pentru fiecare submulțime, să zicem _acert_, caută în noua tabelă cuvintele pentru care literele ordonate sunt _acert_.

**Comment by CatalinFrancu** [comment]
Și încă o idee care merită încercată, o extensie a lui (2) de mai sus.

Pe noua tabelă ții 26 de coloane, numA, numB, ... numZ, întregi, care arată câte litere A, B, ..., Z conține cuvântul. Deci pentru _abac_ am avea numA = 2, numB = 1, numC = 1, restul 0. Indexezi toate coloanele.

Apoi generezi un set de 7 litere, să zicem _aabbbhx_ și faci o singură interogare:

SELECT * FROM boggle WHERE numA <= 2 AND numB <= 3 AND numH <= 1 AND numX <= 1 AND numC = 0 AND numD = 0 AND... (restul sunt pe zero).

Merită testat.

**Comment by raduborza** [comment]
Pentru verificare în loc să facem call-uri la fiecare literă, mai bine
generăm un obiect cu toate soluțiile posibile pentru problema afișată
(probabil că putem face asta în mai puțin de 1-2 secunde), iar verificarea
să se facă local, în javascript. Ca măsură de protecție facem o statistică
pe timpii dintre introducerea a două litere consecutive.

În data de 24 februarie 2016, 13:17, Cătălin Frâncu <
notifications@github.com> a scris:

**Comment by CatalinFrancu** [comment]
Da, păi soluțiile mele (2) și (3) asta încearcă să facă. Din păcate, efortul ăsta trebuie făcut pe server, nu merge făcut pe client în Javascript, pentru că clientul nu are lista de cuvinte corecte.

**Comment by raduborza** [comment]
Păi eu sugeram să se creeze lista de soluții pe server și să se încarce pe
client astfel încît verificările să se facă numai local, la client...

În data de 24 februarie 2016, 17:48, Cătălin Frâncu <
notifications@github.com> a scris:

**Comment by AdamBlade** [comment]
Eu m-am gandit la generarea unei tabele separate pentru joc, desi asta ar insemna ceva duplicare de date.
Caut toate cuvintele de 4,5,6,7 literele, pentru fiecare cuvant caut cuvintele care se pot forma cu literele sale(cuvantul insusi care a fost selectat e valid pentru ca literele se afiseaza aleator pe ecran).
Asa as avea fiecare cuvant cu lista lui de cuvinte posibile, si n-ar mai fi nevoie sa interoghez de fiecare data baza, si nici sa generez permutari (server side) pentru a afla cuvintele posibile la selectarea unui nou cuvant.
Asa as interoga prin AJAX doar tabela asta, si mi-ar returna un cuvant si lista, stocate local.

**Comment by CatalinFrancu** [comment]
@raduborza: Cred că vorbim de două chestii diferite în același timp: dacă pregenerăm toate cuvintele de <= 7 litere, sau doar pe cele pentru un joc în particular (deci un set fixat de 7 litere). Soluțiile mele anterioare erau pentru un joc în particular.

Dar de fapt putem face o pregenerare completă. Nu e o listă mare. Sunt vreo 100.000 de forme legale de <= 7 litere, pentru cuvintele din DEX. Ele ocupă 860 KB (cu diacritice) sau 710 KB (fără diacritice). Cu zip sau gzip se comprimă la 260 KB (cu diacritice) / 210 KB (fără diacritice), iar cu XZ se comprimă la 180 KB (cu diacritice) / 120 KB (fără diacritice).

Cred că 200 KB e acceptabil, chiar și pe un plan de date. Deci recomandările mele, în ordine, ar fi:

* Listă pregenerată. Efectiv o listă de cuvinte de 1-7 litere, ordonată alfabetic, 1 cuvânt pe linie. Poate fi căutată binar. La o mutare pe secundă este arhisuficient. Extra puncte pentru un decompresor de XZ (există gata făcute în JS).
* Tabelă pe server cu vector caracteristic (numA, numB, ... numZ). După ce este ales setul de 7 litere, o singură interogare produce lista de cuvinte corecte pentru acel set. Mă aștept să se miște bine.
* Tabelă cu un câmp suplimentar care să conțină literele cuvântului ordonate (_carte_ => _acert_). După ce este ales setul de 7 litere, sunt necesare 2^7 interogări, unul pentru fiecare subset.

@AdamBlade, nu m-aș chinui cu trie, deși pare că găsești implementări în JS. Pentru 100.000 de cuvinte de <= 7 litere, căutarea binară se va mișca suficient de bine. Reiau explicația soluției cu vector caracteristic (a doua în lista de mai sus).

Pe server pregenerăm o tabelă care conține 27 de coloane: una cu forma (cuvântul) și 26 de întregi care arată câți de A, câți de B, ..., câți de Z conține cuvântul. Deci, pentru _abac_, linia din tabelă ar fi _abac_, 2, 1, 1, 0, 0, ..., 0. Punem câte un index pe fiecare din cele 27 de coloane.

Când jucătorul începe un joc nou, îi generăm un set de 7 litere, să zicem _aaabbcx_. Vrem să extragem din tabelă toate cuvintele legale care se pot forma cu aceste 7 litere sau mai puține, ca să le pasăm la client. Deci vrem acele linii din tabelă care au maxim 3 A-uri, maxim 2 B-uri, maxim 1 C, maxim 1 X. Programul va executa interogarea SELECT din comentariul meu anterior.

Dar, din nou, pentru 200 KB merită implementată prima soluție.

**Comment by raduborza** [comment]
Chiar nu contează dacă generăm pentru un joc în particular sau pentru toate
cuvintele (există pro și contra pentru ambele), ideea era să fie trimis
fișierul pe client.

Pregenerare completă:

   - PRO:
      - generarea este simplă și se poate refolosi;
   - CONTRA:
      - se poate copia dicționarul comprimat (cu tot ce decurge de aici);
      - se poate hăcui pagina astfel încît să se modifice literele (asta
      înseamnă că trebuie să mai facem o validare pe server, la submit);
      - trebuie implementat în javascript verificarea în dicționarul
      complet;


Pregenerare joc particular:

   - PRO:
      - generarea poate varia ca timp în funcție de litere;
      - dimensiune mai mică;
      - verificarea este simplă (practic dacă avem potrivire în listă, este
      soluție corectă...)
      - verificarea e mai rapidă (dar fiind local nu cred că mai contează);
      - mai greu de hăcuit;
   - CONTRA:
      - e un pic mai complicată generarea listei;
      - generarea trebuie făcută de fiecare dată (o să avem un javascript
      generat dinamic);

Paranoicul din mine ar merge pe a doua soluție dacă reușim să pregenerăm
rapid pe server lista de soluții care va fi trimisă pe client.

Radu

În data de 25 februarie 2016, 11:36, Cătălin Frâncu <
notifications@github.com> a scris:

**Comment by CatalinFrancu** [comment]
Paranoia e bună. :-) Ok, @AdamBlade, dacă ai chef să te ocupi de asta, încearcă te rog întâi soluția numită mai sus „cu vector caracteristic”. Dacă interogarea e prea lentă (sper că nu), mergem pe prima soluție, numită mai sus „listă pregenerată”.

**Comment by AdamBlade** [comment]
Salutare, 

Am incarcat o prima tentativa pe repo-ul meu https://github.com/AdamBlade/dexonline.git ,inca sunt probleme dar as dori un feedback.

**Comment by CatalinFrancu** [comment]
Gata, am dat feedback pe pull request. L-am și instalat, merge cu mici modificări.

În SmartyWrap implementăm un mecanism de a specifica ce fișiere JS și CSS vrem. Nu e ideal, dar ne rezolvă niște probleme: vrem să includem doar anumite fișiere și într-o anumită ordine.

**Comment by AdamBlade** [comment]
Eu nu prea inteleg de ce imi da fail cand selectez prima data un nivel de dificultate. 

Imi apare in consola TypeError: result.everyWord is undefined, dar la a doua apasare functioneaza.

Punctajul se acorda, si ridica literele dar nu mereu, uneori ori nu sesiseaza cand apesi enter ori nush exact ce se intampla.

**Comment by AdamBlade** [comment]
Salutare,

Am facut un pull request cu noua versiune. 
Am finalizat zic eu in proportie de 98% ce mi-am propus sa fac.

As dori un feedback daca e ok si daca ar mai fi ceva de adaugat/modificat.
O mica problema o am cu ce cuvinte imi extrage din baza ca fiind valide. De exemplu imi scoate uneori cuvinte care sunt prescurtari sau altceva? Cand le caut in bara de cautare dex imi spun ca n-am drepturi sa vizualizez acel cuvant. Compozitii de genul uu apar ca fiind valide in baza. 
Cam asta ar mai fi singura problema de care stiu.

**Comment by CatalinFrancu** [comment]
Salut,

Mă apuc acum de code review.

Cred că ar fi bine să filtrăm formele permise, păstrându-le doar pe cele care apar în DEX, DOOM2 și DOR. În rest apar termeni prea de nișă (tehnici, arhaici, regionali etc.).

**Comment by AdamBlade** [comment]
Salut,

Apare vreo notificare cand adaug comentarii pe pull request ?

**Comment by CatalinFrancu** [comment]
Da, le-am primit! Nu promit că mai apuc să răspund astă-seară, dar mâine sigur.

**Comment by AdamBlade** [comment]
Ah no problem, cand ai timp. Intrebam pentru ca nu sunt foarte familiar cu GitHub.

**Comment by AdamBlade** [comment]
Salutare,
S-a mai schimbat ceva ?

**Comment by CatalinFrancu** [comment]
Da, am deschis un tichet pentru chestii de reparat: #461. L-am menționat, dar cred că pe celălalt pull request.

Jocul este [disponibil pe dexonline](https://dexonline.ro/scramble), dar nu l-am linkat pentru că creează o primă impresie negativă. Aș vrea să reparăm chestiile din tichet, mici și mari.
