### ISSUE TITLE
Widget Avocatnet.ro

### ISSUE THREAD

**Issue by CatalinFrancu** [dexonline/dexonline#293]
Avocatnet.ro ne propune un schimb de widgeturi, „Cuvântul zilei” la ei pe pagină contra „Legea zilei” la noi pe pagină (sau ceva asemănător). Fiind două proiecte cu implicare civică, mi se pare o idee bună.

Depinde de #292 (care este rezolvat). Necesită un mecanism general de configurare a unui widget „Cuvântul zilei”, pentru alte site-uri care eventual doresc asta.

**Comment by sandriu** [comment]
În momentul ăsta avem 6 widget-uri pe home page. Cel pentru avocatnet.ro ar crea un nou rând de widget-uri, care ar arăta cam golaș. Introducerea lui trebuie corelată cu gradul de folosire a widget-urilor actuale (vom afla asta după 14 septembrie 2016, când public rezultatele chestionarului de feedback pentru noul design).

**Comment by CatalinFrancu** [comment]
Nu știu dacă mai este de actualitate, îl închid.
