### ISSUE TITLE
Migrare la HTML5

### ISSUE THREAD

**Issue by CatalinFrancu** [dexonline/dexonline#298]
HTML5 pare destul de matur. Ceea ce ne trebuie nouă este bine suportat pe toate browserele (mai puțin IE 7, posibil și IE 8).

De investigat cum se comportă HTML5 pe IE8. Putem cârpi codul ca să menținem compatibilitatea cu IE8, câtă vreme rămâne HTML5 valid.

**Comment by sandriu** [comment]
Cred că acest tichet va fi auto-rezolvat de tichetul #468 , care introduce design responsive și Bootstrap (care folosește doar HTML5, nu și HTML4). 
Propun să închidem tichetul ăsta.

**Comment by CatalinFrancu** [comment]
De acord.
