### ISSUE TITLE
Căutarea aproximativă nu funcționează corect

### ISSUE THREAD

**Issue by CatalinFrancu** [dexonline/dexonline#324]
Pentru un caz banal, cînd două litere sînt inversate, nu se oferă varianta corectă.

De exemplu caut „mască” dar scriu greșit „macsă”. Mi se oferă alternativele: Moacșa | măceașă | măcieșă

**Comment by vargaradu** [comment]
Extra problemă ptr căutarea alternativă: Dacă scriu "masc", îmi apare definiția pentru "mâșc" și de asemenea mi se schimbă input textul în "mâșc". Iar acum vreau să adaug un "a", și am "mâșcă".
Nu ar fi mai ok să lăsăm input textul așa cum l-a scris userul?

**Comment by CatalinFrancu** [comment]
Cred că acest comportament este intenționat. E bine să canonicalizăm paginile, ca să nu ne luăm penalizări de la Google pentru pagini duplicate. De aceea, când există un singur rezultat, redirectăm la forma canonică. Pentru „fata” nu se întâmplă asta, de exemplu, pentru că există mai multe rezultate cu diverse diacritice.

**Comment by CatalinFrancu** [comment]
Ar trebui făcut ceva pentru cuvintele scurte - acolo numărul de trigrame este mic, iar o literă schimbată sau o inversiune poate avea un efect devastator. Vezi _buhoi_, care ar trebui mult mai natural să sugereze _buhai_.

**Comment by MateiGall** [comment]
Ar fi bine totuși ca mesajul de redirectare să menționeze și forma (presupus incorectă) care a fost tastată (așa cum se întâmplă la redirectări cu rezultate multiple). Dacă tastez _buhoi_ și mă duce la **buduhoi**, ar fi bine să știu că greșeala a fost _buhoi_ și n-am făcut altă greșeală care m-a dus la **buduhoi** (ca să nu mai încerc o dată).
