### ISSUE TITLE
Brainstorming pentru testare

### ISSUE THREAD

**Issue by CatalinFrancu** [dexonline/dexonline#33]
Ar trebui descrisă o procedură generală de testare. În special pentru a şti dacă modificările la anumite părţi afecteză şi altele (pentur tine e mai simplă treaba, că tu ai creat sistemul, dar celorlalţi poa' să scape ceva). Dacă ai şi cazuri speciale de care te-ai lovit ar fi şi mai bine.

**Comment by CatalinFrancu** [comment]
Hai să decidem ce tip de testare facem, în primul rând.

Cred că unit testing nu se mai pune problema să facem. Avem deja prea mult cod ca să mai recuperăm diferența.

Ce ar merge bine la noi ar fi testarea la nivel de aplicație web, bazată pe scenarii - căutare, contribuție, administrare, logare, delogare etc. N-ar fi ideală pentru un dezvoltator nou, căci tot ce-i poate spune este „scenariul X nu merge”, nu îi dă funcția exactă pe care a stricat-o. Dar este mai ușor de implementat și mult mai bună decât ce avem acum (nimic). Ideal, fiecare dezvoltator va putea să ruleze suita de teste. Minimal, poate exista o singură instalare pe un server separat.

Știe cineva un framework bun pentru asta?

**Comment by andreiepure** [comment]
Se pare că FB a făcut php-webdriver pentru integrarea PHP cu Selenium [1]. Până una-alta, că ar fi util definirea scenariilor, cu pași, pentru ca voluntarii să aibă idei și să le ia din backlog unul câte unul.

[1] https://github.com/facebook/php-webdriver

**Comment by CatalinFrancu** [comment]
php-webdriver sună bine.

Ca scenarii, cred că avem de unde alege. :-) Aș începe cu căutarea, că e de departe cel mai grav lucru care se poate buși.

* click în cutia de căutare (sau assert că e deja în focus)
* tastează un cuvânt, să zicem „cal”
* assert că pe pagina de rezultate există un `div#resultsWrapper > p` cu conținutul „.*Animal domestic erbivor.*”

Apoi merită acoperite celelalte tipuri de căutare:

* cu redirectare automată: _saptamana_
* cu redirectare automată + flash message: _oprobiu_
* cu rezultate aproximative: _abcdef_
* după ID-ul definiției: _12345_
* cu expresii regulate
* etc.

După care ne putem ocupa de alte pagini:

* cuvântul zilei, navigare înainte și înapoi printre zile, assert că există diversele elemente în pagină
* pagina de scrabble (în special cutia de căutare de acolo)
* secțiunea de articole

Sigur, vom contribui și noi la crearea scenariilor. Mai important, mergând înainte vom adăuga scenarii pentru orice cod scriem. Că așa-i frumos. :-)

**Comment by andreiepure** [comment]
Deci Selenium sună bine. Eu nu promit momentan nimic, dar poate ar fi util un task pentru prototipare?
Revening la brainstorm - CSS regression testing? https://css-tricks.com/visual-regression-testing-with-phantomcss/

**Comment by CatalinFrancu** [comment]
M-am jucat cu [Selenium IDE](https://addons.mozilla.org/en-US/firefox/addon/selenium-ide/), un addon de Firefox. Pare foarte mișto și necesită zero programare, dincolo de crearea unei baze de date de test.

Mă apuc de lucru!

**Comment by CatalinFrancu** [comment]
Selenium IDE e funcțional. Mai e nevoie de testele în sine, :-) dar ăla ar fi alt tichet.

**Comment by andreiepure** [comment]
Nu am găsit tichet pentru teste. Se poate crea, să existe în sistem?

**Comment by CatalinFrancu** [comment]
Ok, am creat #546.
