### ISSUE TITLE
eroare la migrare

### ISSUE THREAD

**Issue by raduborza** [dexonline/dexonline#333]
Sînt de fapt două erori:
1. Se rulează (din nou!) patchurile locale (chiar dacă nu sînt sub controlul versiunii și chiar dacă nu la rînd), nu doar cele în conformitate cu schema „live”.
2. codul de migrare dă eroare cînd întîlnește definiția unei proceduri stocate (din cauza schimbării delimitatorului, cred).

> php tools/migration.php
Current schema version is <00116>
/home/radu/public_html/dexonline/tools/../patches/00120.sql -- executing with MySQL
PHP Fatal error:  Uncaught exception 'PDOException' with message 'SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'DELIMITER $'

**Comment by CatalinFrancu** [comment]
(2) Pare că a fost reparat în fa146f51faf1e11a7ce796fc402bf3bc97610476. Pentru (1), sunt convins că există metode mai bune de a face treaba, best practices etc. Dar n-aș sta acum să fac asta la nivel de precommit. Poate când ne mai înmulțim!
