### ISSUE TITLE
generează separat formele scrabble de 2 și 3 litere

### ISSUE THREAD

**Issue by CatalinFrancu** [dexonline/dexonline#334]
Este unul din lucrurile pe care nu le-am preluat în urma colaborării cu F.R.Sc. și ar fi bine să-l oferim și noi.

**Comment by CatalinFrancu** [comment]
Între timp avem liste descărcabile și o [unealtă de căutare](https://dexonline.ro/scrabble). @MateiGall, crezi că mai sunt utile și listele explicite cu 2 și cu 3 litere? Dacă da, pentru care dintre forme? Presupun că doar pentru cele reduse (fără diacritice).

**Comment by MateiGall** [comment]
Cred că nu.
Am impresia că nu se mai ocupă nimeni de la FRSc de lista de cuvinte, scrabbliștii au programe de căutare proprii, iar pentru _dexonline_ nu văd utilitatea.
Propun închidere.
