### ISSUE TITLE
bug la preferința cu "î din i"

### ISSUE THREAD

**Issue by dan2468** [dexonline/dexonline#339]
Tocmai am activat opțiunea „Folosesc ortografia folosită pînă în 1993”, și am descoperit un bug.

Link-ul către „Articolul lunii” nu mai merge: <http://dexonline.ro/articol/Alf_Lombard_-_Despre_folosirea_literelor_î_şi_â> devine <http://dexonline.ro/articol/Alf_Lombard_-_Despre_folosirea_literelor_î_şi_î> care bineînțeles nu funcționează.

PS: O problemă secundară: n-ar trebui să fie „și”, nu „şi”?

**Comment by CatalinFrancu** [comment]
Rezolvat în 792459d3530f9e0cec62ccecbee76b271b78e725. În URL-uri s-a rezolvat misterios de la sine, căci â este codat cu semnul %.
