### ISSUE TITLE
Uniformizarea denumirilor de selectori CSS

### ISSUE THREAD

**Issue by sandriu** [dexonline/dexonline#369]
În momentul de față, template-urile au 3 feluri de selectori CSS:
- camel case: contentProper
- cu cratimă: site-identity
- cu underscore: banner_mainPage.

Ar trebui folosit un singur stil pentru denumiri. De exemplu, "Google HTML/CSS Style Guide" recomandă cratima http://google-styleguide.googlecode.com/svn/trunk/htmlcssguide.xml#ID_and_Class_Name_Delimiters.

**Comment by CatalinFrancu** [comment]
@sandriu Cum mai stăm, mai știi? Pot să-l închid?

**Comment by sandriu** [comment]
Da, poți să-l închizi, fiindcă oricum vom schimba selectorii când trecem pe bootstrap.
