### ISSUE TITLE
Plugin de WordPress

### ISSUE THREAD

**Issue by CatalinFrancu** [dexonline/dexonline#371]
O cutie de căutare în Dexonline pe care oricine să și-o poată adăuga pe blog.

Nu necesită cunoștințe despre codul Dexonline. Trebuie doar să posteze la dexonline.ro/definitie/%s.

**Comment by grigoroiualex** [comment]
Știu că a trecut ceva vreme de când am spus că mă voi ocupa de acest ticket, dar acum este aproape gata: https://github.com/grigoroiualex/dexonline-searchbox-wp-plugin
Aș vrea să mă asigur că am înțeles corect, totuși. Widget-ul trebuie doar să trimită pe pagina dexonline cu definiția cuvântului sau trebuie să încarce definițiile cuvântului pe pagina de wordpress?

**Comment by CatalinFrancu** [comment]
Salut, scuze pentru întârziere. Aș începe cu ceva simplu - doar să trimită la Dexonline.

Dacă ai chef, poate un al doilea plugin ar putea arăta imaginea + definiția zilei. Asta ar fi mai aproape de ce întrebi tu.

**Comment by grigoroiualex** [comment]
Salutare, pe [site-ul meu](http://blog.grigoroiualex.ro) am pus o instanță de WordPress în care am instalat plugin-ul pe care l-am scris. Momentan funcționalitatea este de a trimite pe site-ul dexonline pe pagina cu definițiile cuvântului introdus. Este în regulă?

**Comment by CatalinFrancu** [comment]
Arată excelent! Nu știu nimic despre formatul pluginurilor, așa că nu mă apuc să mă uit prin cod. Ar merita însă să localizezi pentru românește titlul (să zicem „Căutare în Dexonline”) și sugestia din cutie (să zicem „Caută un cuvânt”).

Și să ne spui de unde poate fi descărcat în final, ca să punem link!

**Comment by grigoroiualex** [comment]
Ok. Am să fac și localizarea astfel încât să poată fi selectată limba din pagina de admin.
Apoi o să trimit pluginul către WordPress spre a fi moderat și îndată ce va fi publicat o să revin cu link către el.

**Comment by grigoroiualex** [comment]
Salutare. Pluginul a fost publicat și iată și [link-ul](https://wordpress.org/plugins/dexonline-searchbox/) către el. Se mai poate instala intrând în Dashboard-ul unei instanțe de WordPress și căutându-l printre pluginuri.

**Comment by CatalinFrancu** [comment]
Excelent! L-am instalat și eu pe blogul meu. A fost nevoie să editez bara laterală și să adaug explicit modulul. Am adăugat link către modul din pagina de unelte. Mulțumim!
