### ISSUE TITLE
Ascunde definițiile din DEX '98 când există o definiție identică din DEX '09

### ISSUE THREAD

**Issue by CatalinFrancu** [dexonline/dexonline#386]
Și, în general, la fel pentru ediții consecutive (DN - MDN, DOOM - DOOM 2 etc.).

O definiție este identică cu cea din ediția anterioară când `Definition.similarSource = 1`. Informațiile despre ediții sunt în tabela `SimilarSource`.

**Comment by andreiepure** [comment]
duplicat al lui #331 ?

**Comment by CatalinFrancu** [comment]
De acord. Am mutat acolo niște comentarii și îl închid pe ăsta.
