### ISSUE TITLE
Decide what to do with DLRLV

### ISSUE THREAD

**Issue by CatalinFrancu** [dexonline/dexonline#39]
If we decide to add it, we need to allow newlines in its definitions (i.e., replace `\n` with `<br/>`

**Comment by CatalinFrancu** [comment]
Radu - tu ești tartorul pe lista de dicționare. :-) Eu n-am o opinie, căci n-am văzut un original.

**Comment by CatalinFrancu** [comment]
Va fi rezolvat într-un fel sau altul de #109. Îl propun pentru închidere.

**Comment by raduborza** [comment]
Dacă va fi rezolvat de #109, hai să îl închidem!
