### ISSUE TITLE
Meta description diferit in functie de cuvant

### ISSUE THREAD

**Issue by revolter** [dexonline/dexonline#395]
Ar fi fain ca descrierea paginilor sa se schimbe pe paginile `http://dexonline.ro/definitie/*` astfel incat sa fie indexate de Google si sa ofere un preview direct. De exemplu, ar putea cuprinde textul primei definitii, si in loc de:

![2015-03-03 21-28-39](https://cloud.githubusercontent.com/assets/5748627/6470473/8e2fe7f2-c1ec-11e4-9150-d199e1404c21.png)

sa apara asa:

![2015-03-03 21-30-35](https://cloud.githubusercontent.com/assets/5748627/6470476/96d90d0c-c1ec-11e4-9eb4-2b3de2c395c9.png)

**Comment by hetmann** [comment]
Poti modifica/adauga wwwbase/search.php la linia 295 urmatoarea parte de cod PHP:

// cuv description from searchResults
```php
if (isset($searchResults)) {
  $cuvResults = array_values($searchResults)[0]->definition['htmlRep'];
  $page_description = $cuvResults ? strip_tags($cuvResults) : $page_description;
}
```

**Comment by revolter** [comment]
@hetmann, Faci tu un pull request?

**Comment by CatalinFrancu** [comment]
Salut,

Încă nu avem o opinie despre acest feature request. Vă mulțumim pentru dorința de a ne ajuta, dar nu vrem să munciți degeaba. Ne mai documentăm. Ezităm deși ideea este utilă pentru oameni, dar este posibil rea pentru noi (ne va reduce numărul de pagini afișate).

**Comment by revolter** [comment]
@CatalinFrancu, Inteleg acum de ce e mai ok asa, inchid issue-ul?

**Comment by CatalinFrancu** [comment]
De acord.
