### ISSUE TITLE
Extensii pentru Chrome și Firefox

### ISSUE THREAD

**Issue by CatalinFrancu** [dexonline/dexonline#409]
Comportamentul poate lua diverse forme - selectarea unui cuvânt și click pe o iconiță, sau apăsarea unei combinații de taste etc. Probabil ar trebui o interfață personalizabilă.

Intenția este să meargă mai repede decât deschiderea unui tab nou + căutare.

**Comment by Coropisnita** [comment]
Pentru Firefox există [Dictionary Search](https://addons.mozilla.org/en-US/firefox/addon/dictionarysearch/), în care poți adăuga dexonline și orice alt site. Selectezi cuvântul > click-dreapta > caută in dexonline.

Pentru Chrome am gasit [Lookup Definitions Online](https://chrome.google.com/webstore/detail/lookup-definitions-online/okmbiihjdbcblijmobaacddifcoaggeg), asemănător, dar mai puțin flexibil. Probabil ar fi ușor [de modificat](https://github.com/pMan/Lookup-for-chrome) să includă dexonline.

Sau vreți o extensie dedicată pentru dexonline?

**Comment by CatalinFrancu** [comment]
M-am jucat un pic cu Dictionary Search pentru Firefox. De acord, face cam tot ce vrem noi. Nu e evident cum se configurează. Adică îl găsești în pagina de Extensii, dar s-ar putea să fie prea greu pentru mulți. Ar merita documentat cu capturi de ecran, așa că țin tichetul deschis.

Și cred că ar fi utilă o opțiune să deschidă pagina în același tab. Sau măcar într-un tab adiacent. Acum deschide dexonline în ultimul tab, deci e greu să navighez acolo fără mouse. Hai că le trimit un review + feature request.

**Comment by CatalinFrancu** [comment]
I-am scris lui pMan, autorul lui Lookup Definitions Online, rugându-l să adauge și dexonline.ro la listă.

Am mai găsit și [Context Menu Search](https://chrome.google.com/webstore/detail/context-menu-search/ocpcmghnefmdhljkoiapafejjohldoga), care poate fi extins. Dar metoda e complicată, căci meniul contextual cere clickuri în plus. De asemenea, ar fi tare mișto să deschidă un popup, nu un tab. Acum m-am nărăvit, am pretenții. :-)

**Comment by CatalinFrancu** [comment]
Pare că acum avem ambele extensii!
