### ISSUE TITLE
Click pe cuvinte în Internet Explorer nu merge

### ISSUE THREAD

**Issue by bogdan-calapod** [dexonline/dexonline#410]
Pe Internet Explorer apare tooltip-ul cu „Click pentru a naviga la acest cuvânt” însă dacă dau click nu se întâmplă nimic.

**Comment by raduborza** [comment]
IE nu mai are vreun viitor. Nu cred că are sens să reparăm bugul ăsta.

În data de 9 iunie 2015, 10:36, bogdan5844 <notifications@github.com> a
scris:

**Comment by CatalinFrancu** [comment]
Cel mai probabil bugul a apărut într-unul din commiturile 305c0af7d1fbd9cb2f780131c84883bb0705158f sau 791eee26fecbc9878df269564978ab6a70f28f9d.

Și eu sunt de acord că bugurile de IE sunt foarte, foarte jos pe lista de priorități. Este software neliber și orice minut investit pentru a-l susține este un minut pierdut. În plus, ne e greu să testăm site-ul în IE pentru că nu îl putem rula.

**Comment by liviuroman** [comment]
Pentru că era în discuție un commit făcut de mine, am zis să verific să nu cumva să fi stricat ceva :)

Problema a apărut cu foarte mult timp în urmă. Spun asta pentru că pe Internet Explorer nu ajunge în if-ul cel mare din funcția **searchClickedWord**. Nu intră nici în if, nici in elseif iar restul codului e "inutil" deoarece nu se generează variabila **word**. 

Ar trebui să testeze cineva pe Microsoft Edge. Dacă nici acolo nu merge, eu zic că merită efortul să reparăm eroarea. Revin cu un comentariu dacă reușesc să testez eu.

**Comment by CatalinFrancu** [comment]
Ah, ok, mulțumesc pentru completări. Este posibil ca bugul să fie mai vechi decât modificările tale.

Dacă ai un IE la îndemână și vrei să testezi / repari, noi îți mulțumim. Dar, din nou, este o folosire tare proastă a timpului tău. :-)

**Comment by liviuroman** [comment]
Am testat azi și din nefericire, nici pe Edge nu merge. Se pare că "noul" browser a învățat multe din cel vechi :smiley: Nu am avut onoarea să mă "joc" prea mult cu el, așa că nu vă pot spune de ce nu merge. Cert este că nu intră în acel if. 

În schimb am o nedumerire. Mai sus, în comentariu, este menționat un link de pe Stackoverflow de unde a fost inspirată acea bucată de cod. Dacă pun direct funcția aia, merge perfect. De ce nu a fost pusă funcția așa cum este în acel exemplu? S-a încercat să se facă suport pentru IE4+? 

Pe 29 o să-mi instalez noul Windows. Marele 10 :smile: Atunci o să pot cerceta mai bine problema.

**Comment by CatalinFrancu** [comment]
Mulțumesc pentru testare. Trimiți tu un pull request, te rog? Și apoi mă asigur că merge și pe Chrome / Firefox. Mulțumesc!

**Comment by CatalinFrancu** [comment]
Iată și feedback pentru Maxthon de la un utilizator:

Browserul meu implicit este MAXTHON. După cum am văzut el suportă și Trident și Webkit. Am însă neplăcerea că redirecționarea către deiniții în cazul unui click pe un cuvânt nu merge așa cum ar trebui. Am investigat problema și am ajuns la concluzia că o parte din scriptul din dex.js ar trebui schimbat ca să fie compatibil cu toate browserele.

E vorba de [...] searchClickedWord în [dex.js](https://github.com/dexonline/dexonline/blob/master/wwwbase/js/dex.js)

care în MAXTHON se împotmolește la metoda Selection.modify() [pe mozilla e exemplificată cu avertizarea ca fiind Non-Standard ... https://developer.mozilla.org/en-US/docs/Web/API/Selection/modify]

Deși MAXTHON suportă Webkit, când intră în if-ul ce conține:

      s.modify('move', 'forward', 'character');
      s.modify('move', 'backward', 'word');
      s.modify('extend', 'forward', 'word');

nu returnează adecvat, cuvântul ce conține ă, â, î, ș, ț, ci îl trunchiază, trunchiere depinzând de poziția în care s-a dat click. Ori nu merge până la început, ori nu merge până la capăt din cauza caracterelor cu diacritice.

Astfel, cred că funcția dată ca răspuns inițial pe stackoverflow va funcționa pe toate browserele:

[Bineînțeles, ”str” mai trebuie cosmetizat, pentru că înhață semnele de punctuație.] :)

$(".clickable").click(function(e){
         s = window.getSelection();
         var range = s.getRangeAt(0);
         var node = s.anchorNode;
         while(range.toString().indexOf(' ') != 0) {                
            range.setStart(node,(range.startOffset -1));
         }
         range.setStart(node, range.startOffset +1);
         do{
           range.setEnd(node,range.endOffset + 1);
        }while(range.toString().indexOf(' ') == -1 && range.toString().trim() != '');

        var str = range.toString().trim();
        alert(str);
       });

Eu am testat cu succes acest cod pe MAXTHON.

**Comment by himself73** [comment]
EdgeHTML din Microsoft Edge nu are implementat ”.modify” și nici ”document.selection”, din această cauză nu intră nici în if, nici în elseif. Mnah. La debug, ambele funcții apar ca și ”undefined”.

**Comment by CatalinFrancu** [comment]
Am mai făcut o căutare, pare că există un [plugin jQuery](https://github.com/megahertz/jquery.get-word-by-event) pentru asta. Dacă cineva vrea să-l încerce... :-)

**Comment by himself73** [comment]
Am testat în IE11, Edge, Chrome, Opera, Firefox, Maxthon plugin-ul sugerat de Cătălin, și anume: [plugin jQuery] (https://github.com/megahertz/jquery.get-word-by-event)
În afară de IE11 și Firefox, care intră în ”if”-ul corespunzător lor, toate celelalte intră la ”if”-ul cu Webkit, inclusiv EDGE.
Webkit:
Ceea ce e neplăcut la implementarea aceasta este că stringul returnat trebuie cosmetizat de caracterele (),.[];- etc. pe care le înhață. Neplăcere ar fi la cuvintele cu cratimă: ”într-o”, ”s-a”,  etc. 
IE11:
returnează curat, fără caracterele (),.[];- , orice cuvânt. Neplăcere ar fi că ”range.expand('word');”-ul se oprește la cratimă.
