### ISSUE TITLE
Ancorează de bottom bannerul de pe m.dexonline.ro

### ISSUE THREAD

**Issue by CatalinFrancu** [dexonline/dexonline#411]
**Update:** Bannerul există deja și merge. A rămas însă să-l ancorăm de bottom. Redenumesc tichetul ca să reflecte asta.

----

Statisticile de trafic sunt: 59% desktop, 39% mobil, < 4% tablete. Ar merita să experimentăm cu un banner și pe skinul mobile.

Primul pas este să stabilim amplasarea și rezoluția. Apoi mă ocup eu de crearea campaniilor.

**Comment by raduborza** [comment]
Da, este un motiv viabil!

Radu

În data de 22 iulie 2015, 12:42, Cătălin Frâncu <notifications@github.com>
a scris:

**Comment by liviuroman** [comment]
Merge poziționat între căutare și "Cuvântul zilei". Cu siguranță nu merge un banner cu rezoluție fixă. Trebuie ceva fluid, din punctul meu de vedere.

**Comment by CatalinFrancu** [comment]
Am făcut un experiment cu 2131820e29185abba69256333d5eb96ad20c63e0. Este sus de tot, deasupra meniului. AdSense are deja bannere responsive (https://support.google.com/adsense/answer/3213689?hl=en).

**Comment by sandriu** [comment]
Eu nu aș poziționa un banner pe mobil în interiorul paginii, mi s-ar părea o ticăloșie să întrerupi flow-ul utilizatorilor cu publicitate, pe un ecran mic. O soluție elegantă ar fi plasarea banner-ului sus de tot în pagină (deasupra meniului global) sau jos de tot în pagină, dedesuptul footer-ului.

**Comment by raduborza** [comment]
Și eu am văzut că bannerele sînt de obicei jos (mai rar sus), uneori rămîn
pe ecran tot timpul.
Dar dacă sîntem în dubiu ne uităm să vedem cum fac alții (deșii în
principiu alții fac rost de donații și/sau au alte surse de venituri).

R.

În data de 9 august 2015, 13:25, Sonia Frâncu <notifications@github.com> a
scris:

**Comment by CatalinFrancu** [comment]
Și mie mi-ar plăcea să fie bannerul jos, dar trebuie să rezolvăm următoarea problemă.

* AdSense ne dă bannere responsive, dar trebuie să lăsăm nespecificată înălțimea div-ului (punem doar `width: 100%`).
* Div-ul se ancorează jos cu ceva de genul `position: fixed; bottom: 0`
* Restul paginii trebuie și el inclus într-un div, altfel bannerul va încăleca definițiile
* Și deci nu mi-e clar cum putem specifica înălțimea corectă pentru conținut, fără să o știm pe cea pentru banner.

**Comment by raduborza** [comment]
Nu cred că e diferit de a avea bannerul sus...

Vrei să zici că vrem ceva de genul ăsta, nu? http://jsfiddle.net/LLv3g0n1/1/

R.

În data de 12 august 2015, 16:41, Cătălin Frâncu <notifications@github.com>
a scris:

**Comment by CatalinFrancu** [comment]
E mai complicat ceva, căci nu ai voie să pui `height` pe `footer` (și-l pune AdSense odată ce servește bannerul). Și atunci bannerul îți ascunde conținutul:

http://jsfiddle.net/LLv3g0n1/2/

Pe ultima linie ar trebui să se vadă textul „ultima linie”.

**Comment by raduborza** [comment]
Păi de ce ar trebui să avem interdicția asta? AdSense nu rescrie
proprietatea height, chiar e nevoie să nu fie definită?
Mai sap!

În altă ordine de idei, văd că skinul de mobil s-a bulit (textele cu
©,licența și găzduirea erau fixate în partea de jos și erau și centrate,
acum văd că se duc sus, stînga). O să încerc să le repar că așa se vede
aiurea.

În data de 20 august 2015, 08:58, Cătălin Frâncu <notifications@github.com>
a scris:

**Comment by CatalinFrancu** [comment]
Am mai săpat un pic. De fapt, chiar dacă definești `height` în CSS, footerul tot îți va ocupa ultima linie din conținut. La tine nu se vedea, căci nu aveai destul conținut ca să depășească un ecran. Pentru a rezolva asta, trebuie să pui și pe conținut un `margin-bottom` egal cu `height`-ul de pe footer:

http://jsfiddle.net/LLv3g0n1/3/

Și de aici problema: da, AdSense va rescrie proprietatea `height`, dar atunci trebuie să ne prindem și noi să rescriem `margin-bottom` pe conținut.

Hm, trebuie să meargă cumva mai simplu.

**Comment by sandriu** [comment]
Tichetul acesta a devenit inutil deoarece am unificat interfața de desktop cu cea de mobil în august 2016.
Îl închid.

**Comment by CatalinFrancu** [comment]
Hm, eu l-aș redeschide, căci nevoia rămâne. Înălțimea bannerului se calculează după încărcarea paginii, ceea ce face elementele paginii să alerge, ceea ce este un efect tare neplăcut. Îl putem lăsa să acopere conținutul, dacă altfel nu merge.
