### ISSUE TITLE
Design responsive

### ISSUE THREAD

**Issue by CatalinFrancu** [dexonline/dexonline#412]
Că e la modă. :-)

**Comment by sandriu** [comment]
Pentru desktop și tablete, layout-ul va rămâne în mare cum este acum (cu mici schimbări, în funcție de nevoile de adaptare la mobile).
Pentru mobile, atașez 3 wireframe-uri (aici ecran de 480x800px, cu ceva scroll vertical), cu mențiunea că anumite link-uri din meniul global (hamburger menu) ar trebui ascunse pe mobil, fiindcă paginile respective vor fi greu de folosit de pe ecrane de telefon mobil.

![prototip-mobile-homepage](https://cloud.githubusercontent.com/assets/1265882/9429278/6e94a68e-49d3-11e5-96a6-6f0d3e4b73b9.png)
![prototip-mobile-global-menu](https://cloud.githubusercontent.com/assets/1265882/9429277/6e938de4-49d3-11e5-9e04-e1138058bec1.png)
![prototip-mobile-user-menu](https://cloud.githubusercontent.com/assets/1265882/9429279/6ea66ae0-49d3-11e5-9d78-31b197d9ca35.png)

**Comment by CatalinFrancu** [comment]
Excelent! Începe bine.

În prezent, `templates/pageLayout.html` are un mare „if” care diferențiază paginile de mobil și desktop (caută fullMenu). Practic, am unificat skinurile, dar nu în mod real, ci punând două într-unul sub un „if”. :-) Aș vrea să renunțăm la asta, cu riscul de buși skinurile vechi.

De aceea, noul skin ar trebui să fie chiar regândit de la zero (sigur, bucăți mari din implementare pot fi preluate din vechile skinuri). Nu este un scop să fie 99% identic cu zepu. Poate doar să păstreze câteva elemente comune ca să nu se sperie utilizatorul (culorile, de exemplu).

Media queries sunt bune, dar aș vrea să nu abuzăm de ele ca să prezentăm două site-uri complet diferite. Un exemplu: umbrele meniurilor pot dispărea.

Cred că merită să facem o analiză a elementelor din pagină, să vedem care trebuie să fie vizibile sau compactate cumva. Le marchez cu trei categorii mari: desktop, tabletă, mobil (și „toate”).

### Pe toate paginile

**Logo mic:** toate (SVG?)

* Pe pagina principală este logo-ul mare.

**Meniul principal**

* informații: toate
* contact: toate
* blog: tabletă, desktop
* contribuie cu definiții: desktop
* topul voluntarilor: desktop
* informații pentru programatori: desktop
  * pe tabletă și mobil: o pagină „implică-te” care să explice, în 2-3 fraze, [cum te poți implica](http://wiki.dexonline.ro/wiki/Informa%C8%9Bii#Cum_ne_pute.C8.9Bi_ajuta).
* abrevieri: desktop
* articole: desktop, tabletă
* ghid de exprimare: toate
* cuvântul zilei: toate? depinde și de widgets, vezi mai jos
* cuvântul lunii: desktop, tabletă
* cuvinte aleatoare: desktop
* scrabble: toate
* unelte: desktop
  * pe tabletă și mobil Android: detectăm sistemul de operare și linkăm direct la aplicație
* legături externe: desktop

**Meniul de utilizator**

Aici trebuie discutat un pic. Pe desktop / tabletă vom păstra toate opțiunile, după caz:

* login
* logout
* preferințe
* profilul meu
* cuvinte favorite
* pagina moderatorului

Dar pe mobil nu are sens să permitem login, caz în care doar opțiunea „preferințe” mai rămâne. Și atunci propun așa:

* pe desktop și tabletă: meniu complet
* pe mobil: meniul utilizator ascuns complet, dar în meniul principal adăugăm o opțiune nouă, „preferințe”.

Cred că e mai bine așa decât să fie o poză de avatar cu o singură opțiune.

**Donează:** toate

**Flash messages:** toate (e.g. redirectarea de la oprobiu la oprobriu)

* Trebuie găsit un loc mai bun pentru ele. Poate chiar un overlay care dispare în 2-3 secunde.

**Cutia de căutare:** toate (duh)

**Banner:** toate

* Probabil lățime 100%, dar nu mai mult de 728px pentru ecrane mari.

**Widgets FB / G+ / Blogger:** toate

* Dar aș elimina caseta mare de FB de la sfârșitul paginilor de căutare

**Copyright, licență, găzduire:** toate

### Pe pagina principală

**Logo mare:** toate

**Tagline:** desktop, tabletă - sau și pe mobil?

**Widgets:** analizate individual

* Poate doar cuvântul zilei și spânzurătoarea pe mobil?
* Tot pe mobil, ar merita înlocuit linkul „personalizare elemente” cu x-uri pe fiecare cutie (de discutat)

**Mission statement:** toate

**Comment by CatalinFrancu** [comment]
Un comentariu de la #104: în paginile de rezultate, linkul de declinări / conjugări trebuie să fie vizibil.

**Comment by sandriu** [comment]
M-am uitat acum pe Google Analytics: în ultimul an (2015) aproximativ 42% din traficul total a fost pe mobile (iar restul pe desktop), adică **de 2 ori și ceva mai mult** decât în anul anterior (2014: 18.82% trafic pe mobile). Asta înseamnă că ar trebui să păstrăm pe mobil cât mai mult din interfața de desktop.

**Comment by CatalinFrancu** [comment]
Îl închid. Avem alte tichete cu eticheta [responsive] care descriu ce mai e de făcut.
