### ISSUE TITLE
Unește „dex” și „online” în logo

### ISSUE THREAD

**Issue by CatalinFrancu** [dexonline/dexonline#415]

**Comment by sandriu** [comment]
Gata, vezi mail.

**Comment by CatalinFrancu** [comment]
M-am uitat prin toate imaginile acum și mai trebuie convertite și https://dexonline.ro/img/logo-dexonline-2.png, precum și toate medaliile. Redeschid tichetul.

**Comment by sandriu** [comment]
Pentru medaliile refăcute, vezi mail (thread-ul numit "Proiect: pagina utilizatorului DEX online + embleme").

**Comment by sandriu** [comment]
Pentru logo pătrat, vezi mail (thread-ul numit <<Unește „dex” și „online” în logo (#415)>>).
