### ISSUE TITLE
Cand cuvantul lunii curente este accesat cu /an/luna in URL, linkul 'următorul' este prezent

### ISSUE THREAD

**Issue by andreiepure** [dexonline/dexonline#416]
Reproducere (acum e luna noiembrie - 11)
1. Navighează în browser la https://dexonline.ro/cuvantul-lunii/2015/11 (luna curentă)
2. Apasă pe următorul

Comportament existent: există linkul "următorul" care duce la https://dexonline.ro/cuvantul-lunii/2015/12 (următoarea lună, care nu are cuvânt și se redirecționează către https://dexonline.ro/cuvantul-lunii)

Comportament așteptat: nu ar trebui să apară linkul "următorul", fiindcă este luna curentă

**Comment by CatalinFrancu** [comment]
De acord. Același comportament este așteptat și pentru https://dexonline.ro/cuvantul-lunii (fără /an/lună). Fiind implicit vorba despre luna curentă, nu trebuie să existe linkul „următorul”.
