### ISSUE TITLE
Aceeași definiție în mai multe luni (cuvântul lunii)

### ISSUE THREAD

**Issue by ZalexRO** [dexonline/dexonline#417]
Salut!

Am citit despre bug-ul anterior (cuvântul lunii) și am verificat și pe cele din urmă. Lunile Aprilie - Septembrie au aceeași definiție: mir. Apoi, mai din urmă, Februarie și Martie au aceeași definiție, de asemenea: hebdomadar. În 2014 e cam la fel - mai multe luni cu aceeași definiție. Nu știu dacă e un bug sau nu - eu zic că e, după cum se numește rubrica, "cuvântul lunii".

Comportament așteptat: fiecare lună să aibă o definiție diferită.

Nu știu care-i algoritmul după care alegi cuvântul lunii, dar poate ar fi util să faci o listă cu 12 cuvinte (respectiv 12 ilustrații) pentru 2016 și să fie postate automat pe site în prima zi a lunii respective.

**Comment by CatalinFrancu** [comment]
Salut,

Nu e chiar bug - în lunile în care nu avem un cuvânt, pur și simplu nu alegem unul, îl lăsăm pe cel din luna anterioară. Asta se întâmplă când nici nu s-a detașat vreun cuvânt în numărul de căutări nici nu s-a întâmplat vreun eveniment care să trebuiască marcat. Datorită acestui algoritm, nici nu putem să alegem în avans cuvântul.

Îl închid tentativ ca "will not fix", dar mai vorbim dacă e!
