### ISSUE TITLE
Abrevierile trebuie să stea în tabele, nu în fișiere

### ISSUE THREAD

**Issue by CatalinFrancu** [dexonline/dexonline#420]
Fișierele din [docs/abbrev](https://github.com/dexonline/dexonline/tree/master/docs/abbrev) sunt legate conceptual de valori și ID-uri din tabela Source. Asta creează probleme

De exemplu, dacă cineva folosește softul dexonline pentru a-și publica un dicționar propriu, va vrea să pornească cu o bază de date nouă. În acea bază de date ID-urile vor avea alte semnificații. Dacă își creează un fișier nou cu abrevieri pentru dicționarul său, acesta îi va apărea ca modificare în Git, dar nu-i va putea face commit.

Cred că soluția corectă este ca abrevierile să stea într-un tabel. Nu aș investi timp și într-o interfață de editare, căci abrevierile vor dispărea oricum după #66 (structurarea definițiilor).

**Comment by CatalinFrancu** [comment]
Niște TODO-uri care parcă țin tot de acest tichet.

- [ ] Întrucât forma lungă acceptă notația noastră internă, care apoi este convertită cu `Str::htmlize()`, și întrucât HTML-ul rezultat este folosit ca tooltip (atributul HTML `title="..."`), undeva trebuie să verificăm că HTML-ul rezultat nu conține ghilimele, ca să nu corupă HTML-ul din jur. Probabil conversia formelor lungi la HTML ar trebui făcută în momentul încărcării din baza de date, sau putem chiar stoca HTML-ul într-un câmp nou pe `Abbreviation`.
- [ ] Probabil încărcarea în masă a abrevierilor nu mai este necesară. Odată ce întâlnim o formă scurtă, putem încărca doar acea înregistrare din `Abbreviation`.

**Comment by LadislauStrifler** [comment]
1. Soluția cea mai simplă este ca șirul `$hint`, întors de `htmlize`, să-l trecem prin `htmlspecialchars`. E bine?
2. Nu mă prind despre ce încărcare în masă e vorba. Poți elabora puțin mecanismul gândit de tine? 

Ar mai fi ceva ce deranjează la formatare, și anume: un diez (`#`) solitar care bulește `$hashmap`-ul, iar tot ce e după el nu mai contează. 
De asemenea, ar trebui un `css `separat pentru `tooltips`, deocamdată e `bgcolor: black`, ceea ce-l face prea sumbru. Trebuie ajustat și `bgcolor`-ul pentru șirurile spațiate, că arată nasol pe negru (dacă rămâne negru).
Le poți băga în TODO și mă ocup.

**Comment by CatalinFrancu** [comment]
1. `htmlspecialchars` ar ajuta, dar ar putea arăta urât. Dacă, din orice motiv, pui `%text%` în forma lungă, atunci în tooltip vei obține, textual, `<span class="spaced">text</span>`. Iar dacă pui `@text@`, obții textual `<b>text</b>`. Deci care mai este rostul trecerii prin `htmlize()`?
Am putea să facem `htmlize()` imediat ce încarci fișierul și acesta să-ți dea erori și să refuze formatări care includ ghilimele. Atunci nu mai este nevoie de `htmlspecialchars`. Boldul, italicul etc. se văd bine, iar `%text%` și altele sunt pur și simplu interzise.

2. Ignoră, am judecat eu greșit. Ziceam că poți doar încărca abrevierea care te interesează, având o tabelă indexată, și deci `Abbrev::loadAbbreviations()` n-ar mai fi necesară. În realitate, potrivirea abrevierilor e mai complicată - _loc. adv._ trebuie parsată ca o singură abreviere, nu două, etc. Deci e în continuare nevoie de întreaga listă simultan.

Restul le-aș face în _issues_ separate, ca să nu o deturnăm pe aceasta.

**Comment by LadislauStrifler** [comment]
1. Bine, deci fac o verificare a `csv`-ului
  1.1 Extind tabela Abbreviation cu un câmp `longHtml`, împreună cu redenumirea lui `long` în `longInternal`? 
  1.2 Simplificat, în `long` bag `htmlize`-ul a ceea ce vine din csv?

**Comment by CatalinFrancu** [comment]
Aș merge pe 1.1. Dacă vreodată vom avea interfață de editare, ar fi derutant pentru utilizator ca la reafișare să-i apară cu totul altceva decât când a salvat.

Dar aș lăsa asta pentru V2.0 (un _issue_ nou), ca să nu ținem PR-ul deschis prea mult. Doar bucata cealaltă, cu migrarea datelor, mai trebuie făcută.

**Comment by LadislauStrifler** [comment]
Nu ai reînviat patch-ul corespunzător. :) Am făcut un nou PR.
