### ISSUE TITLE
Ascunderea individuală a formelor flexionare

### ISSUE THREAD

**Issue by CatalinFrancu** [dexonline/dexonline#423]
Chiar dacă modelul permite anumite flexiuni, unele lexeme nu le suportă. De exemplu, _copilule / copile_ sunt ambele ok, dar numai _calule_ e ok (nu și _cale_).

Avem nevoie de o interfață rudimentară cu autocompletare care să permită marcarea / demarcarea formelor ca ascunse. Formele ascunse nu trebuie să apară în paradigme (posibil nici în LOC, căutările de formă flexionară pentru Scrabble etc.).

(Actualizat după discuții cu Matei)

**Comment by raduborza** [comment]
Mmm, nu cred că e un model tocmai potrivit. Se aplică în afară de vocativ? Dacă nu, e mai firesc să gîndim altfel problema (vocativul nu se aplică decît rareori la inanimate, deci e mai firesc să adaugi un tag de vocativ decît să invalidezi modelul general.)

**Comment by CatalinFrancu** [comment]
Nici eu nu sunt încântat de soluția asta. Îți mai dau și eu un motiv: paradigma se tot regenerează, chiar dacă salvezi lexemul fără să fi modificat nimic. De asta nici nu pot salva informația direct în InflectedForm. Asta cu ForbiddenForm e o cârpeală.

Pe de altă parte, trebuie să gestionăm cumva cazul când unele lexeme au forme de vocativ, dar doar o parte din cele permise de model. Multe modele M au problema asta, cum ar fi:

* M12: _copil, moșnegel, cocoșel_ au două forme, _cal_ are doar _calule_ (nu și _cale_)
* M3: _fârtat_ și _comandant_ au două forme, _pilot_ are doar una

În plus, există modele cu 3-4 forme de vocativ : F2 (piuă) și F156 / F157 / F158 (viorea, mărgea etc.). Nu am analizat dacă acelea au astfel de excepții.

Mai discut cu Matei.

**Comment by CatalinFrancu** [comment]
Am trecut prin modelele M1-M36 și am găsit 12 modele care au această problemă:

M1 (l'up) - hatman, blănar / lup, puișor, cocoș
M3 (bărb'at) - fârtat, comandant / coiot, bit
M5 (br'ad) - brigand?, voievod? / brad, plod
M10 (m'ânz) - arbuz?, harbuz? / boz
M12 (c'al) - copil / cal
M13 (s'ac) - vornic, stolnic, drac / melc
M14 (f'ag) - martalog / mag, fag
M16 (mon'ah) - ierarh, patriarh / șah
M20 (buște'an) - agarean / hrean
M23 (podb'al) - zaporojan / swingman, ombudsman
M26 (p'ăr) - văr / măr
M32 (băi'at) - băiat / eluant

În aceste condiții, dublarea modelelor nu este practică.

**Comment by raduborza** [comment]
Dar cine a zis că dublarea modelelor? Cum vocativul nu a fost luat în considerare cînd au fost create modelele din DMLR, nu are sens să ne batem capul cu dublarea, care duce la înmulțirea peste măsură a modelelor.
Apropo, văd că la toate femininele apare o formă de vocativ. Se bazează pe GLR, că din cîte țin eu minte este o formă populară, dar neliterară (n-am apucat să verific în GLR). În plus, unele sînt hilare: „iesleo” :)
Dacă vrem să facem treaba cum trebuie, atunci e necesară o analiză. Simplificat, cînd cuvîntul are formă de vocativ, la  feminin avem -o, la masculin/neutru avem -e, iar la plural e identic cu G-D, pl, articulat. Eventual cu niște alternanțe ale modelului, pe care le știm deja.
Cînd vocativul masculin singular se formează de la plural este o excepție care trebuie marcată ca atare, dar modelul de formare nu se schimbă.
Deci aș propune ceva de genul (să zicem că avem cuvintele din M14):
- M14 pentru cele fără vocativ;
- M14V pentru cele cu vocativ canonic;
- M14v pentru cele cu vocativul pornit de la N, sg., art.;
- M14Vv pentru cele cu ambele.

Sigur, aștept să văd o listă cu toate propunerile de vocativ (

**Comment by CatalinFrancu** [comment]
Între timp mi-a venit idea să lucrăm cu restricții, că exact pentru asta le avem. Putem folosi tot cum spui și tu, două restricții V și W. L-am întrebat pe Matei.

Matei zice că toate vocativele ar trebui permise, căci e greu să tragem linia undeva: vântule, râule, dorule, trenule,... Iar FRSc, dacă le va accepta, la va vrea pe toate.

**Comment by raduborza** [comment]
În acest caz trebuie să ne separăm cumva. Chiar ar trebui să ascundem vocativele alea că nu e tocmai profesionist... :) Numai cînd vezi formele de genul: șoseao! grajdule! gresio! îți vine să rîzi. 
Dacă ei vor să folosească toate vocativele e treaba lor, dar nu e conform gramaticii. Iar noi trebuie să fim sincronizați cu gramatica limbii române, nu cu Federația de Scrabble.

**Comment by CatalinFrancu** [comment]
Am implementat restricții pentru formele de vocativ. Deschid un tichet separat pentru restul implementării (bife de animat / personificabil).
