### ISSUE TITLE
Localizarea skinului

### ISSUE THREAD

**Issue by CatalinFrancu** [dexonline/dexonline#424]
Ar fi drăguț să localizăm site-ul în engleză, folosind gettext sau altă unealtă. O localizare completă ar fi un efort uriaș și în mare parte inutil (nu știu dacă există o nevoie reală pentru toate paginile). Dar
1. Putem localiza cel puțin pagina principală și paginile cu rezultate
2. Putem încerca să extragem automat toate șirurile hard-codate în fișierele .php și .tpl.

O implementare completă ar trebui să includă și un cron job care să verifice periodic să nu apară șiruri noi nelocalizate. Sau, și mai bine, un hook pre-commit.

**Comment by andreiepure** [comment]
Și definițiile să fie tot în română sau să fie și definițiile localizate? Adică transformarea dexonline și în dicționar ro-en?

**Comment by CatalinFrancu** [comment]
A, nu, doar skinul! Actualizez tichetul ca să reflecte asta.

**Comment by CatalinFrancu** [comment]
Hm, am uitat că aveam un tichet! Implementat în #779.
