### ISSUE TITLE
Investighează load-ul pe server

### ISSUE THREAD

**Issue by CatalinFrancu** [dexonline/dexonline#426]
Buddy ajunge la load 8-9 după-amiezele. Amigo e mult mai relaxat.

**Comment by raduborza** [comment]
Cauza care e? php-ul?

**Comment by CatalinFrancu** [comment]
Tocmai, că nu știu. :-) Am senzația că mysql, din ce am mai văzut prin top. Asta ar explica și de ce amigo e așa de lejer, deși din Varnish îi trimitem 6 query-uri din 7.

Eu mai lucrez la o chestie luni și încep să investighez de marți încolo. Dacă ai tu timp mai devreme, ești invitatul meu!

**Comment by raduborza** [comment]
Eu o să fiu plecat în Polonia săptămîna viitoare... încerc duminică să îmi arunc o privire.
Măcar se corelează cu perioadele de trafic mai mare?

A, noi cîte procesoare avem pe buddy?

**Comment by CatalinFrancu** [comment]
Cică avem 4 procesoare, vezi `/proc/cpuinfo`.

M-am jucat azi un pic și am făcut următoarele:

* CPU-ul nu este o problemă, este în mare parte idle (`top`).
* Memoria nu este o problemă, sunt 3-4 GB în cached mem (`top`).
* Discul nu pare solicitat (`iostat` și `iotop`)
* Am dezactivat autocompletarea în cutia de căutare (`acEnable = 0` în `dex.conf`). Nu ajută semnificativ. Am reactivat-o.
* M-am uitat pe configurările lui php-fpm. Nu le înțeleg, dar nu cred că asta e cauza. Amigo e configurat la fel și este bine-mersi.

Una peste alta, suspectez că MySQL este de vină. Este cam primul în `top` și este principala diferență între buddy și amigo. Am continuat astfel:

* Am optimizat toate tabelele.
* Am convertit toate tabelele la MyISAM, care teoretic se pretează mai bine la nevoile noastre (citiri multe, scrieri puține). În special `LexemModel` și `LexemSource` erau InnoDB și sunt folosite frecvent.
* Am rulat [MySQLTuner](https://github.com/major/MySQLTuner-perl). E fantastic! El mi-a recomandat următoarele două modificări.
* Am crescut `max_connections` la 150 (era 100). Nu cred că e important, totuși.
* Am am activat query cache-ul (`query_cache_type = On` și `query_cache_size = 64M`). Cică poate fi un lucru rău dacă există scrieri prea dese. Momentan are un hit rate de 50%, mai vedem.

Pare că toate aceste lucruri au ajutat, dar a trecut și ora de vârf. Vedem în zilele următoare.

Ce mai urmează:

* Să mă prind cum pot afla câte requesturi trimite Varnish pe amigo/buddy. Am senzația că nu respectă configurarea din `/etc/varnish/default.vcl`, care specifică un raport de 6:1 (tocmai fiindcă buddy are și altele pe cap).
* Să monitorizez în continuare query cache-ul (`show status like "qcache%";`).
* Să mai implementez din recomandările lui MySQLTuner. Trebuie să las `mysqld` să ruleze o vreme înainte ca MySQLTuner să poată trage concluzii.

**Comment by raduborza** [comment]
Mai sînt niște tooluri pe site-ul percona: https://tools.percona.com/
Mi-e teamă că fără o sculă de monitorizare a serverului nu scăpăm.

Am rămas dator cu instalarea slave-ului. Ce zici, crezi că ajută? Sau ajută
dacă inversăm sensul: facem masterul pe amigo și slave-ul pe buddy?

Radu

În data de 18 ianuarie 2016, 19:19, Cătălin Frâncu <notifications@github.com

**Comment by CatalinFrancu** [comment]
Momentan load-ul e pe la 1,2-1,5, comparat cu 2,0-6,0 în zilele săptămânii la aceeași oră. Mai așteptăm, dar semnele sunt bune! Am mai modificat și

* Am crescut `max_heap_table_size` și `tmp_table_size` la 64 MB.

Cu slave-ul, sigur, încearcă ce ai tu chef! Amigo ar trebui să mai preia o parte din load. Dacă nu vrem să ne complicăm cu configurații master-slave, o altă variantă ar fi să mutăm OpenX pe amigo (baza de date și/sau serverul).

**Comment by CatalinFrancu** [comment]
A fost ok ieri. Loadul a fost maxim 3,7 vreme de câteva minute și sub 2,5 în majoritatea timpului. Și erorile 500+ s-au redus de la câteva sute la cinci (în special 504, pe care o dă Varnish când nu-i răspunde backendul). Mai monitorizez și zilele următoare.

Din recomandările mysqltuner e una care mă intrigă:

> Temporary tables created on disk: 93% (460K on disk / 494K total)

Asta deși i-am mărit memoria pentru tabele temporare. Mai sap.

**Comment by raduborza** [comment]
Păi load 3,7 înseamnă că sîntem ok (sigur, trebuie verificat că cele 4
procesoare au balansat corect procesele). În afară de sculele implicite
(top/htop,pstree, iostat etc.) avem instalat vreun tool de monitorizare?
Îmi pun în lista de TODO să mă uit pe
https://www.percona.com/webinars/2012-03-28-monitoring-mysql-with-percona-monitoring-plugins
(percona vine cu niște plugin-uri de monitorizare)!

Nu lua nici o recomandare dată de un tool drept literă de lege. Ideea e că
nu trebuie să avem tabele temporare (sau să avem cît mai puține). Bănuiesc
că baza de date încape în memorie integral, așa că dacă scăpăm de tabelele
temporare fac pariu ca scăpăm și de load.
Vezi că avem Percona, ceea ce înseamnă că putem să strîngem informații
despre query-urile SQL din perioada aglomerată, ca să vedem ce se întîmplă.
Cînd mă întorc mă ocup să văd care query-uri ne fac probleme și cum putem
fixa chestia asta!

Parcă am mai întrebat... Nu-i așa că nu avem un istoric al modificărilor de
configurație?

Radu

În data de 20 ianuarie 2016, 09:54, Cătălin Frâncu <notifications@github.com

**Comment by CatalinFrancu** [comment]
Nu avem nici un tool. Avem rapoartele pe care le oferă Nginx, FPM et al, colectate [pe wiki](http://wiki.dexonline.ro/wiki/Unelte_pentru_monitorizare). Dar nimic activ. Dacă vrei, instalează, sigur.

Query-urile lente se loghează la /var/log/mysql/mysql-slow.log. Așa m-am prins că autocompletarea era lentă din cauza clauzei „distinct”. Altele sunt normale (căutări cu FullTextIndex, chestii de admin, căutări cu expresii regulate).

Mda, nu înțeleg destul despre tabelele temporare, voi mai citi ca să învăț.

**Comment by raduborza** [comment]
Query-urile se pot analiza și cu pt-query-digest (sigur, trebuie pașii ăia
de care ți-am zis mai demult într-un e-mail). E ok dacă las de la 13.00 la
16.00 ?
Anul trecut query-urile lente erau logate în buddy-slow.log :) Ai schimbat
tu ceva? :)

Radu

În data de 20 ianuarie 2016, 13:46, Cătălin Frâncu <notifications@github.com

**Comment by CatalinFrancu** [comment]
Sigur, lasă la ce oră vrei tu.

Cred că migrarea la Percona a schimbat destinația logului. Deși e posibil să o fi editat eu manual la un moment dat.

Uitasem să răspund și la întrebarea despre istoric: nu, nu avem decât backup zilnic, dar mai departe de ieri nu mai avem istoricul.

**Comment by raduborza** [comment]
Sigur nu Percona a schimbat, că am făcut backup la variabile după instalare.

Foarte bine că aI schimbat în MyISAM, și eu mă gîndeam să îți propun asta.

Promit să îmi fac timp să studiez db-ul.
Pe 20 ian. 2016 18:31, "Cătălin Frâncu" <notifications@github.com> a scris:
