### ISSUE TITLE
[bug minor] Sortare inconsecventă în ordinea sensurilor

### ISSUE THREAD

**Issue by dan2468** [dexonline/dexonline#428]
„Pont” are două sensuri în multe dicționare.

Pe https://dexonline.ro/definitie/pont/expandat apare sensul 1 primul pentru: DEX '09 (2009), DOOM 2 (2005), DLRLC (1955-1957), Ortografic (2002); dar al doilea pentru: DEX '98 (1998), NODEX (2002), Sinonime (2002).

**Comment by CatalinFrancu** [comment]
Așa e, e enervant. Pe de altă parte, e unul din bugurile (multe) subsumate de #66. Când implementăm asta, implicit nu vom mai afișa definițiile vechi, deci ordonarea greșită nu va mai conta.

Dacă cineva vrea să repare, tranzitoriu, această problemă, va fi nevoie de un câmp nou pe tabela `Definition` care să reflecte acest indice numeric. Nu îmi este clar dacă îl putem extrage automat (probabil da). Dacă nu, trebuie să poată fi editat în `wwwbase/admin/definitionEdit.php`.
