### ISSUE TITLE
Autentificarea OpenId nu funcționează pentru Google

### ISSUE THREAD

**Issue by andreiepure** [dexonline/dexonline#432]
Autentificarea OpenId nu funcționează pentru conturi Google. Am încercat în zile diferite, problema se reproduce cu contul meu (nu am creat al cont, totuși).
Pași de reproducere:
1. Deschide dexonline.ro
2. Apasă pe Anonim -> Autentificare cu OpenId. Ar trebui să ajungi pe https://dexonline.ro/auth/login
3. Apasă pe Google. Ar trebui să fii redirectat pe site-ul Google, https://accounts.google.com
4. Apasă Permiteți, vei ajunge pe pagina revenireOpenidConnect.php.
5. Selectează Numele întreg și apasă autentificare. Vei ajunge pe https://dexonline.ro/auth/revendicare, care va fi o pagină blanc
6. Apasă F5 (refresh). Pagina https://dexonline.ro/auth/revendicare se va reîncărca cu eroarea "A apărut o eroare la autentificare. Vă rugăm încercați din nou."

După multiple reîncercări problema persistă.
Dexonline este în lista de aplicații acceptată în contul meu Google (vezi screenshot)

Browser: Firefox 44.0.2
OS: Windows 10

![dexonline_auth_bug1](https://cloud.githubusercontent.com/assets/9423335/13198496/95e59572-d812-11e5-9af6-5a49ff9f5fdc.PNG)
![dexonline_auth_bug3](https://cloud.githubusercontent.com/assets/9423335/13198502/beef70dc-d812-11e5-9d07-b8a1a8e7e797.PNG)
![dexonline_auth_bug6](https://cloud.githubusercontent.com/assets/9423335/13198510/f4b9555c-d812-11e5-9508-ee0eaef941a2.PNG)

**Comment by raduborza** [comment]
Chiar acum m-am conectat cu contul de Google... Cînd v-ați conectat cu succes ultima oară cu acest cont? Ați încercat cu browsere diferite?
Apropo, am avut o problemă cu autentificarea de la Yahoo și s-a rezolvat cu ștergerea tuturor cookie-urilor (de la Yahoo) din browser!

**Comment by CatalinFrancu** [comment]
S-ar putea să fie ceva intermitent. Ne-au mai lăsat una-două persoane mesaje pe FB cu aceeași problemă. Încerc să investighez acum, dar nu prea știu de unde să o apuc.

**Comment by CatalinFrancu** [comment]
Ah, acum am citit cu atenție punctele (5) și (6) din raport. Pagina goală este un bug care se întâmplă ocazional, nu înțeleg bine de ce, și pe care tot încerc să îl depanez. Are legătură cu stiva pe care o folosim (Varnish - Nginx - php-fpm). Dacă încă mai poți reproduce problema, ne-ar ajuta foarte mult să ne spui ce cod HTTP returnează pagina albă. Firefox pare să aibă o unealtă pentru asta (Ctrl-Shift-Q). Pun pariu că e 502 sau 503 sau pe-acolo.

De aici, pasul (6) e de așteptat. Există un nonce acolo care cauzează eroarea la reîncărcare.

**Comment by CatalinFrancu** [comment]
Chiar am găsit un bug! Am săpat prin loguri. Pare că ai deja un cont înregistrat cu această adresă de e-mail. Deci la pasul (5) încearcă să introduci adresa de e-mail și parola, sau să ceri recuperarea parolei dacă ți-ai uitat-o.

Problema merită rezolvată și la modul general. Trebuie gândite posibilitățile și făcut un pic de design. De exemplu, pot exista două identități OpenID cu aceeași adresă de e-mail (presupun că da)? Și ce vrem în acest caz:

* să permitem autentificarea doar cu una dintre ele
* să permitem oricâte identități OpenID pentru fiecare cont
** caz în care ce adresă de e-mail păstrăm? Facem câmpul editabil, ca pe vremuri?
* să permitem conturi multiple cu aceeași adresă de e-mail, un cont pentru fiecare identitate.

N-am o opinie clară, dar deschid un tichet de brainstorming.

**Comment by andreiepure** [comment]
confirm că asta era problema, m-am putut loga după autentificare, mulțumesc!
