### ISSUE TITLE
sugestie: inlocuit feedmyinbox

### ISSUE THREAD

**Issue by andreiepure** [dexonline/dexonline#437]
La cuvântul zilei (https://dexonline.ro/cuvantul-zilei/): "Vă recomandăm feed my inbox"
Pași:
1. Am mers la https://www.feedmyinbox.com/
2. Am introdus linkul dexonline și email
3. Am primit email de confirmare, am apăsat pe linkul de confirmare
4. Pe pagină mi s-a spus "You reached your feed limit. Please either remove number of feeds to equal current plan or upgrade your plan." Mi-au trimis și email cu asta.

Cum nu am vrut să îmi fac _încă_ un cont pe un sait, pentru a gestiona feedurile, am căutat o alternativă care are un UI aproape identic: https://blogtrottr.com/. Mâine voi vedea dacă funcționează și cât de deranjante sunt reclamele.

Poate mi s-a întâmplat doar mie, n-am testat și cu alt cont. Dacă se reproduce problema, poate trebuie schimbată sugestia.

**Comment by CatalinFrancu** [comment]
Confirm problemele. La mine a fost așa:

* La pasul 2, am bifat și căsuța care cere postările existente.
* Am primit acele postări, cu un link de confirmare a abonării.
* Acel link a deschis o pagină cu eroarea _You have exceeded the number of feeds for your plan. Please login to manage your feed._
* Peste un minut am primit și un e-mail despre _Feed limitation alert_.

Dacă faci tu cercetarea pentru un înlocuitor, noi zicem bogdaproste! :-) Dacă te ajută, am căutat [rss to email "no account"] și am găsit și http://www.shootthebreeze.net/blogalert/

**Comment by andreiepure** [comment]
o să mai caut săptămâna asta. blogtrottr încă nu mi-a trimis email. revin aici cu ce găsesc

**Comment by andreiepure** [comment]
- shootthebreeze.net-  Nu a mers, m-am abonat și nu am primit nimic (am verificat spam-folder-ul)
- ifttt.com- Trebuie cont și nu e 1-stepper, dar îl pun în listă că e cool și trendy
- feed2mail.com
PRO: are reclama mică, aproape insesizabilă (e '888 games' din colț, în poze), trimite cuvântul zilei la începutul zilei (înainte de 1 am)
CONTRA: pe mobil, fonturile apar aiurea (dacă aveți idee de ce, luminați-mă, vă rog)
- blogtrottr.com
 PRO: este afișat corect și pe mobil și pe desktop
 CONTRA: are reclama deranjantă; trimite cuvântul zilei la sfârșitul zilei (după 11 pm)

Fiindcă feed2mail are problema cu fonturile pe mobil (nu știu dacă e fiindcă am Windows Phone, deci de la browserul mobil), recomand blogtrottr.

# Screenshots:
## feed2mail desktop
![feed2email_desktop2](https://cloud.githubusercontent.com/assets/9423335/13376036/c92833e4-ddb8-11e5-85c4-9e2994de0035.PNG)
## feed2mail mobil
![feed2mail_mobil_1](https://cloud.githubusercontent.com/assets/9423335/13376037/d7b01c2e-ddb8-11e5-9acd-ca34651e5921.png)
![wp_ss_20160227_0007](https://cloud.githubusercontent.com/assets/9423335/13376038/dfbc77c8-ddb8-11e5-9e14-6d6054418452.png)


## blogtrottr desktop
![blogtrott_desktop_ad](https://cloud.githubusercontent.com/assets/9423335/13376042/eb6303e4-ddb8-11e5-9305-cc9b74ba81e3.PNG)
## blogtrottr mobil
![blogtrott_mobil_1](https://cloud.githubusercontent.com/assets/9423335/13376056/2c26e86e-ddb9-11e5-9907-d4b2400639eb.png)

**Comment by CatalinFrancu** [comment]
Wow, mulțumim pentru raportul detaliat! Am specificat și `charset=utf-8` în headerul HTTP. Mai poți face, te rog, încă o probă cu feed2mail pe mobil? Dacă tot arată rău, atunci campionul este blogtrottr.

Despre ifttt: cred că un cont nu e o mare problemă. Utilizatorul își dă oricum adresa de e-mail și spune ce feed vrea, deci intimitatea e la un nivel destul de jos. Sigur, e problema unei parole în plus, dar asta ține de confort. Dacă arată și se mișcă mult mai bine decât feed2mail / blogtrottr, eu zic că merită.

**Comment by andreiepure** [comment]
- Nu s-a rezolvat problema cu feed2email pe mobil
![feed2mail_2](https://cloud.githubusercontent.com/assets/9423335/13550757/488a9770-e32d-11e5-9602-2f4e34d7d76e.png)

- IFTT e fain, are o rețetă predefinită pentru RSS->email https://ifttt.com/recipes/147561-rss-feed-to-email , și e configurabil
![iftt_1](https://cloud.githubusercontent.com/assets/9423335/13550750/2047a000-e32d-11e5-8d7b-0016930a5c20.png)
![iftt_2](https://cloud.githubusercontent.com/assets/9423335/13550752/204964d0-e32d-11e5-8126-ce56a2f94f46.png)
![iftt_3](https://cloud.githubusercontent.com/assets/9423335/13550751/2048cf0c-e32d-11e5-9e48-689432e438cb.PNG)

Votez pentru IFTT pentru că reclama de la Blogtrottr e deranjantă pe desktop.

**Comment by CatalinFrancu** [comment]
Excelent, mulțumesc din nou pentru analiză. Am schimbat recomandarea și am mai subțiat și textul din acel div.
