### ISSUE TITLE
Cuvantul zilei - Cheia alegerii nu e afișată pentru cuvintele dinainte de 2013-09-01

### ISSUE THREAD

**Issue by andreiepure** [dexonline/dexonline#438]
Pași:
1. Mergi la https://dexonline.ro/cuvantul-zilei/2015/2/26 . Se vede Cheia alegerii pentru heteronom
2. Hover pe "tehnicolor" - se vede cheia alegerii pentru tehnicolor în hover
3. Apasă pe "tehnicolor" - nu se afișează cheia alegerii pe pagină

Săpând, văd că, deși cuvintele au cheie de alegere, ea nu mai e afișată pt cuvintele dinainte de 2013-09-01

Comportament așteptat: ar trebui "cheia alegerii" să fie afișată deasupra pozei

![cuvantulzilei_bug1_1](https://cloud.githubusercontent.com/assets/9423335/13366636/4debe49c-dce5-11e5-9103-cfb114d8446d.png)
![cuvantulzilei_bug1_2](https://cloud.githubusercontent.com/assets/9423335/13366638/4f7248e2-dce5-11e5-8ce6-8581585ed825.png)

**Comment by CatalinFrancu** [comment]
It's not a bug, it's a feature. :-) Vezi `WOTD_REASON_BIG_BANG`, definit în `wwwbase/wotd.php`. Explicația este că, pe vremuri, cheia alegerii era doar pentru uz intern și o scriam în fraze incomplete, fără diacritice etc. Din 2013 completăm mai conștiincios acel câmp.

Între timp am recuperat și din urmă, am primenit toate cheile vechi, deci acea limitare poate fi ștearsă. Mă ocup eu.
