### ISSUE TITLE
Cuvantul zilei - definițiile lungi au cuvinte acoperite parțial de widgetList

### ISSUE THREAD

**Issue by andreiepure** [dexonline/dexonline#439]
Example grăitoare:
- https://dexonline.ro/cuvantul-zilei/2015/2/27
- https://dexonline.ro/cuvantul-zilei/2014/9/1
- https://dexonline.ro/cuvantul-zilei/2013/9/1

![cuvantulzilei_bug2_1](https://cloud.githubusercontent.com/assets/9423335/13373331/11b8db7c-dd6e-11e5-9ebd-b9f7913e2f3c.png)
![cuvantulzilei_bug2_2](https://cloud.githubusercontent.com/assets/9423335/13373324/d1602a3a-dd6d-11e5-9629-88899aff383d.png)

**Comment by raduborza** [comment]
Așa e designul widgetului, este optimizat pentru rezoluții moderne (pagina se poate derula pentru a vedea definiția mai lungă). Pentru rezoluții mici, oricum, se ascunde widgetul.

**Comment by CatalinFrancu** [comment]
Cel de pe pagina principală se ascunde, aparent ăsta nu (Chromium 48). I-l asignez Soniei, dar prioritatea rămâne #412, care va rezolva de la zero problemele astea.

**Comment by raduborza** [comment]
Mda, am descoperit și eu asta (am schimbat numele unei clase :D). Am fixat eu (dau push acum).
În altă ordine de idei am mai descoperit o chestie, tot legată de widgetul de pe pagina principală:
- sub 983 de pixeli lățime widgetul nu este arătat deloc;
- între 984 și 1093 widgetul are 200px;
- peste 1094 widgetul are 240px;

Am păstrat același comportament și pentru widgetul cuvîntului zilei.
