### ISSUE TITLE
Comentarii multiple fără marcarea autorului

### ISSUE THREAD

**Issue by LadislauStrifler** [dexonline/dexonline#451]
Am adăugat câte un comentariu la unele lexeme care aveau deja un comentariu făcut. La două dintre ele, nu s-a marcat autorul. Iată și o captură de ecran. 
![eroarecomentarii](https://cloud.githubusercontent.com/assets/16460700/14200124/69719104-f7f1-11e5-8050-d79c3c989adb.jpg)

**Comment by CatalinFrancu** [comment]
Codul relevant este în `wwwbase/admin/lexemEdit` liniile 144-149, în special linia 145. Pare că ești pe un sistem care folosește \r\n pentru linie nouă, iar noi am gândit codul doar pentru \n (stilul GNU/Linux). Din cauza asta, sistemul nu-și dă seama că vechiul comentariu este prefix al noului comentariu (deci că s-a adăugat la el).

Îl repar acuș.

**Comment by CatalinFrancu** [comment]
Teoretic reparat de f6b426fc297ef84dbdfdf7d38101b72c1a2fa736, poți verifica, te rog?

**Comment by LadislauStrifler** [comment]
Voi mai comenta câteva, imediat.

**Comment by LadislauStrifler** [comment]
Încă ceva nu e în regulă. Am făcut un comentariu la „maia”, unde mai avea și Matei unul. Am verificat că e OK. Am intrat din nou, am șters comentariul meu anterior, am scris altceva și am dat SALVEAZĂ. Bum! A dispărut autorul și data.

**Comment by CatalinFrancu** [comment]
N-am testat, dar ăsta cred că este feature. Semnăm automat comentariul doar dacă ai adăugat la fostele comentarii, nu și dacă ai modificat în general (atunci nu mai putem decide care e contribuția ta și care e a celor dinainte).

Ar fi varianta să nu semnăm nimic automat, dar să poți tasta ~~~~ ca la Mediawiki și să înlocuiască asta cu nume + dată.

**Comment by LadislauStrifler** [comment]
Cred că ar fi OK cu ~~~~, dar cu un info mic în dreapta câmpului, ca să nu uite lumea.

**Comment by raduborza** [comment]
Dacă deschizi linkul o să vezi comentariile frumos, unul sub altul cu
autorii. De ce am vrea să avem într-o pagină de sumarizare toate
comentariile? În cel mai bun caz aș pune doar lista cu autorii (ce e între
[[ ]]) și aș pune un tooltip cu comentariul corespunzător pe fiecare autor
în parte....

Radu

2016-04-02 13:21 GMT+03:00 Ladislau STRIFLER <notifications@github.com>:

**Comment by CatalinFrancu** [comment]
Îl propun pentru închidere. Dacă tot nu este ok, dacă este important să avem fire de discuție și mai mulți comentatori, putem crea pagini wiki așa cum am procedat în cazul [intrărilor](http://wiki.dexonline.ro/wiki/Special:Toate_paginile/Intrare:). Chiar n-aș vrea să ne batem capul implementând propriul nostru sistem de conversații.

**Comment by raduborza** [comment]
De acord cu închiderea.
