### ISSUE TITLE
pagina lexeme cu comentarii

### ISSUE THREAD

**Issue by LadislauStrifler** [dexonline/dexonline#452]
În pagina viewLexemsWithComments ar trebui ca fiecare comentariu să apară pe o linie separată în cazul în care mai mulți moderatori au făcut adnotări. Sau mai ușor ar fi ca toată paranteza dreaptă, în care se află trecut autorul și data comentariului, să aibă o altă culoare? Ar fi mai ușor de parcurs schimbul de opinii. Dacă s-ar putea face ambele ar fi excelent.

**Comment by raduborza** [comment]
Comentariile sînt pe linii separate. La mine cel puțin. Să înțeleg că
folosești Windows, care strică formatările? :D

Cu culorile: după cum vezi sînt evenimente rare și nu are sens să își
piardă cineva timpul cu așa ceva, dar dacă ai tu chef să implementezi
chestia aia, ești invitatul nostru :)

În data de 1 aprilie 2016, 21:18, Ladislau STRIFLER <
notifications@github.com> a scris:

**Comment by CatalinFrancu** [comment]
Nu-nu, se referă la `/admin/viewLexemsWithComments.php`, acolo tot conținutul unui comentariu este pe o singură linie. De acord, ar fi util. Și ar ajuta la aerisirea paginii.

O soluție completă ar fi să separăm comentariile în înregistrări diferite în baza de date. Dar pare prea mult. M-aș rezuma doar la niște parsări de stringuri.

**Comment by raduborza** [comment]
Păi comentariile nu trebuie să le vezi în interiorul lexemului? La ce te
ajută să vezi comentariile dacă nu știi ce e înăuntru? Iar înăuntru le vezi
cum trebuie, cîte una pe linie. În fine, am pus un quick fix, cred că e
suficient...


R.

În data de 2 aprilie 2016, 10:49, Cătălin Frâncu <notifications@github.com>
a scris:
