### ISSUE TITLE
Loguri mai detaliate

### ISSUE THREAD

**Issue by CatalinFrancu** [dexonline/dexonline#453]
Noi nu prea logăm nimic. Și avem niște mecanisme de logare scrise după ureche. Pur și simplu e nevoie de un sistem mai bun, ceva similar cu syslog, și apoi trebuie adăugate efectiv comenzi de logare peste tot.

**Comment by raduborza** [comment]
Cred că înainte de toate trebuie să ne hotărîm ce vrem să logăm. O listă cu
ce îmi vine acum în cap:

   - orice intrare în paginile de admin (user, timestamp, pagina);
   - orice modificare făcută: pentru tabela Definition avem inclusiv
   versionare. Ar trebui făcută și pentru lexeme, modele și relațiile
   corespunzătoare;
   - să nu avem ștergeri propriu-zise în tabele, ci doar modificarea unui
   status;
   - poate ar fi bine ca toate informațiile astea să fie agregate într-o
   singură tabelă de loguri (eventual partiționată pe luni, ca să o putem
   arhiva ușor);



2016-04-07 11:46 GMT+03:00 Cătălin Frâncu <notifications@github.com>:

**Comment by CatalinFrancu** [comment]
Sigur, de acord! Le implementez ușor-ușor.

Configurația implicită este în `/var/log/dexonline.log`, ca să avem logrotate și tot tacâmul.
