### ISSUE TITLE
Proprietate pe lexeme: animat / personificabil / inanimat

### ISSUE THREAD

**Issue by CatalinFrancu** [dexonline/dexonline#457]
*Update:* voi implementa etichete pe Lexem / LexemModel / Definition.

Din punct de vedere semantic, numai lexemele animate sau personificabile pot avea forme de vocativ (vezi mai jos argumentul gramatical).

* Lexemul trebuie să aibă un câmp nou, întreg, cu valorile 0 = inanimat, 1 = animat, 2 = personificabil.
* Valoarea implicită este 0.
* Valoarea implicită este irelevantă pentru verbe, conjuncții etc. Ne interesează la substantive și adjective.
* La afișarea paradigmei pentru substantive și adjective, codul trebuie să ascundă formele de vocativ pentru lexeme inanimate.

Completarea valorilor se va face de mână, într-o primă fază. Pentru v2.0, ne gândim:

* să marcăm automat ca animate numele de plante, de animale, de profesii, tot ce putem găsi programatic prin definiții;
* să marcăm automat ca personificabile formele de vocativ întâlnite în literatură (după ce punem în funcțiune crawlerul).

> Vocativul este cazul adresării, reprezentând indicarea explicită a alocutorului de către locutor, ca destinatar al mesajului imperativ (o chemare, un ordin, o ameninţare sau o rugăminte), al celui asertiv (de informare, de opinie, de argumentare etc.) sau al celui interogativ.
> Vocativul este caracteristic, în general, substantivelor animate (personale şi nonpersonale), atât comune, cât şi proprii. Substantivele comune care au cazul vocativ sunt cu precădere nume personale generice: bărbat, femeie, băiat, fată, domn, doamnă, domnişoară etc., nume de rudenie sau de relaţii interpersonale: tată, mamă, frate, soră, prieten, amic etc., nume de profesii sau de funcţii: doctor, profesor, dascăl etc., nume etnice: român, turc, grec etc., nume mitologice sau religioase: zeu, zeiţă, zmeu, drac, diavol, înger etc. Substantivele nonanimate realizează cazul vocativ prin personificare: Ce te legeni, codrule, / Fără ploaie, fără vânt. (M. Eminescu, Ce te legeni...), Cât de frumoasă te-ai gătit, /Naturo, tu, ca o virgină. (G. Coşbuc, Vara). Numele comune în cazul vocativ pot avea valori denominative (referenţiale) sau metaforice.

**Comment by raduborza** [comment]
Poate e mai util să generalizăm chestiunea, să refolosim tagurile și să
asociem taguri de tip cîmp semantic (în cazul de față +/-animat,
+/-personificabil) pentru lexeme.
Chiar, tagurile merg și pe definiții și pe lexeme? Că din schemă eu văd că
se leagă doar de lexem...

R

În data de 13 aprilie 2016, 11:42, Cătălin Frâncu <notifications@github.com>
a scris:

**Comment by CatalinFrancu** [comment]
Hmm, nu m-am gândit la asta! Da, ar merge mișto cu etichete. În prezent etichetele merg doar pe sensuri (Meaning). E nevoie de ele și pe lexeme.

**Comment by raduborza** [comment]
Trebuie musai și pe definiții. O să am nevoie să „categorisesc” definițiile
ca fiind din dicționare vechi sau nu..
Probabil și pe dicționare :) Mă rog, cînd ajungem acolo discutăm.

Radu



2016-04-13 18:17 GMT+03:00 Cătălin Frâncu <notifications@github.com>:

**Comment by CatalinFrancu** [comment]
Rezolvat în c562c040c393f417e5f212500ed233ba7318072f, 8d41f32cb48b61022f41df9bc29815fe658a439f și 6a197566ac0e47fa9f400fa8a4364716a3cc54bc.
