### ISSUE TITLE
Sugestii la căutare pentru toate tipurile de afixe

### ISSUE THREAD

**Issue by LadislauStrifler** [dexonline/dexonline#459]
Sugestiile filtrate, pe măsură ce utilizatorul tastează cuvântul căutat, ar trebui să cuprindă și sufixele care apar cu cratimă. Deocamdată doar prefixele sunt sugerate.

**Comment by CatalinFrancu** [comment]
Pare că merge, doar că nu existau lexeme care să înceapă cu cratimă. Și acum este unul singur _(-acant)._ Iar acela apare corect la căutarea _-ac...,_ (autocompletarea se declanșează la minim 3 caractere).

**Comment by LadislauStrifler** [comment]
Merge doar dacă tastezi cratima primul caracter. Vor fi mai multe pe parcurs. N-ar fi interesant să apară chiar dacă tastezi doar litere? Mă gândesc la situația lui -GIR, GIR-, GIR, care nu sunt nicidecum în relație unul cu celălalt. Adică perechea de afixe și lexemul GIR nu au sens comun. Propunerea mea este: să existe în cod o adăugare implicită de cratimă în fața sirului de caractere căutat, modificând SELECT-ul în consecință.

**Comment by raduborza** [comment]
Eu nu aș vrea să mi se polueze lista de rezultate cu cuvinte pe care nu le
doresc. Dacă vreau sufixe, tastez special cratima primul caracter.

În plus, soluția cu adăugarea implicită a unei cratime în față nu e bună:
ar filtra celelalte cuvinte (cele fără cratimă). Așadar ar trebui făcute
 două query-uri, deci am avea un răspuns de două ori mai lent...

În data de 17 aprilie 2016, 19:56, Ladislau STRIFLER <
notifications@github.com> a scris:

**Comment by LadislauStrifler** [comment]
Ar merge și cu un singur query. 
SELECT a,b FROM bla WHERE a LIKE CONCAT('-', var, '%') OR a LIKE CONCAT(var, '%'). 
Dacă nu, închide.

**Comment by raduborza** [comment]
Nu contează că pui într-un singur query sau nu, tot dublu timpului va dura
(OR-ul ăla face o căutare nouă, că mysql-ul nu are cum să caute două
chestii diferite în același timp)...

2016-04-17 23:23 GMT+03:00 Ladislau STRIFLER <notifications@github.com>:

**Comment by CatalinFrancu** [comment]
Nu mă gândisem la asta, Radu are dreptate. Bine, poate merge cu un full text index, nu mă pricep la astea prea bine. Dar încărcarea pe server e un factor important, căci `/ajax/searchComplete.php` e unul dintre cele mai cerute URL-uri (vreo 20% din cereri, am făcut acum un test rapid).

Pe de altă parte, Radu: e clar că nimeni nu va tasta cratima. :-) Deci dacă lăsăm lucrurile așa, condamnăm aceste sufixe să nu fie găsite niciodată.

Ce ziceți de varianta asta: tabela de autocompletare să aibă două câmpuri: valoarea comparată la căutare _(gir)_ și valoarea returnată pentru afișare _(gir, -gir_ sau _gir-)_.

**Comment by LadislauStrifler** [comment]
Dacă ar fi două câmpuri diferite, cu **OR** ar face **SORT_UNION**, după care un **WHERE**. Mie, **EXPLAIN**-ul îmi dă un singur **WHERE**, dacă **OR** e pe același câmp. Probabil, intern, mysql face un fel de **CASE**. Oricum, nu contează dacă nu e acceptabil ca și viteză sau ca și concepție. Ar trebui făcut un stress-test înainte de a modifica ceva la tabele. Nu cunosc tabela de autocompletare. :)

**Comment by raduborza** [comment]
Nu contează cîte WHERE-uri îți dă explainul, contează ce face engine-ul în
spate (te poți juca cu profilingul dacă ai chef să vezi pe unde se pierde
timpul). Și cum are 2 like-uri cu prefix diferit o să trebuiască să treacă
de două ori prin index. Sigur, nu e chiar dublu timpul, că face o singură
sortare pentru lista combinată (chestie care merge rapid acum că d-abia a
convertit Cătălin tabelele la MyISAM și practic acum sînt optimizate, dar
dacă mai adăugăm/modificăm/ștergem chestii și nu le optimizăm, o să meargă
din ce în ce mai greu).

Iar cererea asta, din cîte știu eu, se execută de foarte multe ori, așa că
este important să fie foarte rapidă...

Cătălin, întrebarea nu e dacă cineva tastează cratima (eu am făcut-o de
cîteva ori pînă m-am prins că la noi ba e ba nu e), ci cam cîți și-ar dori
să le apară și sufixele, iar dintre aceștia cîți ar vrea să nu tasteze
explicit și cratima. Căci fie complicăm, fie încetinim site-ul pentru ăia
ț% utilizatori de care am zis. Eu socotesc că ț=0,01, deci efortul nu
merită. Dacă aveți altă părere, negociem :)

În data de 18 aprilie 2016, 12:07, Ladislau STRIFLER <
notifications@github.com> a scris:

**Comment by LadislauStrifler** [comment]
Cel mai simplu ar fi ca elementele de compunere să fie asociate și cu lexeme fără cratimă. **-CER** cu **CER**, **-GIR**/**GIR-** cu **GIR**. Aceasta pentru că **searchClickedWord** nu înhață și cratima. Dar rezultatul afișat ar trebui structurat în așa fel încât elementele de compunere să fie grupate în josul definițiilor lexemului, în cazul în care sunt omografe. În acest fel,  tabela de autocompletare nu va trebui să cuprindă și lexemele cu cratimă iar lista de sugestii nu va fi poluată.
