### ISSUE TITLE
Îmbunătățiri pentru Omleta cuvintelor

### ISSUE THREAD

**Issue by CatalinFrancu** [dexonline/dexonline#461]
- [x] De făcut să meargă în Chrome.
  - [x] În particular, tasta Enter nu pare să puncteze cuvântul.
- [x] De gândit o interfață care să permită jocul doar cu tastatura și doar cu mouse-ul. Oamenii folosesc una sau alta, dar mai rar pe ambele.
  - [x] Doar cu tastatura: de făcut backspace sau altă tastă să trimită toate literele sus.
  - [x] Doar cu mouse-ul: buton care să dea puncte pentru un cuvânt (echivalentul lui Enter); buton care să trimită toate literele sus.
- [x] De dezactivat backspace să nu mai ducă la pagina anterioară.
- [x] De selectat numai cuvinte din LOC (vezi câmpul `LexemModel.isLoc`). Altfel avem prea multe nume proprii.
- [x] De discutat: cuvintele să fie punctate la fiecare literă coborâtă/urcată (deci oricând se modifică setul de jos). Avantajul e că poți găsi rapid cuvinte care diferă doar printr-o literă: _fi / fir / fire_.
- [x] Să meargă și în modul „doar cuvinte de lungime maximă, iar când găsești cuvântul, primești alt set”.
- [x] Timp configurabil.
- [x] Testare pe mobil.

**Comment by AdamBlade** [comment]
Am observat ca sta foarte mult pe nivelele de dificultate mai mari de Normal pentru a genera un cuvant.

**Comment by CatalinFrancu** [comment]
E altceva pe un server încărcat. Pare că generarea permutărilor e rapidă (sub o secundă), dar fiecare din aceste forme trebuie căutată ca să vedem dacă este un cuvânt legal. Iar asta durează, că sunt 7! = 5.040 de interogări.

Vorbisem mai demult despre soluții mai rapide, mai știi? Și ne oprisem până la urmă la [asta cu vector caracteristic](https://github.com/dexonline/dexonline/issues/273#issuecomment-188692851). Ea are și avantajul că putem alege ce forme vrem să exportăm acolo, deci scăpăm de toate numele proprii și alte bălării de cuvinte.

**Comment by AdamBlade** [comment]
Ma gandeam daca n-am putea face un set restrans de cuvinte pentru joc. 
O tabela in care tinem cuvintele pe care le dam utilizatorului. Si o o alta tabela in care tinem ID-uri catre cuvintele care se pot forma din cuvant-ul dat.
Astfel as avea un cuvant random din tabela sa ii zicem randomWord, care are id, cuvant-ul si id-ul catre tabela possibleWords, din asta imi iau id-urile fiecarui cuvant si le extrag din baza, fara sa mai fie nevoie sa fac de fiecare data permutari.
Intrebam de baza pentru ca initial tot trebuie sa fac niste permutari ca sa scot automat cuvintele posibile si sa populez cele doua tabele dupa care intru si aplic o treiere sa elimin referinte care cuvinte nefavorabile, nume proprii, combinatii de genul aa etc.

Ar mai fi intradevar optiunea cu vector caracteristic.

**Comment by CatalinFrancu** [comment]
Ba da, e bine și cum propui tu. Dar am o contrapropunere, o variantă mai simplă și cu o singură tabelă. Hai să-i spunem chiar `Scramble` tabelei, ca să știm pentru ce este. Ea va fi populată, cum spui și tu, cu un subset al tabelei `InflectedForm` și va avea câmpurile:

*  `id` numeric, auto_increment etc.;
* `form`: forma cuvântului (să zicem _portar_);
* `sortedForm`: literele cuvântului ordonate alfabetic (în acest caz, _aoprrt_);
* `createDate` și `modDate` (astea sunt pentru bucătăria internă, trebuie doar să le declari).

Cum populăm tabela? Evident, trebuie doar să sortezi literele pentru fiecare formă extrasă din `InflectedForm`. Va fi un script, să zicem `tools/rebuildScramble.php`, pe care îl rulăm săptămânal.

Cum folosim tabela? Când ai un set de litere, să zicem _raport_, trebuie să ordonezi setul (_aoprrt_), apoi să ceri toate formele pentru care `sortedForm = 'aoprrt'`. Vei obține _portar_, _raport_, _tropar_ și ce-o mai fi.

Are sens, în mare? Dacă da, vor mai fi două finețuri:

1. Ce forme extragem din `InflectedForm`. Va fi un query uriaș, dar te ajut eu să-l scrii când vine momentul. Vrem două chestii: (a) să luăm doar cuvinte din dicționare comune (DEX etc.) și (b) să luăm doar formele gramaticale permise la Scrabble, de exemplu vocativul nu trebuie selectat (_calule_).
2. Cum tratăm, cât mai simplu, cazurile cu și fără diacritice. Nu e greu, uită-te peste declarația lui `InflectedForm` (`show create table InflectedForm;` în MySQL). În esență, trebuie dublat câmpul `sortedForm`, o dată cu collate-ul normal de UTF8 și o dată cu cel românesc.

**Comment by AdamBlade** [comment]
Ar mai fi o adaugare ca in sorted form "aoprrt" trebuie sa avem si cuvinte mai mici decat lungimea initiala, de exemplu port, tor. In rest suna bine abordarea asta pentru ca pot face un singur query bazat pe sorted form.

**Comment by CatalinFrancu** [comment]
Corect!

**Comment by AdamBlade** [comment]
Salutare,

In primul rand imi cer scuze ca am disparut subit. Am avut niste probleme de care a trebuit sa ma ocup si nu am mai avut timp liber pentru nimic.

Acum am rezolvat si as dori sa ma reapuc de treaba si sa termin ce am inceput.

**Comment by CatalinFrancu** [comment]
Bine ai revenit! E ok, viața se întâmplă. :-D

Deci rămânem cu varianta tabelei Scramble, în care fiecare formă este ordonată, da? Atunci:

* Codul MySQL care creează tabela stă în `patches/00....sql` (ia următorul număr nefolosit).
* Scriptul stă în `tools/`, exact. Spune-i `tools/rebuildScramble.php`, să zicem.
* Vei avea nevoie de un obiect-model `php/models/Scramble.php`, corespunzător tabelei `Scramble` (te prinzi dacă te uiți la alte clase din `php/models/`).

**Comment by AdamBlade** [comment]
Salut,

Am facut modificarile ca sa utilizez o tabela separata pentru joc. As dori putin ajutor cu query-ul.

"Ce forme extragem din InflectedForm. Va fi un query uriaș, dar te ajut eu să-l scrii când vine momentul. Vrem două chestii: (a) să luăm doar cuvinte din dicționare comune (DEX etc.) și (b) să luăm doar formele gramaticale permise la Scrabble, de exemplu vocativul nu trebuie selectat (calule)."

**Comment by CatalinFrancu** [comment]
Salut, scuze pentru dispariție, am fost prins câteva săptămâni cu un alt proiect.

Iată query-ul. E mare, cum am promis. :-)

```
select distinct i.formNoAccent
  from InflectedForm i
  join Lexem l on i.lexemId = l.id
  join EntryDefinition ed on l.entryId = ed.entryId
  join Definition d on ed.definitionId = d.id
  join ModelType mt on l.modelType = mt.code
  join Model m on mt.canonical = m.modelType and l.modelNumber = m.number
  join ModelDescription md on m.id = md.modelId and i.inflectionId = md.inflectionId
  where md.applOrder = 0
    and md.isLoc
    and d.status = 0
    and d.sourceId in (1, 2, 3, 4, 5, 15, 19, 21, 27, 40, 65)
    and char_length(i.formNoAccent) between 2 and 7
  order by i.formNoAccent;
```

Dacă vrei, ar fi frumos să o scrii în sintaxa Paris / Idiorm.

De acord cu coloana pentru lungime. Să ai grijă să stochezi `char_length(...)`, nu `length(...)`, pentru ca diacriticele să conteze ca un singur caracter, nu două.
