### ISSUE TITLE
Îmbunătățiri pentru lista de cuvinte ale zilei

### ISSUE THREAD

**Issue by CatalinFrancu** [dexonline/dexonline#462]
Una ușoară: este util să permitem alegerea unei date + a unei descrieri, fără a specifica însă și un cuvânt. Astfel putem consemna evenimente despre care auzim, fără a face atunci efortul de a căuta un cuvânt. Pare că trebuie modificat doar codul din `wwwbase/ajax/wotdSave.php:doSave()`.

Una mai complexă: este util să permitem alegerea unui cuvânt pentru o zi + lună, dar fără specificarea anului. Pare că ar trebui spart câmpul `WordOfTheDay.displayDate` în zi+lună separat și an separat.

**Comment by raduborza** [comment]
Aș propune să rămînă data publicării așa cum e și să adăugăm o tabelă nouă
care să lege cuvintele propuse de o dată (fără an). Cînd un cuvînt este
asociat cu o dată (în vederea publicării), relația se șterge din tabela aia
nouă. Ce zici?

Cînd am proiectat WotD, m-am gîndit să susțină mai multe cuvinte pentru
aceeași zi și să poată accepta ușor și alte tipuri de entități (articole de
exemplu).
Pînă acum nu s-a folosit decît un cuvînt pe zi (și s-a folosit doar
cuvîntul), așa că putem simplifica și aici, că nu cred că vom mai extinde
prea curînd modelul actual!

R.

În data de 12 mai 2016, 12:42, Cătălin Frâncu <notifications@github.com> a
scris:

**Comment by CatalinFrancu** [comment]
Pare că sunt scenarii diferite, dar sigur, hai să le facem pe ambele.

Scenariul meu este: observ că actorul X are 79 de ani și la anul face 80. Vreau să asociez acest eveniment pentru data când va face el 80 de ani, dar nu am timp acum să stau să caut un cuvânt.

Scenariul tău pare să fie: citești despre data ZZ.LL, găsești N evenimente interesante și adaugi definiții pentru ele, dar nu ții morțiș la una anume dintre ele. Vrei ca restul să rămână într-un _pool_ ca să ne fie mai ușor la anul. Zic bine?
