### ISSUE TITLE
Câmpuri auto-referențiale

### ISSUE THREAD

**Issue by LadislauStrifler** [dexonline/dexonline#464]
În pagina de editare lexeme _lexemEdit.php_ sunt câteva câmpuri (Variantă a lui:, Variante: și la paradigmă, câmpul pentru indicarea unui model de flexiune) care permit alegerea lexemului care se editează. Ar trebui filtrată matricea de sugestii și eliminat lexemul în cauză. Niciun lexem nu poate fi varianta lui proprie, sau modelul lui propriu de flexiune. 
Voi da ca exemplu lexemul **LEGITIM** care are două accentuări, în consecință două lexeme. Dacă se editează unul dintre ele și se dorește alegerea celuilalt ca variantă, nu se va putea identifica în lista de sugestii lexemul corespunzător și avem șansa să facem o autoreferire.

**Comment by LadislauStrifler** [comment]
Fiind vorba tot de editare lexeme și câmpul de indicare a unui lexem similar ca și model de flexionare, propun ca în momentul alegerii acestui model să se preia automat și restricția modelului indicat.

**Comment by CatalinFrancu** [comment]
Filtrarea în cauză este destul de complicat de făcut. Folosim o bilbiotecă numită select2, care este personalizabilă, dar dincolo de un punct devine complicat. Dacă confuzia între lexeme este problema, politica noastră este să diferențiem omonimele folosind câmpul „descriere”.

Sau o altă rezolvare este ca lista de sugestii oferită de select2 să includă și accente.

De acord cu a doua cerință (la alegerea unui lexem similar, sistemul să preia nu doar tipul și numărul de model, ci și restricțiile acelui lexem).

**Comment by CatalinFrancu** [comment]
Prima cerință nu se mai aplică deloc, căci nu mai avem variante (avem doar bifa „principal” pe lexeme).

Rămâne a doua cerință
