### ISSUE TITLE
Logoul trebuie refăcut cu fundal transparent

### ISSUE THREAD

**Issue by CatalinFrancu** [dexonline/dexonline#467]
Cel prezent are un fundal gri, care nu mai corespunde.

**Comment by sandriu** [comment]
Atașez versiunea mică de logo cu fundal transparent, pentru paginile secundare. Sunt 2 variante:
- una cu textul și calculatorul în culoare full black, așa cum e logo-ul original (mi se pare că zgârie un pic ochiul, fiind prea intens negrul);
- una cu textul și calculatorul în culoare 90% black (integrare vizuală mai ușoară cu restul de nuanțe de gri din textele headerului).

Ambele versiuni sunt un pic mai mari decât vechiul logo (173x44px în loc de 111x25px), fiindcă pe design-ul responsive avem mai mult spațiu pe verticală.

![logo-dexonline-legat-pagini-secundare-90percent-black](https://cloud.githubusercontent.com/assets/1265882/17132185/4da5f3be-5329-11e6-9f67-db06101d90de.png)
![logo-dexonline-legat-pagini-secundare-full-black](https://cloud.githubusercontent.com/assets/1265882/17132184/4da4fb8a-5329-11e6-873c-026398c16a4a.png)

**Comment by CatalinFrancu** [comment]
Ok, l-am ales pe cel 90%. Poți vedea [rezultatul](http://voronet.francu.com/~cata/dexonline-david/wwwbase/definitie/x). Pentru rezoluții mici am făcut o imagine nouă, doar cu calculatorul (nu am folosit overflow, că era mai complicat).

Ne-ar mai trebui o singură chestie, o menționez în același issue: pentru logo-ul mare din pagina principală putem renunța la [sprite3.png](https://dexonline.ro/img/sprite3.png), căci restul iconițelor din el nu mai sunt folosite. Ne refaci, deci și un logo pe fundal transparent, la 316x82 sau la orice altă rezoluție crezi tu că arată bine? Mulțumesc.

**Comment by CatalinFrancu** [comment]
Ah, stai că îl aveam deja ca PNG, mă ocup eu.
