### ISSUE TITLE
Convertirea tuturor paginilor la Bootstrap

### ISSUE THREAD

**Issue by CatalinFrancu** [dexonline/dexonline#468]
În măsura în care ai răbdare.

**Comment by david-batranu** [comment]
Am făcut majoritatea din ce era în `templates` din ce știu au mai rămas:

- [ ] `top` - stilat nițel tabelul să semene cu bootstrap, sau aplicat un skin de bootstrap 3.
- [ ] `cuvinte` - arată broken pagina așa că am lăsato la urmă.
- [ ] `istoria-definiției` - n-am reușit să găsesc la nimereală un cuvînt cu istoric, voi rezolva cu un SQL query.
- [ ] articolele provenite de pe wiki - nici nu m-am uitat la cod presupun că se poate rezolva cu un XML parser.

**Comment by CatalinFrancu** [comment]
Mă ocup eu de articolele din wiki.

**Comment by CatalinFrancu** [comment]
Lista de cuvinte nu e broken, așa a arătat întotdeauna. :-) O mai folosește @raduborza, nu știu pentru ce.

Am convertit și istoria definiției. N-o vedeai pentru că nu exportăm tabelul history_Definition, fiindcă e foarte mare. Dar poți edita definiții local ca să generezi intrări în history_Definition.
