### ISSUE TITLE
Culoarea #761818 pentru linkuri

### ISSUE THREAD

**Issue by CatalinFrancu** [dexonline/dexonline#469]
Culoarea #761818 era parte din identitatea noastră, e bine să o păstrăm. Dacă unele fișiere trebuie generate cu Less, ar fi utilă și o documentație minimală pentru proces.

**Comment by david-batranu** [comment]
Am integrat culoarea pentru `button-primary`, linkuri și navbar/dropdown hover.

**Comment by CatalinFrancu** [comment]
Perfect! Ar mai trebui o chestie, nu mai deschid un tichet nou pentru asta: div-ul de tip alert în care scrie «N definiții pentru „...”» ar trebui să fie gri sau alb sau altceva decât albastru (ca să nu adăugăm o culoare în plus la paletă).

**Comment by david-batranu** [comment]
Done. Am folosit `panel` fără titlu că e alb.

Am mutat și declinările în el, mi se pare mai ok să facă parte din elementul vizual care conține link-ul pentru expand/collapse .

**Comment by CatalinFrancu** [comment]
Hurrah!
