### ISSUE TITLE
Feedback pentru casetele din pagina principală

### ISSUE THREAD

**Issue by CatalinFrancu** [dexonline/dexonline#470]
Arată ok [așa cum sunt acum](http://resp.dexonline.ro/)? Cum le putem îmbunătăți?

**Comment by sandriu** [comment]
Se pare că avem un bug la 768px: link-ul Donează și restul meniului sunt afișate pe rânduri separate (screenshot de pe resp.dexonline.ro):

![dexonline home page bug la 768px](https://cloud.githubusercontent.com/assets/1265882/17435790/b7f99546-5b1b-11e6-82a6-fb96bc8b4438.png)

**Comment by sandriu** [comment]
Casetele (widget-urile) sunt stilate și fiecare are propria ei culoare de bordură la hover.
