### ISSUE TITLE
Reclame responsive

### ISSUE THREAD

**Issue by CatalinFrancu** [dexonline/dexonline#471]
[AdSense zice](https://support.google.com/adsense/answer/3213689?hl=en) că știe să servească reclame responsive. Trebuie găsită configurația potrivită.

Setările pentru AdSense în `dex.conf` sunt:

    [banner]
    type = openx

    [skin-zepu]
    adsense_mainPage = "1220723485"
    adsense_otherPages = "2401834072"

**Comment by david-batranu** [comment]
Nu am reușit cu `openx` dar a mers cu `adsense`. Intr-adevăr AdSense știe să se scaleze frumos în funcție de dimensiunile containerului. 

O problemă este că necesită reîncărcarea paginii dacă este redimensionată fereastra.

**Comment by CatalinFrancu** [comment]
Bun! Exact la asta mă așteptam. Da, este ok să ceară reîncărcare.

S-ar putea ca și Revive (fost OpenX) să știe să servească bannere responsive, sunt unii pe forumuri care zic că au reușit. Trebuie scris cod JS pentru asta. Vrei să-ți dau acces la adserverul nostru ca să experimentezi? Dacă creezi o zonă nouă + un advertiser nou, nu ai ce să strici.

Dacă nu, e ok, îmi asignez mie tichetul.

**Comment by david-batranu** [comment]
O să încerc să-mi fac eu deploy la un adserver ca să nu poluez producția :)

**Comment by david-batranu** [comment]
Am instalat Revive local și m-am cam pierdut în setări, din ce am văzut implementarea necesită:

- definirea unor zone pentru fiecare dimensiune
- [un JS](http://forum.revive-adserver.com/topic/27-how-to-serve-responsive-ads/#comment-3310) care să încarce zona corectă în funcție de dimensiunile ferestrei

**Comment by CatalinFrancu** [comment]
Îmi bag și eu nasul un pic.
