### ISSUE TITLE
scroll orizontal inutil

### ISSUE THREAD

**Issue by xlotlu** [dexonline/dexonline#473]
Site-ul face scroll orizontal sub 961px, ceea ce este nejustificat la un site content-only, single-column.

Ar trebui să facă scroll doar sub lățimea bannerului, și chiar și așa #contentProper ar putea fi lăsat cu width: auto și un min-width rezonabil.

Dacă se aprobă, modificările sunt simple dar în mai multe locuri - trebuie săpat un pic, și la final trebuie gândit ce se întâmplă cu butonul de "Donează" / cum se adaptează zona de search. Dacă nu primește atenție de sine stătător rog să-l luați în considerare la #412 .

(961px pentru că #menu width: 944px + padding-left: 15px + border: 1px * 2)

**Comment by CatalinFrancu** [comment]
Mulțumim, Ionuț. Nu știu dacă îl investigăm prea mult, că avem în plan un design nou, responsive #412
