### ISSUE TITLE
Căutare mai bună pentru surse

### ISSUE THREAD

**Issue by CatalinFrancu** [dexonline/dexonline#474]
Dropdown-ul de surse a devenit tot mai greu de folosit, căci numărul de surse crește. Conține multe acronime asemănătoare (DLRM, DMLR, DLRC, DLRLC...) și nu este ordonat alfabetic.

Trebuie trecut la Select2, iar la căutare trebuie să caute substring și în numele dicționarului, nu doar în shortName / urlName. Poate chiar și în autor și în editură? De asemenea, trebuie să ignore diacriticele la căutare, fiind un input vizibil tuturor utilizatorilor.

Ar putea fi util să recomande 5-10 dintre cele mai folosite dicționare (înainte ca utilizatorul să tasteze ceva). Nu știu dacă Select2 știe asta.

**Comment by sandriu** [comment]
Cineva mi-a spus că pe partea de UX este greu de folosit dropdown-ul actual, cel puțin pe mobil, din cauză că te obligă să scrollezi mult până la dicționarul căutat.
Am adăugat și label-ul "UX research" pentru determinarea ordinii optime în care să afișăm sursele (de cercetat cu utilizatorii).

**Comment by CatalinFrancu** [comment]
Am adăugat select2 pe selectorul de surse, pare mult mai util acum. Ți-l asignez ție pentru ordonarea surselor.

**Comment by sandriu** [comment]
Mișto, văd că acum avem și acronimele de dicționare și explicarea lor, în interiorul listei. Un pas înainte pe partea de UX.

**Comment by sandriu** [comment]
Până nu-mi uit ideea: văd că acum dicționarele sunt sortate în ordinea invers cronologică a tipăririi lor (cel puțin primele). Ar fi interesant de aflat câți utilizatori și-ar dori la Preferințe o opțiune de genul "Folosește doar dicționare mai recente de [anul tipăririi]", unde "anul" să fie o listă de ani corespunzătoare dicționarelor indexate. 
Cu siguranță una din categoriile posibile de utilizatori dexonline este interesată strict de sensul curent al cuvintelor, care se găsește doar în cele mai recente ediții de dicționare.

**Comment by CatalinFrancu** [comment]
Precizare: Dicționarele sunt sortate conform dexonline.ro/surse, care este o sortare manuală.

Un alt criteriu util ar fi nivelul de completitudine (DEX '09 e complet, DEX '12 și '16 foarte puțin).

**Comment by CatalinFrancu** [comment]
Am pus primele în listă dicționarele cele mai utile (sper): DEX, DOOM2, Sinonime, Antonime. Ordinea nu poate fi schimbată din UI, dar poate fi manipulată în baza de date.

Eu mă declar mulțumit!
