### ISSUE TITLE
Fereastra „Donează prin PayPal” e cam goală

### ISSUE THREAD

**Issue by CatalinFrancu** [dexonline/dexonline#475]
Pe pagina `/doneaza`, fereastra „Donează prin PayPal” a rămas cam goală după conversia la Bootstrap. Pare că se întâmplă deoarece fereastra „Donează online” ocupă mai mult spațiu vertical decât înainte.

Momentan, David a pus un `zoom: 1.5` pe formularul de PayPal.

O altă posibilitate ar fi scurtarea verticală a ferestrei „Donează online”, de exemplu punând etichetele **Suma** și **E-mail** pe aceeași linie cu câmpurile respective.

**Comment by sandriu** [comment]
Dacă în primul panel (Donează online) aduc label-urile Email și Suma pe același rând cu textfield-urile, atunci panelul tot va avea o înălțime prea mare (rămâne spațiu alb în capătul de jos al panelului), vezi screenshot:
![paneluri de doneaza - doar width si display](https://cloud.githubusercontent.com/assets/1265882/17132554/f4f1b58a-532a-11e6-9398-9a307bb87d75.png)

Dacă aplic și schimbările de mai sus, dar schimb și min-height-ul pe paymentSection la 245px (în loc de 290px), atunci va arăta așa:
![paneluri de doneaza - width si display si min-height 245](https://cloud.githubusercontent.com/assets/1265882/17132652/612802cc-532b-11e6-97d3-045db2a52d92.png)
Este ok a doua variantă?

**Comment by CatalinFrancu** [comment]
Da, a doua arată bine. Și aș scoate și zoom-ul de pe formularul de PayPal, că arată cețos. O implementezi tu, sau mi-o lași mie?

**Comment by sandriu** [comment]
O implementez eu, că probabil voi mai depurica și alte lucruri de CSS pe pagina asta.

**Comment by sandriu** [comment]
De testat DACĂ pe dispozitivele mobile poți da click pe iconița de Info care îți arată comisioanele pentru cele 3 tipuri de donație.

**Comment by sandriu** [comment]
După ceva restilizare și curățenie, opțiunile de plată arată așa acum:
- pe desktop:
![pagina-doneaza-optiuni-de-plata-pe-desktop](https://cloud.githubusercontent.com/assets/1265882/17327409/7dd5340e-58c0-11e6-97e1-403aa1bee63f.png)

- pe mobile (simulare din browser de PC):
![pagina-doneaza-optiuni-de-plata-pe-mobile](https://cloud.githubusercontent.com/assets/1265882/17327416/8f41851c-58c0-11e6-9f4d-7373edcf0d2a.png)

Am scos textul "necesar pentru trimiterea confirmării plății" de sub butonul de "Donează prin euPlatesc.ro" deoarece pe desktop acest tip se poate vedea la mouse hover pe labelul "Email*".
Pentru mobile, unde nu avem interacțiune de tip mouse hover,  trebuie testat dacă tip-ul acesta și tip-urile legate de comisioane pot apărea la tap pe ecran - în caz contrar, tip-urile vor trebui afișate textual din prima, când se ajunge la rezoluție de mobile.

**Comment by CatalinFrancu** [comment]
Arată perfect (am făcut push și pe resp.dexonline.ro). Închid tichetul.
