### ISSUE TITLE
Elemente de stilat în pagina de definiții

### ISSUE THREAD

**Issue by CatalinFrancu** [dexonline/dexonline#477]
- [x] fontul în sine - pe unele sisteme pare să afișeze Ș și Ț ca Ş și Ţ
- [x] detaliile de sub fiecare definiție - prezentare, spațiere
- [x] comentariile ([exemplu](http://resp.dexonline.ro/definitie/manuscris))
- [x] articolele lingvistice ([exemplu cu mai multe](http://resp.dexonline.ro/definitie/ortografie)) ([exemplu cu unul singur](http://resp.dexonline.ro/definitie/oprobriu))
- [x] secțiunile de definiții normale, specializate și neoficiale ([exemplu](http://resp.dexonline.ro/definitie/Iisus)) ([exemplu fără definiții normale](http://resp.dexonline.ro/definitie/Simionescu))

**Comment by CatalinFrancu** [comment]
Am încercat să tratez primele două buline. Am trecut la Open Sans, 16px.

Motivul pentru care afișează Ş cu sedilă în loc de virgulă este că eu am instalat local un Open Sans, care pare greșit (l-am inspectat). Cel de la Google este evident corect.

**Comment by aifrim** [comment]
Puteți descărca acel Open Sans de la Google, pus local pe și pus alt nume în definirea @font-face (gen: "ops")

Asta va soluționa suprascrierea fonturilor locale :)

**Comment by CatalinFrancu** [comment]
Da, dar e destul de mare, cam 500 KB comprimat pentru ce ne trebuie nouă. Va genera mult trafic. E mai bine să stea pe un CDN.

Altfel ar fi frumos, și ar rezolva și problema de privacy (prima dată când descarci acel font, Google știe ce pagină vizitezi).

**Comment by aifrim** [comment]
Nu folosiți un CDN care să rezolve problema asta?

Plus că sunt destul de sigur că nu vă trebuie toată familia fontului. Ci
doar regular, italic, bold și bold-italic.

**Comment by CatalinFrancu** [comment]
Păi cred că Google Fonts este CDN-ul. :-) La o căutare rapidă, nu l-am găsit pe vreun alt CDN (iar dacă folosim un CDN obscur, pe care nu-l folosește multă lume, nu rezolvăm mare lucru).

Așa este, doar cele 4 ne trebuie, dar împreună par să aibă spre 500 KB comprimate (ca TTF, cel puțin).

**Comment by aifrim** [comment]
TTF e format de desktop.
WOFF / WOFF2 = The Web Open Font Format (2 vine de la versiune).

Mai multe detalii aici: http://www.w3schools.com/css/css3_fonts.asp

Întredevăr google webfonts e CDN-ul. Dar sunt și alte soluții pe masă. Cum ar fi planul Free de aici https://www.cloudflare.com/plans/ unde aveți și CDN :)

**Comment by CatalinFrancu** [comment]
Mda, dar nu ne-ar ajuta prea mult. Avem destui vizitatori care vin rar, poate o dată pe lună. Dacă stau 1-2 secunde să descarce fontul, asta le strică experiența. De aceea, dacă folosim un font, vreau să fie cât mai probabil să-l aibă deja în cache, deci aș rămâne pe varianta Google fonts.

**Comment by sandriu** [comment]
Pentru stilarea comentariilor: în primul rând, caseta de comentarii nu ar trebui să aibă un visual weight mai mare decât caseta pentru declinări (background-color mai închis).
Eu cred că utilizatorul mediu care caută o definiție pe site va fi interesat în primul rând de:
1. caseta de căutare cuvinte
2. declinarea cuvântului căutat
3. definiția cuvântului căutat
4. comentarii legate de o definiție a cuvântului căutat.
Ordinea poate diferi de la un tip de utilizator la altul, de aceea la un moment dat ipoteza mea va trebui validată prin user testing (am adăugat label "user testing", pentru viitoare referințe).

![pagina-definitiei-prioritatea-elementelor](https://cloud.githubusercontent.com/assets/1265882/17367121/54b451a4-5997-11e6-9ddd-f946caf9f1a4.png)

Prin urmare, stilarea ar trebui să reflecte această ierarhie.

**Comment by sandriu** [comment]
Pentru lista de articole lingvistice atașate unui cuvânt, am optat pentru panel default și listă cu bullet-uri:

![pagina-definitiei-stilarea-listei-de-articole](https://cloud.githubusercontent.com/assets/1265882/17403235/842b2516-5a5f-11e6-962e-254517cb1f26.png)

După ce mutăm conjugările într-un tab nou, vom vedea dacă este necesar un visual weight mai mare pentru lista de articole.

**Comment by sandriu** [comment]
Pentru stilarea secțiunilor de definiții normale, specializate și neoficiale, propun marcarea header-elor acestora ca un callout (clasa nu există în Bootstrap 3, dar am adăugat eu 2 clase în CSS):

![pagina-definitiei-stilarea-sectiunilor-de-definitii-normale-specializate-neoficiale](https://cloud.githubusercontent.com/assets/1265882/17404093/39695e9a-5a63-11e6-853c-8c4f9e925b66.png)

Păreri?

**Comment by CatalinFrancu** [comment]
Ok, de acord cu ambele. Și pe mine mă tenta callout-ul, dar am renunțat văzând că nu e standard.

**Comment by sandriu** [comment]
E posibil să introducă callout-ul în codul standard de Bootstrap de la versiunea 4 (care acum e în alpha 2 release).

**Comment by sandriu** [comment]
Am recompilat Boostrap pentru introducerea noii culori de btn-info și pentru fontul personalizat.
