### ISSUE TITLE
Navigare mai ușoară la cuvântul zilei / lunii

### ISSUE THREAD

**Issue by CatalinFrancu** [dexonline/dexonline#479]
În prezent pentru navigarea între zile și luni avem iconițele din dreapta-sus, care sunt cam mici. Un slider ar fi mai util.

**Comment by sandriu** [comment]
Problema actuală de navigare este pe mobile, unde iconițele din dreapta-sus sunt atât de mici și de apropiate, încât ai șanse mari să dai click pe ce nu vroiai:

![ss cuvantul zilei](https://cloud.githubusercontent.com/assets/1265882/19517742/a0f81414-960b-11e6-93eb-86b7430b7853.png)

Am discutat la un moment dat de introducerea unui slider ca alternativă de navigare prin Cuvântul zilei. Concluzia a fost că mai bine:
- scoatem titlul paginii din panel și îl afișăm indepedent de restul elementelor, conform layout-ului de pe restul paginilor; _în felul ăsta obținem consecvență cu restul de pagini_;
- lăsăm în panel iconițele de navigare stânga-dreapta, dar plasate corespunzător (în stânga iconița pentru navigare în trecut, în dreapta iconița pentru navigare în viitor); _în felul ăsta eliminăm erorile de click pe 2 iconițe plasate inițial foarte aproape_.

Și-acum să trecem la codat.

**Comment by sandriu** [comment]
Iată cum arată acum Cuvântul zilei pe mobil:
![cuvantul zilei - ss mobile](https://cloud.githubusercontent.com/assets/1265882/19521467/76cd3294-961c-11e6-85fe-1ab83814e04c.png)

și Cuvântul lunii, tot pe mobil:
![cuvantul lunii iunie 2016 - ss mobile](https://cloud.githubusercontent.com/assets/1265882/19521482/813fc1e2-961c-11e6-8108-0fbb75f17f59.png)

**Comment by CatalinFrancu** [comment]
Arată mult mai bine! Am comentat pe commituri.

**Comment by sandriu** [comment]
@CatalinFrancu Vezi că și aici avem branch separat, nu uita să-l incluzi în master.

**Comment by CatalinFrancu** [comment]
Credeam că faci tu asta. :-)
