### ISSUE TITLE
Thumbnails mai mari pentru imagini

### ISSUE THREAD

**Issue by CatalinFrancu** [dexonline/dexonline#481]
Acum sunt 48, pare că e loc de mai mult. Ne trebuie doar designul, implementarea o fac eu.

**Comment by sandriu** [comment]
Commit-ul de mai sus mărește thumbnail-ul widget-urilor în funcție de rezoluția ecranelor:
- pe ecrane cu minim 992px width arată așa:
![widget thumbnail 1024px](https://cloud.githubusercontent.com/assets/1265882/17945988/20e9b2be-69fb-11e6-8814-6f7df9834270.png)

- pe ecrane mai mari de 768px și mai mici de 992px arată așa:
![widget thumbnail 768px](https://cloud.githubusercontent.com/assets/1265882/17946009/3e383052-69fb-11e6-8ac7-dec7d11fd227.png)

- pe ecrane mai mici de 768px arată așa:
![widget thumbnail 640px](https://cloud.githubusercontent.com/assets/1265882/17946017/4c0f94b8-69fb-11e6-80ab-1fdc95b2e916.png).

Am folosit 2 dimensiuni de thumbnail (pătrat): 
- 88px (pentru ecrane mari și foarte mici, adică mobile) și 
- 64px (pentru ecrane medii).

**Comment by raduborza** [comment]
Arată foarte bine! 

Nu ar arăta și mai bine (și mai unitar) dacă la ecranele mai mici de 768px lățime să avem thumbnailul aliniat și el la dreapta (ca la cele peste 992px)?

**Comment by sandriu** [comment]
Am refăcut codul astfel încât thumbnails să aibă aceeași dimensiune de 88x88px, pe toate rezoluțiile.

Singura problemă care mai rămânea de fixat era cazul rezoluțiilor foarte mici, de 320px width.
Google Analytics pe ultimele 6 luni (martie-august) spune că cele mai folosite 10 rezoluții pe mobile sunt:
![google analytics march-august 2016 mobile screens](https://cloud.githubusercontent.com/assets/1265882/18171403/888b3de6-706a-11e6-8d6f-e7b4e965f761.png)

Dintre acestea, toate arată bine acum doar cu codul Bootstrap, cu excepția unei rezoluții:
- 540px OK (similar cu 720px, 768px):
![thumbnails la 540px](https://cloud.githubusercontent.com/assets/1265882/18171735/a7a01afc-706b-11e6-8070-f452be26aa88.png)

- 360px OK (similar cu 375px, 480px):
![thumbnails la 360px](https://cloud.githubusercontent.com/assets/1265882/18171774/cd967328-706b-11e6-9384-581fc73a9a43.png)

- 320px **NOT OK** (numele primului joc este parțial ascuns de imagine și nu poate fi despărțit automat în silabe, astfel încât să treacă pe două rânduri, cum se întâmplă la jocul "moara cuvintelor"):
![thumbnails la 320px](https://cloud.githubusercontent.com/assets/1265882/18171889/2f52ca9e-706c-11e6-8553-8125cd56c24a.png)

Soluția de compromis pentru bug-ul de la 320px width a fost să micșorez font-size-ul listei de jocuri:
![thumbnails la 320px bug reparat](https://cloud.githubusercontent.com/assets/1265882/18171999/93864bc6-706c-11e6-9a67-a6f21e8f6cf0.png)

Putem accepta această soluție de compromis deoarece:
- niciun alt widget nu mai folosește listă cu bullet-uri, deci excepția apare într-un singur loc și nu strică consecvența widget-urilor;
- nu putem renunța la listă cu bullet-uri (cu intenția de a refolosi padding-left-ul disponibil) pentru că avem nevoie de un marker vizual care să facă diferența dintre cele două link-uri de jocuri.

**Comment by CatalinFrancu** [comment]
Excelent! Mai am o singură rugăminte. Poți să muți tot ce este specific paginii principale din `wwwbase/css/responsive.css` în `wwwbase/css/autoload/index.css`? Cred că asta include tot ce ține de widget-uri.

Pe urmă mă ocup eu de redimensionarea thumbnail-urilor.

**Comment by sandriu** [comment]
Done.

**Comment by CatalinFrancu** [comment]
Bun! De aici codez eu. Vom avea două mărimi de thumbnails, 88px pe pagina principală și 48 px în alte două locuri: arhiva cuvântului zilei și cuvântul zilei în alți ani (sunt toate pe [aceeași pagină](https://dexonline.ro/cuvantul-zilei/2015/09/01)). Avem #478 pentru acelea.

**Comment by CatalinFrancu** [comment]
Este live, arată bine.
