### ISSUE TITLE
Probleme cu fontul

### ISSUE THREAD

**Issue by CatalinFrancu** [dexonline/dexonline#483]
Nu știu dacă merg „rezolvate” propriu-zis, dar măcar să căutăm un font care nu cauzează aceste probleme.

* La [mirodea](https://dexonline.ro/definitie/mirodea/1005333), î-ul cu accent cauzează probleme __înaintea__ lui, până la litera ș. Mai ciudat, la inspecție (F12), accentul se mută de pe î pe litera următoare. E posibil să fie un bug la implementarea Unicode.
* Idem la [cîrciumă](https://dexonline.ro/definitie/c%C3%AErc%C4%ADum%C4%83/571399)

La câteva persoane diacriticele românești apar cu alt font.

**Comment by aifrim** [comment]
Open Sans—Network resource(6 glyphs)
Times New Roman—Local file(3 glyphs)

E din cauză că sunt folosite 2 fonturi pentru afișarea cuvântului cîrciumă. 

`î́` - acest caracter cauzează problema.

Bănuiesc că voi doriți să afișați cuvintele fonetic.

**Comment by CatalinFrancu** [comment]
Da, dar asta nu ne lămurește prea bine. De ce alege să afișeze acel caracter cu TNR? Din câte știu, ar trebui să fie definit în Open Sans, prin compunere (caracterul Unicode pentru accent poate sta pe orice simbol). Și doi la mână, de ce sunt afectate și caracterele anterioare?

**Comment by aifrim** [comment]
Vă apare un caracter în plus.

	cîrciumă:

	99   "c"
	238   "î"
	769   "́"
	114   "r"
	99   "c"
	301   "ĭ"
	117   "u"
	109   "m"
	259   "ă"

Iar mai departe:

	muștarul-stî́ncilor
	109   "m"
	117   "u"
	537   "ș"
	116   "t"
	 97   "a"
	114   "r"
	117   "u"
	108   "l"
	 45   "-"
	115   "s"
	116   "t"
	238   "î"
	769   "́"
	110   "n"
	 99   "c"
	105   "i"
	108   "l"
	111   "o"
	114   "r"

Acest caracter 769 forțează apariția fontului suplimentar. Oricum. Trebuie să băgați în CSS fonturi de back-up mai similare. Ex: `font-family: "Open Sans", "Arial", sans-serif`

![image](https://cloud.githubusercontent.com/assets/825952/17807997/236a7430-6616-11e6-938a-4fdf6d8e3861.png)

![image](https://cloud.githubusercontent.com/assets/825952/17808018/44f50462-6616-11e6-817d-1cca2bee708a.png)

**Comment by aifrim** [comment]
M-am uitat și e vorba de unicode 0301 pe care îl oare Open Sans-ul dar se pare că nu e afișat bine de Chrome 52.
Observ că pe Firefox 46.1, IE 11 și Edge e afișat cum trebuie.

**Comment by danburzo** [comment]
Am remarcat și eu acum pe iOS problema cu fonturile. După ce ajung la calculator pot să investighez și eu problema.

**Comment by danburzo** [comment]
[Noto Sans](https://www.google.com/get/noto/) se pare că nu are problema asta _atunci cînd nu e luat prin API-ul Google Fonts_. (S-ar putea să fie o problemă cu a combina caractere din script-uri diferite). Dezavantajul e că fișierul WOFF pentru o singură greutate are 220kb...

**Comment by aifrim** [comment]
Atunci nu folosiți font-uri pe care oamenii nu le au.

Arial pentru body
TNR pentru headere

**Comment by CatalinFrancu** [comment]
Vezi și #484 - de testat dacă codul CSS propus acolo mai este necesar sau poate fi eliminat.

**Comment by CatalinFrancu** [comment]
@danburzo Cum ziceam, avem un bug in Bootstrap-ul compilat, că face default la serif în loc de sans-serif. Îl vom rezolva.

Nu-mi place ideea să servim noi înșine fontul. Chiar dacă folosim un CDN, pentru majoritatea utilizatorilor va apărea ca informație nouă, care trebuie descărcată. De la Google Fonts e foarte posibil să aibă deja Open Sans. Mai important, din câte știu diverse browsere suportă diverse formate, deci nu e prudent să servim noi direct WOFF. Specificația de la Google Fonts le enumeră pe toate și browserul își poate alege.

@aifrim Confirm că în Firefox arată bine.

**Comment by danburzo** [comment]
Ziceam doar de faptul că bugul propriu-zis nu cred că poate fi rezolvat cu Google Fonts API, din cauză că nu reușește să construiască caracterul compus din ceea ce cred eu (dar nu-s 100% sigur) că sunt două script-uri diferite. 

Bineînțeles, dacă există un sans-serif în CSS stack se va ameliora mult (chiar suficient) problema.

Vizavi de servitul fonturilor proprii, am menționat WOFF în contextul în care, chiar fiind cel mai bine comprimat format de webfont, e extrem de mare: 200kb x 3 sau 4 greutăți este foarte mult. (Căci de altfel, s-ar putea converti în toate formatele necesare, astfel încît să meargă peste tot).

Aș urmări doar situația pe IOS, încă nu mi-e clar de ce diacriticele nu se văd ok -- s-ar putea, dar n-am verificat încă, să îi fie servit, atunci cînd se cere stylesheet-ul, doar scriptul `latin`, și atunci s-ar putea repara cerînd în mod explicit cu `script=latin,latin-ext` în URL (+ alte script-uri de care mai e nevoie)

**Comment by CatalinFrancu** [comment]
Problema s-a ameliorat mult după declararea lui sans-serif ca fallback. Încă există, dar este mai puțin supărătoare.

Eu m-aș opri aici din investigat. Propun să păstrăm fontul curent. Este posibil să găsim unul care să redea corect accentele combinate, dar este o situație destul de rară în practică. Cred că este preferabil să ne concentrăm pe un font lizibil decât pe unul care să redea corect absolut toate glifele.

**Comment by danburzo** [comment]
Și pe IOS arată cît de cît ok. Cu mențiunea că pe unele pagini (e.g. https://dexonline.ro/contact) se servește o versiune mai veche de Bootstrap, și încă se vede ciudat, dar mă aștept să fie doar o treabă de recompilare a template-urilor.

**Comment by CatalinFrancu** [comment]
Cred că versiunea de Bootstrap e aceeași ca peste tot, doar că pagina de contact este neatinsă de vreo 8 ani. :-) Nu a fost convertită la Bootstrap. Și ar trebui și simplificată, că nu citește nimeni atât.

**Comment by danburzo** [comment]
Acuma s-a reparat, se cerea un `bootstrap.min.css?v=veche`, nu știu exact de ce...
