### ISSUE TITLE
Săgeata de la declinări nu apare pe Chrome

### ISSUE THREAD

**Issue by danburzo** [dexonline/dexonline#484]
[Săgeata de la declinări](http://graphemica.com/%E2%96%BD) nu apare pe Chrome/OS X, se pare că nu face fallback corect.

<img width="86" alt="screen shot 2016-08-22 at 12 33 14" src="https://cloud.githubusercontent.com/assets/205375/17850170/9e63b80e-6864-11e6-8255-1a9a64a4dde0.png">

Soluția cea mai simplă e:
```css
#inflArrow {
  font-family: serif;
}
```
ca să sară peste Open Sans (care oricum nu are caracterul ăsta) și să meargă direct la fonturile de sistem.

**Comment by CatalinFrancu** [comment]
Avem noi o chestie bușită în Bootstrap, că avem Open Sans cu fallback la sans-serif. Vom repara în curând să facă fallback la serif, caz în care acest cod s-ar putea să devină nenecesar. Dar momentan îl preluăm.
