### ISSUE TITLE
Subliniere consistentă a abrevierilor

### ISSUE THREAD

**Issue by danburzo** [dexonline/dexonline#485]
Momentan, pe Firefox abrevierile sunt subliniate de două ori. Asta e din cauză că Firefox a implementat `text-decoration: dotted underline`, și folosește asta în stylesheet-ul browserului pentru `abbr`, pe cînd Webkit folosește `border-bottom` în acest sens.

Ca să arate la fel peste tot, mai trebuie adăugat:

```
abbr[title] {
  text-decoration:none
}
```

(Thread relevant pe Bootstrap: https://github.com/twbs/bootstrap/issues/16574) 

P.S. Îmi cer scuze că loghez buguri fără Pull Requests, după ce îmi pun în picioare environmentul o să vin și cu PR-uri :)

**Comment by danburzo** [comment]
Am reușit să-mi setez (oarecum) environmentul, văd un commit recent cu _recompile Bootstrap_. Unde se țin sursele pentru fișierele CSS minificate?

**Comment by aifrim** [comment]
http://meyerweb.com/eric/tools/css/ :)

**Comment by CatalinFrancu** [comment]
@danburzo Dacă am înțeles bine de la frontenderi, configurația personalizată de Bootstrap stă în `wwwbase/config.json`. O poți încărca la http://getbootstrap.com/customize/ dacă vrei să continui să personalizezi chestii.

**Comment by danburzo** [comment]
Ah, am înțeles, mersi!

**Comment by aifrim** [comment]
@CatalinFrancu @danburzo 
Sunt și alte soluții pentru a configura bootstrap și de a-i aduce fix-uri care să fie în fața la ceea ce au cei de la bootstrap având în vedere că ei muncesc de zori la bootstrap 4 și din când în când la 3.

E vorba de o combinație între npm, bower și gulp. În care avem dependencies stabilite, configurate și compilate.
