### ISSUE TITLE
Segmentation fault 11 la patch-ul 00159.php

### ISSUE THREAD

**Issue by danburzo** [dexonline/dexonline#486]
Am încercat să-mi aduc baza de date proaspăt-instalată la ultima versiune, dar mi se oprește la patch-ul 00159.php cu `Segmentation Fault: 11`. Aveți oare vreo idee ce poate cauza asta, sau cum aș putea rula altfel patch-ul? 

Sau să aștept să ajungă ultimul set de patch-uri în dump-ul de DB și să o reinstalez atunci?

**Comment by danburzo** [comment]
Se pare că aici crapă:
```php
$lms = $orig->getLexemModels();
```

Cu riscul de a pune o întrebare stupidă, dar n-ar trebui să existe metoda `getLexemModels` undeva? Momentan ajunge pe ramura `self::__die('cannot handle method', $name, $arguments);` din BaseObject.

**Comment by CatalinFrancu** [comment]
Mea culpa! Am lăsat cu bună știință repo-ul într-o stare care nu se pupă cu baza de date, că m-am oprit pentru somn. Am sperat că nu se prinde nimeni câteva ore. :-)

Ieri am făcut un merge uriaș din ramura _struct_ în _master_, ceea ce a adus dintr-o dată 15-20 de patchuri. Dintr-o limitare a sistemului, patchurile cu extensia _php_ ar trebui executate imediat ce sunt adăugate la repo, altfel codul se poate schimba și acele patchuri ajung să folosească metode inexistente. Acum, `tools/migration.php` încearcă să execute `00159.php` când codul s-a schimbat și `getLexemModels()` nu mai există.

Voi pune la noapte modificările în producție și deci de mâine dimineață poți descărca baza de date la zi. Până atunci, o soluție este să muți HEAD-ul la fiecare patch php (00159, 00166, 00172, 00175) și să execuți `migration.php`:

```
tail -f /var/log/dexonline.log &
git checkout d3e0a29f4e29da15633a7af595fb1f13e2e00697
php tools/migration.php
git checkout ca68d44dc01f7820df169b574ab99ccf9eb324e3
php tools/migration.php
git checkout 81943f9b9dbf92c5ba8a61163916545e211d53f2
php tools/migration.php
git checkout 57d1cb11de8a64f05ec2777ca496405a4203eb52
php tools/migration.php
git checkout master
php tools/migration.php
```

**Comment by danburzo** [comment]
Cumva am reușit să trec peste patch-ul respectiv (am pus metoda să returneze un array gol) și să ajung într-o stare relativ ok a bazei de date -- astfel încît să pot încărca pagini de definiții. Încă nu merge totul, dar pentru scopurile mele e ok, deci nu e grabă cu baza de date la zi :-)

**Comment by CatalinFrancu** [comment]
Gata, totul este live. Dacă ai nevoie, poți descărca baza de date, care acum este în sync cu codul.
