### ISSUE TITLE
Responsive.css ar trebui să fie ultimul stylesheet

### ISSUE THREAD

**Issue by danburzo** [dexonline/dexonline#488]
Am încercat să repar un bug pentru device-urile cu ecrane mai mici, și anume să scot `margin`-ul de pe tabela cu declinări. Cu ocazia asta am remarcat că, fiindcă `responsive.css` se încarcă înainte de alte stylesheet-uri, nu se pot suprascrie stiluri decît cu `!important` sau cu selectori de specificitate mai mare. 

Dacă `responsive.css` ar fi ultimul stylesheet inclus, s-ar putea folosi aceiași selectori CSS, care vor avea specificitate mai mare din cauza ordinii.

**Comment by CatalinFrancu** [comment]
Hm, ca să răspund inginerește, „la mine merge”. :-) Pe paginile de căutări, de exemplu:

```
<link href="/css/bootstrap.min.css?v=2016082305" rel="stylesheet" type="text/css"/>
<link href="/css/responsive.css?v=2016082304" rel="stylesheet" type="text/css"/>
<link href="/css/paradigm.css?v=2016082304" rel="stylesheet" type="text/css"/>
<link href="/css/autoload/search.css?v=2016081304" rel="stylesheet" type="text/css"/>
```

Motivul pentru ordinea curentă este tocmai ca `responsive.css` să poată suprascrie stilurile lui `bootstrap.css`, iar chestiile specifice paginii curente (`paradigm.css` și `search.css`) să le poată suprascrie pe ambele.

Ce altă ordine ai prefera? Poți controla ordinea din `SmartyWrap.php::addCss()`.

**Comment by danburzo** [comment]
Scuze, cred că m-am exprimat lacunar, sau am înțeles greșit scopul stylesheet-urilor.

În felul în care e acum ordinea, prin faptul că stilurile specifice paginii (de ex. `search.css`) sunt ultimele, și vrem să ajustăm design-ul pentru diverse device-uri, suntem obligați fie: 

* să includem în toate aceste fișiere aceleași `@media` queries pt a ajusta design-ul
* să forțăm nota (cu !important sau specificitate mai mare la selector) în media query-urile din `responsive.css` ca să le suprascriem stilurile

Nu știu cît de ușor de întreținut sunt oricare din variantele astea două.

Eu m-aș fi așteptat la următoarea ordine:

1. `bootstrap.css` vine cu default-urile framework-ului
2. chestiile specifice paginii suprascriu stilurile din bootstrap
3. `responsive.css` conține strict ajustările necesare pentru diversele mărimi de ecran

(Cu mențiunea că la 2, ar putea eventual exista un `dexonline.css` global + fișier CSS pentru pagina curentă)

**Comment by CatalinFrancu** [comment]
Hm, răspund doar la ce mă pricep și o las pe Sonia la restul. :-)

Numele `responsive.css` e cam nepotrivit, din motive istorice. Când am început migrarea la Bootstrap, am denumit skinul (și branchul) _responsive_. De fapt, el nu se ocupă doar de partea de responsiveness, ci include toate declarațiile globale. L-am putea redenumi _main.css_ sau cumva.

Paradigmele (aka flexiunile, aka nume generic pentru conjugări și declinări) nu au fost încă convertite la bootstrap. Și așezarea trebuie schimbată, că e greoaie, în special pentru verbe. Vezi #125. Și ne gândim să înlocuim link-ul de flexiuni cu un tab.

**Comment by sandriu** [comment]
Dacă totul e ok acum (PHP-side), atunci putem închide tichetul.

**Comment by danburzo** [comment]
:+1: și scuze că am dispărut de pe fața pămîntului, am căzut într-un _hellhole_ de muncă, mă întorc cu forțe noi :)

**Comment by sandriu** [comment]
Stai liniștit, @danburzo . Și noi suntem prinși în mai multe proiecte.
Închid tichetul; dacă pe viitor încă ne mai lovim de probleme de precedență la stylesheet-uri, îl redeschidem.

**Comment by CatalinFrancu** [comment]
Pare că e într-un branch? Îl redeschid până îl rezolvăm pe master.

**Comment by sandriu** [comment]
Nu mai este pe branch, a fost integrat cu master când am integrat branch479.
Gata, chiar îl închid acum :)) .
