### ISSUE TITLE
Minimizare / Obusfucare javascript & css

### ISSUE THREAD

**Issue by aifrim** [dexonline/dexonline#491]
Am observat din discuția de la problemele cu fontul că doriți să serviți fișiere cât mai mici.

Sugerez câteva lucruri:

1. Folosirea gulp-ului care să minifice / obusfucheze fișierele statice
    Am făcut un test și de la:

    - `505 KB (517,750 bytes)` de CSS am ajuns la `302 KB (309,842 bytes)`
    - `2.10 MB (2,207,216 bytes)` de JS am ajuns la `1.51 MB (1,589,706 bytes)`

    Asta reprezintă o îmbunătățire de: `30,11%`

2. Folosirea **SASS/SCSS** pentru a scrie codul de CSS.
Astfel puteți compila direct minificat.

**Comment by danburzo** [comment]
Felul în care e construit css-ul acum, în care nu există decît unul sau două fișiere comune + cîte un css individual pentru fiecare pagină în parte face concatenarea impractică.

În plus, faptul că CSS-ul și JS-ul este servit cu gzip face minificarea cvasi-inutilă; minificate sau neminificate, vor avea cam aceeași dimensiune gzip-uită. (Poți testa orientativ asta făcînd zip din versiunea minificată și cea neminificată a CSS-ului).

**Comment by aifrim** [comment]
Am luat 2 fișiere CSS și două fișiere JS și le-am comparat variantele minificate și non-minificate gzipuite.

## responsive.css
`1.28 KB (1,319 bytes)` minified gzipped
`1.54 KB (1,580 bytes)` non-minified gzipped
**`16.88%` mai bine**

## visualDict.css
`387 bytes (387 bytes)` minified gzipped
`445 bytes (445 bytes)` unminified gzipped
**`13.03%` mai bine**

## dex.js
`2.57 KB (2,641 bytes)` minified gzipped
`3.73 KB (3,821 bytes)` unminified gzipped
**`31.09%` mai bine**

# crawler_ajax.js
`369 bytes (369 bytes)` minified gizpped
`500 bytes (500 bytes)` unminified gzipped
**`26.2%` mai bine**

## Rezultat
**`21.8%` mai bine**

**Comment by CatalinFrancu** [comment]
Mulțumim pentru statistici! Sigur, mai puțin e mai bine. :-) Dar depinde și care este procesul (nu știu nimic despre gulp).

Trebuie să avem sursele undeva separat, iar cele minificate trebuie compilate înainte de push?

În development, trebuie să fac această compilare de câte ori modific un fișier, presupun? Sau putem configura sistemul să încarce fișierul ne-minificat dacă este mai nou decât cel minificat? M-am dezobișnuit de limbajele compilate, mi-ar fi lene să compilez la fiecare salvare. :-)

În orice decizie, ar trebui să ținem cont mai ales de cele două pagini care generează 90%+ din conținut: căutările și pagina principală. Pentru acestea, fișierele relevante sunt:

* declarația de font
* jquery-ui
* bootstrap
* responsive.css
* paradigm.css și search.css pentru căutări
* index.css pentru pagina principală

Nu am o opinie despre combinarea fișierelor. Pe de o parte, mai puține requesturi sunt un lucru bun. Câștigul poate fi mai mare decât 1 KB sau 2 KB economisiți. Pe de altă parte, dacă responsive.css trebuie inclus separat în CSS-urile pentru fiecare pagină, se strică cache-ul.

**Comment by aifrim** [comment]
Principiul e în felul următor:

1. Sursele sunt puse undeva separat
2. Se compilează la salvare (automat, nu trebuie să faci tu)
3. Când e mod development se poate lăsa neminificat / neobusfucat
4. Putem să nu concatenăm - doar să le minificăm / obusfucăm.
5. Se pun în gitignore folderele wwwbase/css și wwwbase/js
6. La pull / clone se rulează un task de build (cu setarea de producție / development)

Gulp e rulat prin sistemul npm / nodejs. El citește un gulpfile.js unde sunt definite niște sarcini (tasks).
Momentan pentru noi pot fi:

- **css/scss** &raquo; care testează și îți zice dacă ai greșit ceva și după minifică (dacă e cazul)
- **js** &rqauo; care face un jshint și îți zice dacă ai greșit ceva și după minifică / obusfucă (dacă e cazul)
- **watch** &raquo; care urmărește fișierele css/scss/js și rulează sarcinile de css/scss și js dacă le modifici
- **build** &raquo; care rulează automat taskurile de css/scss și js sub mod development
- **build-production** &raquo; care rulează taskurile de css/scss și js sub modul de producție

Adiacent puteți folosi **bower** pentru gestionarea dependețelor și să preluați variantele .min sau neminificate pentru mediile corecte
- jquery, jquery-ui
- bootstrap
- select2
- tinymce
- etc.

**Comment by CatalinFrancu** [comment]
Wow, sună dezarmant. :-) Există un câștig de câțiva KB la fișierele cel mai des folosite, iar partea de linting sună bine. Dar e o componentă în plus care trebuie întreținută. Lasă-mă, te rog, să-i întreb și pe ceilalți ingineri.

**Comment by aifrim** [comment]
Având în vedere că eu sugerez asta am să și mă ocup făcând modificările de rigoare + documentația adiacentă.

Gulp are o integrare decentă în ATOM și PhpStorm / WebStorm / Netbeans. Poate are și în altele.
Bower e bun pentru managementul dependețelor. 

Ambele necesită documentare - ca să se știe cu ce se mănâncă.

**Comment by aifrim** [comment]
@CatalinFrancu 
Status? Ce părere au?

**Comment by CatalinFrancu** [comment]
Am vorbit cu @raduborza și amândoi am prefera să nu ne complicăm. Există beneficii, dar nu foarte mari și adăugăm un nivel în plus de complexitate. De exemplu, pe paginile de căutare (cazul cel mai comun), am economisi 2-3 KB (din dex.js, responsive.css, paradigm.css și search.css) și am putea economisi 2 requesturi dacă am combina cele 3 CSS-uri într-unul.

Pentru Sass, la fel, nu cred că folosim CSS destul de intens încât să merite. Știu că avem ceva redundanță, dar este foarte puțină.

**Comment by aifrim** [comment]
E în regulă.

Închid acest issue :)
