### ISSUE TITLE
Wiki-ul dexonline

### ISSUE THREAD

**Issue by danburzo** [dexonline/dexonline#492]
Aș putea să încep să adaug/mut niște informații pe wiki-ul de pe Github, dar voiam să întreb înainte dacă este vreo direcție aici. Se dorește păstrarea MediaWiki-ului ca sursă principală de informații? Sau unică? 

Am văzut, de exemplu, că a apărut o pagină nouă despre Database Schema, și aș vrea să o completez pe alocuri.

**Comment by CatalinFrancu** [comment]
Nouă ne place principiul „datele mele pe calculatorul meu”. Dacă sunt chestii care se integrează strâns cu codul, atunci GitHub poate fi un loc mai bun pentru ele. Schema bazei de date ar putea fi un exemplu. Cum vrei tu, îți pot face un cont pe wiki-ul nostru sau îți dau drepturi pe wiki-ul de pe GitHub. Și mulțumim!

**Comment by danburzo** [comment]
O să fac un exercițiu cu database schema pe wiki-ul de Github. Cred că pot deja să creez pagini pe el. De altfel, wiki-ul e tot un repository de Git care poate fi clonat/salvat, iar articolele sunt Markdown.

**Comment by danburzo** [comment]
Am pus [Database Schema](https://github.com/dexonline/dexonline/wiki/Database-Schema) și încă un articol pe Wiki. Mai e de lucru la schema (linkuire cu source code, linkuire referințe la tabele între ele, etc.) dar e un început. 

Mă simt un pic bizar că e wiki-ul liber și nu există process de approval pe informațiile de acolo, dar zic preventiv că nu mă deranjează modificările agresive și/sau ștergerea articolelor, dacă e necesar :)

**Comment by CatalinFrancu** [comment]
Wow, mulțumesc! Arată foarte profi, te-ai chinuit ceva. Am șters pagina de pe wiki.dexonline.ro și am refăcut  linkul (există unul în pagina de informații).

Și eu mă mir că nu pot configura sistemul să-mi trimită e-mail când se modifică ceva pe wiki.

Aș vrea să-ți pot asigna ție tichetul, ca să-l închizi când crezi, dar nici asta nu se poate. :-)
