### ISSUE TITLE
Eroare afișare definiție

### ISSUE THREAD

**Issue by danburzo** [dexonline/dexonline#495]
Am remarcat asta în producție pentru https://dexonline.ro/definitie/casă
<img width="1279" alt="screen shot 2016-08-23 at 14 49 12" src="https://cloud.githubusercontent.com/assets/205375/17890792/c8b7717c-6940-11e6-8649-563129229652.png">

**Comment by CatalinFrancu** [comment]
Oops! Erau niște valori vechi prin cache-ul Varnish, de când am făcut un pic de depanare în producție, cum se face. :-) Am repornit cache-ul și problema a dispărut.
