### ISSUE TITLE
Minor: discrepanță între nr. total de definiții promise vs. afișate

### ISSUE THREAD

**Issue by danburzo** [dexonline/dexonline#498]
[mașină](https://dexonline.ro/definitie/ma%C8%99in%C4%83) &mdash; „Din totalul de 31 sunt afișate 20 definiții”
[mașină/expandat](https://dexonline.ro/definitie/ma%C8%99in%C4%83/expandat) &mdash; „29 definiții”

**Comment by CatalinFrancu** [comment]
Mulțumesc pentru semnalare. Există definiții vizibile doar pentru moderatori (din surse pentru care nu avem drept de republicare). Bugul era că număram definițiile, apoi ascundeam o parte din ele.
