### ISSUE TITLE
Convertește la Bootstrap pagina /cuvinte-favorite

### ISSUE THREAD

**Issue by CatalinFrancu** [dexonline/dexonline#499]

**Comment by vargaradu** [comment]
Ce e de făcut aici mai exact? văd că sunt deja folosite clase de bootstrap aici (container, row, col-md-12, ..)
Vrem să facem să arate pagina asta în stilul paginii "definiție" poate?

**Comment by CatalinFrancu** [comment]
Exact, ar trebui să arate mai ca paginile cu rezultate - definiția întâi, urmată de acea bară standard de acțiuni. Ideal ar fi chiar să extinzi `templates/bits/definition.tpl` cu acțiunea de eliminare dintre favorite.

**Comment by vargaradu** [comment]
Includem și commenturile?

**Comment by CatalinFrancu** [comment]
Dacă există, le includem!
