### ISSUE TITLE
Logo în format SVG

### ISSUE THREAD

**Issue by CatalinFrancu** [dexonline/dexonline#502]
Cred că putem migra fără probleme la logo în format SVG. Avem doar 0,34% din utilizatori pe IE ≤ 8, pentru care SVG-ul efectiv nu merge, deci nu mi-aș bate capul cu un fallback.

O a doua categorie sunt utilizatorii de IE > 8 și Edge (4,04%), pentru care nu merge scalarea SVG-urilor. Pentru aceștia putem scrie niște CSS (vezi [asta](http://codepen.io/tomByrer/pen/qEBbzw?editors=110) și [asta](http://tympanus.net/codrops/2014/08/19/making-svgs-responsive-with-css/)). Eu unul nu mi-aș bate capul nici cu asta. :-)

Trebuie convertit logo-ul din pagina principală și logourile din meniul de navigare (sunt două acolo, în funcție de lățimea paginii).

**Comment by danburzo** [comment]
Pot să mă ocup și eu de asta, dacă este pe undeva o versiune „canonică” a logo-ului.

**Comment by CatalinFrancu** [comment]
Sigur, mulțumim! Mă asignez pe mine, ca să se știe că lucrează cineva la el, dar e al tău.

Anexez logo.svg (.zip, ca să mă lase GitHub): [logo.svg.zip](https://github.com/dexonline/dexonline/files/464357/logo.svg.zip)

**Comment by sandriu** [comment]
Atenție că logo-urile de pe paginile secundare nu erau cu text 100% black (cum este logo-ul original dexonline, gândit CMYK), ci erau 95% black (parcă), pentru a se asorta mai mult cu gri-ul itemilor din meniul de navigare.
Aceleași logo-uri aveau schimbată și grosimea liniei cu care erau desenate, fiindcă liniile nu se scalau bine la micșorarea logo-ului (deveneau prea groase).

@danburzo : dacă ai Adobe Illustrator sau alt program de editare SVG-uri, poți face tu aceste modificări. Dacă nu, te rog spune-mi.

Revin cu un update legat de nuanța exactă de gri + grosimea liniei după ce bootez în Windows, unde am Illustrator.

**Comment by danburzo** [comment]
Mă ocup eu de ele, mai notez aici și observația cu ecranul de 320px de pe Pull Request.

**Comment by CatalinFrancu** [comment]
Ping! @danburzo, ai cumva vreo veste pentru conversia logoului? (E vorba de 90% negru cu linie de 2px / 1px).

E ok dacă nu, viața se întâmplă. :-) Doar să ne dai de veste ca să te deasignăm.

**Comment by danburzo** [comment]
Salutare, mă ocup diseară cînd ajung la laptop :)
