### ISSUE TITLE
Redesign acțiuni pentru definiții

### ISSUE THREAD

**Issue by danburzo** [dexonline/dexonline#504]
Am o propunere pentru îmbunătățirea listei de definiții: 

![page 1](https://cloud.githubusercontent.com/assets/205375/18403852/ebb9b010-76ef-11e6-84c6-82cf2bf5220b.png)

1. Cele două acțiuni (_adaugă la favorite_ și _raportează o problemă_) primesc mica lor coloană în stînga
2. Termenul în aldine devine permalink către definiție
3. Bara de sub definiție rămîne pentru metadata

Dintre toate cele trei, cred că №2 ar fi cel mai complicat. Eventual permalink poate rămîne în bara de metadata, eventual sub forma de _#_ (mă gîndesc că cine știe ce-i aia permalink e familiar și cu convenția diezului).

Ce părere aveți? 

Cu ocazia asta aș expune și acțiunea de _defavorizare_<sup>1</sup> direct în lista de definiții (văd că o dată adăugat în lista de favorite, numai din acea listă mai poate fi șters)

<sup>1</sup> `¯\_(ツ)_/¯`

**Comment by CatalinFrancu** [comment]
Aș unifica tichetul ăsta cu #282. Fie facem un meniu minimalist vizibil tot timpul, bazat mai mult pe iconițe, fie facem o chestie la hover. Într-adevăr, (2.) pare greu de făcut când definițiile sunt doar text blobs (cum sunt acum).

**Comment by danburzo** [comment]
Ah, mi-a scăpat #282. O să mut eu observațiile mele acolo.
