### ISSUE TITLE
Meniul de căutare avansată trece neobservat

### ISSUE THREAD

**Issue by CatalinFrancu** [dexonline/dexonline#520]
Ne-au scris câțiva utilizatori să ne întrebe unde a dispărut. Nici eu nu l-am văzut la început. :-)

@sandriu a propus să revenim la forma veche, cu link:
- în dreapta butonului „Caută” dacă lățimea permite;
- sub butonul „Caută”, aliniat la dreapta, pentru lățimi mici.

**Comment by vargaradu** [comment]
Nu știu exact cum era forma veche, am făcut varianta asta:
![screen shot 2017-01-30 at 13 27 59](https://cloud.githubusercontent.com/assets/12733992/22423029/f51012d8-e6ef-11e6-986a-3e132b47d3c0.png)

Print screenul e de la cel mai mic width posibil cu Firefox. Mi se pare că nu câștigăm prea mult spațiu dacă mutăm butonul de "Menu" sub cel de "Caută", nici estetic nu ar fi. Aș propune:
- Să lăsăm așa pentru toate lățimile, ori
- Să mutăm ambele butoane sub. Ceva de genul:
![screen shot 2017-01-30 at 14 29 15](https://cloud.githubusercontent.com/assets/12733992/22424804/7f4bb9f4-e6f8-11e6-900f-17daf695003e.png)

**Comment by CatalinFrancu** [comment]
Mda, scuze că n-am clarificat care era „forma veche”, [uite-o aici](http://web.archive.org/web/20160305023435/https://dexonline.ro/). Deci meniul hamburger este înlocuit de un link clasic, cu textul „opțiuni” (e mai scurt decât „căutare avansată” și e suficient de clar).

Iar atunci, la lățime mică, cred că ar fi și estetic. Mai faci o încercare, te rog?

**Comment by vargaradu** [comment]
Solved
![screen shot 2017-02-06 at 18 57 22](https://cloud.githubusercontent.com/assets/12733992/22659497/1d61048c-ec9e-11e6-97e6-827a11ea3316.png)
![screen shot 2017-02-06 at 18 57 15](https://cloud.githubusercontent.com/assets/12733992/22659498/1ec5319a-ec9e-11e6-87a1-bb9ca5918da7.png)
Pull request: https://github.com/dexonline/dexonline/pull/550
