### ISSUE TITLE
Elemente de stilat la căutare

### ISSUE THREAD

**Issue by CatalinFrancu** [dexonline/dexonline#532]
Sunt în proces de reorganizare a rezultatelor căutării - în primul rând pentru a ține cont de intrări (intrările grupează mai multe cuvinte, cum ar fi _cârciumar_ și _crâșmar_). Lucrez pe ramura `entriesInSeach` (notă: e un typo, am tastat greșit la creare). Am făcut și o instalare de test pe http://resp.dexonline.ro/

Sunt multe lucruri care se pot întâmpla la o căutare și toate trebuie stilate. Le inventariez aici, începând cu cele mai frecvente.

## Căutare normală

Exemplu cu o singură intrare, cu puține definiții:

http://resp.dexonline.ro/definitie/abstrus

Exemplu cu peste 20 de definiții - trebuie menționat totalul și pus un link _arată toate definițiile:_

http://resp.dexonline.ro/definitie/albastru

Exemple cu o singură intrare care are și forme alternative. Formele alternative sunt de două feluri și cred că ar merita diferențiate: principale (_abager_ și _abagiu_ sunt la fel de acceptate) sau variante (_bocal_, _bocală_ sunt variante pentru _pocal_, forma recomandată fiind _pocal_).

http://resp.dexonline.ro/definitie/viraj

Exemple cu mai multe intrări, fiecare cu sau fără variante

http://resp.dexonline.ro/definitie/ochi
http://resp.dexonline.ro/definitie/hingheri

## În lucru: arbori

Arborii încorporează multe definiții pentru o intrare (dar nu pe toate). Când îi avem, îi prezentăm - nu sunt mulți acum, dar pe viitor vom avea arbori pentru toate cuvintele.

Cred că ar fi bine să prezentăm arborii întâi, urmați de definițiile care nu sunt încorporate, iar definițiile care sunt încorporate să stea la un click distanță - în alt tab sau într-un div încărcabil prin Ajax.

http://resp.dexonline.ro/definitie/c%C3%A2rcium%C4%83reas%C4%83
http://resp.dexonline.ro/definitie/monitor

Note:

* o intrare poate avea mai mulți arbori;
* stilarea arborilor va fi un tichet în sine.

## Căutare aproximativă (când căutarea normală nu dă rezultate)

http://resp.dexonline.ro/definitie/spacan

Fără niciun rezultat:

http://resp.dexonline.ro/definitie/asdasdasdasdasd

## Căutarea unei intrări anume

Când rezultatele includ mai multe intrări omonime, ca de exemplu [cârciumăreasă](http://resp.dexonline.ro/definitie/c%C3%A2rcium%C4%83reas%C4%83) sau [ochi](http://resp.dexonline.ro/definitie/ochi), utilizatorul poate da click pe oricare dintre intrări pentru a vedea doar pagina acelei intrări:

http://resp.dexonline.ro/intrare/c%C3%A2rciumar/8574

## Căutare full-text

Exemplu simplu:

http://resp.dexonline.ro/text/saramur%C4%83%20pe%C8%99te

Exemplu cu număr de rezultate peste limită (trebuie menționat undeva că există **M** rezultate din care sunt afișate **N**).

http://resp.dexonline.ro/text/copil%20mic

Exemplu cu cuvinte ignorate _(stop words):_

http://resp.dexonline.ro/text/%C3%AEn%20alb%20%C8%99i%20negru

Exemplu fără rezultate:

http://resp.dexonline.ro/text/spanac%20stetoscop

## Căutare cu cuvinte multiple

Este o căutare diferită de cea full-text - sunt căutate doar cuvintele-titlu, nu și cuprinsul definițiilor. De remarcat mențiunea de sub header, cu link spre căutarea full-text.

http://resp.dexonline.ro/definitie/cal%20de%20mare

Fără rezultate:

http://resp.dexonline.ro/definitie/abcdef%20ghijkl

Cu cuvinte ignorate (când sunt mai mult de 5 cuvinte, caz rarisim):

http://resp.dexonline.ro/definitie/alb%20negru%20verde%20gri%20roz%20mov%20maro

## Căutare cu expresii regulate

Exemplu simplu:

[http://resp.dexonline.ro/definitie/capo*](http://resp.dexonline.ro/definitie/capo*)

Exemplu cu număr de rezultate peste limită:

[http://resp.dexonline.ro/definitie/c*](http://resp.dexonline.ro/definitie/c*)

Exemplu fără rezultate:

[http://resp.dexonline.ro/definitie/qq*](http://resp.dexonline.ro/definitie/qq*)

## Căutare după ID

Când căutarea conține doar cifre, este prezentată strict definiția cu acel ID:

http://resp.dexonline.ro/definitie/30000

## Diverse avertismente și subtitluri

La căutarea într-un anume dicționar, când nu există rezultate:

http://resp.dexonline.ro/definitie-dge/abstract

După ce te conectezi în contul _doar_oficial_ (sau, alternativ, după ce bifezi la preferințe _Ascunde definițiile neoficiale_):

http://resp.dexonline.ro/definitie/bagabei

Cuvinte care au definiții doar în dicționare pe care nu avem dreptul să le redistribuim:

http://resp.dexonline.ro/definitie/gladiatus

Teoretic, aceste avertismente pot coexista.

## Elemente deja stilate

Aici nu e nimic de făcut, dar le menționez pentru completitudine

* Imagini: http://resp.dexonline.ro/definitie/chitar%C4%83
* Articole: http://resp.dexonline.ro/definitie/numai

## Cazuri artificiale

Aceste cazuri pot fi obținute tastând date aiurea sau editând de mână URL-ul.

Intrare cu ID inexistent:

http://resp.dexonline.ro/intrare/c%C3%A2rciumar/9999999

Definiție cu ID inexistent:

http://resp.dexonline.ro/definitie/999999999

**Comment by sandriu** [comment]
Atenție că la ultimul commit am schimbat culoarea de fundal pentru btn-default, din #fff în #eee, ceea ce a redus din contrastul buton-panel pe pagina Donează:

![screenshot_2016-12-01_18-30-17](https://cloud.githubusercontent.com/assets/1265882/20802275/3ff2cb54-b7f4-11e6-88de-7b766f5eb129.png)

Pe pagina de mai sus, butoanele default ar trebui înlocuite cu săgeți.

**Comment by sandriu** [comment]
@CatalinFrancu Pe paginile cu rezultate-arbori și două sau mai multe intrări, ar trebui afișată mai întâi lista de intrări (echivalentul unui "table of contents" al paginii) și abia apoi afișate definițiile corespunzătoare fiecărei intrări.
Vezi http://resp.dexonline.ro/definitie/c%C3%A2rcium%C4%83reas%C4%83, unde utilizatorul vede în primă fază doar intrarea "cârciumar" și abia după ce scrollează un ecran întreg vede și a doua intrare, "cârciumăreasă (plantă)".

**Comment by CatalinFrancu** [comment]
TODO:

* [ ] arată „a ” în fața verbelor

**Comment by CatalinFrancu** [comment]
Am restructurat niște bucăți din cod. În anumite situații am păstrat intrarea pe o singură linie, când există o singură intrare:

http://resp.dexonline.ro/definitie/aduce
http://resp.dexonline.ro/definitie/c%C3%A2rciumar

Când sunt mai multe intrări, afișez o listă cu intrările:

http://resp.dexonline.ro/definitie/ochi

Desigur, este banal să afișăm lista și când este o singură intrare, dar arată ciudat.

Deschid un tichet separat pentru stilarea arborilor. Pe acesta cred că este ok să-l închid.
