### ISSUE TITLE
Stilarea arborilor

### ISSUE THREAD

**Issue by CatalinFrancu** [dexonline/dexonline#537]
Pe branch-ul `EntriesInSeach` (atenție, typo) afișăm arborii, dacă există. Sunt câteva lucruri de îmbunătățit:

## Dorim separarea sensurilor și a etimologiilor?

S-ar putea să fie mai clar să prezentăm întâi doar sensurile (și comentariile, un caz rar), iar exemplele și etimologiile să le grupăm sub arbore. Exemplu:

http://resp.dexonline.ro/definitie/familie

Este bine așa, sau ar fi mai bine să avem doar sensurile (cele cu numere de ordine), urmate de o listă de exemple, poate cu formatul

* exemplu pentru 1: ...
* exemplu pentru 1: ...
* exemplu pentru 2: ...
* exemplu pentru 2.1: ...

## Găsirea unui loc pentru galeriile de imagini

Când există imagini, iar ele vin în dreptul definițiilor, totul arată bine:

http://resp.dexonline.ro/definitie/chitar%C4%83

Dar când există și imagini, și arbori, încălecarea arată urât:

http://resp.dexonline.ro/definitie/automobil

## Stilarea arborilor

Vezi `templates/bits/meaningTree.tpl`. Componentele sunt:

* __breadcrumb__ (numerotare): numere și puncte pentru sensuri, goală în rest
* __tip:__ etimologiile / exemplele / comentariile sunt marcate ca atare
* __conținutul__ propriu-zis
* __surse:__ dicționarele care atestă sensul
* __etichete:__ figurat, ironic, rar, disciplina de aplicare etc.
* __relații:__ sinonime, antonime etc.

După mintea mea, am folosit etichete _(labels)_ din boostrap, cu culorile schimbate.

**Comment by sandriu** [comment]
Legat de "Dorim separarea sensurilor și a etimologiilor?":
- conform [prototipului](http://t1rn4h.axshare.com/#g=1&p=pe_vertical_) creat de mine acum o lună (parola dexy), recomand afișarea etimologiilor și a exemplelor în contextul fiecărui sens și subsens. Nu văd avantajele separării arborelui de sensuri de lista de exemple.

**Comment by sandriu** [comment]
Stilarea arborilor a ajuns în acest punct la momentul actual:

![stilarea arborilor pe 30dec2016](https://cloud.githubusercontent.com/assets/1265882/21563904/9395acc0-ce8f-11e6-8507-5744938bab33.png)

@CatalinFrancu dacă ești mulțumit de aspectul paginii din screenshot, atunci se cheamă că mi-a mai rămas de stilat doar partea cu "Găsirea unui loc pentru galeriile de imagini".

**Comment by CatalinFrancu** [comment]
Uneori par să fie prea multe exemple. Vezi [șterge](http://resp.dexonline.ro/definitie/%C8%99terge) sau [an](http://resp.dexonline.ro/definitie/an). Mi-e teamă să nu îngreuneze citirea sensurilor. Ce zici?

**Comment by CatalinFrancu** [comment]
De afișat partea de vorbire undeva.
