### ISSUE TITLE
Meniul acoperă reclama

### ISSUE THREAD

**Issue by CatalinFrancu** [dexonline/dexonline#547]
Când utilizatorul expandează un meniu (în special _Articole și resurse_), el acoperă reclama, ceea ce este contrar [cerințelor AdSense](https://support.google.com/adsense/answer/4533983?hl=en). Asta poate genera clicuri invalide.

O propunere era să mutăm reclama sub prima definiție. @sandriu spune însă că asta poate duce la _banner blindness_ (utilizatorul să ingnore taburile, antetul și prima definiție).

Contrapropuneri:

* Mutăm reclama sub primele 2-3 definiții, sau, mai general, sub atâtea definiții cât să avem minim 10 linii de text (inclusiv detaliile de sub definiție).
* Mutăm reclama sus de tot, înaintea meniului. Sunt site-uri care fac asta ([The Guardian](https://www.theguardian.com/international), de exemplu).

**Comment by vargaradu** [comment]
Eu subscriu pentru mutatul reclamei sus, mi se pare cel mai ușor de adaptat pentru fiecare ecran.

Aș adăuga altă problemă pe care am observat-o cu reclamele: au poziție absolută + width fix, ceea ce face creează ecranelor cu width mediu și mic să le fie tăiat din partea dreaptă a reclamei:
![screen shot 2017-01-29 at 18 52 51](https://cloud.githubusercontent.com/assets/12733992/22406488/3a2571f2-e654-11e6-8163-b8925f04e3ee.png)

Se poate rezolva ușor cu [Specify an expandable width and a fixed height](https://support.google.com/adsense/answer/6307124?hl=en#adv)

**Comment by raduborza** [comment]
Dacă nu se poate după prima definiție, atunci votez pentru varianta a doua (cea cu reclama sus).
Dar să fim pregătiți să o punem la loc :)

**Comment by CatalinFrancu** [comment]
@vargaradu Dacă se întâmplă doar la redimensionare, iar apoi la refresh reclama arată bine la noua rezoluție, aș zice să nu ne batem capul. Nu e un caz frecvent.

**Comment by CatalinFrancu** [comment]
39efdb350e32e463256e96a7040143095368152c
