### ISSUE TITLE
Unealtă de contorizare a contribuțiilor

### ISSUE THREAD

**Issue by CatalinFrancu** [dexonline/dexonline#561]
Pentru `PRIV_ADMIN`, o mini-pagină care contorizează suma lungimilor definițiilor trimise de un utilizator între două date, grupate pe fiecare sursă (și totalul). Datele implicite prepopulate în formular pot fi începutul și finalul trimestrului trecut (ianuarie-martie, aprilie-iunie etc.).

**Comment by raduborza** [comment]
Aș contoriza și numărul de corecturi făcute (comparînd cu textul OCR inițial)

**Comment by CatalinFrancu** [comment]
De acord. Pentru claritate, originalul (așa cum iese de la OCR + postprocesare) stă în tabela `OCR`, unde câmpul `definitionId` indică ID-ul definiției create din această înregistrare OCR.
