### ISSUE TITLE
Eroare la importarea ultimei baze de date în MySQL

### ISSUE THREAD

**Issue by danburzo** [dexonline/dexonline#563]
Salutare,

Am tras o versiune _fresh_ a bazei de date și la import am primit eroarea asta:

```
ERROR 1293 (HY000) at line 1859: Incorrect table definition; there can be only one TIMESTAMP column with CURRENT_TIMESTAMP in DEFAULT or ON UPDATE clause
```

Știți oare de unde provine și/sau cum poate fi remediată?

**Comment by danburzo** [comment]
Am aflat [în răspunsul ăsta](http://stackoverflow.com/questions/4489548/why-there-can-be-only-one-timestamp-column-with-current-timestamp-in-default-cla). Dintr-un motiv sau altul, MAMP vine cu MySQL 5.5.x, va trebui să mă uit cum mă pot actualiza.

**Comment by CatalinFrancu** [comment]
Dacă e ceva prea enervant, dă-ne de veste și vedem ce putem rescrie ca să scăpăm de acea cerință și să fim compatibili cu 5.5. Noi avem Percona pe server, iar eu dezvolt pe MariaDB, deci e de dorit să nu fim prea dependenți de un server sau de o versiune anume.

**Comment by danburzo** [comment]
Mie personal nu mi-a fost greu deloc, mi-am instalat doar versiunea nouă de MAMP, care vine cu MySQL 5.6. Dacă vrem să meargă pe 5.5 atunci da, ar trebui modificată cerința din DB. N-am reușit să obțin un "market share" al versiunilor de pe Google.
