### ISSUE TITLE
OpenID e cam... mort

### ISSUE THREAD

**Issue by CatalinFrancu** [dexonline/dexonline#569]
Susținerea pentru OpenID pare să se diminueze pe zi ce trece.

* Lista furnizorilor de OpenID, care se voia o pagină oficială, [nu mai există](http://openid.net/get-an-openid/).
* În general, o mulțime de furnizori au renunțat să mai furnizeze identități sau au dispărut cu totul (cam jumătate din [lista asta](http://openidexplained.com/get)).
* OpenID Connect se vrea a fi viitorul, dar nu știu dacă, în afară de Google, îl furnizează cineva. Noi acceptăm identități OpenID Connect, dar ocazional se mai plânge lumea că nu le merge.

Oare să revenim la un sistem de conturi normale, cu parolă? De când există managere de parole bune (Keepass / KeepassX etc.), cred că stresul unei parole în plus nu mai este o problemă.

Ar închide și #434. Ar influența (simplifica?) implementarea lui #567.

**Comment by CatalinFrancu** [comment]
Update: Nici [Wordpress](https://en.support.wordpress.com/settings/openid/) nu mai oferă OpenID.

**Comment by andreiepure** [comment]
Sunt confuz, [lista asta](http://openid.net/certification/) pare la zi. În plus, nu e mai simplu pentru utilizatori o integrare cu OAuth (dacă nu cu OpenId Connect)?
Cât despre managerele de parole, ar fi bun un sondaj pentru câți useri dexonline le folosesc.

**Comment by CatalinFrancu** [comment]
Sunt convins că nu e mort oficial. Dar pare că, practic, e greu să te mai loghezi cu un OpenID. [Pagina oficială](http://openid.net/) era pe vremuri orientată către utilizator, cu ghiduri pas cu pas despre cum să faci rost de un OpenID. Acum e plină de jargon de business. Dacă eu am N conturi pe diverse site-uri, nu este deloc clar care dintre ele pot fi folosite ca OpenID (și care este URL-ul).

Cred că OAuth nu ni se aplică nouă, greșesc? Înțeleg că este util pentru importarea datelor de pe alte site-uri.

Pentru OpenID Connect avem suport, testat doar pe Google. Într-adevăr, pare că mai sunt și [alți furnizori](https://connect2id.com/products/nimbus-oauth-openid-connect-sdk/openid-connect-providers) și ar merita să-i adăugăm. E un pic enervant că trebuie adăugate explicit butoane, dar măcar asta arată care din conturile mele pot fi folosite ca OpenID.

**Comment by slava-v** [comment]
Acum mai degraba folosești Google, Facebook sau Yahoo pentru logare la un website. Eu personal prin 2009-2010 am dat de OpenID. Atunci cind Google și Facebook deja aveau implementate o versiune de Open Identity Standard. Consider ca trebuie de urmat aceeași cale de suspendare a supportului pentru OpenID http://www.janrain.com/myopenid-service-ends/, îndata ce va fi implementată funcționalitatea de autentificare cu Google sau/și Facebook.

**Comment by revolter** [comment]
Si eu, personal, prefer Facebook, Google sau chiar Twitter sau GitHub.

**Comment by CatalinFrancu** [comment]
Pînă la urmă vom reveni la modelul clasic, cu nume de utilizator și parolă. Îmi cer scuze că am luat unilateral această decizie. OpenID Connect ne dădea ocazional bătăi de cap și ne cerea timp pe care nu-l prea avem.

Dincolo de aspectul tehnic, mai este și problema că OpenID Connect mi se pare o recunoaștere a eșecului lui OpenID. Google și Facebook au plecat în direcții complet diferite și fiecare are _walled garden_-ul său. Nu-i interesează cu adevărat interconectarea. Vor doar să graveze în mintea utilizatorilor „eu sînt Internetul și prin mine ajungi pe orice alt site.”
