### ISSUE TITLE
Pagină goală pentru definiție

### ISSUE THREAD

**Issue by danburzo** [dexonline/dexonline#570]
Salutare, pagina de aici apare goală: https://dexonline.ro/definitie/chei

**Comment by CatalinFrancu** [comment]
Mda, știm de problemă. Se întâmplă pe toate paginile cu imagini din dicționarul vizual. La bază e un bug tare straniu, doar pe unul dintre servere: PHP-ul nu vrea să rezolve _hostnames_ (ceea ce bușește o conexiune prin FTP de care avem nevoie). Am trecut direct adresa IP în fișierul de configurare, ca să-l repar provizoriu, și voi investiga separat cauza problemei.
