### ISSUE TITLE
Link-ul către cuvântul zilei anterior sare o zi

### ISSUE THREAD

**Issue by CatalinFrancu** [dexonline/dexonline#571]
Azi, 27 martie, pagina https://dexonline.ro/cuvantul-zilei/2017/03/27 are un bug: linkul pentru ziua anterioară duce de fapt către 25 martie. Bugul nu apare în alte pagini, unde linkul merge corect, din zi în zi. De asemenea, bugul nu apare de la URL-ul scurt https://dexonline.ro/cuvantul-zilei/

Nu sunt sigur dacă mâine problema se va translata la 28 martie -- presupun că da.

Se comportă la fel și pe beta, deci nu ține de Varnish.

**Comment by bftanase** [comment]
Salut,

Problema vine de la DST si se manifesta doar pt ziua de 27 martie. 

Aici
https://github.com/dexonline/dexonline/blob/85948a78cd22cc572f95ed59079b5b33754d9c4f/wwwbase/wotd.php#L95

Aveti

    SmartyWrap::assign('prevday', date('Y/m/d', $timestamp - ONE_DAY_IN_SECS));

Presupun ca timezone-ul default este setat pe Europe/Bucharest, ca pe UTC nu se manifesta. Atunci cand se face diferenta in secunde in codul de mai sus, datorita schimbarii de ora se sare peste o zi.

O varianta mai sigura ar fi calcularea folosind API-ul de DateTime:
ceva de genul

```
$date = new \DateTime('2017/03/27');
$previousDay = $date->modify('-1 day');
echo $previousDay->format('Y/m/d');
```

**Comment by CatalinFrancu** [comment]
Genial! Mulțumim pentru investigație. Confirm că aceeași problemă se întâmplă și la ora de iarnă ([30.10.2016](https://dexonline.ro/cuvantul-zilei/2016/10/30)), când legătura spre ziua următoare duce tot la 30.10.2016.
