### ISSUE TITLE
eroare la incarcare baza de date 

### ISSUE THREAD

**Issue by gelusi** [dexonline/dexonline#586]
Salut 

La incarcarea bazei de date (first time) apare o eroare noua: 
 zcat /tmp/dex-database.sql.gz | mysql -uroot -p DEX
si eroarea este 👍 

ERROR 1293 (HY000) at line 1841: Incorrect table definition; there can be only one TIMESTAMP column with CURRENT_TIMESTAMP in DEFAULT or ON UPDATE clause

multumesc

**Comment by CatalinFrancu** [comment]
@raduborza Linia 1841 pare să fie definiția tabelei `OrthographicReforms`, introdus în cf009a618217ca05278ca7e76f75afebb701d677:

```mysql
CREATE TABLE `OrthographicReforms` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `name` varchar(40) COLLATE utf8_romanian_ci NOT NULL,
  `year` smallint(6) DEFAULT NULL,
  `majorReformId` int(11) DEFAULT NULL COMMENT '# - minor, NULL - major',
  `description` varchar(255) COLLATE utf8_romanian_ci DEFAULT NULL,
  `createDate` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `modDate` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `name` (`name`)
)
```
Probabil este o incompatibilitate între MySQL și MariaDB / Percona (pe ultimele două merge bine).

**Comment by gelusi** [comment]
OK. Vreti sa modific eu sau modificati voi? 
Crezand ca totul e ok am inceput mutarea clonei de pe dex.cartiere.ro pe un server dedicat.

**Comment by LadislauStrifler** [comment]
Nu este chiar o incompatibilitate de distribuție, ci de versiune. Mi-a tușit și mie la MySQL 5.5 și am sărit la 5.7. Va funcționa dacă faci importul pe o versiune mai mare sau egală cu MySQL 5.6.5, versiune de la care începând s-a scos restricția de o singură coloană TIMESTAMP.

**Comment by raduborza** [comment]
Cum zice și Ladislau, nu este un bug. Trebuie update la mysql.
