### ISSUE TITLE
API-ul returneaza 301 pentru anumiti termeni

### ISSUE THREAD

**Issue by revolter** [dexonline/dexonline#597]
Nu stiu sigur daca s-a modificat ceva in legatura cu API-ul, dar in ultimul timp am inceput sa primesc mai multe erori.

Inainte, daca termenul cautat nu era gasit identic, raspunsul era totusi cel corect, banuiesc ca acum s-a vrut ca url-ul sa reflecte raspunsul trimis.

Ca exemplu, https://dexonline.ro/definitie/perseide/json redirecteaza catre https://dexonline.ro/definitie/perseid%C4%83, ceea ce are sens, dar:

1) as vrea sa stiu, de curiozitate, daca acest comportament era si inainte
2) ar trebui sa redirecteze catre https://dexonline.ro/definitie/perseid%C4%83/json, si https://dexonline.ro/definitie/perseide catre https://dexonline.ro/definitie/perseid%C4%83

**Comment by CatalinFrancu** [comment]
Mulțumesc pentru semnalare, am reparat problema. Într-adevăr, la redirectare uitam să adăugăm și formatul printre parametri.

Sigur comportamentul exista și înainte, căci vrem URL-uri canonice. De exemplu, este util ca [elevului](https://dexonline.ro/definitie/elevului) să redirecteze la [elev](https://dexonline.ro/definitie/elev). O singură clasă de redirectări este nouă: nu este bine ca [ochiului](https://dexonline.ro/definitie/ochiului) să redirecteze la [ochi](https://dexonline.ro/definitie/ochi), căci există „ochiul” ca substantiv și „a ochi” ca verb, or utilizatorul, prin căutarea [ochiului], a indicat că se referă inechivoc la substantiv. În astfel de situații redirectăm explicit la intrarea pentru substantiv: https://dexonline.ro/intrare/ochi/38563.

Toate aceste lucruri merg acum consecvent în HTML, JSON și XML.
