### ISSUE TITLE
Omogenizarea și portabilizarea în aplicație a parametrului pentru spațiul alocat fișierelor temporare

### ISSUE THREAD

**Issue by LadislauStrifler** [dexonline/dexonline#603]
Se poate face în mai multe feluri.
1. mers pe un Core::getTempDir(), unde s-ar mai putea altera calea (la nevoie).
2. sau pe varianta sys_get_temp_dir(), dar ce ne facem dacă aplicația nu poate scrie aici?
Votez prima variantă, ca să putem testa dacă is_writable.

**Comment by CatalinFrancu** [comment]
Păi și dacă nu is_writable, unde scriem? :-) Cred că trebuie să ne punem încrederea că sistemul de operare returnează ceva rezonabil la `sys_get_temp_dir()`. @raduborza , tu ce zici?

**Comment by raduborza** [comment]
In tmp we trust!

**Comment by LadislauStrifler** [comment]
Vă convine o funcție ca aceasta sau e  nejustificată abordarea?
`  static function getTempDir() {
    if ( defined('DEX_TEMP_DIR') ) {
       return DEX_TEMP_DIR;
    }

    if ( function_exists('sys_get_temp_dir') ) {
        $temp = sys_get_temp_dir();
        if ( is_dir( $temp ) && is_writable( $temp ) ) {
          return $temp;
        }
    }      

    $temp = self::getRootPath().'tmp';
    $success = mkdir($temp);
    if ( $success && is_dir( $temp ) && is_writable( $temp ) ) {
      return $temp;
    }
    
    $temp = Config::get('global.tempDir');
    if ( is_dir( $temp ) && is_writable( $temp ) ) {
      return $temp;
    }
        
    return DIRECTORY_SEPARATOR.'tmp';      
  }`

**Comment by CatalinFrancu** [comment]
Ce să zic, pare overkill („supraucidere”, ca să zic așa). Și chiar nu e sănătos să existe cinci mecanisme pentru a controla același comportament. Înțeleg că poate ocazional nu vrei să fie /tmp, deci variabila din `dex.conf`, cu valoarea implicită sis_get_temp_dir() (în caz că instalatorul insistă să șteargă linia din `dex.conf`).

```php
return Config::get('global.tempDir', sys_get_temp_dir());
```

Iar `sys_get_temp_dir` e definită în PHP 5.2.1 aparent, adică de [peste zece ani](http://php.net/releases/), deci hai să presupunem că există fără să mai testăm. :-)

**Comment by LadislauStrifler** [comment]
Trebuie să existe un plan de rezervă (fallback) în situația când în directorul întors de funcția `sys_get_temp_dir()` nu se poate scrie. Nu zic să fie 5 mecanisme; 2-3 ajung, dar să nu fie hardcodat este cel mai important.

**Comment by CatalinFrancu** [comment]
Păi rămâne cum am propus eu? M-aș mira ca `sys_get_temp_dir()` să returneze ceva read-only, dar ai dreptate, sunt și alte motive pentru posibilitatea de a configura directorul.

**Comment by LadislauStrifler** [comment]
La mine așa a fost. Nu aveam acces în C:\WINDOWS\TEMP-ul întors de `sys_get_temp_dir(),` crede-mă!

**Comment by CatalinFrancu** [comment]
A, wow. Din misterele Windows-ului. :-) Bun, atunci facem și test de `is_dir($temp) && is_writable($temp)`, iar dacă eșuează, tipărim un avertisment, să le scutim timp altora, nu?
