### ISSUE TITLE
La ștergerea unui sens, trimiterile către acel sens sunt șterse tacit

### ISSUE THREAD

**Issue by CatalinFrancu** [dexonline/dexonline#607]
Mai util ar fi un avertisment, linkuri către sensurile care trimit la cel șters etc.

**Comment by MateiGall** [comment]
Sau măcar blocarea ștergerii până nu se înlocuiesc (elimină) respectivele trimiteri...
Sunt destul de frecvente situațiile, pentru că avem sensuri duble, generate de micile diferențe între edițiile DEX structurate automat. Trimiterea e de regulă către primul sens găsit, iar acesta (fiind din DEX'98) este înlocuit ulterior cu sensul formulat în DEX'09.

**Comment by CatalinFrancu** [comment]
Am înțeles - o pun prima pe listă (dar abia luni, cred).

**Comment by CatalinFrancu** [comment]
Am optat pentru următoarea soluție: butonul pentru ștergerea sensului este dezactivat dacă există mențiuni despre acest sens. Tabelul de mențiuni include acum și butoane pentru ștergerea mențiunilor respective.
