### ISSUE TITLE
Problema la parsarea unui XML

### ISSUE THREAD

**Issue by tavy14t** [dexonline/dexonline#615]
Am dat peste un cuvant pentru care response-ul dat de server apare eronat (Opening and ending tag mismatch). Pe formatul JSON e in regula, doar la XML apare problema, una de parsare: https://dexonline.ro/definitie/fir/xml

**Comment by LadislauStrifler** [comment]
Era defectă definiția. Am modificat-o. Avea o imbricare de etichete - $@$@ chiar la final. Propusesem eu la un moment dat o avertizare pentru moderator la suprapunerea unor etichete de formatare, lipsa unor închideri sau deschideri de paranteză/ghilimele. Se pare că ar trebui făcut un utilitar și periată toată baza de date.

**Comment by LadislauStrifler** [comment]
Cine închide ușa?

**Comment by CatalinFrancu** [comment]
Sistemul dă acum un avertisment pentru formatări imbricate incorect. Nu spune și poziția, asta ar fi și mai util, dar e util și așa. Cred că îl putem închide pe acesta.
