### ISSUE TITLE
Decuplarea de LOC

### ISSUE THREAD

**Issue by raduborza** [dexonline/dexonline#623]
În acest moment sistemul de declinări este strîns legat de LOC. Avînd în vedere că criteriile adoptate de LOC sînt mult mai laxe (permițînd inclusiv flexiuni inexistente în surse oficiale), este necesară o decuplare a flexiunilor noastre de cele LOC.

În primă fază trebuie să descoperim care este modul optim pentru realizarea acestei decuplări și modul în care putem importa (cherry pick) modificările făcute pentru LOC.

**Comment by CatalinFrancu** [comment]
[analiză și proiectare] e totuna cu [brainstorming]? :-)

Eu propusesem ca valoarea booleană `Lexem.isLoc` să primească 3 valori care să arate pe cine interesează lexemul: (1) doar dexonline, (2), doar LOC, (3) ambele. Pentru migrare, valorile cu `isLoc = false` ar deveni (1) doar dexonline, iar cele cu `isLoc = true` ar deveni (3) ambele. În timp cele din categoria (3) ar putea intra în (2) dacă decidem că pentru dexonline nu sunt de interes. Care ar fi acelea? Cred că Matei ne poate spune cel mai bine dacă a creat lexeme pentru LOC care nu sunt susținute de niciun dicționar.

Pe lângă `Lexem.isLoc` mai există și `ModelDescription.isLoc`, care interzice în întregime o formă flexionară (vocativul etc.). Pe acela cred că îl putem păstra ca atare.

La căutările publice (pentru utilizatori), mai trebuie adăugat filtrul după valorile 1 și 3. La căutările de administrator probabil nu trebuie filtrat (e.g. în casetele de navigare rapidă).

**Comment by MateiGall** [comment]
Lexeme „pure” (cuvinte noi) nu cred să fi creat. Dar mai știi? :-)
În schimb au fost create flexiuni fără susținere în dicționare, fie pentru că la momentul respectiv nu aveam informații, fie pentru că unele forme flexionare lipseau în mod „ilogic” (de regulă plurale) ... plus alte decizii ale FRSc.
Un exemplu este chiar **scrabble** - _scrabblul_ :-)

**Comment by MateiGall** [comment]
Nu poate fi șters, pentru că e în LOC (FRSc a stabilit, de fapt, flexiunea; sursa DOR trebuie eliminată, a fost pusă la structurarea automată).

Dacă se implementează stările (1), (2) etc., sigur că-l putem trece „doar LOC”. Varianta T1 nu e necesară, avem omonimul cu N24-- (cf. DOOM), la care eventual eliminăm pluralul (pe care dicționarele nu îl dau, dar care mie mi se pare firesc pentru sensul 2 din DEX.

**Comment by MateiGall** [comment]
Pentru lexemele T1 peste care trecem am putea adăuga un model I99 și o etichetă [flexiune necunoscută], ca să le putem depista mai ușor la nevoie (și să nu rămână amestecate cu miile de T1 pe care nu le-am parcurs).

**Comment by MateiGall** [comment]
Păi n-ajungem tot acolo?
Ar însemna să adăugăm sursa LOC_XX pe toate lexemele bifate și să eliminăm la afișare lexemele care au doar acestă sursă (și deocamdată sunt multe care n-au vreo sursă).
Eu nu văd care-i diferența în final, dar ... nu mă opun, dacă așa e mai simplu...

**Comment by CatalinFrancu** [comment]
Și mie mi se pare complicat cu sursa nouă. Sursa este pentru definiții. Ea poate fi aplicată pe lexeme, dar apoi interogările devin greoaie, inclusiv cele publice (marea masă a căutărilor).

**Comment by raduborza** [comment]
Sursa este de fapt o colecție de cuvinte asociate cu o flexiune și o glosă care poate fi nulă. Cu ce ar diferi LOC de DOR sau DOOM, de exemplu?

Mie îmi pare mai complicat procesul prezentat mai sus (nu mai zic de partea de upgrade a unei versiuni de LOC). În plus, probabil că modificarea ne va folosi să ne gîndim și cum să filtrăm flexiunile!

**Comment by MateiGall** [comment]
Nu văd ce legătură au versiunile LOC (decât în varianta cu eticheta propusă de Radu). Altfel, LOC e în permanentă modificare (versiunea în lucru), iar atunci când FRSc stabilește să o „înghețe” .... cred că operațiile pe care Cătălin le-a făcut și la versiunile anterioare vor fi asemănătoare, aplicându-se doar lexemelor cu starea „doar LOC” și „LOC și dexonline”.
Avem deja două stări: (1) „doar dexonline” (ce actualmente nu are bifa LOC) și (2) „LOC și dexonline” (cele cu bifă). Bănuiesc că cel ami simplu e să creăm o nouă stare (3) „doar LOC”, în care să mutăm încet-încet tot ce nu vrem să apară în dexonline.
Mai trebuie adăugată o preferință a utilizatorilor care vor să vadă (2) și (3).

Nu mi-e clar cum se vor stabili drepturile diferitelor categorii de voluntari...

**Comment by LadislauStrifler** [comment]
Eu văd o incongruență la (2) „LOC și dexonline” privitor la aspectul legat de acele forme atipice pentru care nu dorim să creăm o nouă flexiune. Ar fi o idee să fie „LOC”-uite formele flexionare. Astfel, pe modelul **scrabblul**, FRSc va putea introduce și **vaporile** sau orice altă formă atipică asociată paradigmei standard.

**Comment by MateiGall** [comment]
Dacă mergem pe ideea de a crea un lexem (și un model de flexiune) separat pentru aceste forme atipice, nu e nicio problemă. Lexemul va fi (1) dacă FRSc nu-l acceptă, (3) dacă dexonline nu-l vrea și (2) dace e ok pentru toată lumea. **Scrabblul** (scrabble - N76.1) ar fi (3), **vaporile** (NL1 sau ce vom stabili) ar fi (1) etc.

**Comment by CatalinFrancu** [comment]
Am avut o discuție mai lungă pe e-mail (subiect _LOC - separare_, începută pe 12.10.2018) și am ajuns la concluzia:

> Arhivarea tuturor versiunilor, cu păstrarea bazelor de date dacă FRSc le vrea. Înghețarea și arhivarea versiunii live („6.0”), ca să avem și modificările de la 5.0 încoace. Ștergerea completă a tot ce ține de LOC din dexonline, cu păstrarea strict a listelor de forme reduse (echivalentul unui fișier text chior cu un cuvînt pe linie), ca să continue să funcționeze pagina de interogare Scrabble.

Nu știu cum să abordăm cerința inițială a lui Radu: „modul în care putem importa (cherry pick) modificările făcute pentru LOC.”. Ar fi grozav să le putem face undo dacă nu sînt de interes pentru dexonline.
