### ISSUE TITLE
Scanează alte pagini lipsă din MDA2

### ISSUE THREAD

**Issue by CatalinFrancu** [dexonline/dexonline#625]
* volumul 1, paginile 276 și 277 (eventual de inserat în C.pdf între paginile 5 și 6);
* volumul 2, paginile 72 și 73 (eventual de inserat în M2.pdf între paginile 71 și 72);
* volumul 2, paginile 88 și 89 (eventual de inserat în M2.pdf între paginile 85 și 86);
* volumul 2, paginile 388 și 389 (eventual de inserat în P.pdf între paginile 145 și 146).

Adaugă primul cuvânt de pe fiecare pagină în tabela PageIndex (pentru vol. 1 am rezolvat eu).

**Comment by raduborza** [comment]
Paginile lipsă ar trebui puse în cloud, la sursele respective!

**Comment by CatalinFrancu** [comment]
Da, te asignez pe tine când le am, că tu ai drepturi.

**Comment by raduborza** [comment]
Cătălin, nu prea înțeleg ce înseamnă C 5-> 275, 6 -> 278...

Cred că paginile lipsă sînt unic determinate de volum și pagina din volum (eventual, litera, ca informație suplimentară).

**Comment by CatalinFrancu** [comment]
Da, mi-am notat în stilul meu confuz. :-) Refac acum descrierea.

**Comment by LadislauStrifler** [comment]
Le scanez eu.

**Comment by CatalinFrancu** [comment]
Nu le scana, le avem deja pe toate.
