### ISSUE TITLE
Etichete la definiții în editEntry.php

### ISSUE THREAD

**Issue by LadislauStrifler** [dexonline/dexonline#628]
Ar fi util ca și la vizualizarea intrării/arborelui definițiile asociate să afișeze etichetele, în special cele de **modificat**.
Chiar și șablonul pentru **comentariu** ar fi frumos să se aplice.

**Comment by CatalinFrancu** [comment]
Da, e nevoie, îmi spunea și Matei. Mersi că ai deschis tichet!
