### ISSUE TITLE
Elimină trimiterile nenecesare (cele de tipul |cuvânt|definiție|).

### ISSUE THREAD

**Issue by CatalinFrancu** [dexonline/dexonline#632]
Multe dintre trimiterile de tipul `|cuvânt|definiție|` sunt nenecesare, căci `cuvânt` este o formă flexionară a lui `definiție` (cu sau fără diacritice), iar un clic pe el ar duce oricum la definiție.

- [x] Găsește-le și elimină-le din definiții.
- [x] Generează un raport cu trimiterile din definiții care nu corespund acestui criteriu.
- [x] Fă sistemul să dea un avertisment, la salvarea unei definiții, pentru trimiterile care sunt nenecesare.
- [x] Găsește-le și elimină-le din sensuri.
- [x] Generează un raport cu trimiterile din sensuri care nu corespund acestui criteriu.
- [x] Fă sistemul să dea un avertisment, la salvarea unei arbore, pentru trimiterile care sunt nenecesare.
- [x] Script interactiv pentru corectarea din linia de comandă.
- [x] Rulează totul în producție.

**Comment by CatalinFrancu** [comment]
Am rulat patch-ul în producție, am corectat manual câteva și am încărcat un gist cu cele rămase

[Trimiteri rămase](https://gist.github.com/CatalinFrancu/2b5ea85524a1c0cc5b6184608520198e)

@cezarelnazli, dacă mai ai chef să continui, mi-aș dori următoarele:

* Să copiezi patch-ul într-un script în `tools/`, ca să-l putem rula repetat.
* Să-l faci interactiv (din linia de comandă). Pentru fiecare trimitere pe care nu știe să o rezolve, să ofere opțiunile 1 (sau S sau altcumva) pentru ștergere și 2 (sau E sau altcumva) pentru specificarea unui înlocuitor manual. Și sigur, 3 sau I pentru ignorare (lasă nemodificat și treci mai departe).
* Să-l faci să meargă similar și pentru sensuri (tabela Meaning). Acolo linkul de editare pentru un sens `$m` este `https://dexonline.ro/editTree.php?id={$m->treeId}`.

Din gistul de mai sus văd multe pe care le-aș repara  (majoritatea), dar procedura curentă e lentă (click pe link + navigare la bară + corectare).

**Comment by cezarelnazli** [comment]
Voi continua, dar spre sfârșitul săptămânii.

**Comment by CatalinFrancu** [comment]
Un succes răsunător. :-) Au mai rămas 68 de definiții și 31 de sensuri cu trimiteri care chiar își au rostul, din totalul inițial de peste 1.200! Mulțumim, @cezarelnazli.
