### ISSUE TITLE
Probleme la crearea intrării

### ISSUE THREAD

**Issue by MateiGall** [dexonline/dexonline#633]
Când se creează o intrare nouă din pagina de editare a definiției:
- sistemul nu acceptă un ominim, trebuie o diferențiere (de regulă o paranteză cu o mențiune); această diferențiere n-ar trebui să fie preluată și în forma noului lexem creat (ci eventual în descriere).
- această intrare ar trebui să aibă automat și un arbore asociat (procedura e folosită de regulă în cazul unor sensuri diferite).

**Comment by CatalinFrancu** [comment]
Aha, ok. Ca avertisment, ocazional mai șterg toți arborii goi (fără sensuri, relații, mențiuni). Deci odată arborele creat, ar fi bine să-i și dai ceva dintre datele acestea.
