### ISSUE TITLE
Actualizare afișare informații

### ISSUE THREAD

**Issue by MateiGall** [dexonline/dexonline#638]
Ar trebui eliminată menționarea părții de vorbire de pe paradigmă (acum avem etichete vizibile, mai detaliate).
Tipul de model ar putea să rămână, pentru linkul către editare, dar vizibil doar în pagina de editare a lexemului (informația e criptică pentru utilizatorii obișnuiți).

**Comment by CatalinFrancu** [comment]
Mulțumim, @LadislauStrifler! Iată un exemplu din producție: [vădană](https://dexonline.ro/definitie/v%C4%83dan%C4%83). Nu e ideal că celula din stânga-sus rămâne fie goală, fie (când există surse) începe cu o linie goală. Pe de altă parte, avem (de mult) deschis #125 pentru îmbunătățirea afișării prezentărilor, deci n-aș investi prea mult timp pentru această reparație în particular.

**Comment by CatalinFrancu** [comment]
Moderatorii au deja cutia de selecție pentru modele din pagina moderatorului (caseta „modele de flexiune”). Este suficient, sau preferi să fie și un link direct din pagina lexemului?

**Comment by MateiGall** [comment]
Cred că e suficient. Editarea unui model nu mai e ceva uzual...
În celula din stânga-sus se poate muta eticheta (ca să nu rămână goală).

**Comment by MateiGall** [comment]
Tot la acest topic aș mai adăuga și afișarea etichetelor de pe intrări și arbori (acestea din urmă inclusiv pe pagina intrării).
