### ISSUE TITLE
Unele valori din Definition.createDate au fost suprascrise

### ISSUE THREAD

**Issue by CatalinFrancu** [dexonline/dexonline#643]
Cauzat de `00238.php` (și de o ciudățenie din Idiorm). Voi recupera valorile dintr-o copie mai veche a bazei de date și voi documenta aici procedura.

**Comment by CatalinFrancu** [comment]
În producție, găsesc definițiile afectate cunoscând ora rulării scriptului

```
mysql> select unix_timestamp('2017-11-14 08:00:00');
+---------------------------------------+
| unix_timestamp('2017-11-14 08:00:00') |
+---------------------------------------+
|                            1510639200 |
+---------------------------------------+
1 row in set (0.00 sec)

mysql> select unix_timestamp('2017-11-14 18:00:00');
+---------------------------------------+
| unix_timestamp('2017-11-14 18:00:00') |
+---------------------------------------+
|                            1510675200 |
+---------------------------------------+
1 row in set (0.00 sec)

mysql> select id from Definition where createDate between 1510639200 and 1510675200 and id < 1000000 order by id into outfile '/tmp/bad-ids.txt';
Query OK, 579 rows affected (0.01 sec)

mysql> Bye
dex@buddy:/var/www/DEX$ wc /tmp/bad-ids.txt 
 579  579 3905 /tmp/bad-ids.txt
```
Copiez fișierul rezultat pe calculatorul cu copia veche a bazei de date.

Aici extrag valorile corecte pentru `createDate` și mă asigur că numărul de linii este același (deci toate ID-urile există în această bază de date).

```bash
cata@voronet:~$ cat /tmp/bad-ids.txt | while read id; do mysql -u root DEX2 -e 'select id, createDate from Definition where id = '$id -s -N; done > /tmp/id-createDate.txt
cata@voronet:~$ wc /tmp/id-createDate.txt 
  579  1158 10274 /tmp/id-createDate.txt
```

Generezi enunțuri SQL pentru actualizarea câmpului `createDate`.

```bash
cata@voronet:~$ cat /tmp/id-createDate.txt | while read id cd; do echo update Definition set createDate = $cd where id = $id';'; done > /tmp/fixCreateDate.sql
cata@voronet:~$ head -n 3 /tmp/fixCreateDate.sql 
update Definition set createDate = 1048233600 where id = 5093;
update Definition set createDate = 1046678400 where id = 7934;
update Definition set createDate = 1046678400 where id = 8202;
```

Copiez fișierul .sql în producție.

În producție, execut fișierul.

```bash
$ cat /tmp/fixCreateDate.sql | mysql -u root DEX
```

**Comment by LadislauStrifler** [comment]
OK, dar ce a făcut să fie suprascrise ai aflat? Acea „ciudățenie” din idiorm m-ar interesa.

**Comment by cezarelnazli** [comment]
Actualiza cumva automat și câmpul ăla când se salva definiția nouă?

**Comment by CatalinFrancu** [comment]
În `phplib/models/BaseObject.php`, funcția `save()` pune valoarea curentă pentru câmpurile `modDate` și `createDate` dacă nu există deja. Iar câmpul `createDate` nu există atunci când obiectul este obținut prin încărcarea selectivă doar a anumitor câmpuri, în cazul nostru:

```php
$definitions = Model::factory('Definition')
->select('id')
->select('internalRep')
->select('htmlRep')
->select('sourceId')
->where(...)
->where(...)
->find_many();
```

De ținut minte: când încărcăm obiecte pe care urmează să le salvăm la loc, e mai prudent să le încărcăm complet (fără apeluri la `select()`).

**Comment by LadislauStrifler** [comment]
Și bănuiesc că e valabil doar pentru câmpul de tip dată, că altfel ar fi haos. :)

**Comment by CatalinFrancu** [comment]
Aproape sigur doar câmpul `createDate` este problematic pentru că doar pe acela îl modificăm explicit în `BaseObject`. În rest, presupun că Idiorm știe să nu se atingă de câmpurile care lipsesc complet din obiect.
