### ISSUE TITLE
Replicare sursă la exemple (în editare arbore)

### ISSUE THREAD

**Issue by MateiGall** [dexonline/dexonline#645]
La adăugarea unui exemplu, odată cu preluarea tipului de la cel precedent, să se preia și sursa.
De regulă se prelucrează aceeași sursă (DLRLC) și s-ar economisi câte un clic (alegerea altei surse e mai puțin frecventă).

**Comment by MateiGall** [comment]
Nu e tocmai bine. Procedura trebuie să funcționeze doar la adăugarea unui exemplu **după** unul precedent (să nu preia și sursele de la sens, care pot fi multiple).
La primul exemplu din sens sursa se va seta manual.

**Comment by CatalinFrancu** [comment]
A, acum am înțeles. Ok, așa am procedat. Sursele se copiază și la subexemple, dacă vreodată ai nevoie de așa ceva. :-)
