### ISSUE TITLE
Setare nume structurist (în editare intrare)

### ISSUE THREAD

**Issue by MateiGall** [dexonline/dexonline#646]
La salvarea intrării să se aplice automat numele celui care structurează, dacă valoarea este „niciunul” (similar cu ce s-a implementat doar pentru „în lucru”). Se evită manevrele de selectare a numelui, iar procesul nu e obligatoriu să treacă prin „în lucru”...
Eventual să se adauge o bifă „automat” la structurist (valoare ce se va păstra la închiderea sesiunii).

**Comment by CatalinFrancu** [comment]
În unele situații este o idee bună, dar nu întotdeauna. Dacă modifici doar o greșeală de tipar sau adaugi o paranteză la descriere, poate nu vrei să preiei toate atribuțiile structuristului. Ar trebui detaliate condițiile când să se întâmple asta, și s-ar putea să fie complexe. De exemplu: dacă din pagina intrării mă duc în pagina arborelui și încep să adaug sau să organizez sensuri, este clar că mi-am însușit intrarea. Dar acest comportament este complex și mai greu de urmărit.

**Comment by MateiGall** [comment]
Tocmai de aceea am specificat că atribuirea automată trebuie să se facă:
- (1) doar dacă există bifa „automat” (ca să poți inactiva temporar opțiunea dacă nu vrei să preiei intrarea)
și
- (2) dacă intrarea nu a fost rezervată de alt structurist (ca să poți face modificări fără a schimba numele).

Oricum, până nu vor opera mai mulți structuriști și nu vor apărea situații mai complexe ... pe mine m-ar ajuta.

**Comment by CatalinFrancu** [comment]
Am implementat un „mod” (denumirea proprie pentru preferințe care pot fi activate / dezactivate cu o combinație de taste). Poți activa modul structurist cu Alt-T. Dacă nu ții minte, meniul Utilizator -> Hotkeys enumeră toate combinațiile, și pe câteva dintre ele poți da și clic.

**Comment by MateiGall** [comment]
Acest mod nu ar trebui să împiedice „eliminarea” numelui dacă așa dorește structuristul; ar trebui să permită selectarea manuală a opțiunii „niciunul”, măcar pentru starea „neîncepută”.
[Știu că se poate face trecând temporar prin modul „anonim”, dar e un pic cam anapoda]

**Comment by CatalinFrancu** [comment]
Am adăugat opțiunea să poți șterge structuristul, dacă există deja. Totuși, soluția nu e perfectă: la următoarea salvare te pune înapoi. :-) Intenția mea originală era exact să ieși din modul structurist, să salvezi intrarea, apoi să reintri. Modul structurist (Alt-T) e ca o bifă, dar nu ocupă loc în interfață.

**Comment by MateiGall** [comment]
Ok, poate rămâne și cu alternarea modului (Alt+T), e destul de simplu.

Eu am multe situații când, structurând o intrare, găsesc ceva de modificat
/ adăugat la altă intrare, dar nu stau să o finalizez pe aceasta din urmă.
Și nu vreau să mi se adauge în coada de intrări „în lucru”...


*Matei GALL*
* <http://dexonline.ro>*
*http://dexonline.ro <http://dexonline.ro>*

2017-12-04 12:55 GMT+02:00 Cătălin Frâncu <notifications@github.com>:
