### ISSUE TITLE
Organizarea nomenclaturii binare

### ISSUE THREAD

**Issue by CatalinFrancu** [dexonline/dexonline#647]
Nomenclatura binară (denumirile științifice ale animalelor și plantelor, de ex. _Mentha piperita_) este în prezent vraiște. Dorim să organizăm informația într-un fel anume, exemplificat la [splină](https://dexonline.ro/definitie/splin%C4%83):

* Fiecare nume de specie primește un arbore și o intrare separată (în cazul în care numele popular este obținut prin compunerea unor cuvinte cu alte sensuri, cum ar fi _mătasea-broaștei_).
* Fiecare nume de specie primește un lexem compus format din termenii generic și specific.
* Intrarea este asociată numai cu lexemul compus _(Mentha piperita_, nu și _Mentha_ sau _piperita_).
* Genurile (primul termen când denumirea are 2+ termeni) se scriu cu majusculă.
* Lexemele compuse și fragmentele componente sunt etichetate cu o etichetă (momentan [biologie], vom stabili ulterior numele).

Lexemele existente sunt în general etichetate cu modelul I2 (`/admin/viewLexemsByModel.php?modelType=I&modelNumber=2`).

De văzut:

* Cum depistăm sensurile deja create (la parsarea DEX '98 / DEX '09) pentru a le extrage.

De făcut concret:

- [x] Modifică definițiile din DFL, înlocuind abrevierea genului cu numele complet, de exemplu **A. griseum** cu **Acer griseum.** Astfel, lexiconul va fi extras complet, iar la consultarea originalului se va deschide pagina corectă.
- [x] Confruntă numele de specii cu [The Plant List](http://www.theplantlist.org/), corectează ce trebuie.
- [x] Creează intrări și lexeme pentru genuri, cu literă mare și cu modelul corect.
- [x] Creează intrări și lexeme compuse pentru specii.
- [x] Șterge intrările care rămân asociate doar cu lexeme nume de specii (tip I, număr 2.2).

**Comment by MateiGall** [comment]
N-ar fi bine să punem pe lexemul compus latinesc și o etichetă [**biologie**] sau ceva similar? Vezi [https://dexonline.ro/admin/lexemEdit.php?lexemId=281498](url)
Lexemele componente (_chrysosplenium_, _alternifolium_) se păstrează, sau dispar?
Ce facem cu denumirile familiilor gen _Saxifragaceae_?

**Comment by CatalinFrancu** [comment]
Ba da, ar fi util! Chiar mă gândeam că la compunere se pierde numărul de model (I2). Oare să punem chiar \[nomenclatura binară\]? Acesta este [termenul potrivit](https://ro.wikipedia.org/wiki/Nomenclatur%C4%83_binar%C4%83), dar sună lung și pompos.

Lexemele componente trebuie păstrate, altfel nu avem cum să le obținem pe cele componente. Pot rămâne I2 și purta aceeași etichetă, cred.

Dacă te referi la _saxifragacee_ (ca și _pinacee, salmonide_ etc.), acelea sunt cuvinte românești, nu ar trebui să influențeze procesul de mai sus.

**Comment by MateiGall** [comment]
Mă refeream exact la denumirea latină a familiei, așa cum figurează în DFL (la Chrysosplenium).
Tot acolo apare și CRISOSPLENIUM, plus un L care nu știu ce reprezintă...

**Comment by CatalinFrancu** [comment]
A, ok. N-aș merge la familii sau mai sus, totuși nu suntem atlas.

L-ul e posibil să fie abreviere, dar mi-e lene să caut în original. :-)

N-aș prelua formele vechi sau greșelile de sintaxă. Într-o lume ideală chiar aș căuta pe Google toate speciile pentru confirmare, am mai văzut greșeli sistematice de-a lungul anilor.

**Comment by LadislauStrifler** [comment]
L. mai mult ca sigur este Linnaeus.

**Comment by CatalinFrancu** [comment]
Cred că ar fi o idee bună să trecem prin DFL întâi, căci acolo numele de specii sunt mai ușor de dedus. Pot scrie un program care să creeze automat intrări și lexeme compuse, să pună modelul I2 pe lexemele simple, să pună majusculă la gen etc. Apoi putem uni aceste intrări cu cele pentru denumirea comună a plantei (dacă există).

**Comment by CatalinFrancu** [comment]
Am făcut cam tot ce puteam face cu DFL. Restul mențiunilor (inclusiv speciile de animale, de care nu m-am atins) apar prin alte dicționare mai greu de parsat automat. Vor trebui organizate după aceleași principii la momentul structurării.
