### ISSUE TITLE
Lexeme care pot fi și principale și variante

### ISSUE THREAD

**Issue by CatalinFrancu** [dexonline/dexonline#649]
Unele lexeme pot fi formă principală în anumite intrări, dar variantă în altele. În prezent, nu putem reprezenta această situația, întrucât proprietatea este stocată în câmpul boolean `Lexem.main`, ceea ce înseamnă că lexemul este ori formă principală peste tot, ori variantă peste tot.

De văzut ce putem face.

**Comment by CatalinFrancu** [comment]
O idee: două câmpuri în formularul de editare a intrării - unul pentru forme principale, unul pentru variante. Evident, `Lexem.main` dispare. Rămâne întrebarea unde stocăm informația. Teoretic, pe LexemEntry.

**Comment by MateiGall** [comment]
O să încerc să adaug aici exemple, pe măsură ce mai întâlnesc.

1. Verdaică (variantă pentru verdoaică în multe surse, principal în Sinonime).

**Comment by CatalinFrancu** [comment]
Nu știu dacă am discutat asta pe e-mail: nu putem pur și simplu clona lexemele? Ai întâlnit multe astfel de situații până acum?

**Comment by MateiGall** [comment]
Da, sunt multe cazuri. N-am mai adăugat exemple...
Probabil se poate face o căutare a lexemelor asociate cu mai multe intrări și o inspectare a cazurilor care se încadrează aici...
Sigur că putem clona lexemele, dacă nu vă deranjează redundanța. Ar mai fi și de stabilit o notație unitară a acestor cazuri (o descriere, ca să putem asocia corect intrările).

**Comment by CatalinFrancu** [comment]
Aha, mulțumesc. Speram să scăpăm ușor. :-)

**Comment by CatalinFrancu** [comment]
Pare că cea mai naturală soluție este cea menționată mai sus: câmpuri separate pentru formele principale și variante (și migrarea informației din bifa de acum în noul format).

Va afecta tabela de asociere `EntryLexem`, care acum va avea informație în plus (tipul de asociere). Voi implementa o soluție generală, căci avem multe tipuri de asocieri și pe viitor toate pot căpăta informații în plus.

**Comment by CatalinFrancu** [comment]
Am rezolvat eu cazul _verdaică_, pentru testare.

**Comment by MateiGall** [comment]
E ok, dar am o sugestie de optimizare a editării. Să se păstreze casuța cu bifa „principal”, iar la unificarea intrărilor, variantele să fie adăugate automat pe câmpul corespunzător. Acum, după unificare, sunt necesare 3 operații: ștergerea lexemului, adăugarea lui la variante, salvare.

**Comment by CatalinFrancu** [comment]
Comportamentul actual este:

* Lexemele au fost mutate în lista de forme principale / variante după cum aveau / nu aveau bifa pusă.
* La unificare, formele principale se duc în lista de forme principale a intrării-destinație, iar variantele la variante.

Dacă observi altceva, să-mi spui, că trebuie reparat! Altfel, nu prea înțeleg la ce ar ajuta păstrarea bifei. Și pe ce ar sta bifa, tot pe lexem? Exact asta urmăream să reparăm, faptul că același lexem poate fi și formă principală, și variantă, deci bifa pe lexem este insuficientă.

**Comment by MateiGall** [comment]
Ce ai făcut cu eliminarea bifei și repartizarea variantelor în alt câmp e ok.
Cum procedăm în continuare? Un lexem fără bifă (cum sunt toate acum) e considerat **principal** și când unific intrarea lui cu alta, în care trebuie să devină **variantă**, este adăugat la prima categorie și trebuie să țin minte să-l șterg apoi și să-l mut în cealaltă.
Înțeleg că ar trebui să urmez o procedură diferită: să mut întâi lexemul în câmpul de variantă și abia apoi să fac unificarea. Cam la fel de incomod...
Ai dreptate, bifa nu ajută ... și nici nu văd altă soluție mai comodă... Cred că putem lăsa așa, închizând tichetul.

**Comment by CatalinFrancu** [comment]
Mai am o idee care ar economisi multe clicuri: între cele două câmpuri, două butoane ▲ și ▼ care să mute **toate** lexemele la principale, respectiv la variante. Apoi mai trebuie să salvezi pagina, apoi poți face unificarea.

Ideal ar fi ca săgețile să existe pe fiecare lexem în parte, dar ar încărca prea mult interfața.

**Comment by MateiGall** [comment]
Da, minunat!
Ar mai fi de menționat că procedura de eliminare a bifei nu a rezolvat cazurile deja structurate. Un lexem care era principal într-o intrare și variantă în alta, a rămas principal în ambele...

**Comment by CatalinFrancu** [comment]
Păi situația aceea este inerent ambiguă, tocmai din cauza insuficienței vechii reprezentări. Am cum să depistez cazurile unde doreai ca lexemul să fie și principal, și variantă? Fără să le includ și pe cele unde lexemul pur și simplu este principal în ambele intrări?

Redeschid tichetul pentru  implementarea butoanelor ▲ și ▼.

**Comment by MateiGall** [comment]
Nu prea văd cum pot fi depistate acele situații... Poate căutând toate intrările cu mai multe lexeme; de regulă ar trebui să fie unul singur principal.
Dar cred că nu e o chestiune gravă (lexemul figurează principal în loc de variantă). Dacă le întâlnim pe parcurs (sau le semnalează Radu!), le corectăm.

Pentru butoane, nu cred că interfața se complică prea mult dacă acel mic semn se adaugă chiar pe lexem, lângă cel de ștergere (sau de editare). E suficient un singur semn „sus-jos” (↕), cu acțiune diferită în funcție de locul lexemului...

**Comment by CatalinFrancu** [comment]
Da, dar ne-am duce ușor-ușor spre o interfață prea aglomerată. Ar fi drăguț un meniu contextual care să includă toate acțiunile, dar librăria aceea pentru selecții este un modul separat și este complicat să intru atât de adânc sub capota lui.
