### ISSUE TITLE
Avertisment la crearea de lexeme dependente

### ISSUE THREAD

**Issue by CatalinFrancu** [dexonline/dexonline#654]
La crearea unui lexem nou pentru verb, sistemul creează și lexeme pentru infinitiv și, eventual, participiu. Dacă deja există lexeme cu aceeași formă ca infinitivul și participiul, sistemul trebuie să dea un avertisment.

**Comment by LadislauStrifler** [comment]
Ar fi o idee ca la „Reafișează” să se verifice aceste lexeme și să decidă înainte de generarea paradigmei ce e de făcut (creare/ignorare). Nu știu câți lucrează cu acest instrument, dar eu așa procedez. Prima dată verific paradigma apoi dau „Salvează”

**Comment by MateiGall** [comment]
Eu nu trec prin reafișare dacă sunt sigur de modelul ales.
Dar cam tot acolo ajungem și cu un mesaj de atenționare, cu două răspunsuri (unul implicit).

**Comment by CatalinFrancu** [comment]
Hm, tocmai mi-am dat seama că sistemul verifică deja existența lexemelor de F (sau IL) și A (sau PT). Dacă există, nu creează duplicate. @MateiGall, tu ai observat duplicate?

**Comment by LadislauStrifler** [comment]
Vezi mailul meu din: Thu 30.11.2017 16:33 cu subiect „dădălcire IL”

**Comment by MateiGall** [comment]
De verificat. Poate cazul „dădălci(re)” a fost anterior modificărilor de cod...

**Comment by CatalinFrancu** [comment]
Am înțeles - sistemul caută doar lexeme F/IL și A/PT. Dacă există lexeme, dar sunt T1, atunci creează duplicate. Ok, repar acum.

**Comment by LadislauStrifler** [comment]
Nu sunt sigur că e reparată. La `dăvăsi` mi-a creat `dăvăsit` **PT2**, deși exista `dăvăsit` **T1**. Eu i-am creat paradigma celui din urmă după incident. Nu a rămas să dea doar uărning? Situația este similară și la IL.

**Comment by CatalinFrancu** [comment]
Da, acesta este comportamentul dorit (cred!). Dă avertisment, dar creează în continuare noul lexem. Dacă tipul lexemului este diferit de F sau de IL (infinitive lung), respectiv de A sau de PT (participii), sistemul nu vrea să presupună că acel lexem poate fi luat și folosit pentru scopul nostru, nici măcar dacă este de tip T. Pare mai prudent așa!

**Comment by MateiGall** [comment]
Eu zic că e ok doar avertisment. Lexemul T1 poate a fost creat pornind de la alt sens și e necesar.

Bine ar fi ca moderatorii să țină cont de avertisment și să verifice (rezolve) duplicatele și să mai caute și prin rapoarte ce a rămas în aer. Avem acum vreo 10 definiții neasociate (de la Radu), vreo 22 de intrări, 24 lexeme și 2 arbori (care nu pricep cum au ajuns neasociați).

**Comment by LadislauStrifler** [comment]
Nu înțeleg pe deplin ce anume ai aprobat, @MateiGall. 
1. Faptul că la **`dăvăsi`** s-a creat și **`dăvăsit`** **PT2**, deși exista **`dăvăsit`** **T1**
2. În cazul în care se găsește un duplicat să nu se mai creeze automat **PT**

De obicei, după ce disociez din varii motive un obiect, îl și șterg.

**Comment by MateiGall** [comment]
Da, poate că `dăvăsit` T1 a apărut de la un s.n. și va fi etichetat ulterior ca N1/N24... Nu are rost să-l ștergem din start, iar PT2 e normal să fie creat asociat cu definițiile verbului.
Chiar și la crearea unui IL107 e posibil ca existentul T1 să aibă alt sens și alt model (ex. F103).

Observația cu ștergerea era mai mult pentru Laura/Laurențiu (chiar și Radu), cred că ei lasă multe astfel de „ne-asocieri”. Poate le mai explică cineva, eu le-am făcut un instructaj și mi-e teamă că dacă insist, iar se supără Laurențiu...

**Comment by LadislauStrifler** [comment]
[dăvăsit](https://dexonline.ro/definitie/d%C4%83v%C4%83sit/1053902) a apărut de la un adjectiv căruia nu i s-a generat paradigma. PT2 n-a făcut decât să-l duplice. De aceea am zis că poate înainte de salvare să se propună, după o verificare prealabilă, creare sau ignorare PT și/sau IL.
De fapt, partea proastă este că se creează intrări și lexeme noi, în cazul de față prin moderarea lui MDA2, fără să fie generate și paradigmele corespunzătoare.

**Comment by MateiGall** [comment]
Cu propunerile de soluționare (ștergere/păstrare) am fost și eu de acord (poate nu e prea complicat de implementat).
Faptul că moderatorii nu se ocupă și de etichetarea lexemelor create, iar numărul (imens) de T1 crește ... e altă discuție...

**Comment by CatalinFrancu** [comment]
Arborii _iris_ și _adonis_ rămăseseră neasociați dintr-un bug într-un script al meu care prelucrează nume de specii din DFL. I-am reasociat.
