### ISSUE TITLE
Migrează comentariile lexemelor în wiki

### ISSUE THREAD

**Issue by CatalinFrancu** [dexonline/dexonline#658]

**Comment by LadislauStrifler** [comment]
Comentariile de până acum s-au păstrat?

**Comment by CatalinFrancu** [comment]
Da, le-am migrat deja [în wiki](https://wiki.dexonline.ro/wiki/Special:Toate_paginile/Lexem:). Am convertit inclusiv numele de utilizatori dexonline în nume de utilizatori MediaWiki.

**Comment by LadislauStrifler** [comment]
OK, acestui filtru [wiki](https://wiki.dexonline.ro/wiki/Special:Toate_paginile/Lexem:) se poate adăuga la afișare după `Lexem:137778` și lexemul ca atare? În exemplul dat: `(sămânții)` ?

**Comment by CatalinFrancu** [comment]
Nu prea am cum să fac asta, pentru că se pierde legătura de la lexem la pagina wiki. Forma lexemului se poate schimba, doar ID-ul este imutabil.
