### ISSUE TITLE
Butoane pentru semne complexe

### ISSUE THREAD

**Issue by CatalinFrancu** [dexonline/dexonline#659]
În pagina de editare a definiției dorim un rând de butoane pentru inserarea la cursor a unor semne mai complex de tastat (á, à, ä ș.a.m.d.).

Setul de butoane trebuie să fie implicit ascuns și să poată fie deschis apăsând pe un buton. Trebuie să-și țină minte starea închis/deschis cu un cookie.

Setul de butoane trebuie să fie personalizabil pentru fiecare utilizator. Cred că un mecansim drăguț este acesta: la apăsarea unui buton „personalizează”, utilizatorul primește un input field în care poate tasta caracterele pe care le dorește, separate prin virgulă, de exemplu „á,à,ä”. Acest șir de caractere este salvat într-un cookie, iar pe baza lui sistemul generează automat butoanele. Această cerință presupune că utilizatorul poate obține toate caracterele de care are nevoie (din taste, din pagini web, din tabele Unicode etc.) și că folosește sistemul doar ca să le acceseze mai rapid.

Sistemul trebuie să interacționeze bine cu TinyMCE, care poate fi activ sau nu.

Codul trebuie să fie refolosibil și pe alte pagini.

**Comment by LadislauStrifler** [comment]
Ca să rafinăm și mai mult, nu s-ar putea rezolva printr-o fereastră modală să încărcăm butoanele respective? Astfel ar fi valabile global, oriunde în administrare (dacă e nevoie).

**Comment by raduborza** [comment]
1. Permitem și caractere care se pot combina (de exemplu U+0301 - combining acute accent)? Întrebarea se poate citi și așa: permitem utilizatorului să introducă orice caractere dorește sau îi limităm lista în vreun fel?

2. N-ar fi bine să își creeze omul și scurtăturile corespunzătoare: https://go.tinymce.com/blog/creating-keyboard-shortcuts-tinymce/ ?

**Comment by LadislauStrifler** [comment]
@david-batranu, am o rugăminte și o întrebare!
Dacă și @CatalinFrancu ar fi de acord, propun următoarele:
1. Cred că e nevoie și de unele explicații referitoare la butoanele implicite (dar nu numai - editorul și-ar putea lăsa unele notițe referitoare la glifă). 
În situația în care se folosesc semne (nu caractere) din afara ariei de tastare naturală, ar fi comod ca glifele adăugate să poarte și o explicație. (vezi imaginea anexată) Această explicație (tooltip) poate fi pe aceeași linie cu gilfa, despărțită printr-un caracter uzual - punct și virgulă `;` (să zicem)
Aș mai face o delimitare a secțiunilor `chirilic`, `grecesc` și `altele` printr-un `hr` sau un `fieldset`
```html
<fieldset>
    <legend>Caractere CHIRILICE</legend>
</fieldset>
```
codificat în `3 cratime` (vezi imagine anexată).
Cele două semne adăugate recent pentru pasajul invizibil ar fi bine să facă parte din setul de butoane implicite.

2. Multitudinea de caractere nu s-ar putea reduce printr-un buton „**shift**” care să comute între minuscule și majuscule? (până la urmă facem o tastatură virtuală - hehe) Sau ca să nu fie fereastra modală așa de înaltă s-ar putea modifica lățimea acesteia.
![inserareglife 1](https://user-images.githubusercontent.com/16460700/36932473-045254f2-1ed2-11e8-9689-58ad26cf5727.jpg)

**Comment by CatalinFrancu** [comment]
Nu știu @david-batranu mai are timp/chef pentru V2.0, asta e decizia lui. :-)

Eu sunt de acord cât timp sintaxa doar extinde sistemul existent, adică îți permite chestii noi, dar sistemul curent, cu o glifă pe linie, continuă să funcționeze. Pare că propunerea ta este în acest spirit. Altfel editorii se vor speria, sunt sigur de asta.

Nu știu dacă butonul Shift este ușor de implementat - trebuie testat că în Javascript conversiile între litere mari și mici merg bine. Dacă merg, în orice caz este imperativ ca Shift-ul să arate în timp real noile valori (dacă eu caut `Ξ`, este important ca, la apăsarea lui Shift, `ξ` să se transforme în `Ξ`, ca să-l văd).

Oricum, aș face asta într-un tichet nou.

**Comment by david-batranu** [comment]
> Nu știu dacă @david-batranu mai are timp/chef pentru V2.0, asta e decizia lui. :-)

Face băiatu.

Mi se pare că se complică nițel sintaxa, o să trebuiască să facem diferențierea între upper/lower case (shift), tooltip și să păstrăm în continuare posibilitatea de a adăuga mai mult de un caracter: https://github.com/dexonline/dexonline/pull/669#issuecomment-354298404

**Comment by LadislauStrifler** [comment]
@CatalinFrancu poți deschide tu un tichet nou importând comentariul meu, sau trebuie să o fac ab initio?
Aș mai avea de adăugat că inserarea unui caracter prin metoda ferestrei modale derulează până la final câmpul „conținut”. În acest moment cursorul (bara pâlpâitoare) dispare din câmpul vizual, rămânând totuși înfipt în locul inserării. La o apăsare de tastă câmpul „conținut” se derulează înapoi sus, până la poziția inserării. E vorba doar de browserul meu Chrome oare?
