### ISSUE TITLE
Schimbarea notației pentru accente

### ISSUE THREAD

**Issue by CatalinFrancu** [dexonline/dexonline#660]
Mai jos vorbesc despre două funcții, `sanitize()` care curăță și standardizează notația internă și `htmlize()` care convertește notația internă la HTML. Probabil va exista niște refactoring, dar conceptual cei doi pași vor rămâne.

- [x] Accentul tonic (cel care indică pronunția) va fi notat intern cu caracterul apostrof (`'`) înaintea caracterului de acccentuat. Exemplu: COP'IL.
- [x] Apostrofurile literale ([exemplu1](https://dexonline.ro/definitie/%C8%9Binuta%C8%99/734351) [exemplu2](https://dexonline.ro/definitie/cositur%C4%83/576854)) vor fi notate intern cu `\'`.
- [x] `sanitize()` va înlocui orice formă de apostrof cu cel ASCII, `\'` (de văzut câte caractere Unicode există deja în definiții pe post de apostrof).
- [x] `htmlize()` va înlocui `\'` cu ghilimea (`’` , Unicode U+2019). Pe viitor vom vedea dacă avem nevoie de mai multe simboluri (în funcție de sursă, de limba de proveniență a etimologiei etc.).
- [x] `htmlize()` va înlocui `'X` cu `<span class="tonic-accent">X</span>` pentru orice semn `X`.
- [x] De văzut dacă în CSS vom sublinia clasa `tonic-accent` (`text-decoration: underline`) sau vom căuta o soluție pentru punct dedesubt (de putut [se poate](https://stackoverflow.com/questions/27472905/add-a-single-dot-below-each-character-using-css)).
- [x] Examinarea manuală a caracterelor `'` existente. Majoritatea pot fi înlocuite în masă cu `\'` (pentru a fi tratate ca apostrof literal), dar sunt și excepții (vezi comentariul de mai jos).
- [ ] Scripturile existente pentru curățarea textului ieșit din OCR vor fi aduse la zi (dacă se poate).
- [x] [Ghidul voluntarului](https://wiki.dexonline.ro/wiki/Ghidul_voluntarului) va fi adus la zi.
- [x] Editorii vor fi anunțați de noile notații. Dacă din script nu putem să înlocuim noi `Á` cu `'A`, vom avea nevoie de ajutorul lor.
- [x] Generatorul indexului full-text trebuie învățat să ignore apostrofurile înainte să spargă definițiile în cuvinte (în `phplib/rebuildFullTextIndex.php:extractWords()`).
- [x] La click pe cuvânt (în JS) sistemul trebuie să ignore `<span class="tonic-accent">`, astfel ca la clic pe `COP<span...>I</span>L` să se ducă la _copil_, nu la _cop_.
- [x] Definițiile și sensurile care conțin orice formă de apostrof sau ghilimea trebuie reconvertite la HTML.

Ghilimele:

- [x] Funcția `sanitize()` va înlocui `„` și `”` cu `"` (ghilimele ASCII), cu excepția celor prefixate cu `\`.
- [x] Caracterele existente `„` și `”` vor fi înlocuite în masă cu `"` (ghilimele ASCII) și lăsată funcția `htmlize()` să-și facă treaba. Este posibil ca aceasta să strice unele definiții, deși n-am găsit exemple.

Altele:

- [x] Comentariile cu :heart: de mai jos, în afară de cele cu :+1:, pe care le-am rezolvat deja.

**Comment by LadislauStrifler** [comment]
Aș dori ca punctul:
Caracterele existente ` ' ` vor fi înlocuite în masă cu `\'` (pentru a fi tratate ca apostrof literal).
să fie executat după o prealabilă deratizare manuală. Vorbesc aici de acele cazuri când ` ' ` trebuie schimbat cu 'PRIME' (U+2032) sau ` '' ` trebuie schimbat cu 'DOUBLE PRIME' (U+2033). (minute, secunde, inch)

**Comment by LadislauStrifler** [comment]
O altă conversie necesară în `sanitize()` pe viitor:
'MASCULINE ORDINAL INDICATOR' (U+00BA) trebuie schimbat cu 'DEGREE SIGN' (U+00B0)

**Comment by LadislauStrifler** [comment]
l' nu ar trebui înlocuit peste tot cu l\' pentru că exemplifică ль-ul rusesc înmuiat

**Comment by LadislauStrifler** [comment]
Există situații când trebuie ras și spațiul de după apostrof - Scriban `c' un` și multe alte exemple similare.

**Comment by CatalinFrancu** [comment]
Înțeleg deci că există mai multe caractere asemănătoare cu apostroful și avem motive legitime să le folosim pe toate? Deci cerința _`sanitize()` va înlocui orice formă de apostrof cu cel ASCII, `\'`_ pică?

La modul general, nu vom ajunge vreodată să avem curățenie totală (și să prevenim apariția de noi greșeli). _That way madness lies_ :-)

**Comment by LadislauStrifler** [comment]
Deratizarea manuală pentru minute/secunde - țoli/inch eu zic că am făcut-o. Ar mai fi de trecut prin BD cu niște RLIKE-uri să fim siguri.
Un parser pentru Scriban ar trebui acum cu o listă prealabilă `c' un`, `c' o`, `c' ai`, `într' un`, `s' o` ș.a.m.d., sau verificat, tot așa, manual.

**Comment by CatalinFrancu** [comment]
Am făcut eu înlocuiri în masă în Scriban acum. At testat pe `s' a ` -> `s\'a `, apoi am inspectat vizual restul. Nu cred că a scăpat nimic care să nu trebuiască înlocuit.

**Comment by CatalinFrancu** [comment]
Am făcut deratizarea la apostrofurile existente. După o combinație de înlocuiri în masă, înlocuiri manuale și corectare de greșeli, în prezent nu mai avem apostrofuri libere (fără `\`) în definiții.

**Comment by MateiGall** [comment]
Pentru definițiile structurate (arbori) trebuie făcut ceva? E vreo restricție privind apostrofurile (sau alte caractere speciale) folosite?

**Comment by CatalinFrancu** [comment]
Aveam eu notat pe lista mea secretă :-) să trec și prin sensuri. Am trecut acum (atât pentru apostrofuri, cât și pentru ghilimele). Ar fi util să putem face înlocuiri în masă și în sensuri. Am deschis acum tichetul #675 pentru asta.

**Comment by CatalinFrancu** [comment]
@LadislauStrifler Referitor la `º` (U+00BA) versus `°` (U+00B0), pare că avem nevoie și de primul pentru [in-quarto](https://dexonline.ro/definitie/in-quarto) și [in-octavo](https://dexonline.ro/definitie/in-octavo). Pe acelea le-am _eșapat_ (haha) cu `\` și urmează să învăț sistemul să respecte `\` cu prioritate maximă (ca să ne asigurăm că avem un mod de a introduce absolut orice caracter dacă totuși ne trebuie).

**Comment by LadislauStrifler** [comment]
@CatalinFrancu la quarto și octavo te-ai ghidat după wiki-ul italian? Că pe cel englezesc și german e cu `degree sign`, iar pe cel franțuzesc cu superscript. :) 
La [adagio](https://dexonline.ro/definitie/adagio/441777) ce este... și de ce? :)

**Comment by CatalinFrancu** [comment]
Păi m-am gândit că numele caracterului este _masculine ordinal indicator_, adică exact ce vor să fie _quarto_ și _octavo_ (al patrulea / al optulea). La _adagio_ habar n-am ce-ar putea fi Ad° :-)

**Comment by LadislauStrifler** [comment]
Hm! [Uite](https://en.wikipedia.org/wiki/Ordinal_indicator) ce citesc eu. Deși nu indică locul/ordinea, s-ar putea să ai dreptate și să se folosească același semn.

**Comment by CatalinFrancu** [comment]
Nu știu ce trebuie să citesc de pe pagina aia. :-) Sper că nu pe toată! Am decupat la întâmplare un º și l-am căutat pe [unicodelookup.com](https://unicodelookup.com/). Pare să aibă codul U+00BA.

**Comment by LadislauStrifler** [comment]
Nici englezii nu știu ce vor. Pe [pagina asta](https://en.wiktionary.org/wiki/8%C2%BA) e cu ordinal.

**Comment by CatalinFrancu** [comment]
Eu mă declar mulțumit de tichetul ăsta. :-) Au mai rămas cele două chestii nebifate. Pentru stil, aș lăsa pur și simplu subliniere, nu m-aș arunca la punct. Pentru OCR, @raduborza, e ceva de modificat? Dacă OCR-ul produce deja ___'a 'e 'i___, atunci nu mai e nevoie de nimic. Dacă produce ___á é í___, acelea ar merita înlocuite cu prima variantă (dar nu și în etimologii, dacă se poate).

**Comment by raduborza** [comment]
Păi produce exact ce vede! Sigur, limba română nu are á, é, í, astfel că de obicei OCR-ul ignoră accentele.
O să mă uit să văd cam care e proporția de accente și o să pun opțiune de transformare a accentelor în variante cu '.

**Comment by raduborza** [comment]
Eu zic că mai bine închidem tichetul ăsta și facem unul nou, doar pentru partea de OCR.

Că pun o listă mai lungă cu ce e de făcut...

**Comment by CatalinFrancu** [comment]
Ok! Să-l deschizi tu, te rog, ca să pui lucrurile de făcut în descriere.
