### ISSUE TITLE
Îmbunătățiri la editarea intrărilor / arborilor

### ISSUE THREAD

**Issue by MateiGall** [dexonline/dexonline#663]
- [x] 1. Pe pagina intrării ar fi bun un buton de ștergere a arborilor (plasat pe bara arborelui, lângă cel de editare), inactiv dacă arborele nu e gol. - Ar ajuta la ștergere, fără a mai trece prin pagina arborelui.
- [x] 2. Operația de creare a arborelui (asociat unei intrări) ar trebui să se facă fără a trece direct în pagina arborelui (sau să-l deschidă într-un tab separat). - Cred că editorul e interesat să rămână inițial în pagina intrării (din care copiază sensuri).
- [ ] 3. Ar fi bună și posibilitatea de a clona un sens (adăugarea unui sens identic, cu păstrarea tuturor surselor, etichetelor, relațiilor). - Avem sensuri preluate global dintr-o sursă (ex. mai multe expresii înșiruite) și ar fi mai simplu de clonat și șters parțial decât adăugarea cu decuparea părților.

**Comment by CatalinFrancu** [comment]
Rezolvat. Sensurile sunt acum clonate cu tot subarborele („cu tot neamul” :-) ) și sunt adăugate după sensul selectat. Dacă preferi să clonăm strict sensul, sau să îl așezăm altundeva, e ușor de modificat.
