### ISSUE TITLE
API pentru cuvantul zilei (word of the day)

### ISSUE THREAD

**Issue by revolter** [dexonline/dexonline#664]
Revin cu cererea din https://github.com/dexonline/dexonline/issues/562#issuecomment-284268491 pentru o mai buna vizibilitate a progresului.

Un API (`JSON` si `XML`, ca si pentru definitii), care sa returneze un raspuns, cu aceeasi structura ca cel de la definitii, pentru un cuvant ales din baza de date pentru ziua curenta (relativ la data server-ului poate?). Evident, de fiecare data cand e apelat, sa returneze acelasi cuvant, optional cu cache headers care sa ii zica sa expire la finalul zilei.

**Comment by LadislauStrifler** [comment]
Dacă e bine [în acest fel](https://gist.github.com/LadislauStrifler/1a9356a59943f140bbfec416c4ed3158), atunci e gata.

**Comment by revolter** [comment]
Ar putea sa contina si link catre imagine?

**Comment by LadislauStrifler** [comment]
Sigur, toate?
`requested` la imaginea mare, iar `others `la imaginea mică e bine?

**Comment by revolter** [comment]
Pentru mine, da.

**Comment by CatalinFrancu** [comment]
:heart: Arată bine! Rămîne să-i alegem un URL. Poate fi netradus, nu cred că are nevoie de localizare. Ar putea fi `/wotd-api` pentru ziua curentă, respectiv `/wotd-api/YYYY/MM/DD` pentru o dată oarecare.

În caz că ajută, aș vedea codul așa. În `lib/Router.php`:

```php
'wotd/api' => [
  'en_US.utf8' => 'wotd-api',
],

...

const PARAMS = [
  ...
  'wotd/api' => [ 'year', 'month', 'day' ],
];
```

Apoi în `routes/wotd/api.php` scris codul care varsă acele fișiere. Probabil trebuie scos factor comun cu routes/wotd/view.php pentru partea de permisiuni, extragere din baza de date etc.

**Comment by LadislauStrifler** [comment]
Eu am avut altă idee, menținând sintaxa de la definiție/intrare, care așteaptă sau nu `&format=`.
URL-ul rămâne același, de pildă:
**la cerere, putând fi oricare zi**
`cuvantul-zilei/2019/11/11` -  _format html_
`cuvantul-zilei/2019/11/11/` -  _format html_
`cuvantul-zilei/2019/11/11/json` - _format json_
`cuvantul-zilei/2019/11/11/xml` - _format xml_

**ziua curentă**
`cuvantul-zilei` - _format html_
`cuvantul-zilei/` - _format html_
`cuvantul-zilei/json` - _format json_
`cuvantul-zilei/xml `- _format xml_

Identic și la `cuvantul-lunii`.

Am făcut deja în `Router.php` niște modificări. Am declarat regex pentru fiecare (zi și lună).
Am modificat `PARAMS`, ca să i le pot oferi lui `wot(d/m)/view.php` .
```
'wotd/view' => [ 'year', 'month', 'day', 'format' ],
'wotm/view' => [ 'year', 'month', 'format' ],
```
Prin regex testez dacă URL-ul le conține, le bag frumos în `$_REQUEST` și le azvârl către `wot(d/m)/view.php`.

@CatalinFrancu, parcă e mai consecvent așa.

**Comment by CatalinFrancu** [comment]
Da, asta era cealaltă variantă. Dacă-i deja făcut, atunci așa să-i rămînă numele. :-) Nu e favoritul meu pentru că nu permite direct cuvantul-zilei/json (pentru ziua curentă), dar nu pare o mare pierdere.

**Comment by LadislauStrifler** [comment]
@CatalinFrancu dar am scris că permite. :)

**Comment by LadislauStrifler** [comment]
Nu l-am închis, dar îl propun pentru închidere. Trimiterea unui `Cache-Control` nu mi se pare de luat în seamă atâta timp cât pagina mai poate suferi modificări chiar în timpul zilei. Dacă cumva ar fi de bun augur, atunci adaug.

**Comment by CatalinFrancu** [comment]
> @CatalinFrancu dar am scris că permite. :)

Ah, pardon. Voi începe să scriu treaz!

**Comment by revolter** [comment]
Multumesc mult @LadislauStrifler! Ma oftic putin, pentru ca dupa foarte mult timp, am reusit si eu sa imi pun la punct environmentul de development local (pentru ca macOS si pentru ca lenes, nu pentru ca dureaza atat de mult), si urma sa ma apuc de asta :)) Dar, evident, nu e nici o problema ca ai facut tu. O sa pot acum sa fac https://github.com/revolter/DexRoBot/issues/2 ❤️
