### ISSUE TITLE
Inserare indici în definiție și comentariu.

### ISSUE THREAD

**Issue by MateiGall** [dexonline/dexonline#667]
Pentru a indica locul unei corecturi efectuate într-o definiție și explicată în comentariu, ar fi necesară o modalitate de marcare.
Propun utilizarea unor indici, diferiți de cei utilizați în mod normal (^1, ^2 etc.). O soluție ar fi **^C1**, **^C2** etc.
Ar fi util însă dacă procedura ar fi ușurată prin implementarea unor butoane (cu incrementare automată), care să evite combinațiile de caractere greu de tastat (ex. **^{[1]}**).

**Comment by CatalinFrancu** [comment]
Am o idee mai generală. Câmpul comentariu ar dispărea de tot, iar definițiile ar căpăta o nouă sintaxă pentru inserarea direct în text a comentariilor. Propun sintaxa {{...}}. Pentru [ecumenic](https://dexonline.ro/definitie/ecumenic/1084371) am avea:

> $@ecuménic, \~ă@ a$ [#At:# CANTEMIR, #ap.# CADE / #V:# $@i~@$ / #Pl:# $~ici, ~ice${{În original, incorect accentuat: $~íci, ~íce.$}} / #E:# #fr# @$oecuménique,$@ #ngr# @$οἰκουμενικός$@{{În original, incorect: $οἰκουμευικός$}}] @1@ Investit cu autoritate extinsă asupra...

Iar sistemul ar extrage și numerota pasajele între {{...}} ca note de subsol, numerotate automat, cam așa:

> _**ecuménic, \~ă** a_ [At: CANTEMIR, ap. CADE / V: _**i~**_ / Pl: _~ici, ~ice_<sup>[1]</sup> / E: fr _**oecuménique,**_ ngr _**οἰκουμενικός**_<sup>[2]</sup>] **1** Investit cu autoritate extinsă asupra...
> [1] În original, incorect accentuat: $~íci, ~íce.$
> [2] În original, incorect: $οἰκουμευικός$

Dezavantaj:

* Nu mai este vizibil public cine a scris un comentariu.

Avantaje:

* Este clar la ce anume se referă un comentariu
* Paternitatea comentariilor este vizibilă în istoria definiției.
* Comentariile capătă automat versiuni ca și definițiile, fiind incluse în acestea.

**Comment by LadislauStrifler** [comment]
Dezavantaj: ?
Nu ar exista dacă între {{...}} punem un ID și ținem o tabelă separată de comentarii unde relaționăm și autorul.
Huh?

**Comment by CatalinFrancu** [comment]
Da, n-ar fi rău! Dar aș insera acolo chiar ID-ul utilizatorului. Deci sintaxa ar putea fi {{comentariu|userId}}. La salvare, sistemul inserează acele ID-uri unde nu există deja. Sigur, asta înseamnă că utilizatorii își pot însuși comentariile altora -- dar aia se poate și în prezent, nu mi-aș face griji.

Rămâne de văzut dacă putem scăpa fără o tabelă suplimentară. La limită, am putea ține comentariile în definiție și să le extragem din Javascript la afișare. Dar pare urât. Parcă mai bine le extragem într-o tabelă separată (mă refer doar la versiunea HTML -- cea internă cu {{...}} ar locui mereu în definiție).

**Comment by LadislauStrifler** [comment]
Dacă ținem tabelă separată avem și istoric de comentarii.
