### ISSUE TITLE
Redirectare gresita pentru șocî́te

### ISSUE THREAD

**Issue by revolter** [dexonline/dexonline#670]
Desi definitia pentru `șocî́te` exista [aici][1], este imposibil de gasit folosind API-ul sau site-ul.

1. Daca accesezi [definitia][1] si dai click pe cuvant, esti redirectat la https://dexonline.ro/definitie/societate.
2. Daca accesezi [API-ul pentru cuvant][2], esti redirectat la https://dexonline.ro/definitie/societate/json.

Asta e din cauza literei `î́` care are un accent ciudat deasupra?

  [1]: https://dexonline.ro/definitie/%C8%99oc%C3%A2te/716841
  [2]: https://dexonline.ro/definitie/%C8%99oc%C3%AE%CC%81te/json

**Comment by LadislauStrifler** [comment]
Este vreun motiv pentru care nu cauți cu ortografia nouă → `șocâte`?

**Comment by revolter** [comment]
Incercasem prin bot-ul de Telegram care foloseste API-ul dexonline si nu returna corect, probabil a fost problema de cache.

1. Nu ar trebui atunci inlocuit cu ortografia noua?
2. Exceptand orice altceva, pare gresit faptul ca atunci cand dai click pe cuvantul a carui definitie e afisata, esti redirectat la un cuvant complet diferit, ceea ce nu se intampla la majoritatea cuvintelor. La fel de gresit pare si ca nu returneaza definitia corecta atunci cand cauti exact cuvantul care are intrare in baza de date.

**Comment by CatalinFrancu** [comment]
Am rezolvat o problemă din două, e maximul la care pot spera. :-) Am eliminat accentele de pe __Ấ__ și __Î́__. Știam de problemă, o observasem și la [pîine](https://dexonline.ro/definitie-dlrlc/p%C3%A2ine), [mîine](https://dexonline.ro/definitie-dlrlc/m%C3%A2ine) și alte cuvinte cu grafia veche. Astfel, acum măcar clicul pe __șocî́te__ duce, corect, la __șocîte__.

A doua parte ar merita și ea rezolvată: sistemul să înlocuiască automat ortografia veche cu cea nouă în textul căutat. Dar e nevoie de un pic de _brainstorming_, să nu scăpăm vreun caz din vedere. @raduborza, ce părere ai de modificările astea?

1. Preferința _Folosesc ortografia folosită până în 1993_ se va referi doar la afișare (acel postfiltru de Smarty).
2. La căutare, schimbarea de ortografie se va întâmpla pentru toată lumea, indiferent de preferința de mai sus. Motivația este că, oricum, nimeni nu ar avea de ce să caute _pîine_, pentru că singurul lexem pe care îl avem este _pâine_.

**Comment by raduborza** [comment]
Observația 2. nu este tocmai corectă, am primit multe mesaje de la oameni care caută cu î (sigur, cei mai mulți nu  își setează preferința respectivă). Nu zic că și eu am obiceiul ăsta (iar eu sînt obligat să am preferința dezactivată), că eu mă descurc... 
Dacă zici că _pîine_ e transformat în _pâine_ e relativ ok, acoperă problema. Totuși, dacă cineva găsește într-un text vechi _stangen_, așa îl va căuta, noi nu vom ști să îl modificăm în _stânjen_...

Cu observația 1 sînt de acord (dar afișarea nu trebuie să implice și cîmpurile de editare, dacă este posibil – acum nu face asta și din cauza asta eu nu pot folosi opțiunea și nu m-am învrednicit să o fixez)

**Comment by revolter** [comment]
`șocîte` nu ar trebui sa redirecteze acum la `șocâte`? Parca am observat ca dexonline are un fel de cautare de cuvinte apropiate atunci cand nu gaseste unul, corect?

**Comment by LadislauStrifler** [comment]
Este același comportament sesizat de mine, pe mail (vezi firul **`VÎRȘĂ`**) care la căutare, cu modul post93, te duce la **`VIRUSA`**.
Ceea ce este disfuncțional, în opinia mea!, este corelarea între opțiunile:
`[x] Pun eu diacritice în căutare`
`[ ] Folosesc ortografia folosită pînă în 1993 (î din i)`
setare la care te-ai aștepta să scrii **`VÎRȘĂ`** sau **`ȘOCÎTE`** și să te ducă la definiția cu pricina.
Ceea ce ar trebui să primeze este căutarea, nu afișarea, prin interschimbabilitatea dintre Î și Â.
Dacă am optat pentru diacritice, conștient de ceea ce scriu, înseamnă că `VÎRȘĂ` este un cuvânt valid. Fiind post93, motorul ar trebui să-l convertească în `VÂRȘĂ` și să caute în consecință.

O altă inadvertență este și afișarea cu ortografia aleasă în preferințe.
Atâta timp cât **`Scriban`** și **`Șăineanu`** nu sunt convertite la noua ortografie, nici **`DOOM2`** (în special) nu ar trebui să fie convertită la cea veche.

Să nu uităm că mai sunt dicționare care ar trebui **_restaurate_** la ortografiile în care au fost scrise (**`DOOM`**, **`DLRM`** ș.a., pe care nu le știu). Cred că acest aspect ar trebui să facă subiectul unui alt tichet.

**Comment by MateiGall** [comment]
1. `ȘOCÎTE` ar trebui să redirecteze la `ȘOCÂTE`, nu la o pagină de ambiguitate (cred eu). Acest comportament ar trebui să intervină doar dacă `șocâte` nu e un lexem corect.
2. Redirectarea este inutilă în cazul cuvintelor-titlu (dar dacă codul e mai simplu așa ... nu deranjează).

**Comment by CatalinFrancu** [comment]
@raduborza Prin observația 2. nu spuneam că lumea n-ar căuta _pîine_, ci că e OK să înlocuim căutarea _pîine_ cu _pâine_. De acord că asta nu rezolvă toate ortografiile vechi, dar o rezolvă pe cea pre-1993, care e mult mai comună decât altele ieșite complet din uz. _Stangen_ nu e un exemplu bun, acela e variantă și chiar redirectează la _stânjen_. :-)

La 1., de acord că ar fi cool să lase câmpurile neatinse. Din păcate, e complicat să ne dăm seama ce e un „câmp”. E ușor să modificăm _output filter_-ul din smarty să nu se atingă de `<input value="...">` și de `<textarea>...</textarea>`. Problema e că mai sunt și select2-uri, editorul TinyMCE... Pare greu să fim siguri că am prins toate cazurile.
