### ISSUE TITLE
Unifică contribuie.php și definitionEdit.php

### ISSUE THREAD

**Issue by CatalinFrancu** [dexonline/dexonline#684]
E cod duplicat, în mare parte. Ce dorim:

- [x] Să permită aceleași cazuri particulare pentru anonimi / utilizatori fără privilegii și pentru editori (utilizatori cu `PRIV_EDIT`). Sunt diverse `if`-uri prin cod, trebuie ținut cont de ele.
- [x] Să împace cumva comportamentele când niciun ID nu este specificat. În prezent, `contribuie.php` creează o definiție nouă, iar `definitionEdit.php` aduce o definiție nouă din OCR.
- [x] Să creăm un privilegiu nou, să zicem `PRIV_TRAINEE`, care să ofere dreptul de a lua cuvinte din coada OCR. În rest, drepturile pentru `PRIV_TRAINEE` trebuie evaluate și puse la valori minime (probabil aproape de drepturile pentru anonimi).

**Comment by raduborza** [comment]
Aș propune să facem chestiunea asta în doi pași:

1. Adăugăm noul tip de utilizator: _Contributor_ și îi dăm drepturi limitate (asta implică că utilizatorul este logat);
2. Extindem funcționalitatea și la pagina _Contribuie cu definiții_ (aici trebuie să existe și posibilitatea utilizatorului anonim, care are și mai puține drepturi)

Ce drepturi aș da _Contributor_:

- acces la Pagina de editare de definiții pentru adăugarea definițiilor **noi** în starea _temporară_ (cu necesitatea moderării);
- acces la Pagina de editare de definiții pentru preluarea definițiilor din **coada OCR** în starea _temporară_ (cu necesitatea moderării);
- limitare a numărului de definiții nemoderate
- fiecare contributor trebuie să aibă un moderator asignat;
- posibilitatea de a-și corecta propriile definiții (conform punctului anterior, asta ar însemna că corectura implică trecerea în _temporară_);
- posibilitate limitată de a crea intrări noi (lăsînd la o parte că nu e foarte clar definită problema, aici e un pic mai complicat);

**Comment by CatalinFrancu** [comment]
Și deci pasul 1 s-ar ocupa mai întâi de `definitionEdit.php`? Iar pasul 2 ar copia lucrurile și la `contribuie.php`? N-aș vrea să scriu chestii de două ori. Aș prefera să fac întâi unificarea, pentru ca apoi, când adăugăm utilizatorul _Contributor_, să am o singură pagină de modificat.

De acord cu drepturile. _Fiecare contributor trebuie să aibă un moderator asignat_ sper că se implementează soft. :-) N-aș face un câmp pentru asta etc. Deși hm, ar fi util ca „mentorul” să primească un email când numărul de definiții nemoderate se apropie de limită.

La _posibilitate limitată de a crea intrări noi_, aș lăsa libertate deplină, în fond anonimii o au acum. Când o definiție este ștearsă, orice intrări și lexeme care rămân orfane sunt șterse și ele, deci problema nu degenerează.

**Comment by CatalinFrancu** [comment]
Au rămas nefăcute:

* Posibilitatea utilizatorului anonim. Realist vorbind, nu mai este necesară.
* Fiecare stagiar să aibă un moderator asignat. Aș lăsa asta să se întâmple de la sine, cel puțin până când știm mai bine detaliile de implementare.
