### ISSUE TITLE
tools/dumpDatabaseXml încă folosește abrevierile din fișiere

### ISSUE THREAD

**Issue by CatalinFrancu** [dexonline/dexonline#695]
Trebuie convertit la noul sistem implementat de @LadislauStrifler. De văzut de ce folosește cod propriu în loc să-l refolosească pe cel din `phplib/Abbrev.php`.

**Comment by LadislauStrifler** [comment]
Ah, am pierdut din vedere dumpu'. M-am legat de el cu #692, dar n-am ținut minte pentru abrevieri.
