### ISSUE TITLE
Accentul secundar

### ISSUE THREAD

**Issue by CatalinFrancu** [dexonline/dexonline#698]
Să poată fi marcat în lexeme, folosind ghilimelele ASCII (`"`). La afișare să fie înlocuit cu o clasă CSS (probabil în `Str::highlightAccent()`). De verificat că bucățile din cod care gestionează paradigmele nu sunt afectate -- generarea flexiunilor, editarea modelelor etc.

**Comment by LadislauStrifler** [comment]
Nu cred că e bine cu ghilimele. Într-o definiție nu poți folosi această notație. Nu doar la lexeme este necesar.

**Comment by CatalinFrancu** [comment]
Hm, bună observație. Ok, atunci dublu apostrof (`''`) ar fi următoarea variantă naturală, dar e necesară mai multă atenție la bucățile de cod sus-menționate.

**Comment by CatalinFrancu** [comment]
Pare rezolvat în 4433bf710a982be2fcdec0fa76a58866589b5fca, nu? Mă asignez pe mine pentru verificarea generării paradigmelor (deja văd un bug).

**Comment by LadislauStrifler** [comment]
Da, era rezolvat parțial. La generarea paradigmelor a făcut BUM și am zis că revin. Mersi pentru preluare.

**Comment by CatalinFrancu** [comment]
Ok. Am făcut și un script care să genereze toate paradigmele tuturor lexemelor și să compare cu ce avem. Ne va fi bun și pe viitor.

**Comment by CatalinFrancu** [comment]
Probabil ar trebui reimportat DOOM2 (nu complet, ci doar identificate definițiile care conțin accente secundare). Nici nu trebuie neapărat adăugate accentele automat. Chiar și semnalarea definițiilor în cauză ar fi un pas înainte, urmat de modificarea lor manuală (mă aștept să le putem prelucra în câteva ore).

**Comment by MateiGall** [comment]
Da, cred că depinde ce format a avut sursa. Poate ne lămurește @raduborza .

Pentru modificarea afișării accentului primar (literă cu accent -> literă subliniată) se poate face ceva, sau tot manual ... în timp?

**Comment by raduborza** [comment]
Păi DOOM2 a fost introdus de mine după ce am OCR-izat formatul pdf (din păcate nu eu am scanat, astfel că calitatea a fost slăbuță). Am preferat să corectez într-un fișier separat, ca să am viteză mai mare (pe atunci nu exista pagina OCR care ajută mult, ca azi)

Nici nu mai țin minte dacă mi-au scăpat accentele secundare sau doar le-am sărit că nu aveam suport pentru ele (sînt mai mult de 5 ani, totuși).

**Comment by MateiGall** [comment]
Știu că atunci nu aveam suport pentru accentul secundar. Eu mă refeream la faptul că litera în cauză a fost înlocuită cu o majusculă. Același lucru apare la [eterogenitate](https://dexonline.ro/definitie/eterogenitate/764579). dar nu și la [eterosugestie](https://dexonline.ro/definitie/eterosugestie/764583). Poate mai sunt și alte cazuri...

**Comment by raduborza** [comment]
Atît timp cît pdf-ul după care am introdus cuvintele este disponibil tuturor moderatorilor (de fapt e o versiune un pic mai clară), cred că este evident pentru toți cei care se uită în el că este o scăpare. 

Alte cazuri de care? Scăpări? Sînt convins că mai sînt!

**Comment by MateiGall** [comment]
N-am știut că documentul pe care ai lucrat este același cu cel vizibil acum. Mă gândisem că poate a fost un tratament general pentru literele inițiale cu accent secundar (ceea ce ar fi ajutat la o înlocuire în masă). Abia după toată discuția am constatat că această „regulă” nu se respectă.

Rămâne întrebarea: se poate face ceva pentru înlocuire în masă? Un nou import ar ajuta cu ceva?

**Comment by raduborza** [comment]
La ce ar putea ajuta un nou „import”? Că nu înțeleg ideea lui (nu ar fi rău ca propunerile astea să fie explicate clar de la bun început, că altfel o să facem un ping-pong inutil de mesaje)!
Sînt aceleași fișiere lucrate de mine, dar fără corecturile făcute pe dexonline (după adăugarea definițiilor), deci imho ar face mai mult rău decît bine.

**Comment by MateiGall** [comment]
A fost ideea lui @CatalinFrancu . Eu nu știu „dedesubturile” din baza de date.

**Comment by CatalinFrancu** [comment]
Ce voiam să zic era doar să reprocesăm originalul ca să depistăm cuvintele cu accent secundar. Dacă le-am putea și insera automat în definiții ar fi și mai frumos, evident, dar chiar și listarea cuvintelor cu accent secundar ar fi suficientă, apoi putem edita manual definițiile.

**Comment by raduborza** [comment]
Ar fi mișto să poată exista o aplicație magică care să facă OCR așa de bine încît să detecteze accentele duble (cel curent nici măcar pe alea simple nu reușește să le extragă)! Uite un eșantion ce conține accente d-alea secundare; dacă descoperiți softul care ne ajută..., sînt sincer interesat de el!
![doom2 - e antion accent secundar](https://user-images.githubusercontent.com/6553326/39590282-20147da2-4f09-11e8-8e21-6baa944ab768.png)

**Comment by raduborza** [comment]
A, dacă reușește cineva să facă lista cuvintelor care au accente secundare, promit că le introduc eu!

**Comment by raduborza** [comment]
Accent secundar au toate cuvintele mai lungi, formate cu sau fără prefix(oid)e. Doar că DOOM2 nu și-a propus să le afișeze... După cum spun și cei de la DOOM2, accentul secundar e marcat doar în cazurile în care pot exista ezitări:
![image](https://user-images.githubusercontent.com/6553326/39617090-01165172-4f87-11e8-9074-3e16646ad78b.png)

Cazul particular menționat de tine este explicat în DOOM:
![image](https://user-images.githubusercontent.com/6553326/39617136-28687408-4f87-11e8-9ece-bd2735d4f81b.png)

Fenomenul este destul de important, iar dacă pentru vorbitorii nativi nu ar trebui să conteze prea mult, pentru străini lipsa accentului secundar e sigur deranjantă, în special în cazul sufixelor tari (cele care „fură” accentul principal): c**a**lcul, calcul**a**bil, calculabilit**a**te (mai ales că există și calc**u**l)!

Ar fi interesant un studiu pe tema accentului secundar (nu prea există, cel puțin nu pe internet), dar dacă nu îl facem noi nu cred că va apărea prea curînd!
