### ISSUE TITLE
Generalizarea interacțiunii dintre etichete și modele (pe lexeme)

### ISSUE THREAD

**Issue by CatalinFrancu** [dexonline/dexonline#700]
În prezent, avem niște `if`-uri prin cod, care la salvarea lexemului schimbă modelul din F în IL dacă există eticheta [infinitiv lung] (caută `lexemeAutoType` prin cod). Trebuie generalizat mecanismul ca să includă și numere de model și să permită și modificarea inversă (aplicarea unei etichete în prezența unui model). Cazuri cerute de @MateiGall:

- [x] toate lexemele cu model M primesc eticheta „substantiv masculin”; analog pentru F - „substantiv feminin”, N - „substantiv neutru” și A - „adjectiv”.
- [ ] toate lexemele cu etichetă „adverb” și model I1 își modifică modelul din I1 în I8; analog pentru „interjecție” - I10, „conjuncție” - I11, „prepoziție” - I12.
- [x] toate lexemele cu model I3 primesc eticheta „nume propriu”; analog pentru I2 - „termen biologic”.

Și, ca de obicei,

- [x] script pentru armonizarea situațiilor existente.

**Comment by CatalinFrancu** [comment]
Note pentru mine însumi.

Cazuri existente:

* creare lexem dependent: tip -> +etichetă (ex. IL → [infinitiv lung]);
* editare: tip + etichetă -> tip nou (ex. F + [infinitiv lung] → IL);
* editare: tip + lipsa etichetei -> tip nou (ex. IL + lipsă [infinitiv lung] → F);

Generalizare (în toate cazurile numărul poate fi `*`, cu sensul de „indiferent de număr”):

* tip + număr → +etichetă;
* tip + număr + [etichetă] → tip + număr;
* tip + număr + lipsă [etichetă] → tip + număr;

**Comment by CatalinFrancu** [comment]
@MateiGall O posibilă problemă: lexemele _ca, de, fără, până_ au și eticheta [conjuncție], și [prepoziție]. Scriptul care le va eticheta va alege unul dintre modelele I11 și I12, care se nimerește să ruleze primul. Dorim să păstrăm aceste lexeme ca I1? Sper că nu, nu știu cum aș face asta. :-)

**Comment by MateiGall** [comment]
Da, există diverse cazuri de lexeme cu 2-3 etichete (inclusiv unele cu _interj., adv., simbol_ etc.

Eu văd două rezolvări:

1. Clonăm lexemele astfel încât să avem o singură etichetă și un singur model pe fiecare (chiar dacă modelele sunt practic identice I8=I9=I10 etc.). Dezavantaj: redundanță în baza de date.
2. Păstrăm un singur lexem fără etichete, cu un model nespecificat I1, iar etichetele le mutăm pe intrare/arbore.

Cred că @raduborza ar trebui să decidă, el exprimase unele cerințe privind etichetele.
