### ISSUE TITLE
Copiere proprietăți la lexeme identice/similare

### ISSUE THREAD

**Issue by LadislauStrifler** [dexonline/dexonline#702]
În momentul indicării unui lexem similar, la editarea acestuia, ar fi bine ca, de asemenea, și etichetele să fie preluate.

**Comment by MateiGall** [comment]
Da. Chiar dacă unele etichete nu se potrivesc, e mai simplă eliminarea decât adăugarea.

**Comment by CatalinFrancu** [comment]
Dacă voi ziceți că e bine, atunci facem. :-) Bănuiesc că vă interesează preluarea etichetelor privind partea de vorbire? Că cele de registru stilistic etc. nu prea au legătură cu „similitudinea”, care se referă doar la flexiune.

**Comment by LadislauStrifler** [comment]
Da, doar la etichetele referitoare la părțile de vorbire m-am gândit.
