### ISSUE TITLE
Generare defectuoasă flexiune lexeme compuse

### ISSUE THREAD

**Issue by LadislauStrifler** [dexonline/dexonline#703]
La generarea paradigmei lexemelor compuse, în momentul în care un lexem component are o restricție S, lexemul compus cu opțiunea „flexiune completă” la cel restricționat afișează defectuos pluralul la N.-Ac.
ex: **autoimprecație** avea restricție **S**
**autoimprecație**-legământ la N.-Ac. plural afișa tot variantele de singular
Ar trebui să exemplifice prin `—` imposibilitatea generării flexiunii.

**Comment by CatalinFrancu** [comment]
Și eu înclin spre opinia lui Matei. O cale de mijloc ar fi ca butonul „autocompletează” să preia restricțiile lexemelor și să populeze automat căsuța de restricții (a lexemului compus). Moderatorul poate decide dacă le păstrează sau nu.
