### ISSUE TITLE
Informații lexem

### ISSUE THREAD

**Issue by MateiGall** [dexonline/dexonline#705]
Pe pagina de afișare a flexiunilor ar fi bine să figureze (în bara de titlu) și celelalte informații (număr, silabisiri, pronunții) din pagina de editare. Ar fi în ajutorul moderatorului, care n-ar mai fi nevoit să acceseze pagina de editare ca să verifice existența/corectitudinea acestor elemente.
Eventual aceste informații să fie afișate doar pentru moderatori, să nu încarce pagina celorlalți utilizatori (și să-i deruteze).

**Comment by CatalinFrancu** [comment]
Vezi [kimeridgian](https://dexonline.ro/definitie/kimeridgian/paradigma) (silabisire și pronunție), [zoantrop](https://dexonline.ro/definitie/zoantrop/paradigma) (doar silabisire).

Cum ți se pare? Le-am lăsat pentru toți utilizatorii până la urmă. Nu cred că derutează, fiindcă scrie clar „silabisire” și „pronunție”.

**Comment by MateiGall** [comment]
Arată bine.

De discutat dacă aceste informații (și cele referitoare la partea de vorbire) trebuie (sau e bine) să fie afișate și în tabul „sinteză”. Eu cred că aici ar trebui sintetizate toate informațiile...

**Comment by MateiGall** [comment]
Eu așa îmi imaginez „sinteza”: sensurile, etimologiile, relațiile, partea de vorbire, pronunții, silabisire... informații care trebuie să fie vizibile direct. De ce să mai dau un clic ca să văd dacă e substantiv, verb sau interjecție?
Rămân taburile pentru formele flexionare și pentru definiții, pentru cei care vor informații suplimentare.
Aș vrea și părerea celorlalți ... și facem cum zice majoritatea :-)
