### ISSUE TITLE
Excluderea unor pasaje din indexarea full-text

### ISSUE THREAD

**Issue by LadislauStrifler** [dexonline/dexonline#710]
Propunere:
În momentul de față și pasajele ▶◀ sunt indexate, dar la căutările full-text este posibil ca unele cuvinte căutate să nu fie afișate. Aceasta creează confuzie.
Similar acestor subșiruri, s-ar mai putea exclude și comentariile `{{...}}`, care doar alterează oarecum conținutul definiției.

**Comment by CatalinFrancu** [comment]
De acord, iar asta ne ajută și cu #709, dacă și când vom adăuga notația pentru corectură.
