### ISSUE TITLE
Îmbunătățiri la înlocuirea în masă

### ISSUE THREAD

**Issue by CatalinFrancu** [dexonline/dexonline#717]
- [x] Dacă o definiție modificată conține un comentariu, acesta trebuie extras și regenerat.
- [x] Dacă o definiție modificată este structurată, trebuie generat un avertisment (unul singur pentru întreaga pagină!)

**Comment by LadislauStrifler** [comment]
Nu doar asta, ar trebui să dea avertisment care dintre definițiile modificate sunt structurate. Am întâlnit acum cazuri (înlocuire `â` în `î` în DLRLC) când și în structurare erau greșeli. Făcându-le multe manual am avut posibilitatea de a le vizualiza. În caz că modificarea se face „la vrac”, se vor pierde.

**Comment by CatalinFrancu** [comment]
Ok, am actualizat primul comentariu. Rămâne de văzut cât de lung va fi acel avertisment dacă modificarea afectează 50, 100, ... 1.000 de definiții structurate.

**Comment by LadislauStrifler** [comment]
Ok, atunci am o ideea mai bună. 
1. Clonarea în css a lui `.defWrapper` sub denumirea de `.defStructuredWrapper` și colorarea cu o nuață mai pală, să zicem #1ec2301f. (arată cam nasol)
sau
2. Implementarea unor [checkbox-uri bootstrap.](https://bootsnipp.com/snippets/featured/checkboxradio-css-only) care prin culoarea lor roșie vor avertiza că sunt definiții structurate. Celelalte, nestructurate, vor fi verzi. (mai simpatic)

Astfel, scăpăm de avertismente, iar moderatorul poate sări acele definiții și să revină manual la ele.

**Comment by CatalinFrancu** [comment]
De acord! Nu trebuie clonat stilul, putem doar pune în plus `.defStructuredWrapper` care schimbă culoarea.

Și aș mai adăuga și un checkbox pentru debifarea tuturor definițiilor structurate (ca să le poți rezolva întâi pe restul).

**Comment by LadislauStrifler** [comment]
Am făcut cu un flag `$showStructuredWrapper` implicit `false `pentru că `bits/definiton.tpl` e inclus din multe părți. De unde e nevoie, trebuie pasat parametrul pe `true` ca să coloreze fundalul.
Dar nu-mi prea place cum arată. :) Parcă e dezechilibrată toată lista.
Rămâne checkbox-ul. Aici, similar, vrei să pun o clasă în plus la toate, să zicem după `objCheckbox` pun `objCheckboxStructured` comandate de big boss `toggleAllStructured`?

**Comment by LadislauStrifler** [comment]
Vezi @CatalinFrancu că eu mă ocup de tichetul acesta. Sper să nu ne suprascriem. :)
Ar fi bine dacă mi-ai da și mie assign la unele tichete, ca să știm, să nu uităm. :)
Deocamdată am ajuns la varianta:
Țin minte toate ID-urile de definiții structurate modificate într-o matrice.
Dacă matricea nu este goală pun jos în dreapta un buton care va afișa lista (trimitere într-o pagină separată, cu fereastră separată, în caz că vrea să verifice linkurile).
La finalul finalului, dacă dă salvare îl duc direct pe moderator la lista respectivă. Asta poate fi chiar din prima salvare, dacă nu sunt atâtea definiții câte a filtrat.
Cam așa:
![git 717-bulkreplace](https://user-images.githubusercontent.com/16460700/38369280-0aba88cc-38f0-11e8-8843-fbf30344e57f.jpg)

**Comment by LadislauStrifler** [comment]
Dacă schimb ceva la definiția [POLI-](https://dexonline.ro/definitie/poli/1000265) m-am ras! Asociată cu 149 de intrări. :)
Întrebarea este: Cum ar trebui să fie alcătuită pagina de afișare a definițiilor structurate, adică ce informații ar trebui să vizualizăm? 
O succesiune de linkuri către intrări? Definiția mai are rost să apară, sau doar un id?

**Comment by MateiGall** [comment]
Ar fi util să se afișeze și definiția (cel puțin porțiunea care este supusă modificării), pentru ca moderatorul să vadă imediat dacă în arbore e de modificat ceva, sau a făcut structuristul modificarea și se poate trece mai departe.
[Eu am făcut modificări (corecturi) în arbori, fără a modifica și definițiile ... ca să nu mă încurc :-)]

**Comment by CatalinFrancu** [comment]
Stai, nu ne complicăm prea mult? Credeam că vrem doar ca moderatorul să vadă că vor exista modificări în definiții structurate și să aibă opțiunea să sară peste acelea. Deci funcțional ne trebuie doar un buton „debifează toate definițiile structurate”. Ca prezentare, colorarea bifei arată tare bine, dar s-ar putea să fie neclară fără un text.

O pagină separată pare prea mult, nu?

**Comment by LadislauStrifler** [comment]
Mi-a venit o idee și mai măreață, numai să nu mă luați la bătaie. :)
Tabela `EntryDefinition` să aibă un câmp boolean `definitionModified` (să zicem). În momentul modificărilor pe definiții (în cazul nostru cele bulk) acest câmp se pune pe true.
Lista intrărilor la care sunt asociate definițiile în cauză să cuprindă doar acele intrări care sunt terminate (status=4), deci structuristul (!sic) nu mai revine curând. În caz că se află în altă stare (nu știu ce înseamnă „așteaptă moderarea” - @MateiGall?), nu se vor emite avertismente. (o ba?)
Sunt o grămadă de definiții asociate intrărilor neterminate. Unele nici n-au fost parcurse întrucât au fost făcute automat, altele sunt în lucru. Definițiile să fie marcate cu o semnalizare de fundal (dar nu neapărat - poate fi o icoană după linkul care comută starea structurării), în lista de la editarea intrării.
Deocamdată, lista care se va afișa la finalul înlocuirilor în masă cuprinde toate intrările și arată așa:
![git 717-bulkreplacestructured 1](https://user-images.githubusercontent.com/16460700/38435358-1315938c-39da-11e8-835f-fbb828afa613.jpg)

**Comment by MateiGall** [comment]
> nu știu ce înseamnă „așteaptă moderarea”

@LadislauStrifler Această stare a fost gândită pentru a fi utilizată de structuriști în primă fază, urmând ca un moderator să verifice și să treacă intrarea în stare „terminată”. Eu am trecut la „terminate” cam toate intrările structurate, pentru că nu le mai verifică (în principiu) nimeni. Au rămas în „așteptare” câteva cu probleme, sperând la o clarificare din partea celorlalți.
Oricum, o veritabilă stare „terminată” nu va exista practic niciodată, deoarece apar noi surse (iar unele vechi nu știm încă cum să le tratăm).

**Comment by LadislauStrifler** [comment]
Eventual am putea colora legăturile către pagina de editare conform status-ului intrării. `primary`/`danger` = structurat, `info`/`success` = neînceput, `warning` = în lucru. Pare cam curcubeu. :)
![git 717-bulkreplacestructured 3](https://user-images.githubusercontent.com/16460700/38440609-a19ce01e-39ea-11e8-89f1-b5ae855458bf.jpg)

**Comment by MateiGall** [comment]
Nu prea are importanță „curcubeul” dacă informația ajută. Oricum, unealta e folosită de doar câțiva moderatori...

**Comment by LadislauStrifler** [comment]
Bun! Treaba nu e chiar simplă. Trebuie rescris mai mult decât am anticipat pentru a soluționa prima cerință. 
Se poate întâmpla ca înlocuirea să survină în comentarii. În cazul acesta `diff`-ul poate arăta așa:
```AMPL
tîrîți{{{-târâți→tîrîți/40545-}{+tîrîți→tîrîți/40545+}}}
``` 
asta pentru că nu am lăsat spații în comentariu. Șirul ar trebui să ducă la:
```html
<del>târâți→tîrîți/40545</del><ins>tîrîți→tîrîți/40545</ins>
```

dar în momentul de față extragerea notei de subsol este defectuoasă. Nu ia în considerare `}}}` la final și o ia pe arătură. Am rezolvat, dar...
nici `FootnoteHtmlizer::htmlize` nu este pregătit pentru sintaxa:
```AMPL
{-târâți→tîrîți/40545-}{+tîrîți→tîrîți/40545+}
``` 
pentru că extrage poziția ultimului `/` și rupe șirul înainte de a se încheia cu `+}`. 
N-ar fi un capăt de țară, am putea extrage ceea ce e numeric din subșirul de după `/` pentru `$f->userId`, apoi cu înlocui ambele ocurențe și pregăti șirul în consecință, cu anumite derogări/restricții, pentru afișare, respectiv salvare.
Concluzie:
Cât privește comentariile, eu cred totuși că acestea ar trebui cumva evitate în `bulkReplace`. Eventual, pe mai târziu,  făcută o opțiune „include comentarii”, creând un parametru `$showFootnotes` pentru afișarea acestora. 
Ar mai fi pasajele ▶◀, care nici ele n-ar trebui alterate; oricum nu se văd în `diff` decât în cazul în care modificăm logica buclei care folosește `Constant::HTML_PATTERNS`.

**Comment by MateiGall** [comment]
Menționez aici că la structurarea exemplelor din DLRLC eu am păstrat ortografia din original în porțiunea „citată” (scrisă cu italice), dar am înlocuit **î** cu **â** și **sînt** cu **sunt** în porțiunile „adăugate” (între paranteze drepte).

Având în vedere că aceste două tipuri de ortografie se regăsesc în cadrul aceluiași sens, ar trebui să se decidă dacă:

1. adoptăm o ortografie globală (veche) - fiind necesară o corectură a definițiilor structurate;
2. păstrăm stilul adoptat de mine - necesitând un tratament diferit în cazul corecturilor în masă.

Eu n-am o preferință fermă, dar ... aș vrea să știu cum procedez în continuare.
Dintr-o discuție mai veche am înțeles că în final vom adopta ortografia actuală în toată structurarea, prin urmare pot continua varianta 2. Niște precizări ar fi utile (ca să le adaug și în ghid).

**Comment by LadislauStrifler** [comment]
@CatalinFrancu nu știu la care propuneri te referi. La cea cu booleanul pe `EntryDefinition` sau la capturile de ecran. 
Dacă la cele din urmă, no brublem sunt făcute!
Dacă e cea cu booleanul, atunci la ce-mi folosește asocierea? La rescrierea acelei valori `modified`?

**Comment by CatalinFrancu** [comment]
La varianta cu booleanul, voiam să explic că multe asocieri derivă din clasa abstractă `phplib/models/Association.php` (cum ar fi `EntryDefinition`, `EntryLexeme`, `LexemSource`...). Iar acea clasă „știe” deja că rolul ei principal este să asocieze două obiecte, dar moștenitorii pot avea și câmpuri în plus.

Hm, dar de ce am nota acolo informația de modificare? Nu e ceva ce ține strict de definiție? De exemplu, să păstrăm un câmp `structuredTime` data când a fost marcată ca structurată. Dacă `modDate > structuredTime`, înseamnă că definiția a fost modificată ulterior.

**Comment by LadislauStrifler** [comment]
Merge și cu `structuredTime`, dar nu mai bine `structuredDate`? Să fim consecvenți. :) Dar în acest caz nu devine superfluu `structured` = 0/1? că `structuredDate` mă gândesc că va fi implicit `null`.

**Comment by CatalinFrancu** [comment]
Ok, `structuredDate` să fie. Putem renunța la `structured` atunci, dar bifa în interfața grafică trebuie să existe în continuare. Dacă editorul o debifează, atunci `structuredDate` revine pe 0 sau `null`, nu?

**Comment by LadislauStrifler** [comment]
Ah, da! Poate fi și 0 implicit (pare logic, fiind `int`), deci revine pe zero. :)

**Comment by LadislauStrifler** [comment]
Dacă nu implementăm o nouă librărie maleabilă de `Diff`, înlocuirile `â` în `î` din cadrul comentariilor vor arăta așa în definiție:
````AMPL
{-tîrîți{{târâți→tîrîți/40545}} -}{+tîrîți{{tîrîți→tîrîți/40545}} +}
````

...în consecință, afișarea modificărilor în cadrul definițiilor este viciată, apărând două note de subsol:
````html
<del>tîrîți<sup class="footnote" data-original-title="" title="">[1]</sup> </del>
<ins>tîrîți<sup class="footnote" data-original-title="" title="">[2]</sup> </ins>
````

iar html-ul notei de subsol nu evidențiază modificarea.
Dacă doar adăugăm `{` și `}` la caracterele de `trunchiere` arată și mai rău:

````AMPL
{{{-târâți→tîrîți/40545}} -}{+tîrîți→tîrîți/40545}} +}
````

... ceea ce duce la afișarea total eronată a definiției:
````html
tîrîți<sup class="footnote" data-original-title="" title="">[1]</sup> -}{+tîrîți→tîrîți/40545}} +}
````

Noua librărie `Diff` trebuie să permită ciopârțirea șirului la fiecare caracter de trunchiere, nu să le lipească, așa cum face actualmente. De abia apoi vom putea evidenția schimbarea în cadrul notei de subsol.

**Comment by CatalinFrancu** [comment]
N-am înțeles exact exemplul, dar înțeleg concluzia. Sigur, căutăm o bibliotecă Diff mai extensibilă.

**Comment by LadislauStrifler** [comment]
Închidem aici?

**Comment by CatalinFrancu** [comment]
Da, ai făcut mult peste cerințele originale! :+1:
