### ISSUE TITLE
Lexemele fragment neasociate duc la pagina principală

### ISSUE THREAD

**Issue by LadislauStrifler** [dexonline/dexonline#721]
În momentul căutării unor forme de lexem, să zicem [\*pedal\*](https://dexonline.ro/definitie/*pedal*), se afișează ca link: [sesquipedale (specie de plante)](https://dexonline.ro/lexem/sesquipedale/237506), lexem neasociat cu nicio intrare, fiind fragment.
1. Ori lexemele fragmente n-ar trebui să facă parte din lista returnată la căutare
2. Ori lexemele fragmente ar trebui asociate cu intrările în cauză (nu cred că e o idee bună pentru că **`lui`** ar trebui asociat cu o grămadă de intrări)
3. Ori logica de redirecționare, de fapt legătura de sub `sesquipedale (specie de plante)` să ducă la intrarea [Angraecum sesquipedale](https://dexonline.ro/lexem/Angraecum%20sesquipedale/283839) (tind să cred că e la fel de proastă idee ca No.2)
4. altă idee

Pentru mine rămâne doar 1.

**Comment by MateiGall** [comment]
Și eu aș opta pentru 1.

În schimb, ca (fost) scrabblist - poate e utilă și rebusiștilor -, mi-aș dori o listă cu toate formele flexionare corespunzătoare (pedalam, pedalelor, pedaleze, pedalistă etc.).

**Comment by CatalinFrancu** [comment]
Listarea formelor flexionare parcă ar sta mai bine separat de căutare (poate chiar pe pagina de scrabble). Ideea e că creează multă redundanță, zeci de cuvinte care ar fi legături spre aceeași intrare. Deci nu aș face asta varianta implicită. Ar putea fi cel mult o bifă în plus la căutarea avansată, dar și acolo e bine să fim cumpătați, să nu încărcăm formularul.

Dacă vrei deschide un tichet, cu ce alte cerințe ar mai fi (poate și lungimea să fie un parametru? poate să caute doar prin LOC?).

**Comment by MateiGall** [comment]
Am deschis #722, dar nu e nicio grabă.
