### ISSUE TITLE
Îmbunătățiri la editarea arborilor

### ISSUE THREAD

**Issue by MateiGall** [dexonline/dexonline#724]
- [x] Buton suplimentar (colorat distinct) pentru „**adăugare exemplu**” având ca efect adăugarea unui subsens marcat „**exemplu**”, dacă sensul de pornire este diferit. În caz contrar efectul va fi același cu cel al butonului „**adaugă sens**”.

- [x] La apăsarea butoanelor de adăugare (sens, subsens, exemplu), activarea implicită a zonei de editare (plasarea cursorului în această zonă).

- [x] La apăsarea butoanelor personalizate pentru „**surse**” și „**etichete**”, activarea implicită a zonei de editare (plasarea cursorului în această zonă).

- [x] La autocompletarea câmpului „**relații**” să se elimine lexemele cu majusculă (nume proprii) sau să fie listate după cele comune, chiar dacă acestea au și o descriere.

- [x] La autocompletarea câmpurilor „**surse**” și „**etichete**” să se afișeze întâi cele care încep cu secvența tastată (ex. tastând „**s**” la surse, lista să înceapă cu Sinonime, nu cu DEX-S).

**Comment by CatalinFrancu** [comment]
Câteva observații:

* La (1) n-am folosit culori, ci iconițe. Să-mi spui cum ți se pare.
* La (4) am făcut pur și simplu câmpul case-sensitive. Deci _ion_ va returna doar cuvintele comune, iar _Ion_ doar numele proprii.
* La (5) în cazul surselor m-am băgat destul de adânc în mațele acelei biblioteci de selecție căutabilă. Să-mi spui dacă observi probleme!

**Comment by MateiGall** [comment]
- La (1) n-ar strica și o culoare (palidă, gălbuie...) pe buton. Ajută pentru cei cu vedere slabă.
- La (4) e ok, cu mențiunea că afișarea e mult mai lentă.

Mai adaug aici un punct.
- [ ] La unificarea arborilor și intrărilor, e posibil ca după selectarea destinației (destinațiilor), acțiunea să se poată finaliza și cu „Enter”? E mai comod (mâna e deja pe tastatură).

**Comment by CatalinFrancu** [comment]
> La (1) n-ar strica și o culoare (palidă, gălbuie...) pe buton. Ajută pentru cei cu vedere slabă.

Am făcut butonul de culoarea implicită pentru avertismente. Dacă preferi alta, folosește orice [color picker](https://www.google.com/search?q=color+picker) și dă-mi nuanța dorită. :-)

> Apăsarea butoanelor (inclusiv cele personalizate: surse, etichete) ar trebui să lase cursorul în acest câmp.

Acum am înțeles că tu doreai ca după alegerea unei surse personalizate să ajungi tot în editor! Citisem greșit inițial și puneam cursorul în cutia de surse (ca să poți imediat tasta numele altei surse). Am implementat corect acum.

> La unificarea arborilor și intrărilor, e posibil ca după selectarea destinației (destinațiilor), acțiunea să se poată finaliza și cu „Enter”? E mai comod (mâna e deja pe tastatură).

Merge cu Tab, apoi Enter. Acesta e mecanismul standard din HTML, de navigare între câmpuri folosind Tab. Îl modific dacă vrei, dar am vrut să mă asigur că știi despre mecanismul standard.

> Caseta de surse (inclusiv butoanele personalizate) nu s-ar putea muta pe un rând imediat după rândul de butoane „+sens, subsens etc.”? Mișcarea de trecere +sens -> surse -> editor ar fi mai naturală.

În general, asta se rezolvă cu o chestie numită `taborder` prin care spun în ce ordine sunt activate câmpurile când apeși Tab. Dar, pentru ca focusul să nu sară aiurea înainte și înapoi, e mai bine să așezăm și vizual în pagină câmpurile în ordinea în care dorești să le parcurgi. Deci ar fi ok așa?

* coloana stângă: surse, editorul de sens;
* coloana dreaptă: tipul, etichetele, relațiile.

**Comment by CatalinFrancu** [comment]
Ok, am rearanjat câmpurile. Să-mi spui cum ți se pare acum. Am observat că tu ai multe valori frecvente predefinite, am încercat să dimensionez corect coloanele.

**Comment by MateiGall** [comment]
Înțeleg că aranjamentul propus de mine (alinierea butoanelor în stânga) nu e posibil. Atunci poate o aliniere pe dreapta? Și etichetele între surse și tip.
Aș dori ca mișcarea de trecere de la +sens -> surse -> etichete să fie cât mai scurtă și cât mai „dreaptă”, fără plimbare stânga-dreapta. Probabil o să mai scot din butoane, acum e mai simplă și tastarea de când ai rezolvat autocompletarea...

**Comment by CatalinFrancu** [comment]
A, ba sigur că se poate, am implementat acum ordinea cerută. E mai bine? Singurul dezavantaj e că această așezare îl poate încurca pe un nou venit, care nu are valori predefinite și vede doar „+” în stânga și câmpurile în dreapta.

Am reparat și problema autocompletării lente la arbori, acum merge din nou instantaneu.

**Comment by CatalinFrancu** [comment]
Sigur, am implementat-o (puteam să jur că am făcut-o deja!).

**Comment by MateiGall** [comment]
Mai e o chestie care mă sâcâie.
Dacă după un exemplu apăs „+ sens” (sau subsens) ar trebui să comute tipul de pe „exemplu” pe „sens” (scutește clicul respectiv) păstrând indentarea. Se păstrează sursele de la exemplu.

Ar fi bine ca și adăugarea etimologiei, comentariului, diferențierii... să fie posibilă cu butoane dedicate (colorate diferit), cu setarea automată a tipului. Loc pe rândul de butoane e destul.
Mi-ar plăcea și o rearanjare a butoanelor: după primele 3 să vină săgețile, apoi cele două actuale și apoi eventual cele noi.

**Comment by CatalinFrancu** [comment]
> Dacă după un exemplu apăs „+ sens” (sau subsens) ar trebui să comute tipul de pe „exemplu” pe „sens” (scutește clicul respectiv) păstrând indentarea. Se păstrează sursele de la exemplu.

Nu-s sigur că am înțeles care e scenariul. Vrei să poți adăuga un subsens la un exemplu? Asta nu sună bine.

> Ar fi bine ca și adăugarea etimologiei, comentariului, diferențierii... să fie posibilă cu butoane dedicate (colorate diferit), cu setarea automată a tipului. Loc pe rândul de butoane e destul.

Le-am făcut să meargă. Momentan au aceeași culoare (și un pic estompată). Ești sigur că vrei patru culori? :-)

> Mi-ar plăcea și o rearanjare a butoanelor: după primele 3 să vină săgețile, apoi cele două actuale și apoi eventual cele noi.

Sper că am înțeles bine, este OK acum?

**Comment by MateiGall** [comment]
> Dacă după un exemplu apăs „+ sens” (sau subsens) ar trebui să comute tipul de pe „exemplu” pe „sens” (scutește clicul respectiv) păstrând indentarea. Se păstrează sursele de la exemplu.

>> Nu-s sigur că am înțeles care e scenariul. Vrei să poți adăuga un subsens la un exemplu? Asta nu sună bine.

Nu. Adaug un sens după un exemplu (pe același nivel, ca subsens al sensului cu exemplele). Când apăs „+ sens” rămâne bifat „exemplu”, ceea ce mă obligă la un clic suplimentar.

> Ar fi bine ca și adăugarea etimologiei, comentariului, diferențierii... să fie posibilă cu butoane dedicate (colorate diferit), cu setarea automată a tipului. Loc pe rândul de butoane e destul.

>> Le-am făcut să meargă. Momentan au aceeași culoare (și un pic estompată). Ești sigur că vrei patru culori? :-)

Da, mi-ar fi mai ușor să le disting. Cum nu prea mai sunt alți structuriși, cred că nu deranjează pe nimeni :)

> Mi-ar plăcea și o rearanjare a butoanelor: după primele 3 să vină săgețile, apoi cele două actuale și apoi eventual cele noi.

>> Sper că am înțeles bine, este OK acum?

Dacă ai putea lăsa butonul pentru exemple lângă „subsens” ar fi mai bine. Îl folosesc mult mai des decât pe ultimele trei.

**Comment by MateiGall** [comment]
Butonul „etimologie” adaugă pe nivel subsens, ar trebui să adauge pe nivel de sens.

**Comment by CatalinFrancu** [comment]
Pare că se adună multe reguli diferite și vom începe amîndoi să ne încurcăm în ele. :-)

* Dacă stau pe un sens și apăs butoanele sens/subsens, atunci se creează un frate/fiu.
* Dacă stau pe un sens și  apăs butoanele colorate, atunci se creează sensuri-fiu. Ca excepție, dacă  deja stau pe un sens de același tip cu butonul apăsat (de ex. stau pe un exemplu și apăs butonul „exemplu”), atunci se creează un sens-frate.
* Dacă stau pe exemplu și apăs „sens” sau „subsens”, atunci se creează un sens-unchi (frate cu părintele exemplului).

Ca să ilustrez complexitatea, iată un tabel cu comportamentul. Trebuie citit ca „dacă stau pe un sens de tip A și apăs butonul B, vreau să fie adăugat sensul C”. Tipul noului sens adăugat este întotdeauna dat de butonul B. Valoarea X înseamnă: Acest scenariu nu ar trebui să se întîmple în practică. De aceea, orice comportament este acceptabil și voi lua o decizie care să facă codul cît mai scurt.

| | sens | subsens | etimologie | exemplu | comentariu | diferențiere |
|-|-----|-----|-----|-----|-----|-----|
| sens | frate | fiu | frate | fiu | fiu | fiu |
| etimologie | X | X | frate | X | fiu | fiu |
| exemplu | unchi | unchi | X | frate | fiu | X |
| comentariu | unchi | unchi | X | X | frate | X |
| diferențiere | unchi | unchi | X | fiu | fiu | frate |

Am nimerit-o cît de cît? După ce stabilim comportamentul ideal, putem începe negocierile ca să ținem complexitatea la un nivel rezonabil.

**Comment by MateiGall** [comment]
Iată cum văd eu funcționarea: 

  | sens | subsens | etimologie | exemplu | comentariu | diferențiere
-- | -- | -- | -- | -- | -- | --
sens | frate | fiu | frate | fiu | Y | Y
etimologie | X | X | frate | X | fiu | fiu
exemplu | unchi | frate | X | frate | fiu | X
comentariu | unchi | frate | X | X | frate | X
diferențiere | unchi | frate | X | fiu | fiu | frate

Valoarea Y înseamnă că ambele valori frate/fiu ar fi posibile, dar nu e esențial, se pot muta ulterior, sunt cazuri rare (deocamdată); lasă cum e.
La ultimele 3 -> subsens aș prefera frate (cu modificarea bifei pe „sens”). Dacă după un exemplu urmează o expresie/locuțiune etc. care e tot fiu al sensului cu exemplul, ar trebui să rămân pe același palier. Nu văd de ce trebuie să mă treacă la „unchi”.
Sper că se înțelege (și e fezabil).

**Comment by CatalinFrancu** [comment]
Ok, aș zice că am implementat exact tabelul de mai sus. Sper că n-am stricat nimic. :-) N-am testat foarte mult partea de copiere a surselor, pentru că nu-mi mai amintesc exact cînd voiai să fie copiate sursele.
