### ISSUE TITLE
Expresii/sintagme de negăsit la căutarea cuvintelor componente

### ISSUE THREAD

**Issue by dan2468** [dexonline/dexonline#743]
> M-aș fi așteptat să fie găsită expresia [a pune batista pe țambal](https://dexonline.ro/definitie/a%20pune%20batista%20pe%20%C8%9Bambal/537356) atât la căutarea după [batista](https://dexonline.ro/definitie/batista) (lucru care se întâmplă), cât și după [țambal](https://dexonline.ro/definitie/%C8%9Bambal) (lucru care nu se întâmplă).
> 
> Trebuie făcute manual legături în baza de date pentru fiecare expresie, către definiția fiecărui cuvânt ce o compune (cum pare să sugereze #75)?

Edit: Scuze, văd acum că sunt afișate doar primele 20 de rezultate de la căutarea [țambal](https://dexonline.ro/definitie/%C8%9Bambal), trebuia să expandez ultimele 3 pentru a găsi expresia.

Voi deschide un _issue_ nou cu duplicarea butonului "arată toate definițiile" la sfârșitul paginii…

**Comment by CatalinFrancu** [comment]
Pare că te-ai prins că era într-adevăr vorba despre arătat toate definițiile. Ai dreptate, trebuie făcute manual legăturile. Din câte știu, în general sunt cam făcute!
