### ISSUE TITLE
Butonul "arată toate definițiile" ar trebui afișat și la sfârșitul paginii

### ISSUE THREAD

**Issue by dan2468** [dexonline/dexonline#744]
În cazul căutărilor cu mai mult de 20 de rezultate (e.g. [țambal](https://dexonline.ro/definitie/%C8%9Bambal)), se poate ușor crea impresia că nu există o expresie rară, dacă utilizatorul trece în revistă definițiile returnate și ajunge la sfârșitul paginii de rezultate fără a o găsi (mesajul „maximum 20 afișate” și butonul „arată toate definițiile” de sus nu atrag mult atenția, ceea ce e foarte OK).

Propun ca la sfârșitul paginii să fie din nou disponibil un buton de genul „Afișează și următoarele *3* definiții”, iar destinația lui să fie de forma `https://dexonline.ro/definitie/%C8%9Bambal/expandat#continuare` unde `continuare` este ancora la definiția nr. 21.
Sau poate e mai prietenos să se încarce automat rezultatele rămase la derularea paginii?

Ar trebui evidențiată lipsa unor definiții și în cazul în care utilizatorul caută cu `Ctrl+F` expresia într-o pagină cu rezultate parțiale (când riscă deci să nu o găsească).
Soluția simplă ar fi ascultarea de apăsări de taste (dar e prea aproape de un key logger), sau una mai puțin fiabilă ar fi detectarea schimbării verticale a viewport-ului când browser-ul afișează caseta de căutare.

**Comment by CatalinFrancu** [comment]
De acord cu butonul sau cu derularea automată / infinită. Nu am o opinie între cele două.

**Comment by CatalinFrancu** [comment]
M-am mai gândit. Parcă nu-mi mai place ideea cu derulare infinită. N-ai cum să obții lista completă **decât** dacă derulezi, nu știi dacă s-au încărcat următoarele 20 de rezultate sau toate etc.

Nici interferența cu Ctrl-F nu mi se pare o idee bună. Am mai văzut site-uri care interceptează Ctrl-F și invariabil constat că l-au reimplementat mai prost. Dacă îl interceptăm doar ca să detectăm că e nevoie să încărcăm restul de rezultate, s-ar putea să nu meargă bine. În Chromium am tot pățit că nu reindexează automat bucățile încărcate dinamic și nu știu care este politica (un clic în pagină **pare** să declanșeze reindexarea corectă, dar nu-s sigur).

Deci aș lăsa butonul la început + sfârșit. Acel buton, plus textul "maximum 20 afișate", sar destul de bine în ochi.
