### ISSUE TITLE
Docker & un framework mai bun

### ISSUE THREAD

**Issue by rennokki** [dexonline/dexonline#758]
Any thoughts about Docker? Tree-ul proiectului este destul de vechi comparativ cu metodele actuale de infrastructură și ineficient la instalare. Sunteți deschiși la un PR pentru Docker?

Asta deschide mai multe porți, printre care și pornirea de containere pentru ElasticSearch, poate eficientizează căutarea.

**Comment by CatalinFrancu** [comment]
Sigur, nu avem nimic împotrivă, cîtă vreme nu interferează cu instalarea „normală”. @david-batranu are [niște instrucțiuni](https://github.com/david-batranu/dexonline-docker) care, din cîte știu, merg perfect. E nevoie de mai mult?

**Comment by rennokki** [comment]
Păi modificarea asta de infrastructură o să afecteze instalarea normală. Proposal-ul este pentru modificarea infrastructuri și pentru production. Mă gândeam să ruleze strict pe containere și eventual poate fi folosit horizontal scaling cu HAProxy și Swarm & K8s pentru orchestration.

Probabil că e o schimbare drastrică venită într-un issue mic, dar urmăresc ca această schimbare să fie bună și de actualitate cu tendințele în DevOps-ul actual. :small_airplane:

**Comment by david-batranu** [comment]
Părerea mea de 2 bani: asta pare a genul de schimbare de dragul schimbării. Dexonline are, momentan, o arhitectură destul de simplă, robustă și ușor de menținut.

Complicarea arhitecturii adăugînd Docker, Kubernetes, Rancher, etc. are sens (poate) pentru siteuri mai mari cu mai multe "moving parts". Dexonline, deși poate "invechit" tehnologic, face ce face foarte bine și eficient.

Singurul motiv pentru care există acel repo este mania mea pentru distro-hopping. După un timp m-am săturat să configurez a N-oară Apache și MariaDB.
