### ISSUE TITLE
Ordonare listă abrevieri

### ISSUE THREAD

**Issue by LadislauStrifler** [dexonline/dexonline#760]
Extragerea listei de abrevieri pentru marcarea lor în definiție trebuie să se facă după un număr de ordine în lista abrevierilor. Unor abrevieri trebuie să li se acorde prioritate și verificate înaintea celorlalte, cum ar fi: 
1. `G-D:` înaintea lui `D:` în _MDA2_, 
2. `s. pr.` înaintea lui `pr.` și `s.` în _Ortografic 01_

pentru că la cea de-a doua abreviere sistemul nu va mai ajunge niciodată din moment ce o înhață pe prima.
Astfel:
1.  `G-D:` (genitiv-dativ) va fi marcat defectuos ca `G-#D:#`
2.  `s. pr.` (substantiv propriu) va fi marcat defectuos ca `#s.# #pr.#` (substantiv) (pronume) 

Dacă la _MDA2_ s-ar putea rezolva trunchierea abrevierii `G-#D:#` prin definirea lui `G` (inexistent în momentul de față), la _Ortografic 01_ nu s-ar putea defini `#pr.#` pentru că aceasta corespunde abrevierii **_pronume_**.
Nu văd o soluție de compromis, pentru că nu doar moderatorul analizează definiția, ci și scripturi viitoare. Moderatorul ar putea sesiza eroarea și modifica manual încadrarea cu diezi, dar scriptul mi-e că nu prea are cum să decidă.

**Comment by CatalinFrancu** [comment]
Abrevierile sînt deja examinate în ordinea descrescătoare a numărului de cuvinte, deci `s. pr.` e tratat și marcat înainte de `s.` și de `pr.`. Am pus într-o definiție oarecare din Ortografic '01 textul `mama s. pr. tata` și mi-a marcat corect `#s. pr.#`. Tu observi altceva?

La `G-D` într-adevăr exista bugul că cratima nu era considerată ca separator de cuvinte, deci `G-D` era considerat ca un singur cuvînt și nu era tratat înaintea lui `D`. Am corectat asta, acum pare că se comportă corect.

Am căutat cu înlocuitorul în masă `G-#D#` și `#G#-#D#`, nu par să existe ocurențe.

**Comment by LadislauStrifler** [comment]
Din moment ce am scris am observat. Acum nu mai observ.
Dacă mi-a scăpat ceva redeschid.
Mulțumesc!
