### ISSUE TITLE
Fragmente lexeme compuse

### ISSUE THREAD

**Issue by MateiGall** [dexonline/dexonline#765]
Unele fragmente ale lexemelor compuse se formează prin trunchierea unui lexem (ex. vino-ncoace).
În acest fel, lexemul compus nu poate fi etichetat ca atare, sistemul negăsind fragmentul (_-ncoace_).
Ca urmare, intrarea **vino-ncoace** nu va fi afișată la căutarea lui **încoace** (decât dacă se adaugă și acest lexem la intrarea compusă).

Ar trebui ca sistemul să permită formarea fragmentelor prin trunchierea unui lexem (de regulă prima sau ultima literă).

Chestiunea se intersectează oarecum și cu problema căutărilor prin clic pe un fragment (parcă este un tichet pe tema asta).

**Comment by LadislauStrifler** [comment]
Cred că lexemele ar trebui să aibă „particularitatea” de a fi ecthlipsabile. Adică ar putea permite acea fuziune cu cuvântul anterior. În general e vorba de cele cu în-. 
Astfel, paradigma s-ar îmbogăți cu acel fragment de care are sistemul nevoie la compuse.

**Comment by CatalinFrancu** [comment]
Bun! Păi hai să colectăm toate scenariile posibile.

### La început de cuvînt

1. Cred că partea asta nu depinde de paradigmă. Trunchierea unui cuvînt este aceeași pentru toate formele flexionare. Zic bine? Sau există cuvinte care se trunchiază doar la anumite forme?
1. Cîte litere se trunchiază? Întotdeauna una? Pot fi și mai multe, deci _abcde_ să devină _cde_? Mai interesant, pot exista mai multe scenarii pentru același cuvînt? Deci _abcde_ să poată deveni și _bcde_ și _cde_?

### La sfîrșit de cuvînt

Văd treaba așa:

1. Operăm la nivel de model + flexiune. Nu putem marca cu totul flexiunea masculin, n.-ac. singular articulat ca elidabilă, căci _iepurele_ nu elidează. Deci în [editorul de modele](https://dexonline.ro/admin/editModel.php?id=118) adăugăm o bifă nouă „poate elida”.
1. Trebuie și o bifă pe lexem, iar elidarea se întîmplă doar dacă flexiunea o permite **și** lexemul o permite. Astfel, modelul de prepoziție (I12) în general permite elidarea, dar doar pentru lexemul _cu_, nu și pentru _spre_.
1. Aceeași întrebare ca mai sus: putem elida mai multe litere? Sau scenarii multiple pentru același cuvînt?

**Comment by MateiGall** [comment]
Pe moment nu-mi amintesc cazuri cu elidarea mai multor litere sau cu scenarii multiple.
Aș zice să încercăm rezolvarea pentru o singură literă și vedem apoi dacă ne lovim și de alte situații.

**Comment by CatalinFrancu** [comment]
La început de cuvînt există cazul _-l_, care presupun că este elidarea lui _îl_ (acuzativul lui _el_).

**Comment by CatalinFrancu** [comment]
_v-un_ și _v-o_ par să fie contrageri în interiorul cuvîntului, nu? Acelea pot fi pur și simplu create ca variante.

Ar mai fi și _-s, -i_ de la verbul _a fi_ _(nu-s, nu-i)_ și _își_ de la _sine_. Pare că regula 1 la început de cuvînt depinde ocazional și de forma flexionară. O întrebare este: la început de cuvînt se trunchiază vreodată altă literă decît _î_? În funcție de asta văd două implementări:

1. Dacă doar _î_ se trunchiază, atunci ne trebuie doar o bifă pe lexemele care se pot trunchia și se trunchiază toate formele flexionare care încep cu _î_: _îs_ și _îi_ pentru a fi, _își_ pentru sine etc. Unele lexeme cu accentul pe _î_ nu se trunchiază, deci nu poartă bifa: _înger_, _însă_ (oare?).
1. Dacă pot fi și alte litere trunchiate, atunci ne trebuie bife pe model + flexiune + forma exactă (ex. doar _își_ dintre toate cele de G.-D.) și bife pe lexem. Se trunchiază acele forme permise și de model, și de lexem.

La final de cuvînt oricum este necesară implementarea 2, căci pot elida diverse litere (_-l, -u_, poate și altele).

**Comment by LadislauStrifler** [comment]
Ar mai fi: _îmi_ (eu), _îți_ (tu)

Nu vreau să fiu rău, dar știi că discuția `cu-n` nu e încheiată. :)

**Comment by MateiGall** [comment]
> Ar mai fi: îmi (eu), îți (tu)

Cred că unele din astea nu trebuie tratate în mod special, fragmentele (_mi_, _ți_ etc.) regăsindu-se și ca formă separată în paradigmă.
Ex. clic pe **-mi** din **nu-mi** duce și la **mi** (nota) și la **eu** (pron.).

**Comment by MateiGall** [comment]
> Dar, depinde unde dai clic. :) Dacă dai în silabație? de exemplu:

Nu cred că cineva caută să afle semnificația ... unui fragment-silabă :-)
Sper că nu e cazul să ne ocupăm de toate silabele și de toate posibilitățile de a da clic undeva...

> Apropo: N-ar trebui implementată cu această ocazie și particularitatea gerunziului de a primi vocala de legătură -u-, pentru conexiunea cu pronume neaccentuate? exemplu: lăsându-și

Asta da. N-am tratat cazul, pentru că nu ne interesa la scrabble :-)

**Comment by LadislauStrifler** [comment]
Nu doar gerunziul primește vocala _-u-_, ci și participiul în perfectul compus. ex.: `dusu-s-a, plânsu-mi-s-a`

**Comment by CatalinFrancu** [comment]
Pentru referință, lista completă a lexemelor care **nu** încep cu _î_ și au flexiuni care încep cu _î_ este: _eu, tu, el, fi, sine, vrea_.

**Comment by MateiGall** [comment]
Cred că avem și situații mai complexe, care nu intră la „lexeme compuse” (ex. 'neața), dar ... n-ar fi rău să le rezolvăm măcar pe cele mai simple și mai frecvente.

**Comment by CatalinFrancu** [comment]
Și eu zic că, dacă în rest rămîn cîteva zeci de situații, putem crea lexeme și/sau modele noi pentru ele.

**Comment by CatalinFrancu** [comment]
- [ ] Script care să unifice intrările create pentru lexemele dependente cu afereză: deci _mpăcare_ cu _împăcare_ și _mpăcat_ cu _împăcat_.

**Comment by CatalinFrancu** [comment]
Pare că a a rămas o singură chestie de implementat aici: adăugarea lui _-u-_ la gerunzii și participii. Cîteva întrebări:

1. Fenomenul are vreun nume?
2. Este valabil pentru toate verbele? Pare că da.
3. Se întîmplă și la alte părți de vorbire?

Va fi un pic complicat la participiile VT, căci trebuie să-i explic sistemului că _dorit_ este adjectiv, dar _doritu-_ nu.

**Comment by LadislauStrifler** [comment]
1. Fenomenul nu cred că se numește nicicum. Pentru encliză, în stadiul actual al limbii, (citind mai mult despre aceasta) de fapt este `păstrarea` vechiului _u_ final în vederea uniunii fonetice. 
„1. Presentandu nationei una carte de insemnatatea acestei-a...”
„... limb'a unui poporu **_fiendu_** productulu acellui poporu...”
„d'intre instrumentele de musica, unele canta, _**suflandu**_ in elle; altele canta, _**facundu**_ se vibre alle loru corde” 
„circanea avis = passere ce sbora in cercu, **_invertinduse_**” (sic!)
„_bolta elicoide_ sau _bolta in vertetiu_, care se inaltia **_invertindu-se_** in giurulu unei asse, ca bolt'a unei scare”
2. Cu amendamentul că trebuie să accepte gerunziu sau participiu.
3. Nu știu

**Comment by LadislauStrifler** [comment]
1. și participii
„cartile noului testamentu s’au **_scrissu_** in limb’a greca”
„**_dussu-s’a_** careva d’in voi, se veda cumu mai e unchiului?”
„Socrate a **_dedussu_** filosofi'a d'in ceru si a **_introdussu-a_** in casele omeniloru;”
„In femininulu _ua_, vocalea _u_ nascuta din _l_, se confunde cu _a_ scurtu in _o_. Scrierea acellei vocali devine superflua, cându verbulu precedente termina in _u_, precumu in : _rogu-a_, **_am rogatu-a_**, _rogandu-a_.”

**Comment by CatalinFrancu** [comment]
Am rezolvat și formele lungi. Am ales să definesc două flexiuni nou, _Participiu pasiv lung_ și _Gerunziu lung_. Asta facilitează identificarea formelor flexionare care trebuie tratate diferit (colorate cu maro, sufixate cu cratimă și nu se flexionează mai departe ca adjectiv).

Am modificat automat toate modelele pentru verb. Pentru fiecare formă scurtă am creat una lungă prin adăugarea unui _-u_ final. Accentul (cred) nu este afectat.

Mai sînt de regenerat paradigmele pentru ~11.000 de verbe, asta mai durează un pic.
