### ISSUE TITLE
Afișare infinitiv lung, participiu.

### ISSUE THREAD

**Issue by MateiGall** [dexonline/dexonline#768]
Cred că afișarea acestor elemente alături de lexemul principal (în tabul sinteză, vezi [îndumica](https://dexonline.ro/definitie/%C3%AEndumicare)) nu e adecvată.
E suficient că la căutarea unui astfel de IL / PT se afișează intrarea verbului.
Explicațiile se referă la verb, nu la infinitivul / participiul respectiv.
Se poate adăuga eventual un mesaj explicativ.

**Comment by CatalinFrancu** [comment]
Parcă am mai avut discuția asta, dar nu mai știu dacă am hotărît ceva, și ce.

Cred că o soluție bună ar fi:

1. Separăm intrările pentru verb, infinitiv lung, participiu.
1. Le asociem pe toate cu același arbore, cel pentru infinitiv.
1. Dacă infinitivul lung și participiul au și sensuri proprii (de ex. _intrare_), vor avea arbori suplimentari pentru acelea.

**Comment by MateiGall** [comment]
> 1. Separăm intrările pentru verb, infinitiv lung, participiu.
> 2. Le asociem pe toate cu același arbore, cel pentru infinitiv.

Situația actuală este conformă cu 1. și 2.

> 3. Dacă infinitivul lung și participiul au și sensuri proprii (de ex. _intrare_), vor avea arbori suplimentari pentru acelea.

Aici intrările au arbori proprii, fără a mai fi asociate și cu arborele infinitivului. E normal să fie așa, au definiții proprii.

Dar în cazurile 1. și 2. nu văd de ce în sinteză trebuie să apară și formele de IL / PT, definițiile nefăcând referire la acestea.
Eventual să afișăm separat aceste forme (ascunse sub un mesaj), cu link la fiecare către paradigma respectivă (care nu e vizibilă în tabul _conjugări_ al verbului).

**Comment by CatalinFrancu** [comment]
Ah, corect! Da, nu e fantastic că se întîmplă așa. În prezent, regula este cam așa:

* Prima apare descrierea arborelui
* Apoi apar toatele lexemele asociate cu toate intrările asociate cu arborele.
* Elimin duplicatele.
* Pun variantele în gri (le estompez).

Pare că am făcut asta intenționat în aabbea5c79e73a587e3349bffd53fcc8930721d7, dar nu mai știu de ce. Văd o discuție pe e-mail în acea perioadă („Intrări infinitiv și participiu”, începută pe 15.08.2017), dar nu pare chiar relevantă.

Evident, soluția cea mai directă e să șterg lexemele și să las strict descrierea arborelui. Dar mă sîcîie că nu mai știu de ce am implementat sistemul curent. :-)

**Comment by MateiGall** [comment]
Cred că totul a pornit de la afișarea intrărilor pentru IL / PT, care nu au definiții proprii și nici arbori. Făcând asocierea definițiilor / arborilor de la infinitiv la aceste intrări, lexemele asociate apar și la verb.
Cred că simpla eliminare a lexemelor cu model IL sau PT ar rezolva problema.

Poate că și la căutare ar trebui modificat ceva. Căutarea unei forme flexionare a IL / PT să ducă la intrarea verbului (ca în prezent; nu știu dacă modificările preconizate strică ceva).

**Comment by CatalinFrancu** [comment]
> Cred că simpla eliminare a lexemelor cu model IL sau PT ar rezolva problema.

Da, dar nu aș vrea să fac cazuri particulare prin cod: „afișează lista cu lexeme, dar șterge-le pe cele IL și PT”. Parcă aș prefera să șterg toatele lexemele, căci se aliniază și cu principiul de la intrări: nu punem în aceeași listă părți de vorbire diferite. Atunci arborele s-ar numi doar „dumica”. Asta e bine cînd cauți „dumica”, dar te poate nedumeri cînd cauți „îndumicare” sau chiar „dumicare”. Oare cît de rău o fi?

> Căutarea unei forme flexionare a IL / PT să ducă la intrarea verbului (ca în prezent; nu știu dacă modificările preconizate strică ceva).

În prezent nu cred că-i așa! [îndumicată](https://dexonline.ro/definitie/îndumicată) duce la îndumicat. Dar asta poate fi suficient, căci definițiile sînt asociate cu intrările pentru V, IL și PT.

**Comment by MateiGall** [comment]
>> Cred că simpla eliminare a lexemelor cu model IL sau PT ar rezolva problema.

> Da, dar nu aș vrea să fac cazuri particulare prin cod: „afișează lista cu lexeme, dar șterge-le pe cele IL și PT”. Parcă aș prefera să șterg toatele lexemele, căci se aliniază și cu principiul de la intrări: nu punem în aceeași listă părți de vorbire diferite. Atunci arborele s-ar numi doar „dumica”. Asta e bine cînd cauți „dumica”, dar te poate nedumeri cînd cauți „îndumicare” sau chiar „dumicare”. Oare cît de rău o fi?

Adică să elimini și variantele? De ce?

>> Căutarea unei forme flexionare a IL / PT să ducă la intrarea verbului (ca în prezent; nu știu dacă modificările preconizate strică ceva).

>În prezent nu cred că-i așa! îndumicată duce la îndumicat. Dar asta poate fi suficient, căci definițiile sînt asociate cu intrările pentru V, IL și PT.

Nu chiar; _îndumicată_ duce la paradigma lexemului _îndumicat_, dar în sinteză este arborele **dumica**,
cu variantele lui. Informațiile sunt complete: forma provine de la participiu, iar definițiile explică infinitivul.
În schimb afișarea lui _îndumicat_ în denumirea arborelui **dumica** nu pare potrivită.

**Comment by CatalinFrancu** [comment]
> Adică să elimini și variantele? De ce?

Nu-nu, mă refeream strict la tabul _sinteză_, la titlul arborelui. Acum este _dumica  îndumicare  îndumicat  dumeca  dumnica  îndumica_, propuneam să-l facem doar _dumica_ (sau orice valoare pui în descrierea arborelui).

> Nu chiar; _îndumicată_ duce la paradigma lexemului _îndumicat_, dar în sinteză este arborele **dumica**, cu variantele lui. Informațiile sunt complete: forma provine de la participiu, iar definițiile explică infinitivul. În schimb afișarea lui _îndumicat_ în denumirea arborelui **dumica** nu pare potrivită.

A, te refereai la arbori! Atunci nu, modificările nu ar afecta asta.

**Comment by MateiGall** [comment]
>> Adică să elimini și variantele? De ce?

> Nu-nu, mă refeream strict la tabul sinteză, la titlul arborelui. Acum este _dumica îndumicare îndumicat dumeca dumnica îndumica_, propuneam să-l facem doar _dumica_ (sau orice valoare pui în descrierea arborelui).

Păi unde mai vedem variantele în sinteză? Păstrăm doar afișarea lor și a paradigmelor prin apăsarea butonului în tabul conjugări?
Eu mă gândeam să afișăm titlul arborelui: _dumica dumeca dumnica îndumica_,

**Comment by CatalinFrancu** [comment]
Ok, am implementat ascunderea lexemelor IL/PT. Nu prea-mi convine că avem încă un caz particular, dar într-adevăr nici lipsa tuturor variantelor din tabul sinteză nu era o soluție.

**Comment by MateiGall** [comment]
Ok.
Poate că ar trebui adăugate niște mesaje explicative la afișare, ca să înțeleagă utilizatorul de ce la căutarea lui _îndumicare_ vede definițiile verbului **dumica** (și în tabul sinteză este arborele acestui verb).
