### ISSUE TITLE
Lexeme cu apostrof literal (o'clock)

### ISSUE THREAD

**Issue by CatalinFrancu** [dexonline/dexonline#772]
Trebuie făcută sintaxa `\'` să meargă și în lexeme la fel cum merge în definiții (să nu folosească apostroful pentru accent tonic).

**Comment by CatalinFrancu** [comment]
@MateiGall, Acum ar trebui să meargă (cu `\'`). Am pus la loc lexemul _five o'clock_ în modelul N24, iar lexemele-fragment _five_ și _o'clock_ cred că pot fi șterse.

**Comment by CatalinFrancu** [comment]
Pare să fie din cauză că, la căutarea cu autocompletare a intrărilor, de fapt sistemul caută prin formele lexemelor asociate. Mi se pare că am avut un motiv pentru asta. Deci caută _shimmy_ sau _volens_ sau alt lexem din acea intrare. E un pic neintuitiv, știu. :-)

**Comment by MateiGall** [comment]
Aha! Păi ca să fie mai intuitiv, o să creez și o să asociez intrării un lexem „Lexeme neasociate”. Cred că nu deranjează în altă parte.
