### ISSUE TITLE
API-ul nu mai functioneaza

### ISSUE THREAD

**Issue by revolter** [dexonline/dexonline#774]
https://dexonline.ro/definitie/test/json returneaza HTML in loc de JSON

**Comment by CatalinFrancu** [comment]
Oops! Am schimbat niște chestii și aparent am ajuns la 10 parametri în rewrite-ul de URL, ceea ce aparent [nu e permis](https://stackoverflow.com/a/10982305/6022817). Scuze că n-am testat!

**Comment by revolter** [comment]
Nici o problema! Testez eu API-ul aproape zilnic. 😃 Nu intelegeam de ce nu imi mai merge bot-ul si initial am crezut ca e de la Telegram sau de la mine. Mersi mult ca ai rezolvat asa repede. ❤️
