### ISSUE TITLE
Reparsare DEX '09

### ISSUE THREAD

**Issue by CatalinFrancu** [dexonline/dexonline#777]
Unele definiții nu au fost parsate; de încercat din nou și văzut unde crapă.

**Comment by MateiGall** [comment]
Pentru îmbunătățirea procesului de structurare ar fi bine ca:

1. Diferențele dintre ediții să fie vizibile în pagina de editare a intrării (se evită trecerea prin pagina de editare a definiției).
2. În cazul definițiilor identice să se aplice automat eticheta noii ediții pe toate (sub)sensurile unde există eticheta ediției precedente. Acest proces ar trebui rulat o dată, apoi făcută etichetarea în momentul adăugării noilor definiții. Dacă intrarea (și definiția din ediția precedentă) a fost structurată, se va bifa totodată și noua definiție ca „structurată”.
3. În pagina de editare a arborelui să existe posibilitatea selectării multiple a (sub)sensurilor, cu aplicarea simultană a unei etichete (de regulă o sursă).

_[Probabil trebuia să deschid un tichet separat cu aceste probleme]_

**Comment by CatalinFrancu** [comment]
a949e9f4e05239fe287247aaa4536e87179ecf4b

**Comment by CatalinFrancu** [comment]
Am adus la zi și rulat din nou scriptul. A modificat [17.399 de arbori](https://gist.github.com/CatalinFrancu/484516bdbe259a1a0671d4b833f7e04b)!

**Comment by CatalinFrancu** [comment]
M-am uitat și pe cele 3 cerințe, am nevoie de niște clarificări.

1. Parcă diferențele sînt rezonabil de vizibile deja, nu? Vezi [musti (vb.)](https://dexonline.ro/editEntry.php?id=35916). N-am uitat de reordonarea corectă a sensurilor, urmează.
1. Etichetarea cu [DEX '09] a făcut-o scriptul de mai sus. Nu înțeleg partea cu rulat o dată, apoi făcută etichetarea. Pentru marcarea ca structurate a definițiilor identice, fac acuș un script separat.
1. Da, pentru asta deschide te rog un tichet. Pare o cu totul altă mîncare de pește, și nu chiar ușoară. :-)

**Comment by MateiGall** [comment]
> Am adus la zi și rulat din nou scriptul. A modificat 17.399 de arbori!

Sper că nu a modificat și arbori structurați.

> 1. Parcă diferențele sînt rezonabil de vizibile deja, nu? Vezi musti (vb.). N-am uitat de reordonarea corectă a sensurilor, urmează.

Da, dacă sensurile sunt preluate din ambele ediții. Eu mă refeream la absența celor noi și mi-ar fi plăcut să văd dacă sunt diferențe. Dacă însă scriptul a adăugat tot ... nu mai e nevoie. Am totuși rețineri, văd că la _învârteală_ (pe care o structurez acum) nu apare DEX'09. Sau trebuie să aștept vreo actualizare a bazei de date...

> 2. Etichetarea cu [DEX '09] a făcut-o scriptul de mai sus. Nu înțeleg partea cu rulat o dată, apoi făcută etichetarea. Pentru marcarea ca structurate a definițiilor identice, fac acuș un script separat.

Mă refer la ediții noi. Când cineva adaugă definiții din DEX'12 sau DEX'16, iar intrarea e structurată, scriptul să adauge automat etichetele sursei și să bifeze definiția ca structurată.

**Comment by CatalinFrancu** [comment]
> Sper că nu a modificat și arbori structurați.

Și eu. :-) Teoretic nu, am fost extra-paranoic.

> Da, dacă sensurile sunt preluate din ambele ediții. Eu mă refeream la absența celor noi și mi-ar fi plăcut să văd dacă sunt diferențe. Dacă însă scriptul a adăugat tot ... nu mai e nevoie. Am totuși rețineri, văd că la _învârteală_ (pe care o structurez acum) nu apare DEX'09. Sau trebuie să aștept vreo actualizare a bazei de date...

Scriptul nu s-a atins de arbori unde deja există sensuri cu sursa [DEX '09]. Am observat și eu că n-a modificat nimic cu _Î_, dar am presupus că le-ai structurat tu manual.

> Mă refer la ediții noi. Când cineva adaugă definiții din DEX'12 sau DEX'16, iar intrarea e structurată, scriptul să adauge automat etichetele sursei și să bifeze definiția ca structurată.

Ok! Am deschis #782.

**Comment by MateiGall** [comment]
> Scriptul nu s-a atins de arbori unde deja există sensuri cu sursa [DEX '09]. Am observat și eu că n-a modificat nimic cu Î, dar am presupus că le-ai structurat tu manual.

Nu am terminat încă litera Î, mai am vreo 3 pagini DLRLC. Pe astea le fac manual, dar rămân alte intrări care n-au definiții din DLRLC și n-ar fi rău să treacă scriptul prin ele. Iar dacă de Î nu s-a atins ... poate mai e vreo hibă și au scăpat și altele...

**Comment by CatalinFrancu** [comment]
O precondiție ca să examineze o definiție este să nu fie deja marcată ca structurată. _Învârteală_ pare că e deja marcată (am o copie locală care e veche de vreo săptămînă și acolo deja e marcată). O fi acesta motivul? Îmi poți da vreun alt exemplu cu _î_?

**Comment by MateiGall** [comment]
Nu cred că era marcată, abia azi am făcut-o. Apoi am mai făcut _învârti_ (în aceeași situație).
Urmează _învârtire_, cu definiții identice '98 și '09 (etichete doar '98). O las nefăcută, ca să analizezi.

**Comment by MateiGall** [comment]
Am impresia că la reparsare ai marcat ca structurate definițiile din '09, ceea ce e incorect (văd intrări nestructurate cu singura definiție structurată cea din '09).
Chiar dacă toate sensurile au fost incluse în arbore, ele nu sunt ierarhizate, marcate exemplele, adăugate sinonimele, toate etichetele etc.
În plus denaturează căutarea definițiilor nestructurate.
Procedura asta a mers la DOR, că nu avea explicații, dar nu prea merge la alte surse...

**Comment by cipy** [comment]
(almost random question, but a bit related)

Daca am nevoie doar de cuvintele provenite din Dex '09, cum pot sa le extrag?

Cu multumiri @CatalinFrancu @MateiGall

**Comment by MateiGall** [comment]
@cipy Cred că se poate face cu o interogare MySQL pe baza de date ... dar nu mă pricep la asta.
Oricum, cred că trebuie să precizezi ce fel de cuvinte cauți: definiții întregi, cuvinte-titlu, forme flexionare...

**Comment by cipy** [comment]
@MateiGall doar cuvinte-titlu, mersi! 👍

**Comment by CatalinFrancu** [comment]
```sql
select distinct lexicon from Definition where status = 0 and sourceId = 27 order by lexicon;
```
Poți citi și [documentația pentru schemă](https://github.com/dexonline/dexonline/wiki/Database-Schema#definition).

**Comment by CatalinFrancu** [comment]
> Am impresia că la reparsare ai marcat ca structurate definițiile din '09, ceea ce e incorect (văd intrări nestructurate cu singura definiție structurată cea din '09).

Ok, am demarcat toate definițiile structurate, din DEX 2009, care sînt asociate cu intrări nestructurate (neîncepute sau în lucru). Pentru referință, comenzile SQL au fost:

```sql
create temporary table badDefs as (select d.id from Definition d join EntryDefinition ed on d.id = ed.definitionId join Entry e on ed.entryId = e.id where sourceId = 27 and structured = 1 group by d.id having max(e.structStatus) <= 2);
update Definition d join badDefs bd on d.id = bd.id set d.structured = 0;
```
