### ISSUE TITLE
Bifă pentru preluarea accentului din fragment în lexemul compus

### ISSUE THREAD

**Issue by CatalinFrancu** [dexonline/dexonline#799]
Vezi de exemplu [coadă-de-găină](https://dexonline.ro/admin/lexemeEdit.php?lexemeId=236934) (acces restricționat). În prezent este accentuat ca co'adă-d'e-gă'ină. Accentul lui _de_ nu ar trebui preluat.

**Comment by CatalinFrancu** [comment]
Rezolvat. Implicit bifa „preia accentul” este pusă. Am șters-o automat și am regenerat paradigmele pentru compusele cu fragmentele _de cu la pe ca și a în său cel_, precum și latineștile/italieneștile _in con cum dal non_.

Pentru referință, interogarea SQL este

```sql
update Lexeme part
  join Fragment f on part.id = f.partId
  join Lexeme c on f.lexemeId = c.id
  set f.accented = 0, c.staleParadigm = 1
  where part.formNoAccent in ('de', 'cu', 'la', 'pe', 'ca', 'și', 'a', 'în', 'său', 'cel', 'in', 'con', 'cum', 'dal', 'non');
```

**Comment by LadislauStrifler** [comment]
Mnah! E bifată și asta. :)
