### ISSUE TITLE
La clic pe „arată originalul” se fac 4 apeluri către getSimilarRecord.

### ISSUE THREAD

**Issue by CatalinFrancu** [dexonline/dexonline#800]
De investigat de ce.

**Comment by LadislauStrifler** [comment]
Am investigat puțin. 
Dacă bine văd, sunt două declarări `id="sourceDropDown"` în șablon, ceea ce induce confuzie, acționarea/schimbarea lui fiind angajată de `$('#entryIds, #sourceDropDown').change(updateFieldsJson);` în `definitionEdit.js`.

**Comment by LadislauStrifler** [comment]
`pageModalActions.tpl` mai încarcă de două ori `sourceDropDown.tpl`, deci selectorul pentru `updateFieldsJson` ar trebui diferențiat cu `'[name="source"]'`
