### ISSUE TITLE
php tools/migration.php e busit in OSX (cel putin)

### ISSUE THREAD

**Issue by cipy** [dexonline/dexonline#803]
Am instalat cu brew mariadb (10.3.11) si php (7.3.0)

Si desi nu ai nevoie de migrari in ultimul db, am incercat:

> dexonline someone$ php tools/migration.php 
> PHP Fatal error:  Uncaught Error: Call to undefined method Locale::init() in /Users/someone/Work/dexonline/phplib/Core.php:40
> Stack trace:
> 0 /Users/someone/Work/dexonline/phplib/Core.php(139): Core::init()
> 1 /Users/someone/Work/dexonline/tools/migration.php(16): require_once('/Users/someone/Wo...')
> 2 {main}
>   thrown in /Users/someone/Work/dexonline/phplib/Core.php on line 40
> 
> Fatal error: Uncaught Error: Call to undefined method Locale::init() in /Users/someone/Work/dexonline/phplib/Core.php:40
> Stack trace:
> 0 /Users/someone/Work/dexonline/phplib/Core.php(139): Core::init()
> 1 /Users/someone/Work/dexonline/tools/migration.php(16): require_once('/Users/someone/Wo...')
> 2 {main}
>   thrown in /Users/someone/Work/dexonline/phplib/Core.php on line 40

Posibil Fix:

`sed -i.back 's/Locale::init();/new Locale();/' phplib/Core.php `

**Comment by CatalinFrancu** [comment]
Hm, ar merita mers un pic pe fir. Aproape sigur asta se întîmplă pentru că pare să existe deja o clasă [Locale](http://php.net/manual/en/class.locale.php). N-am știut asta, iar pe instalarea mea n-o am, dar posibil pe a ta o ai. Poți testa ipoteza adăugînd următorul cod la începutul lui `Core::init()`:

```php
    $l = new Locale();
    var_dump($l);
    exit;
```

Dacă e asta, atunci nu cred că `new Locale();` rezolvă cu adevărat problema, ci doar creează o cu totul altă clasă. Iar întrebarea e de ce e preferată acea clasă și nu a noastră, căci apelul `spl_autoload_register('Core::autoload', false, true);` are al treilea parametru (prepend) pus pe `true`.

**Comment by CatalinFrancu** [comment]
Mulțumesc! Pare că problema este, într-adevăr, existența unei clase Locale. Am să o redenumesc.
