### ISSUE TITLE
un db mai mic (read only)

### ISSUE THREAD

**Issue by cipy** [dexonline/dexonline#804]
Ar putea fi adaugat la readme/documentatie

Daca nu aveti nevoie de o baza de date "live" read+write, o puteti comprima imediat dupa import:

```
zcat /tmp/dex-database.sql.gz | mysql -u root dexonline
cd /var/lib/mysql/dexonline
sudo systemctl stop mariadb
sudo -u mysql myisampack *.MYI
sudo -u mysql myisamchk -rq *.MYI
sudo systemctl start mariadb
```

Si da, dupa compresie, toate tabele myisam devin **read only**

in mariadb (10.3.11) rezultatele dupa compresie arata o reducere de 50% cu metoda de mai sus:
> 3.4G	/var/lib/mysql/dexonline/
> 1.7G	/var/lib/mysql/mixpackdexonline/

Daca va plictisiti de ele asa, ori aveti nevoie de read+write, le puteti reface/decomprima:

```
cd /var/lib/mysql/dexonline
sudo systemctl stop mariadb
sudo -u mysql myisamchk -u *.MYI
sudo systemctl start mariadb
```

**Comment by CatalinFrancu** [comment]
[Adăugat](https://wiki.dexonline.ro/wiki/Instruc%C8%9Biuni_de_instalare#Desc.C4.83rca.C8.9Bi_baza_de_date)! Mulțumim pentru propunere.
