### ISSUE TITLE
HTTP ERROR 500 - la căutare restrânsă per dicționar

### ISSUE THREAD

**Issue by LadislauStrifler** [dexonline/dexonline#806]
În cazul în care nu există nicio definiție asociată lexemului căutat din dicționarul ales se primește ca rezultat o pagină de eroare.
ex.: https://dexonline.ro/definitie-doom/face

**Comment by CatalinFrancu** [comment]
Localizarea, bat-o vina! Am trîntit niște acolade fără să verific.
