### ISSUE TITLE
Selecție candidați la autocompletare compuse

### ISSUE THREAD

**Issue by LadislauStrifler** [dexonline/dexonline#812]
Încă ar mai fi o mică problemă de selecție și aranjare a listei de candidați la autocompletare, și anume: 
![image](https://user-images.githubusercontent.com/16460700/50371731-94cb8d00-05b8-11e9-83ac-1e539bdb907b.png)
Sistemul favorizează simbolul ceriului **Ce** în locului pronumelui **ce**, deci un lexem care nu ar trebui să apară în compuse. 
O posibilitate ar fi ca alegerea candidaților să elimine din start unele modele, respectiv I6 (eventual ș.a.).

**Comment by CatalinFrancu** [comment]
Am decis să prefer pur și simplu formele care păstrează același _case_.
