### ISSUE TITLE
Creare lexeme IL

### ISSUE THREAD

**Issue by LadislauStrifler** [dexonline/dexonline#813]
Există un mic bug (zic eu) la crearea lexemelor IL (probabil  și PT) atunci când lexemele cu pricina există și nu au flexiune (`model T`). Pe lângă dublarea lexemului și intrarea este dublată. 
Cel mai recent caz este la [ciruire id=277572](https://dexonline.ro/editEntry.php?id=277572) rezultat din flexionarea lexemului `cirui` de la intrarea [cirui id=236049](https://dexonline.ro/editEntry.php?id=236049).
Deși intrarea [ciruire id=236051](https://dexonline.ro/editEntry.php?id=236051) exista, și aceasta, și lexemul T au fost dublate. De abia după ce am șters lexemul cu modelul T am observat că și intrarea era dublată. :( M-am oprit aici dacă ar fi ceva de investigat.
Că dublează lexemul aș putea înțelege, dar intrarea parcă nu ar trebui dublată. Care sunt cazurile în care o astfel de manevră ar fi necesară? Sunt cazuri de omografie IL-SF?

**Comment by CatalinFrancu** [comment]
@MateiGall, tu ce părere ai? Să luăm exemplul _colinda_ (ne prefacem că n-ar exista deja). Creăm lexemul _colindat_ PT2, apoi observăm că există deja _colindat_ N24 cu intrare proprie. Este o idee bună să asociem noul participiu cu intrarea pentru substantivul neutru? Mie mi se pare că nu.

**Comment by LadislauStrifler** [comment]
@CatalinFrancu e vorba că nu există N24 _colindat_. Există doar T1 _colindat_, așa am și scris. În acest caz din urmă, și lexemul, și intrarea sunt dublate. Dacă există N24 atunci sistemul nu mai creează PT2, parcă așa e schema, nu?

**Comment by MateiGall** [comment]
Evident că nu.
Cel mai bine ar fi ca moderatorii să rezolve aceste situații la momentul respectiv (cu asistență din partea sistemului, care să afișeze mesaje informative și să creeze doar lexemele / intrările necesare). Dar asta e altă discuție, despre câte / ce operații trebuie să facă fiecare moderator (mai mult sau mai puțin experimentat).
Asocierile greșite sunt mai puțin supărătoare în cazul intrărilor nestructurate, dar e păcat că la cele structurate vor fi necesare operații suplimentare pentru remedierea nepotrivirilor.

Eu cred că:
1. Dacă există lexem F omonim, lexemul IL nu trebuie creat (iar definițiile nu se asociază cu intrarea).
2. Dacă există lexem A omonim, lexemul PT nu trebuie creat (iar definițiile nu se asociază cu intrarea).
3. Dacă există lexem T omonim, noul lexem (IL sau PT) se creează, fiind mai ușor de eliminat ulterior lexemul T decât de creat și etichetat cel nou. Obs. Dacă intrarea corespunzătoare lui T se unifică cu cea nou creată (IL sau PT), lexemul T este șters automat, deci nu trebuie șters înainte de unificare (pentru că rămâne intrarea neasociată).

**Comment by LadislauStrifler** [comment]
Ne aflăm în cazul 3 expus de tine, @MateiGall !
Cazul concret de care am vorbit era așa:
Au fost create intrările `cirui` și `ciruire` ca urmare a definițiilor din **MDA2**. Ambele intrări aveau asociate lexeme `model T1` (_cirui_, respectiv _ciruire_ -  ca urmare a moderării).
La `cirui` i-am generat conjugarea, astfel creându-se automat _lexemul_ `IL - ciruire`, care a creat automat _intrarea_ `ciruire`, dar această intrare exista deja!, cu definiție aferentă și lexem `model T1`.
Eu consider că nu are rost să se creeze o altă (a doua) intrare omografă, ci asocierea lexemului `IL` cu intrarea existentă și ștergerea lexemului `model T1`, iar mai apoi....
... ca să și observăm că s-au produs astfel de situații, este necesar un nou raport privind lexemele `IL` asociate **solitar**(!) unei intrări cu definiții. Se presupune cu probabilitate mare că aceste lexeme ar trebui să fie `model F`, deci vor trebui reetichetate și schimbat modelul.
Concret, dacă `ciruire IL` s-ar fi asociat cu intrarea `ciruire` și s-ar fi șters `ciruire T1`, am fi avut intrare `ciruire` asociată cu X definiții (nu contează, dar în cazul nostru una) și **un singur lexem** `ciruire IL`. Concluzie - `ciruire IL` este cu siguranță (sau fiind precauți 99%) `model F`.

Evident, trebuie raport similar și pentru `PT`-uri solitare asociate unei intrări ce conține definiții.

**Comment by MateiGall** [comment]
Eu am spus cum ar trebui să funcționeze sistemul, nu cum funcționează acum (asta știu, am trecut și eu pe aici și am mai semnalat problema).
Mai precis ar trebui să fie așa:
- la etichetarea verbului (cirui) NU se creează lexem / intrare IL ciruire (PT ciruit) dacă există deja omografă cu lexem F (A) sau T, iar definițiile NU se asociază cu intrarea existentă.
- - dacă lexemul existent e T, acesta ar putea fi etichetat automat F (107 / 113 după caz) sau A (2 / 4...), urmând ca intrarea să fie definitivată ulterior (există și posibilitatea să fie necesar alt tip, așa că acest pas poate fi omis).
- - dacă lexemul existent e F (A), NU se modifică nimic.
- actuala procedură (se creează lexem IL (PT) și intrare, se asociază definițiile) se aplică doar dacă lexemul existent are alt tip (N, I, P...).
[Verificați și voi; pare ok?]

Adaug aici și o rugăminte pentru pagina de editare a lexemului: la modificarea tipului din F în IL (din A în PT) și reciproc, numărul modelului să se păstreze (e improbabil să fie alt număr, iar 1 implicit oricum e greșit).

**Comment by LadislauStrifler** [comment]
Pot fi de acord cu bulina neagră 1, chiar dacă eu ziceam să se creeze totuși IL. Important este să nu se creeze automat intrări dublate, omografe.

**Comment by CatalinFrancu** [comment]
> Adaug aici și o rugăminte pentru pagina de editare a lexemului: la modificarea tipului din F în IL (din A în PT) și reciproc, numărul modelului să se păstreze (e improbabil să fie alt număr, iar 1 implicit oricum e greșit).

Am desprins #886 pentru asta.

> dacă lexemul existent e T, acesta ar putea fi etichetat automat F (107 / 113 după caz) sau A (2 / 4...), urmând ca intrarea să fie definitivată ulterior (există și posibilitatea să fie necesar alt tip, așa că acest pas poate fi omis).

Momentan se generează un avertisment ([link la cod](https://github.com/dexonline/dexonline/blob/master/lib/models/Lexeme.php#L726)). N-am testat personal, dar asta pare că fa ce codul. :-) Să desprind și pentru asta un tichet, sau nu e important, în virtutea acelui mecanism de unificare care șterge automat lexemul T1?
