### ISSUE TITLE
Lexemele compuse nu generează forma apocopată

### ISSUE THREAD

**Issue by LadislauStrifler** [dexonline/dexonline#817]
![image](https://user-images.githubusercontent.com/16460700/50504753-b5d42800-0a67-11e9-953b-f0d78c8db554.png)

**Comment by CatalinFrancu** [comment]
Asta trebuie rezolvată, dar dau de niște complicații.

1. Tehnic vorbind, toate fragmentele pot admite apocopă, de ex. [liberu-arbitru](https://dexonline.ro/intrare/liber-arbitru/160345/paradigma). Dar asta nu se întîmplă întotdeauna, ci depinde cu ce literă începe următorul fragment. De exemplu [încurcă-lume](https://dexonline.ro/definitie/%C3%AEncurc%C4%83-lume/paradigma) nu trebuie să genereze forma _*încurc-lume_.

2. Sistemul de lexeme compuse preia, în prezent, o singură formă dacă fragmentul generează mai multe forme. De exemplu, [tata-socrul](https://dexonline.ro/definitie/tat%C4%83-socru/paradigma), nu și +*tatăl-socrul_, deși _tată_ are două forme articulate. Asta îmi dă niște bătăi de cap, dar să zicem că e rezolvabilă.

De aceea, cred că o soluție de compromis ar fi o bifă pe fiecare fragment, „admite apocopă”. Dacă e pusă, și dacă forma care este selectată pentru fragmentul respectiv admite apocopă, atunci ea este preluată în lexemul compus.

**Comment by LadislauStrifler** [comment]
Nu știu dacă e așa de complicată problema. Nu găsesc exemple de compuse care să aibă apocopă la termenul de dinaintea cratimei. Sigur, forme populare putem întâlni, dar până la urmă eventualele `gândacu-de-mai` sau `stârcu-cenușiu-mic` vor duce la forma principală pentru că sunt compuse din gândac sau stârc care au apocopa gândacu- sau stârcu-.

**Comment by CatalinFrancu** [comment]
Da, dar ideea noastră grandioasă (nu mai știu pe ce _thread_) era ca clicul pe cuvînt să decupeze mai întîi forma cu cratime și să caute prin Ajax ca să vadă dacă vreun lexem compus generează acea formă. Deci ar fi util să generăm _gândacu-de-mai_.

**Comment by LadislauStrifler** [comment]
Ar trebui investigat prima dată dacă există astfel de cazuri.
