### ISSUE TITLE
Afișare paradigmă lexeme invariabile

### ISSUE THREAD

**Issue by MateiGall** [dexonline/dexonline#818]
Paradigma lexemelor invariabile nu este afișată (în pagina de editare a lexemului - pe motiv că există doar o formă invariabilă).
Dacă se bifează una din căsuțele **admite afereză / apocopă** nu se poate vedea dacă forma elidată e generată corespunzător, situație care poate apărea în cazul în care modelul respectiv nu are bifată admiterea apocopei.

**Comment by CatalinFrancu** [comment]
Exact asta aveam eu mîzgălit pe hîrtia mea cu lucrușoare de făcut. :-) Mersi că ai deschis un tichet!
