### ISSUE TITLE
Dublu-click în TinyMCE să selecteze și altceva decît literele

### ISSUE THREAD

**Issue by CatalinFrancu** [dexonline/dexonline#819]
Ar trebui incluse cel puțin tildele, ceea ce ar ajuta la formatarea corectă a variantelor și a formelor de plural. Posibil să ne intereseze și apostroful, care altfel ar „sparge” formele în două.

Nu știu cît suport are TinyMCE pentru asta. De investigat.

**Comment by LadislauStrifler** [comment]
Eu aș investiga doar dacă ai putea da mai multe detalii. Mie îmi funcționează, să zicem, corect dublu-clicul. Niște exemple concrete mi-ar fi de ajutor. (definiții exacte, poziție exactă de clicuit etc.)

**Comment by CatalinFrancu** [comment]
Ai testat asta, respectiv că dublu-click pe cuvînt selectează și tildele? Încearcă, să zicem, la [zălezit](https://dexonline.ro/admin/definitionEdit.php?definitionId=1140403), varianta _**ziliz~**_. Mie îmi selectează doar literele!

**Comment by CatalinFrancu** [comment]
Avem un editor care așa lucrează. Și mie mi se pare un sistem cam lent, dar dacă îi putem face viața mai ușoară, de ce nu? Dacă ai timp de o analiză, ar fi mișto! Sigur, dacă descoperim că e prea greu sau iese o mare cîrpeală, putem să nu implementăm.

**Comment by LadislauStrifler** [comment]
Să luăm exemplul șirului: `aargh bla-bla~, (alandala) boing grrr`
Oriunde m-aș afla cu cursorul în cadrul lui `bla-bla~`, apăsând pe B sau I se formatează întreg fragmentul, cu tot cu tildă. Nu e necesar să selectez nimic, doar să mă aflu în interiorul fragmentului. Dezavantajul este că în acest mod de operare (de neselectare a vreunui pasaj), șiruri fără spațiu ca cel aldin din: 
`aargh`**`bla-bla~,(alandala),`**`boing grrr` vor fi în întregime formatate. Cu alte cuvinte, formatarea fragmentului în caz de neselectare se oprește la spațiu, nu la semne de punctuație.
Cam asta ar fi buba? Editorul vrea să selecteze prin dublu-clic fragmente de text mărginite doar de anumite caractere (spațiu, virgulă, paranteză ș.a.), adică să restrângă numărul semnelor la care selectarea prin dublu-clic _se oprește_ și să extindă setul de caractere la care _nu se oprește_.

**Comment by CatalinFrancu** [comment]
Editorul zice că se adaptează la starea de fapt. Și că va încerca să folosească mai mult tastatura. Deci l-aș închide ca nenecesar.
