### ISSUE TITLE
utf8 -> utf8mb4 în baza de date

### ISSUE THREAD

**Issue by CatalinFrancu** [dexonline/dexonline#820]
Altfel caracterele pe patru octeți dau eroare la salvare (de exemplu [fermata](https://www.fileformat.info/info/unicode/char/1d110/index.htm)). Din MySQL,

```sql
update Definition set internalRep = '𝄐' where id = 690130;
show warnings;
```

Mulțumiri @LadislauStrifler pentru raportare.

**Comment by CatalinFrancu** [comment]
Cam asta a fost. Au fost schimbări masive la nivelul bazei de date. Am ales să nu fac un patch, căci durează mult și e mai rentabil să o redescarci (mîine dimineață).

La nivel de cod au fost 48fb9048c0f8a2b48ba36ed9140b3086d201bfbd și d7a79187b89c2f36d086bdf7f7e7e0be5daf5690, am uitat să le anexez aici.

Și au mai fost și modificări simple în configurația serverului.

**Comment by LadislauStrifler** [comment]
Harașo!
