### ISSUE TITLE
Eliminare zonă facebook

### ISSUE THREAD

**Issue by MateiGall** [dexonline/dexonline#821]
Mi-aș dori eliminarea zonei de facebook din josul paginilor de căutare (rezultate, declinări, sinteză) pentru moderatori; sau măcar o opțiune de a ascunde această zonă.
Consider inutil să o văd de mii de ori și am impresia că încetinește încărcarea paginilor.

**Comment by LadislauStrifler** [comment]
Dacă folosești Chrome, ai la dispoziție **uBlock origin**. E aproape ca Dero. Te scapă de 99% dintre pete.

**Comment by CatalinFrancu** [comment]
Am ascuns oricum FB pentru toți utilizatorii privilegiați, să fie. Că veni vorba, am ascuns și bannerul. Dar așa e, pe site-uri unde nu ești prieten cu programatorul, :-) poți folosi diverse extensii de browser.
