### ISSUE TITLE
Editare intrare

### ISSUE THREAD

**Issue by MateiGall** [dexonline/dexonline#834]
Pe lângă butoanele de „asociază...” și „disociază...” din pagina de editare a intrării ar fi util și un buton care să combine cele două operații. Unele definiții trebuie pur și simplu mutate la o altă intrare, ceea ce necesită în prezent două operațiuni de căutare + selectare + asociere / disociere.

**Comment by CatalinFrancu** [comment]
Rezolvat! După ce apeși pe „asociază”, butonul apare în popup. Vei vedea acolo două butoane, _copiază_ și _mută_. Tehnic e un pic mai simplu așa, căci refolosesc același popup.

**Comment by MateiGall** [comment]
Constat că acum ar fi util ca la clonarea intrării să fie bifate implicit cele patru opțiuni de copiere (definiții, lexeme etc., cum a fost inițial).

**Comment by CatalinFrancu** [comment]
Asta a fost simplă. :-)

**Comment by MateiGall** [comment]
Ar fi util ca una din bifele „v structurată” / „x nestructurată” să aibă altă culoare, să fie mai ușor de observat la parcurgerea listei.

**Comment by CatalinFrancu** [comment]
Sigur. Am folosit verdele implicit din bibliotecă. Dacă vrei ceva și mai vioi, să-mi spui.

**Comment by MateiGall** [comment]
Ar fi util ca butonul de „urcare” a variantelor să fie dublat, unul având ca funcție doar urcarea primului lexem din listă (iar celălalt pentru întreaga listă).
Aceste butoane (sus / jos) ar putea fi plasate pe lateral, în dreptul câmpurilor corespunzătoare (fiind astfel mai clar rolul lor).
