### ISSUE TITLE
Spam pagina Facebook

### ISSUE THREAD

**Issue by ematt** [dexonline/dexonline#836]
Buna ziua,

Pe [pagina de facebook ](https://www.facebook.com/dexonline) se posteaza spam. Care ii statusul ei? Este hackuita?

**Comment by LadislauStrifler** [comment]
S-ar putea ca pagina să fie scăpată de sub control. Nici închiderea nu mai funcționează.
![image](https://user-images.githubusercontent.com/16460700/53678530-f8fd8200-3cc8-11e9-970c-1adca81fca2c.png)

**Comment by ematt** [comment]
Cred ca optiunea se refera la orarul de functionare si doar modifica textul de la "Despre". 

Mai are vreun admin acces la pagina?

**Comment by CatalinFrancu** [comment]
@raduborza se ocupă de pagina Facebook. Cealaltă pagină a devenit owner al paginii dexonline prin phishing. Radu a făcut demersuri pentru revocarea accesului acelei pagini; inclusiv un român care lucrează la  Facebook ne-a ajutat și a făcut un raport intern. Momentan n-am rezolvat nimic. Ce învățăm de aici? Eu unul nimic suplimentar, știam deja că Facebook e o porcărie. Acum am în plus un exemplu personal. :-) </rant>

**Comment by raduborza** [comment]
@ematt din păcate nu mai are nimeni acces de admin, iar facebook nu se deranjează să răspundă în vreun fel, deși am făcut multiple rapoarte (cel puțin deocamdată nu am primit vreun răspuns, iar singurul răspuns primit spune că maxim de concesie e să ne facă din nou admini (ceea ce e inutil dacă nu șterg și Page Ownerul, care se pare că are drepturi mai mari decît adminul). Poate ajută dacă raportați pagina pentru spam!

Eu am învățat aici că nu are sens să pierzi timpul pe platforme în care drepturile minimale ți-s călcate în picioare, așa că și dacă obținem din nou controlul asupra paginii, cel mai probabil o vom închide.
