### ISSUE TITLE
Modificări la clonarea lexemului

### ISSUE THREAD

**Issue by CatalinFrancu** [dexonline/dexonline#840]
- [x] Clonarea tuturor proprietăților.
- [x] Adăugarea automată a numerotării (originalul cu 1, clona cu 2).
- [x] Renunțarea la descrierea CLONĂ. Ideal ar fi să obligăm utilizatorul să treacă ceva totuși acolo, dar la apăsarea pe „clonează”, deja datele sînt salvate fără descriere. De gîndit.
- [x] De indicat cumva, la asocierea cu intrări, dacă lexemul este principal sau variantă, ca să nu mai trebuiască vizitată și pagina intrării. Probabil se poate face prin dublarea cîmpului în interfață (așa cum este acum pe pagina intrării).

Propuse de @MateiGall

**Comment by MateiGall** [comment]
Adaug aici o propunere legată de pagina de editare a lexemului.
La salvarea paginii să se afișeze un mesaj (ca la intrări și arbori) Mi s-a întâmplat să nu funcționeze clicul pe „Salvează” și modificările n-au fost operate.

**Comment by LadislauStrifler** [comment]
Numerotarea am făcut-o, dar mi-am dat seama că pot exista în DB și nume proprii numerotate (ex.: [aba](https://dexonline.ro/definitie/aba/paradigma)). Cum se dorește numerotarea, cu sau fără NP-uri?

**Comment by LadislauStrifler** [comment]
Pentru punctul 3 (și 4), @CatalinFrancu, avem posibilitatea să o facem automat sau prin chestionar prealabil (modal). 

Având în vedere că procesul de clonare numerotează lexemele, moderatorul este nevoit să revină asupra unui lexem sursă dacă nu a trecut în prealabil nimic la descriere (numărul va fi generat automat). Câmpul descriere devine într-un fel obligatoriu, nu cum afișează textul înlocuitor: „_opțională, pentru diferențierea omonimelor_”, deși putem rămâne la numerotare din moment ce există etichetele. 
Eu descrierea o mai folosesc la specificarea accentului în cazul omografelor.

Pentru punctul 4, nu trebuie să dublăm câmpul. Ajunge o bifă sub formă, sau nu?
![image](https://user-images.githubusercontent.com/16460700/68424857-950f4f80-01ad-11ea-8572-ed271e8dc231.png)

eventual invers, debifat:
![image](https://user-images.githubusercontent.com/16460700/68424991-d56ecd80-01ad-11ea-862b-723acdf31aad.png)

**Comment by MateiGall** [comment]
Cum funcționează numerotarea în cazul celor care au deja numere? Dacă am 5 lexeme numerotate și îl clonez pe cel cu nr. 2 ce număr primește noul lexem? Bănuiesc că se alocă următorul număr disponibil din șir...

Pentru nume proprii eu cred că ar trebui eventual numerotare separată, ele fiind deja diferențiate prin majusculă (de regulă nu trebuie număr, numele propriu fiind unic). Dar nu mă deranjează nici dacă rămân la grămadă.

Îmi place ideea cu bifa, eventual cu butoane active alternativ principal/variantă.

**Comment by LadislauStrifler** [comment]
Numerotarea nu e chiar simplă. Cred că tot timpul trebuie făcută o renumerotare, pentru că ar putea fi situații când lexemul clonat are numărul 2 pentru că numărul 1 a fost șters.
La salvarea lexemelor omonime ar trebui numerotate din oficiu. Există vreun impediment de prezentare legat de acest aspect?

**Comment by CatalinFrancu** [comment]
Da, pare fezabil să verificăm numerotarea la ștergere / clonare / editare. Aș da doar un avertisment, nu aș bloca operația.

Bifa pe lexem nu merge, pentru că un lexem poate fi principal într-o intrare și variantă într-alta. Vezi _abac, patent, mlădi_ și alte 500 de lexeme. Le-am găsit cu interogarea:

```sql
select l.id, l.form
  from Lexeme l
  join EntryLexeme a on l.id = a.lexemeId
  join EntryLexeme b on l.id = b.lexemeId
  where a.main = 1
    and b.main = 0;
```

Deci aș zice că proprietatea principal/variantă este o proprietate a asocierii, nu a lexemului nici a intrării.

**Comment by MateiGall** [comment]
Just! Am scris comentariul precedent înainte de a mă trezi bine :)
Ar trebui ca bifele respective să fie lângă fiecare intrare asociată, ceea ce pare mult prea complicat.

**Comment by CatalinFrancu** [comment]
Corect! Deci rămîne varianta cu dublarea cîmpului. Nu e neapărat simplu, dar e deja implementat pe pagina lexemului, se adaptează relativ ușor.

**Comment by LadislauStrifler** [comment]
Nu înțeleg de ce [aleatoriu](https://dexonline.ro/editare-intrare?id=1355) este și principal, și variantă, dar ai dreptate Cătă, am pierdut din vedere asocierea multiplă.

Nu, Matei, nu e complicat să afișăm în căsuța intrării dacă lexemul este principal sau variantă.
![image](https://user-images.githubusercontent.com/16460700/68458778-4e9d0d80-020c-11ea-868b-2dfaaad03012.png)

**Comment by LadislauStrifler** [comment]
Cu toate acestea, varianta dublării rămâne cea mai practică, fiindcă la o reasociere cu un singur câmp de select2 nu poți să specifici principal/variantă.

**Comment by MateiGall** [comment]
Am corectat intrarea „aleatoriu”, nu știu cum a apărut dublarea lexemului.

Afișarea nu e complicată. Eu mă refeream la plasarea bifelor pe fiecare intrare, ca să salvăm direct cu atributul dorit.

**Comment by LadislauStrifler** [comment]
În consecință, renumerotarea va avea în vedere forma binară a lexemului. 
1. `colan != Colan`
2. `col == col` cu restricții de model sau nu? `col = I-7P`, `col = I-7S` și `col = N24`

**Comment by MateiGall** [comment]
Nu mi se pare ok ce e acum la „col”. Eu cred că ar trebui să avem doar col^1 (s.n.) și col^2 (afix). De ce să duplicăm lexeme cu aceeași paradigmă?
Eventual col^2 să fie diferențiat în col^2 (pref.) și col^3 (suf.) dacă marcăm diferit lexemele, cu cratimă (col- / -col).

**Comment by LadislauStrifler** [comment]
Sunt de acord, dar așa au fost indicațiile la momentul respectiv. Definițiile parcă erau asociate cu lexeme când am moderat **DETS**. Mi-am dat osteneala să le diferențiez. Acum, că avem intrări și definițiile sunt asociate cu acestea, putem regândi situația.

**Comment by MateiGall** [comment]
Eu nu am cunoștință de asemenea indicații; nici în ghidul pentru structurare nu cred că e menționat așa ceva.
Lexeme diferite trebuie să avem doar pentru părți de vorbire diferite sau paradigme diferite.

**Comment by LadislauStrifler** [comment]
Deocamdată sunt aici:
![image](https://user-images.githubusercontent.com/16460700/68479479-1cef6b00-023b-11ea-9a77-f8965894dbfd.png)


Definițiile, și ele, sunt împărțite în două categorii:
![image](https://user-images.githubusercontent.com/16460700/68479809-e6662000-023b-11ea-8967-143540e46ecd.png)

Dacă corespunde, încep să testez salvările și clonările dacă nu cumva explodează.
