### ISSUE TITLE
Bug la modalul de glife

### ISSUE THREAD

**Issue by CatalinFrancu** [dexonline/dexonline#844]
> În momentul închiderii modalului cu tabelul de glife, dacă apăs din nou Alt+Q blochez interfața și cu șoarecele nu mai pot da clic pe nimic. Merge doar săritura cu TAB între câmpuri.
> Alt+Q, alegi glifa și în timp ce dispare modalul mai apeși o dată Alt+Q.

Testat pe Chrome. Raportat de @LadislauStrifler.

**Comment by MateiGall** [comment]
La mine (tot pe Chrome) merge. Evident apăs iar Alt+Q după ce se închide fereastra cu glife, nu „în momentul închiderii”...

**Comment by LadislauStrifler** [comment]
Pentru referințe ulterioare:
La acționarea prea rapidă a scurtăturii (alt+q), între dezactivarea modalului de glife și revenirea la formularul de editare, bootstrap nu apucă să elimine stratul de obscurizare, acestea acumulându-se până la opacizarea ferestrei.
![image](https://user-images.githubusercontent.com/16460700/68410863-28d32280-0192-11ea-8156-82563c78e97e.png)
