### ISSUE TITLE
Selectare automată a cuvântului lunii

### ISSUE THREAD

**Issue by dan-bizdadea** [dexonline/dexonline#848]
In urma unor discutii pe blogul dexonline(https://blog.dexonline.ro/2019/03/pagina-de-facebook-a-dexonline-a-fost-sparta/) s-ar putea pune problema alegerii cuvantului lunii in mod automat sau semi-automat astfel (propunere):
1. Crearea unui bloc care sa afiseze cele mai populare 10-20 de cuvinte ale lunii si cat de cunoscut este fiecare cuvant (se poate folosi numarul de rezultate gasite de Google pentru fiecare cuvant ca fiind o masura a popularitatii)
2. Evidentierea acelor cuvinte care nu au mai fost alese drept cuvinte ale lunii.
3. Daca nici un administrator nu alege un cuvant intr-un termen prestabilit, se alege unul din cuvintele nefolosite anterior din lista respectiva in functie de numarul de rezultate pe google.
4. (Optional) Se poate verifica si google trends 
5. In cazul publicarii automate a cuvantului, imaginea asociata se poate genera pe baza unui template prestabilit.

**Comment by CatalinFrancu** [comment]
De acord. Aș face pasul 3 doar după o notificare prin e-mail, căci alegerea ar trebui să-i aparțină totuși unui om. Cu cît automatizăm mai bine treaba (pașii 1-2), cu atît e mai mare șansa ca restul de efort să-l facă cineva. :-)

Pasul 5 nu văd cum s-ar automatiza!

**Comment by dan-bizdadea** [comment]
Ok cu pasul 3. Oricum ar elimina mult din efortul uman daca pana acolo ar fi automatizat.
Pentru pasul 5 ma gandeam doar la un placeholder (chenar+text) tot pentru cazul limita in care nu s-ar putea gasi o imagine reprezentativa. 
Ideea era ca afisarea in front sa pastreze design-ul actual care implica si o poza pe langa text.

**Comment by LadislauStrifler** [comment]
Cred că pe asta am lămurit-o într-o discuție prin e-mail în care @raduborza zicea că nu e tocmai bine să fie automatizat procesul.

**Comment by CatalinFrancu** [comment]
De acord.
