### ISSUE TITLE
Conjugation / declension tabs are broken on safari (iOS)

### ISSUE THREAD

**Issue by rpappalax** [dexonline/dexonline#853]
Up until a few weeks ago I was able to launch dexonline using Safari and look up conjugations and declensions. That feature has since stopped working.

**Comment by CatalinFrancu** [comment]
Thanks for letting us know. I cannot run Safari, but would you be willing to submit a Javascript console log?

**Comment by rpappalax** [comment]
> Thanks for letting us know. I cannot run Safari, but would you be willing to submit a Javascript console log?
Mulțumesc, @CatalinFrancu.  Acum nu pot repro problemă.  Closing
