### ISSUE TITLE
Intermittent Gateway time-out

### ISSUE THREAD

**Issue by rpappalax** [dexonline/dexonline#854]
Receiving “404 Gateway Time-out” intermittently this week

**Comment by CatalinFrancu** [comment]
Yup, it does that every now and then due to too many MySQL connections. It's been tricky to pin down so far. :-/

**Comment by LadislauStrifler** [comment]
It's really annoying, @CatalinFrancu. Now and then... again!

**Comment by MateiGall** [comment]
Annoying ... mai ales când lucrez la un arbore și la salvare pierd toată munca.

**Comment by CatalinFrancu** [comment]
I poked around a little and increased `pm.max_children` from 100 to 200 in the FPM configuration on both backends. Here is a list of findings so far (notes to myself, mostly).

**Log excerpts in chronological order**

    (chum, FPM log) [02-May-2019 15:37:54] WARNING: [pool www] seems busy (you may need to increase pm.start_servers, or pm.min/max_spare_servers), spawning 8 children, there are 8 idle, and 40 total children
    (buddy, FPM log) [02-May-2019 15:38:01] WARNING: [pool www] seems busy (you may need to increase pm.start_servers, or pm.min/max_spare_servers), spawning 8 children, there are 18 idle, and 36 total children
    (chum, FPM log) [02-May-2019 15:38:39] WARNING: [pool www] server reached pm.max_children setting (100), consider raising it
    (buddy, Nginx log) 2019/05/02 15:38:36 [alert] 27947#27947: 768 worker_connections are not enough
    (buddy, Percona log) 2019-05-02 15:40:21 1892 [Warning] Too many connections

**Slow queries**

This does not seem to be a problem. There are 215 slow queries spread throughout that day, most of them at 2-3 seconds.

**Tweaking the FPM setup**

I used [this answer](https://stackoverflow.com/a/25098060/6022817) as a guide.

**Comment by LadislauStrifler** [comment]
Again, today 05.05.2019, at 11:42, after submitting a lexem-edit form of [cauțiune](https://dexonline.ro/editare-lexem?lexemeId=282070)... timeout!

**Comment by CatalinFrancu** [comment]
Reduced [keepalive_timeout](https://nginx.org/en/docs/http/ngx_http_core_module.html#keepalive_timeout) from 65 to 10 on main server. This cut the number of waiting connections from ~800 to ~400.

**Comment by CatalinFrancu** [comment]
Raised `max_connections = 500` (up from 150) in `my.cnf`.

**Comment by rpappalax** [comment]
Folosesc dexonline zilnic dar n-am văzut această eroare în 3 săptămâni, closing

**Comment by adrianvintu** [comment]
Si eu am observat ca cam pica situl dexonline, destul de des chiar.

Ultima oara am observat acum cateva zile, maxim inceputul lunii.

**Comment by CatalinFrancu** [comment]
Ok, îl voi redeschide dacă reapare problema. Încerc să surprind problema live ca să pot rula `show processlist` în MySQL.
