### ISSUE TITLE
Prefix con- + în... transformat în conân... 

### ISSUE THREAD

**Issue by LadislauStrifler** [dexonline/dexonline#855]
La clic pe cuvânt redirecționarea nu funcționează. Trebuie exclus și prefixul con-.
Deocamdată _conînțeles_, _conînțelegere_.

**Comment by CatalinFrancu** [comment]
Trebuie modificat [aici](https://github.com/dexonline/dexonline/blob/master/lib/Constant.php#L139), cît timp nu există excepții, deci cuvinte care chiar încep cu _conâ-_ (cred că nu există).
