### ISSUE TITLE
Editare lexem

### ISSUE THREAD

**Issue by MateiGall** [dexonline/dexonline#860]
La clonarea unui lexem ar fi bine să existe în câmpul pentru intrare și posibilitatea creării unei noi intrări (similar cu procedura din pagina de editare a definiției).
S-ar evita astfel asocierea clonei cu o intrare oarecare, urmată apoi de clonarea intrării și disocierea lexemelor.
Alte modificări necesare:

1. Eliminarea descrierii CLONĂ xxx (de regulă trebuie ștearsă și înlocuită cu altă descriere).
2. Valoare implicită în câmpul „intrări” = intrarea asociată lexemului origine (e mai ușor de șters decât de completat).
3. Mesaj de informare la salvare (mi s-a întâmplat să nu meargă clicul pe „salvează”) sau mesaj de confirmare la părăsirea paginii fără salvarea modificărilor.

**Comment by CatalinFrancu** [comment]
Gata, cred că merg toate. Pentru (3) afișez mesajul obișnuit verde la salvarea și la clonarea lexemului. Nu am avertismentul la părăsirea paginii; dacă îl fac, ar merita generalizat la toate paginile de editare și e ceva mai complex.
