### ISSUE TITLE
Ordonare variante la afișare

### ISSUE THREAD

**Issue by LadislauStrifler** [dexonline/dexonline#869]
În mod normal unele variantele ar trebui să aibă prioritate față de altele, mai puțin folosite sau învechite. Ele se pot ordona în cadrul câmpului de selecție, în formularul de editare-intrare, dar această ordonare nu este luată în seamă la afișare. 
Exemplu: [kilogram-metru](https://dexonline.ro/definitie/kilogram-metru), unde varianta fără liniuță de unire (**kilogrammetru**) este prima în caseta de selecție, dar se afișează ultima.

**Comment by CatalinFrancu** [comment]
Ok, eu n-am nicio obiecție! Le-am ordonat alfabetic pentru cazurile cu foarte multe variante, de exemplu [coropișniță](https://dexonline.ro/definitie/coropișniță). Dar cred că nu-i rău nici să păstrăm ordinea dată de editor.
