### ISSUE TITLE
BUG: API nu mai funcționează

### ISSUE THREAD

**Issue by valinaga** [dexonline/dexonline#871]
Pentru orice căutare, ex: `https://dexonline.ro/definitie/oc*/json`
Răspuns: `{ "type": "searchResults", "word": "oc*", "definitions": [ ] } `
Am încercat mai multe variante de definiție fără rezultat. 
Căutarea normala web `https://dexonline.ro/definitie/oc*` funcționează corect.

**Comment by CatalinFrancu** [comment]
Vezi în #562: API-ul XML sau JSON merge doar pentru căutări normale, ex `https://dexonline.ro/definitie/spanac/xml`. Ar fi binevenite și cele pentru alte tipuri de căutări (full-text, regex etc.), dar momentan nu are cine să le implementeze. Așteptăm zîna programării să vină...
