### ISSUE TITLE
Spell checker for Firefox is broken

### ISSUE THREAD

**Issue by CatalinFrancu** [dexonline/dexonline#893]
The file [dex-ff.xpi](https://dexonline.ro/static/download/dex-ff.xpi) no longer installs in newer versions of Firefox. The generating script is `tools/rebuildFirefoxSpellChecker.php`. @adakaleh kindly provided us with a [link](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/manifest.json/dictionaries) for fixing it.

**Comment by adakaleh** [comment]
Ok, am actualizat extensia:
https://addons.mozilla.org/en-US/firefox/addon/ortodex/
https://github.com/adakaleh/ortoDEX

Nu am umblat deloc la dicționare, sunt exact cele din vechiul [dex-ff.xpi](https://dexonline.ro/static/download/dex-ff.xpi). Ar trebui actualizate. Deocamdată doar am înlocuit install.rdf cu manifest.json și am șters niște directoare inutile. Am testat, funcționează.

Am pus și un [pull request](https://github.com/dexonline/dexonline/pull/896) cu schimbările necesare. Nu am instalat dexonline local, așa că vă rog să le testați.

Nu știu dacă e ok [licența](https://github.com/adakaleh/ortoDEX/blob/master/LICENSE.txt), probabil trebuie să o schimb în GPLv3... sau AGPLv3?

**Comment by CatalinFrancu** [comment]
Excelent, mulțumim! Îl accept și îl testez acum.

**Comment by CatalinFrancu** [comment]
A, iar referitor la licență: conform [proiectului GNU](https://www.gnu.org/licenses/license-list.html#informal), licența este compatibilă cu GPL, doar că nu este copyleft. Dacă vrei să o înlocuiești cu una copyleft, pentru a perpetua libertatea și la copierea următoare, noi nu ne supărăm. :-) Dar și licența WTF este suficientă.

**Comment by adakaleh** [comment]
Bun, [GPLv3](https://github.com/adakaleh/ortoDEX/blob/master/LICENSE.txt) să fie.
