### ISSUE TITLE
Cuvantul lunii in json

### ISSUE THREAD

**Issue by CosminMihuMDC** [dexonline/dexonline#902]
Exista vreo modalitate prin care putem lua json pentru cuvantul lunii?

Pe acceasi idee am incercat: https://dexonline.ro/cuvantul-lunii/2020/06/json dar nu merge.

**Comment by CatalinFrancu** [comment]
Pare că nu. E nevoie de modificări în [routes/wotm/view.php](https://github.com/dexonline/dexonline/blob/master/routes/wotm/view.php) similare cu [routes/wotd/view.php](https://github.com/dexonline/dexonline/blob/master/routes/wotd/view.php) și [templates/json/wotd.tpl](https://github.com/dexonline/dexonline/blob/master/templates/json/wotd.tpl)
