### ISSUE TITLE
Copyright-ul imaginii nu e prezent in API-ul cuvantului zilei

### ISSUE THREAD

**Issue by revolter** [dexonline/dexonline#905]
Related to #664.

**Comment by CatalinFrancu** [comment]
Done! Am pus doar numele, nu și creditele în HTML, care conțin (de regulă) linkul extern spre pagina FB/Instagram a autorului. Dacă sînt importante și acelea le putem obține, dar trebuie structurată nițel informația din tabela de autori.

**Comment by revolter** [comment]
As zice ca e bine sa avem acces prin API la toate informatiile la care are acces si interfata web. Sunt forme diferite de credite?

**Comment by CatalinFrancu** [comment]
Majoritatea creditelor au forma:

```html
© imagine <a target="_blank" href="/spre/miolk">Cosmin - Miolk</a>
```

Aici, `/spre` este un router intern de pe vremea cînd aveam obsesia să nu _leak_-uim pagerank, dar are și avantajul că putem contoriza clicurile. Deci sînt două probleme: (1) că am servi HTML nestructurat și (2) că am obliga programul tău să treacă prin serverul dexonline ca să afle URL-ul real.

Desigur, se poate rezolva cu o informație mai bine structurată, să zicem:

```
  credits: "© imagine [Cosmin - Miolk]"
  url: "http://real.url.com/"
```

Dar asta presupune ceva muncă pentru schimbarea structurii interne a informației, că ar fi ciobănește să o convertim doar în apelurile la API.

**Comment by CatalinFrancu** [comment]
Și, colac peste pupăză, la o căutare exhaustivă am descoperit și o excepție care nu se încadrează în formatul _© autor_:

https://dexonline.ro/cuvantul-zilei/2016/09/20

Trebuie păstrat suportul pentru asta, îl mai folosim ocazional.

**Comment by revolter** [comment]
Da, vazusem link-ul cu `/spre/` dar uitasem de asta.

Nu ar merge ca `/spre/` sa fie expus si ca API? Si atunci, website-ul ar face in continuare redirect, iar API-ul pentru cuvantul zilei ar contine ceva gen:

```json
"author_id": "miolk"
```

si am face un alt request `/author-info/miolk`, care ar raspunde cu ceva gen:

```json
"name": "Cosmin - Miolk",
"url": "http://real.url.com/"
```

Off-topic: Fix la 13:00 trimit notificarile pentru cuvantul zilei, si aproape la 13:00 ai trimis si tu primul mesajul. Deci am primit notificari legate de cuvantul zilei si pe mail, si pe Telegram 😃

**Comment by revolter** [comment]
> https://dexonline.ro/cuvantul-zilei/2016/09/20

N-ar putea sa fie si `Țărancă torcând` in raspunsul de la API?
