### ISSUE TITLE
Lipseste extensia de la imaginea pentru cuvantul zilei de 27.07.2020

### ISSUE THREAD

**Issue by revolter** [dexonline/dexonline#906]
URL-ul e
`https://dexonline.ro/static/img/wotd/thumb300/2020/07/culuc.`
in loc de
`https://dexonline.ro/static/img/wotd/thumb300/2020/07/culuc.jpg`

**Comment by MateiGall** [comment]
Am adăugat eu. Sper că e ok.

**Comment by revolter** [comment]
Pe website e incarcata tot fara extensie, si la fel si pe API: https://dexonline.ro/cuvantul-zilei/json.

**Comment by CatalinFrancu** [comment]
Am rezolvat eu acum. N-am vrut să intervin ieri, fiind ziua curentă, ca să nu fac chirurgie pe cord deschis. Pe lîngă corectura făcută de Matei (redenumirea imaginii din file manager) mai trebuie modificat și tabelul cuvîntului zilei, editată intrarea în cauză și ales numele nou de fișier.

**Comment by revolter** [comment]
Nu cunosc deloc sistemul vostru, dar s-ar putea adauga o verificare ca sa previna greseli de genul pe viitor?

**Comment by CatalinFrancu** [comment]
Sigur! Nu există _sanity check_ perfect, dar orice pas ajută. :-)

**Comment by revolter** [comment]
Aparent, fix-ul din e298441 nu a functionat: https://dexonline.ro/cuvantul-zilei/2020/09/27.

**Comment by CatalinFrancu** [comment]
Mulțumesc. Am uitat că imaginea zilei poate fi trimisă și prin email. Mai băgăm o fisă. :-)
