### ISSUE TITLE
Căutare cu regex îmi inlocuiește î în â deși nu e necesar

### ISSUE THREAD

**Issue by vilie** [dexonline/dexonline#909]
Bună ziua,

Încerc să caut următorul regex `.*[ășțâî].*[ășțâî].*[ășțâî].*[ășțâî].*`

Acest regex îmi este înlocuit în `.*[ășțââ].*[ășțââ].*[ășțââ].*[ășțââ].*` deși nu ar trebui. Cel puțin prima și ultima apariție clar nu ar trebui înlocuită (putem avea cuvinte care încep sau se termină cu î).

Menționez că asta se intâmplă deși am bifat _Folosesc ortografia folosită pînă în 1993 (î din i)_

**Comment by CatalinFrancu** [comment]
Voi adăuga un caz în plus de tratat în #870. Nu promit să ne ocupăm curînd de el (dezvoltarea este momentan înghețată).
