### ISSUE TITLE
Date mai bune pentru Moara cuvintelor

### ISSUE THREAD

**Issue by CatalinFrancu** [dexonline/dexonline#913]
Putem începe să folosim sensurile principale active pentru Moara cuvintelor, pentru a scăpa de problemele din `DefinitionSimple`. Pare că avem 75.000:

```sql
select count(*)
  from Meaning m
  join Tree t on m.treeId = t.id
  join TreeEntry te on t.id = te.treeId
  join Entry e on te.entryId = e.id
  where m.parentId = 0
    and m.type = 0
    and m.internalRep > ''
    and t.status = 0
    and e.structStatus = 4;
```

Exemple:

| description | internalRep |
| --- | --- |
| echivalență | Simptom care substituie un altul obișnuit pentru o anumită boală. |
| neanalizabil | (Despre texte, cuvinte) Care nu poate fi analizat. |
| foșni | A produce un sunet ușor prin mișcare sau prin frecare. |
| leiță | Monedă de valoare mică (egală cu 20 de parale), care a circulat în trecut. |
| novocaină | Substanță chimică în formă de ace incolore, inodore, cu gust ușor amar, puțin solubile în apă, solubile în alcool, folosită ca anestezic local. |
| contractualist (s.m.) | (Adept) al contractualismului. |
| coși | (Despre vopsea, tencuială etc.) A se desprinde (de pe o suprafață) prin umflare; a se scoroji; a se coji; a se coșcovi. |
| dezastru | Nenorocire mare. |
| număruș | Sorți pentru recrutare. |
| deseca | A elimina apa din diferite materiale. |

**Comment by MateiGall** [comment]
Cred că mai e de lucru. De ex. pentru „clismă” (https://dexonline.ro/definitie/clism%C4%83/sinteza) a prezentat sensul 2, care de fapt face referire la sensul 1 și e neclar în absența acestuia (care operație?).
Sau poate trebuie intervenit în arbori și puse legături în astfel de cazuri unde „acest/această” face referire la un sens anterior.

**Comment by CatalinFrancu** [comment]
Am observat și eu asta la [margarină (2)](https://dexonline.ro/definitie/margarin%C4%83/sinteza). Cred că varianta 2 ar fi mai bună, cu referințe către clismă (1), respectiv margarină (1). Definițiile ar deveni prea ușor de ghicit, dar măcar utilizatorul n-ar trebui să dea cu banul.

Nu cred că e cazul să mergi în urmă pentru asta, dar pe viitor ar fi util!
