### ISSUE TITLE
Bug la semnalarea greșelilor.

### ISSUE THREAD

**Issue by MateiGall** [dexonline/dexonline#927]
La operațiunea făcută din pagina intrării cu butonul „semnalează”, dacă definiția este „nestructurată” înaintea semnalării iar apoi este bifată „structurată”, semnalarea dispare din raportul de greșeli semnalate.

**Comment by CatalinFrancu** [comment]
De acord. De fapt bugul era generalizat: orice formă de editare a definiției (dintre care marcarea ca structurată e doar una) ștergea automat și greșelile. De exemplu, era imposibil să editezi o definiție reparînd o greșeală semnalată, dar păstrînd alta.

Am adăugat legăturile `[ignoră]` și în pagina de editare a definiției. Deci de acum raportările trebuie întotdeauna șterse explicit.
