### ISSUE TITLE
API-ul pentru cuvantul zilei nu functioneaza in anumite cazuri

### ISSUE THREAD

**Issue by revolter** [dexonline/dexonline#931]
Si anume, `https://dexonline.ro/cuvantul-zilei/2021/07/02/json` functioneaza, dar `https://dexonline.ro/cuvantul-zilei/2021/07/2/json` nu functioneaza.

Am dat peste problema asta pentru ca API-ul in sine returneaza `2` sub cheia `day`, in loc sa returneze `02`. Sub cheia `month` vine `07`, nu `7`, deci nu e consistent.

**Comment by CatalinFrancu** [comment]
Cred că pentru API-uri este mai bine să folosim mereu două cifre (deci să nu acceptăm URL-urile cu `/07/2/json`). Am reparat codul să folosească mereu acest format în JSON și XML. Mulțumesc pentru semnalare!
