### ISSUE TITLE
Reprezentare gresita pentru o definitie

### ISSUE THREAD

**Issue by revolter** [dexonline/dexonline#936]
Definitia cu id-ul `795738`, returnata de https://dexonline.ro/definitie/simt/json, incepe cu `1@) simț@` / `1<b>) simț</b>`, si este afisata ca
> 1<b>) simț</b>

in loc de
> <b>1) simț</b>

**Comment by MateiGall** [comment]
Corectat. Mulțumesc.

*Matei GALL*
* <http://dexonline.ro>*
*http://dexonline.ro <http://dexonline.ro>*

**Comment by revolter** [comment]
Super, multumesc!
