### ISSUE TITLE
Design mod întunecat

### ISSUE THREAD

**Issue by raduborza** [dexonline/dexonline#937]
Pentru mobile ar fi utilă existența unui _dark mode_ pentru a consuma mai puțină baterie.

Adaug aici ce rămîne de făcut, ca să nu fie îngropate undeva într-un comentariu. -- @CatalinFrancu 

- [x] ~~Documentează cookie-ul în principiile de confidențialitate.~~
- [x] ~~Asigură-te că Varnish ignoră cookie-ul de mod întunecat.~~
  - (nimic de făcut, informația stă în local storage, nu în cookie).
- [x] Studiază paleta de culori și adapteaz-o la modul întunecat. @sandriu 
- [x] Placeholderele din cîmpuri sînt greu de citit - fă-le mai luminoase.
- [x] (ar fi drăguț) Caută temă pentru blog.dexonline.ro.
- [x] Logo cu prefers-media-query pentru blog.dexonline.ro
- [x] (ar fi drăguț) Caută temă pentru wiki.dexonline.ro.
- [x] Servește medaliile direct ca SVG cu fundal transparent (de luat fișierele de la @sandriu).

**Comment by CatalinFrancu** [comment]
M-am jucat un pic cu asta [pentru Dignitas](https://github.com/TeamDignitas/dignitas/issues/200) și am tras concluzia că Bootstrap 5 nu are suport direct pentru asta. Nu putem include în Sass valorile pentru cele două palete (condiționat de `@media (prefers-color-scheme: dark)`, căci Sass-ul lui Bootstrap așteaptă culori hardcodate, nu condiționate de nimic.

Probabil varianta corectă este să scoatem din template-urile HTML toate clasele care controlează culorile, să zicem `text-white`. De asemenea, trebuie să vedem cum sînt redate diversele componente din Bootstrap. Deci va fi multișor de lucru.

**Comment by raduborza** [comment]
Da, cam pare că Bootstrap nu are suport direct, dar tipul ăsta zice că l-a făcut să meargă [aici](https://github.com/vinorodrigues/bootstrap-dark-5) la **Method 4**! Văd că a scris și un ghid. Nu mă pricep nici la css, nici la Bootstrap, dar logica îmi spune că nu ar trebui să fie mult prea complicat. 

Nu știu, în schimb, dacă are sens să facem o chestie pe care o vom pierde cînd facem update la Bootstrap... :wink:

**Comment by CatalinFrancu** [comment]
Am dat peste acea resursă, dar nu explică prea clar cum procedează. Pare că a umblat în Scss, a extins codul Bootstrap. O putem folosi ca _drop-in replacement_, dar nu avem garanția că nu ne va durea cîndva în viitor.

O variantă mai migăloasă, dar mai fără surprize, ar fi să declarăm pur și simplu un bloc CSS în care să suprascriem culorile care trebuie suprascrise. Vor fi multe, probabil de ordinul zecilor. Pentru păstrarea ordinii, ar trebui scoase din template-urile `.tpl` mențiunile explicite de culoare (`text-light`, `bg-dark` etc.). Asta ar fi oricum o bună practică (HTML-ul n-ar trebui să conțină chestii de stil).

**Comment by CatalinFrancu** [comment]
Am implementat ideea de mai sus în [Dignitas](https://github.com/TeamDignitas/dignitas/compare/dark-mode) (nu e live încă) și a fost rezonabil de ușor. Grosul este în fișierul `colors.css`, care face două chestii:

1. Definește variabile CSS pentru 16 nuanțe de gri, de exemplu `--c-eee` pentru culoarea `#eee`. În dark mode, acestea sînt redefinite complementar, deci `--c-eee` capătă valoarea `#111`. În restul CSS-ului înlocuim toate culorile hard-codate cu aceste variabile. Asta ne dă o inversiune naturală în dark mode, lăsînd restul culorilor neatinse (verde, roșu etc.).
2. Suprascrie culorile lui Bootstrap, strict pentru componentele pe care le folosim. E un pic migălos, dar nu-i greu.

Voi implementa asta și pentru dexonline.

Temă de gîndire: implementăm și un buton + cookie pentru comutarea manuală? Sau respectăm doar preferința de dark-mode a browserului / sistemului de operare? Eu aș merge pe varianta a doua.

**Comment by raduborza** [comment]
Ca să îți răspund mai întîi la întrebare: cred că trebuie să începem cu varianta cea mai simplă, oricare ar fi ea!

Și eu m-am jucat un pic cu css-ul. Practic, am inversat în clasa **body** culorile atributelor _color_ și _background-color_ ca să văd cum merge (dpdv logic asta ar trebui să fie suficient) : am descoperit că avem niște clase care suprascriu/dublează atribute fără o nevoie evidentă): de exemplu în clasa card se redefinește _background-color_ ca #fff deși era tot #fff

**Comment by CatalinFrancu** [comment]
Am pus rezultatul pe [beta](http://beta.dexonline.ro/)! Cum ți se pare?

Poți vedea [modificările aici](https://github.com/dexonline/dexonline/compare/dark-mode). Cum ai observat și tu, bootstrap este destul de redundant. De exemplu, definesc variabila CSS `--bs-primary: #bb2d3b`, dar apoi nu o folosesc, ci în CSS-ul generat apare tot `#bb2d3b`. Am citit despre asta, cică au menținut valorile hardcodate ca să suporte Edge. :rofl: Probabil în BS6 vor adopta variabilele.

**Comment by sandriu** [comment]
Am creat Dark theme și am schimbat un pic și Light theme-ul, ca să fie ambele teme similare ca paletă și ca număr de culori folosite. Tema curentă de pe dexonline folosea nu mai puțin de 44 culori diferite, am redus numărul lor la 24.

[dexonline Light theme & Dark theme v1.pdf](https://github.com/dexonline/dexonline/files/7482392/dexonline.Light.theme.Dark.theme.v1.pdf)

**Comment by sandriu** [comment]
@CatalinFrancu Am testat azi implementarea Light theme și Dark theme (pe desktop) și am descoperit că încă mai sunt câteva culori de schimbat, vezi lista de mai jos.

[dexonline Light theme & dark theme - culori de schimbat.pdf](https://github.com/dexonline/dexonline/files/7498300/dexonline.Light.theme.dark.theme.-.culori.de.schimbat.pdf)
