### ISSUE TITLE
Baza de date nu e completa in link-ul de download

### ISSUE THREAD

**Issue by marianpavel** [dexonline/dexonline#945]
Salutare,

Am downloadat o versiune noua la baza de date, documentatia este outdated, cel putin schema care arata legaturile intre key iar arhiva sql contine urmatoarea structura:

<img width="221" alt="Screen Shot 2021-11-30 at 20 29 42" src="https://user-images.githubusercontent.com/8260460/144106708-2be93b58-f827-418c-a551-0ab98eba55e4.png">

**Comment by CatalinFrancu** [comment]
Am făcut o nouă trecere prin documentația wiki a schemei. Au trecut trei ani, ce să-i faci. :-) dexonline nu folosește în mod explicit _foreign keys_, dar legăturile sînt specificate în documentație. Am precizat și că tabelele `Crawler*` nu sînt folosite în prezent.

**Comment by marianpavel** [comment]
@CatalinFrancu , iar legat de arhiva? ma indoiesc ca aceea este toata baza de date dexonline, nu am gasit in nici un tabel definitiile cuvintelor, am o versiune mai veche care are de 3x mai multe tabele printre care si tabela `Definition `care lipseste. In screenshot-ul de mai sus este tot ce contine ultima arhiva de `sql `de pe link-ul din documentatie.

**Comment by CatalinFrancu** [comment]
Hm, straniu, dar foarte posibil! Pe 5 noiembrie am schimbat unul dintre cele două servere ale noastre și am trecut printr-o perioadă de reconfigurări. Este posibil ca scriptul care rulează noapte de noapte să fi generat ceva trunchiat. Dar baza de date la zi ar trebui să includă tot. Mai poți descărca o copie, te rog?

**Comment by marianpavel** [comment]
Am downloadat din nou arhiva, intr-adevar,  acum apare tabela de `Definition` la sfarsit si sunt mult mai multe tabele, dar la definitii sunt doar 200+ inserari ceea ce e gresit.

**Comment by CatalinFrancu** [comment]
Am testat acum pe [copia la zi](https://dexonline.ro/static/download/dex-database.sql.gz) și primesc toate definițiile (vreun milion). Pentru o parte dintre ele textul este trunchiat; asta este de așteptat căci nu avem drepturi de redistribuire. Dar înregistrările există.

Sigur, este copia de astăzi, dar parcă îmi amintesc că și cea de ieri avea aceeași dimensiune (vreo 300 MB). Mai poți încerca o dată, te rog? Mulțumesc.

**Comment by marianpavel** [comment]
Am verificat, inchid ticketul, acum este ok.
