### ISSUE TITLE
Înlăturare referințe către aplicația de Android

### ISSUE THREAD

**Issue by eduardb** [dexonline/dexonline#960]
Salutări! Cu părere de rău am remarcat că autorul aplicației "DEX pentru Android", Adrian Vîntu, are un comportament nedemn pentru ai fi menționată aplicația în secțiunea "unelte" a siteului, jignind în mod grosolan utilizatorii care lasă feedback constructiv (screenshot mai jos cu exemple). De asemenea, calitatea aplicației a scăzut considerabil în momentul în care autorul a introdus login obligatoriu, plus că spamează zilnic utilizatorii promovând propriile articole pe alte teme.
Există numeroase alte aplicații similare pe Play Store, poate ar trebui considerate în locul acesteia.

Cu stimă,
Un utilizator dexonline.ro

<details>
  <summary>Screenshot</summary>
 
 ![Screenshot_20220403-170750_Google Play Store.jpg](https://user-images.githubusercontent.com/2426348/161434539-67d5e1ed-9599-442d-b93e-63ce5b75c25e.jpg)
</details>

**Comment by CatalinFrancu** [comment]
Sîntem de acord cu tine că tehnologia trebuie supusă eticii. Dar problema în cauză pare mai nuanțată. [Dreptul la replică](https://adrianvintu.net/2021/03/08/cum-arata-un-it-st-analfabet-functional/) al autorului, dincolo de limbajul vehement, are niște argumente rezonabile.

În plus, privind strict acest tichet:

* GitHub este un loc pentru raportări de _bug_-uri, nu pentru campanii de linșaj.
* Aceeași decență care recomandă un limbaj decent recomandă și semnalarea acestui gen de chestiuni pe canale private înaintea escaladării pe forumuri publice.
* Captura de ecran nu include exemple de feedback constructiv, sau poate sînt înecate în marea de invective personale.
* Loginul obligatoriu sună ca o funcție ortogonală pe calitatea aplicației.
* Autorul mi-a confirmat că loginul nu este obligatoriu pentru funcționalitatea de bază.

Dintre acele „alte aplicații similare” le-am instalat pe primele cinci, din care trei nu dau niciun fel de credit proiectului dexonline, ale căror date le folosesc. Dacă e să  aleg între un om care spune niște adevăruri necizelate și unul care își însușește un lucru pe care noi îl dăm liber (și gratuit), îl prefer pe primul.
