### ISSUE TITLE
Caractere cu sedilă

### ISSUE THREAD

**Issue by MateiGall** [dexonline/dexonline#968]
Sistemul transformă automat caracterul „ş” în „ș” (s cu sedilă / s cu virgulă), ceea ce împiedică notarea corectă a etimologiilor din limba turcă (vezi alışveriş).
N-ar trebui să evităm transformarea la etimologii? Eventual doar în cazul provenienței din turcă?

**Comment by CatalinFrancu** [comment]
Nu merge cumva cu `\ş`? Sigur am prevăzut un mecanism, dar nu mi-l amintesc. :angel:

**Comment by MateiGall** [comment]
Ai dreptate, nu m-am gândit.
